# SPDX-License-Identifier: MIT
"""Canonical equation: frozen-SegNet head is EXACTLY rank-4 linear; closed-form flip distance.

MEASURED 2026-07-15 on the real frozen weights (``upstream/models/segnet.safetensors``,
sha256 ``68956e328d4c5d875389a1a444870e6bac1c052c9986123827af95c07c6991b6``), bit-exact
argmax parity vs the cached n96 GT (``gt_n96.npz`` lstars: 0 mismatched pixels / 96 frames).

The law
-------
The segmentation head is ``Conv2d(16 -> 5, k=3)`` with ``activation=None`` (modules.py:105),
i.e. the 5 logits at every pixel are a FIXED LINEAR functional of the 16-channel penultimate
feature map's 3x3 patch (a 144-dim vector ``f``).  Because argmax depends only on logit
DIFFERENCES, the entire argmax partition is a hyperplane arrangement generated by the
CENTERED head, whose measured singular values are ``[3.128, 2.154, 2.025, 1.796, 0.0]`` —
EXACTLY rank 4 (fp32 recon err 5.96e-8).  For class pair ``(c, c')``:

    margin_{c,c'}(f)   = <w_c - w_{c'}, f> + (b_c - b_{c'})
    flip_dist_feat(f)  = |margin_{c,c'}(f)| / ||w_c - w_{c'}||_2

``flip_dist_feat`` is the EXACT (not first-order) minimal L2 perturbation of the local
144-dim penultimate patch that flips that pixel's pairwise ordering — closed form, because
the head is linear.  Measured pair norms ``||w_c - w_{c'}||``: Lane rows are LARGEST
(Road-Lane 3.953, Lane-Movable 4.007, Lane-MyCar 3.862, Lane-Undrivable 3.748) vs
2.60-2.95 for all non-Lane pairs -> per unit feature perturbation, Lane boundaries move
the most.  Measured boundary-pixel medians of ``flip_dist_feat`` (8 frames of n96):
Undrivable-Movable 0.081, Road-Movable 0.106, Road-Lane 0.131, Road-MyCar 0.171,
Road-Undrivable 0.177 — all small vs the typical penultimate activation magnitude 0.47.

Scope / honesty: the closed form is exact IN PENULTIMATE PATCH SPACE.  Pulling it back to
pixel space goes through the nonlinear encoder/decoder (first-order only; measured
first-order pixel-space flip distances median L2 ~8.8 in 0-255 input units, n=45 boundary
pixels — sub-LSB RMS if spread frame-wide, i.e. boundary flips are realization-limited by
uint8/R, not gradient-limited).  Axis: ``[macOS-CPU advisory]`` frozen CPU-torch fp32;
research_only; no score claim.

Artifacts: ``experiments/results/segnet_fractal_20260715/{stage_a,stage_b1,stage_b2}.json``
Memo: ``.omx/research/segnet_recursive_fractal_factorization_20260715.md``
"""

from __future__ import annotations

from collections.abc import Mapping, Sequence
from typing import Any

from tac.canonical_equations.equation import (
    RECALIBRATE_ON_NEW_ANCHORS,
    CanonicalEquation,
    EmpiricalAnchor,
)
from tac.provenance.builders import build_provenance_for_macos_cpu_advisory

EQUATION_ID = "segnet_head_rank4_linear_flipdist_v1"
AXIS = "[macOS-CPU advisory] frozen CPU-torch fp32; real frozen weights"
SEGNET_WEIGHTS_SHA256 = "68956e328d4c5d875389a1a444870e6bac1c052c9986123827af95c07c6991b6"
STAGE_A_ARTIFACT = "experiments/results/segnet_fractal_20260715/stage_a.json"
STAGE_B1_ARTIFACT = "experiments/results/segnet_fractal_20260715/stage_b1.json"

#: MEASURED centered-head singular values (stage_a.json head_centered_singvals).
HEAD_CENTERED_SINGVALS = (3.128, 2.154, 2.025, 1.796, 0.0)
#: MEASURED pair normals ||w_c - w_c'|| (stage_a.json head_pair_normals).
HEAD_PAIR_NORMS: Mapping[str, float] = {
    "Road-Lane": 3.953, "Road-Undrivable": 2.602, "Road-Movable": 2.942,
    "Road-MyCar": 2.705, "Lane-Undrivable": 3.748, "Lane-Movable": 4.007,
    "Lane-MyCar": 3.862, "Undrivable-Movable": 2.946, "Undrivable-MyCar": 2.869,
    "Movable-MyCar": 2.910,
}


def head_flip_distance_feature_space(margin: float, pair_norm: float) -> float:
    """Exact minimal L2 penultimate-patch perturbation flipping a pairwise ordering.

    ``margin`` is the (signed or absolute) pairwise logit margin at the pixel;
    ``pair_norm`` is ``||w_c - w_c'||_2`` of the flattened (16*3*3) head difference.
    Exact (not first-order) because the head is linear with activation=None.
    """
    if pair_norm <= 0:
        raise ValueError("pair_norm must be > 0")
    return abs(float(margin)) / float(pair_norm)


def head_pair_normals_from_weight(weight: Any) -> dict[tuple[int, int], Any]:
    """Compute the 10 class-pair difference normals from a (5, C, kh, kw) head weight.

    Returns flattened difference vectors keyed by (c, c') with c < c'.
    Works on numpy arrays or torch tensors exposing ``reshape``.
    """
    wf = weight.reshape(5, -1)
    return {(c, cp): wf[c] - wf[cp] for c in range(5) for cp in range(c + 1, 5)}


def head_difference_rank(singvals: Sequence[float], rel_tol: float = 1e-6) -> int:
    """Rank of the centered head = dimension of the argmax-relevant projection (== 4)."""
    svs = [float(s) for s in singvals]
    if not svs or svs[0] <= 0:
        return 0
    return sum(1 for s in svs if s > rel_tol * svs[0])


def build_segnet_head_rank4_linear_flipdist_v1() -> CanonicalEquation:
    provenance = build_provenance_for_macos_cpu_advisory(
        archive_sha256=SEGNET_WEIGHTS_SHA256,
        source_path=STAGE_B1_ARTIFACT,
        captured_at_utc="2026-07-16T03:20:00Z",
    )
    anchors = (
        EmpiricalAnchor(
            anchor_id="segnet_head_rank4_recon_fp32_20260715",
            measurement_utc="2026-07-16T03:05:00Z",
            inputs={
                "weights_sha256": SEGNET_WEIGHTS_SHA256,
                "head": "segmentation_head.0.weight (5,16,3,3) + bias (5,)",
            },
            predicted_output={"centered_head_rank": 4, "reason": "argmax depends on differences of 5 functionals"},
            empirical_output={
                "centered_head_rank": 4,
                "singvals": list(HEAD_CENTERED_SINGVALS),
                "rank4_recon_maxabs_err": 5.960464477539063e-08,
            },
            residual=5.960464477539063e-08,
            source_artifact=STAGE_A_ARTIFACT,
            measurement_method=(
                "SVD of centered flattened head (5x144) from the real frozen safetensors; "
                "rank-4 reconstruction max-abs error; verified through the real forward with "
                "bit-exact argmax parity vs cached gt_n96 lstars (0 mismatches / 96 frames)"
            ),
            provenance=provenance,
            empirical_verification_status="VERIFIED_VIA_EMPIRICAL_ANCHOR",
        ),
        EmpiricalAnchor(
            anchor_id="segnet_head_pair_flipdist_boundary_medians_20260715",
            measurement_utc="2026-07-16T03:05:00Z",
            inputs={
                "frames": "8 of n96 real GT frame_1 (stride 12)",
                "boundary_def": "4-neighbor argmax label disagreement",
            },
            predicted_output={"law": "flip_dist_feat = |margin| / ||w_c - w_c'||"},
            empirical_output={
                "median_flipdist_feat": {
                    "Undrivable-Movable": 0.081, "Road-Movable": 0.106, "Road-Lane": 0.131,
                    "Road-MyCar": 0.171, "Road-Undrivable": 0.177,
                },
                "penultimate_typical_activation": 0.473,
            },
            residual=0.0,
            source_artifact=STAGE_B1_ARTIFACT,
            measurement_method=(
                "exact pairwise logit margins at boundary pixels through the real frozen forward, "
                "divided by the exact frozen pair norms (closed form; no surrogate)"
            ),
            provenance=provenance,
            empirical_verification_status="VERIFIED_VIA_EMPIRICAL_ANCHOR",
        ),
    )
    return CanonicalEquation(
        equation_id=EQUATION_ID,
        name="Frozen SegNet head is exact rank-4 linear; closed-form pairwise flip distance",
        one_line_summary=(
            "Argmax partition = hyperplane arrangement in a 4-dim projection of the "
            "penultimate 3x3-patch space; min flipping perturbation = |margin|/||w_c-w_c'|| "
            "(exact closed form)."
        ),
        latex_form=(
            r"m_{cc'}(f)=\langle w_c-w_{c'},f\rangle+(b_c-b_{c'}),\quad "
            r"d^{\mathrm{flip}}_{cc'}(f)=\frac{|m_{cc'}(f)|}{\|w_c-w_{c'}\|_2},\quad "
            r"\operatorname{rank}\big(W-\bar W\big)=4"
        ),
        python_callable_module_path=(
            "tac.canonical_equations.segnet_head_rank4_flipdist_20260715:"
            "head_flip_distance_feature_space"
        ),
        domain_of_validity={
            "network": "frozen contest SegNet (smp.Unet tu-efficientnet_b2, classes=5, activation=None)",
            "weights_sha256": SEGNET_WEIGHTS_SHA256,
            "space": "penultimate 16-ch feature map, 3x3 patch (144-dim); EXACT there; "
                     "pixel-space pullback is first-order only",
            "axis": AXIS,
            "research_only": True,
            "score_claim": False,
            "promotion_eligible": False,
            "verdict_scope": "frozen-weight structural law + n96-subset boundary measurement",
        },
        units_in={"margin": "logit", "pair_norm": "logit_per_unit_feature_L2"},
        units_out={"flip_distance": "penultimate_feature_L2"},
        empirical_anchors=anchors,
        predicted_vs_empirical_residual={"centered_head_rank": 0.0},
        last_calibration_utc="2026-07-16T03:20:00Z",
        next_recalibration_trigger=RECALIBRATE_ON_NEW_ANCHORS,
        canonical_consumers=(
            "margin-residual lever (#226) / MC finisher (#396) closed-form targets",
            "whitebox full campaign (#514) frozen-structure inventory",
        ),
        canonical_producers=(
            "experiments/results/segnet_fractal_20260715/stage_a_weights.py",
            "experiments/results/segnet_fractal_20260715/stage_b1_gates_head.py",
        ),
        provenance=provenance,
    )


__all__ = [
    "EQUATION_ID",
    "HEAD_CENTERED_SINGVALS",
    "HEAD_PAIR_NORMS",
    "build_segnet_head_rank4_linear_flipdist_v1",
    "head_difference_rank",
    "head_flip_distance_feature_space",
    "head_pair_normals_from_weight",
]
