# SPDX-License-Identifier: MIT
"""Canonical equation: STORE-NOTHING-but-xi pose carrier — the keyframe payload collapses to ~0
marginal bytes when frame0 is the witness's OWN warped render (Track B, 18927a1ae).

THE MEASURED FINDING (Track B ``keyframe_rate_minimization_builds_20260702`` + the byte-close
BIT-EXACT confirm this session): the warp-real-luma pose carrier's DOMINANT rate cost is the STORED
real keyframe luma (video-derived -> COUNTED in archive.zip; rate ~0.03-0.07 native, MEASURED 0.464
at ds4/n6). But PoseNet does NOT need the keyframe TEXTURE -- it needs a domain-COHERENT frame pair
differing by the ego-motion, and the SDF witness ALREADY renders that. So store ONLY the twist xi
(+ homography H for decode-simplicity) and warp the witness's OWN frame0 render by xi. The keyframe
payload -> ~0 marginal bytes; the render is FREE (rule-118, generated by the INR from the counted
weights+code).

TWO coupled facts (advisory / research-signal ONLY; NOT a contest score; pointer 0.19110 UNMOVED;
NEVER MPS -- d_pose is the frozen CPU-torch PoseNet authority):

1. RATE COLLAPSE (byte-close BIT-EXACT MEASURED, n6/t1, this session via
   ``tools/levelset_byte_close_and_eval.py --pose-carrier-mode store_nothing``): the pose-carrier
   section drops from **697941 B** (warp_real_luma ds4 stored keyframe) to **1049 B** (store_nothing
   H+xi only) -- the archive.zip rate_term 0.5133 -> 0.0491. frame0 DECODE IS BIT-EXACT
   (frame0_max_abs_uint8_diff = 0; the shipped inflate warp of the witness render == the numpy-fp32
   oracle). byte-optimal (xi-only, H FREE via exp_se3) = 600*12 B fp16 = 7200 B at n600.

2. POSE SUFFICIENCY (Track B n600, classmean PROXY for the witness render): the texture-free
   class-mean render warped by xi gives d_pose **4.97** pre-residual at ~0 marginal rate; +lf24
   -> **1.12** (BETTER than the full real keyframe 1.37). The witness's OWN render is RICHER than the
   classmean proxy -> the store-nothing d_pose is an UPPER-bounded <= 4.97 pre-residual. The trained
   rank-6 dxi residual (residual-mode table, w_pose>0) closes the FIXED offset toward the target --
   whether it reaches the table carrier's d_pose is the OPEN #205 question (NO borrowed number).

VERDICT (honest, NO-FAKE): store-nothing DOMINATES the stored-keyframe carrier ON RATE (byte-close
MEASURED, bit-exact) and is pose-COMPETITIVE (Track B measured, pre-residual). It is the #205 A/B
pose arm (``--pose-carrier-source generated`` / ``derive_store_nothing_205_config`` /
``PoseGauge.STORE_NOTHING_XI``). REACTIVATION -> the #205 checkpoint measures the REAL witness-render
d_pose through this byte-closed decode (the residual-closed offset), the ONLY number that upgrades
this from advisory to a pointer-moving row.

Consumers: the DSL PoseGauge (STORE_NOTHING_XI chart) + the store_nothing_205 launch config.
Producer: the byte-close tool + the Track B rate-minimization tools.
"""
from __future__ import annotations

from tac.canonical_equations.equation import (
    CanonicalEquation,
    EmpiricalAnchor,
    RECALIBRATE_ON_NEW_ANCHORS,
)
from tac.provenance.builders import (
    build_provenance_for_predicted,
    build_provenance_for_research_sidecar,
)

EQUATION_ID = "store_nothing_pose_carrier_rate_collapse_vs_dpose_v1"

_UTC = "2026-07-02T00:00:00Z"
_ADVISORY = "[macOS-CPU advisory]"
_BYTE_CLOSE_REPORT = ".omx/research/store_nothing_pose_carrier_wiring_20260702.md"
_TRACK_B_REPORT = ".omx/research/keyframe_rate_minimization_builds_20260702.md"
_RATE_DENOM = 37_545_489.0

# byte-close MEASURED (n6/t1, BIT-EXACT) -- store_nothing vs warp_real_luma(ds4) on the SAME checkpoint.
_SECTION_TABLE_DS4 = 697941     # warp_real_luma ds4 pose-carrier section bytes (stored keyframe)
_SECTION_STORE_NOTHING = 1049   # store_nothing pose-carrier section bytes (H+xi only, n6)
_RATE_TERM_TABLE_DS4 = 0.5133   # archive.zip rate_term with the ds4 stored keyframe
_RATE_TERM_STORE_NOTHING = 0.0491  # archive.zip rate_term store_nothing (base witness + ~1KB carrier)
_FRAME0_MAX_ABS_DIFF = 0        # store_nothing frame0 decode bit-exact (shipped inflate == numpy oracle)

# byte-optimal xi-only (the design ships this; H derived FREE via exp_se3).
_XI_BYTES_PER_PAIR = 12         # 6 dims * fp16 (2 B)
_N_PAIRS_FULL = 600

# Track B MEASURED (n600, classmean PROXY, frozen CPU-torch PoseNet) -- pre-residual.
_DPOSE_CLASSMEAN_LF0 = 4.975    # store-nothing classmean-only (texture-free), the UPPER bound
_DPOSE_CLASSMEAN_LF24 = 1.123   # store-nothing classmean + lf24 (BEATS full real keyframe 1.367)
_DPOSE_FULL_REAL_KEYFRAME = 1.367  # the expensive warp-real-luma baseline it competes with


def store_nothing_marginal_bytes(n_pairs: int) -> int:
    """The byte-optimal STORE-NOTHING marginal pose payload = ``n_pairs * 12`` (xi-only, fp16;
    H is derived FREE via exp_se3). The stored real keyframe luma (the warp_real_luma cost) is GONE."""
    return int(n_pairs) * _XI_BYTES_PER_PAIR


def store_nothing_rate_term(n_pairs: int) -> float:
    """Contest rate-term contribution of the byte-optimal store-nothing pose payload alone
    (``25 * n_pairs*12 / 37_545_489``). ~0 marginal (7200 B @ n600 -> 0.0048)."""
    return 25.0 * float(store_nothing_marginal_bytes(n_pairs)) / _RATE_DENOM


def build_store_nothing_pose_carrier_rate_collapse_vs_dpose_v1() -> CanonicalEquation:
    """Build the #205 STORE-NOTHING-but-xi rate-collapse / d_pose canonical equation."""

    anchor_rate = EmpiricalAnchor(
        anchor_id="store_nothing_byte_close_rate_collapse_bit_exact_n6_t1_20260702",
        measurement_utc=_UTC,
        inputs={"vehicle": "levelset_witness", "checkpoint": "levelset_pose_smoke_20260627T070546Z/t1",
                "n_pairs": 6, "carrier_a": "warp_real_luma_ds4", "carrier_b": "store_nothing",
                "tool": "tools/levelset_byte_close_and_eval.py --pose-carrier-mode store_nothing"},
        predicted_output={"store_nothing_marginal_bytes_at_n600": store_nothing_marginal_bytes(_N_PAIRS_FULL),
                          "store_nothing_rate_term_at_n600": store_nothing_rate_term(_N_PAIRS_FULL)},
        empirical_output={"section_bytes_warp_real_luma_ds4": _SECTION_TABLE_DS4,
                          "section_bytes_store_nothing": _SECTION_STORE_NOTHING,
                          "rate_term_warp_real_luma_ds4": _RATE_TERM_TABLE_DS4,
                          "rate_term_store_nothing": _RATE_TERM_STORE_NOTHING,
                          "frame0_decode_max_abs_uint8_diff": _FRAME0_MAX_ABS_DIFF,
                          "verdict": ("RATE COLLAPSE: 697941 B -> 1049 B (section); rate_term 0.5133 -> "
                                      "0.0491; frame0 decode BIT-EXACT (max_abs=0). store-nothing "
                                      "DOMINATES the stored-keyframe carrier on rate.")},
        residual=0.0,
        source_artifact=_BYTE_CLOSE_REPORT,
        measurement_method="byte_close_bit_exact_n6_frozen_cpu_torch",
        provenance=build_provenance_for_research_sidecar(
            sidecar_path=_BYTE_CLOSE_REPORT,
            reactivation_criteria=("re-measure the store-nothing REAL witness-render d_pose through the "
                                   "byte-closed decode on a converged #205 checkpoint (--dxi-source ckpt)"),
            measurement_axis=_ADVISORY,
            hardware_substrate="m5_max_cpu",
        ),
    )
    anchor_dpose = EmpiricalAnchor(
        anchor_id="store_nothing_pose_sufficiency_classmean_proxy_n600_preresidual_20260702",
        measurement_utc=_UTC,
        inputs={"n_pairs": 600, "source": "classmean_proxy_for_witness_render", "residual": "dxi=0",
                "partner": "self_warp_coherent_pair"},
        predicted_output={"store_nothing_dpose_upper_bound": _DPOSE_CLASSMEAN_LF0},
        empirical_output={"dpose_classmean_lf0": _DPOSE_CLASSMEAN_LF0,
                          "dpose_classmean_lf24": _DPOSE_CLASSMEAN_LF24,
                          "dpose_full_real_keyframe": _DPOSE_FULL_REAL_KEYFRAME,
                          "verdict": ("pose-COMPETITIVE pre-residual: classmean 4.97 (the witness render "
                                      "is richer -> store-nothing d_pose <= 4.97); +lf24 1.12 BEATS the "
                                      "full real keyframe 1.37 at ~0 rate. Post-residual d_pose is "
                                      "#205-gated (NO borrowed 3.4e-5).")},
        residual=0.0,
        source_artifact=_TRACK_B_REPORT,
        measurement_method="n600_frozen_cpu_torch_posenet_classmean_proxy_preresidual",
        provenance=build_provenance_for_research_sidecar(
            sidecar_path=_TRACK_B_REPORT,
            reactivation_criteria=("measure the REAL witness-render d_pose (not the classmean proxy) "
                                   "with the trained dxi residual on a converged #205 checkpoint"),
            measurement_axis=_ADVISORY,
            hardware_substrate="m5_max_cpu",
        ),
    )
    anchor_bspline = EmpiricalAnchor(
        anchor_id="se3_bspline_xi_rate_error_curve_first_firing_n600_20260707",
        measurement_utc="2026-07-07T00:00:00Z",
        inputs={"n_pairs": 600, "xi_source": "xi_from_pose_calibration(gt_poses, s_t=0.044, s_r=0, pitch=0)",
                "q_levels": 4096, "fit": "sampled-control cumulative SE(3) cubic B-spline (Sommer 2020)",
                "tool": "experiments/results/ground_frame_chart_20260707/fire_se3_bspline_n600.py"},
        predicted_output={"hoped": "knot payload (hundreds of B) replaces the coded xi table (~3.2KB)"},
        empirical_output={
            "baseline_xi_table_bytes_delta_ar": 3200,
            "baseline_quantization_geometry_err_px": {"max": 0.3127, "mean": 0.1282},
            "spline_direct_replacement": ("DEAD at every knot count 4..601: derive-H probe-point error "
                                          "53-703 px MEAN (300-1000x the 0.13 px quantization floor) — "
                                          "the xi sequence carries essential per-pair high-frequency "
                                          "content the sampled-fit spline destroys"),
            "spline_as_predictor_residual_floor": ("VIABLE headroom: knots(M=16) 224 B + order-0 "
                                                   "residual entropy 1958 B = 2182 B floor vs 3200 B "
                                                   "table (~1 KB / ~0.0007 rate), lossless on the "
                                                   "quantized grid; PENDING a real residual coder + "
                                                   "model overhead"),
        },
        residual=0.0,
        source_artifact="experiments/results/ground_frame_chart_20260707/se3_bspline_rate_error_curve.json",
        measurement_method="numpy_fp64_derive_h_probe_point_displacement_plus_order0_entropy",
        provenance=build_provenance_for_research_sidecar(
            sidecar_path="experiments/results/ground_frame_chart_20260707/se3_bspline_rate_error_curve.json",
            reactivation_criteria=("build the residual coder (spline-predictive + static-PMF residual) "
                                   "and measure REAL coded bytes vs the 3200 B table; or LSQ spline fit "
                                   "(the sampled-control fit is the falsified implementation, not the "
                                   "spline paradigm — Catalog #307)"),
            measurement_axis=_ADVISORY,
            hardware_substrate="m5_max_cpu",
        ),
    )
    anchor_coder = EmpiricalAnchor(
        anchor_id="xi_spline_residual_real_coder_delta_res_wins_n600_20260707",
        measurement_utc="2026-07-07T20:00:00Z",
        inputs={"n_pairs": 600, "xi_source": "xi_from_pose_calibration(gt_poses, s_t=0.044, s_r=0, pitch=0)",
                "q_levels": 4096,
                "coder": "tac.boundary_math.xi_spline_residual_coder (spline_residual cid=2 + delta_res cid=3)",
                "tool": "experiments/results/xi_residual_coder_20260707/measure_xi_residual_coder.py"},
        predicted_output={"floor_from_firing": "2182 B (M=16 knots 224 B + order-0 residual entropy 1958 B)",
                          "band": "real coder lands in [2182, 3200] B"},
        empirical_output={
            "best_spline_arm_bytes": 3120,  # M=48, rice; knot sweep M in {4..128}
            "delta_res_no_spline_bytes": 2714,  # delta predictor + rice — the MEASURED WINNER
            "baseline_delta_ar_bytes": 3200,
            "saving_vs_delta_ar_bytes": 486,
            "saving_vs_delta_ar_rate": 0.00032,
            "residual_schemes_measured_bytes": {"varint": 5043, "zlib9": 2939, "rice": 2665},
            "bit_identical_to_shipped_table": True,
            "verdict": ("SPLINE PREDICTOR DEAD as a rate lever too: post-spline residual == plain "
                        "q-delta innovation statistically (rice 2664 vs 2665 B — the xi innovation "
                        "is WHITE ego jitter; knots pay 224-349 B for nothing). The REAL win is the "
                        "ENTROPY STAGE: rice on the same deltas the delta_ar arithmetic coder spends "
                        "3200 B on costs 2714 B total (delta_res mode, bit-identical, -486 B / "
                        "~0.00032 rate). The 2182 B order-0 floor is mostly UNREALIZABLE "
                        "model-overhead mirage: active residual channels have ~9-bit entropy with "
                        "near-unique support (~530 distinct / 600 samples) so no transmitted-PMF "
                        "coder approaches the empirical order-0 number."),
        },
        residual=0.0,
        source_artifact="experiments/results/xi_residual_coder_20260707/xi_residual_coder_curve.json",
        measurement_method="real_coded_bytes_bit_identity_asserted_numpy_fp64_cpu",
        provenance=build_provenance_for_research_sidecar(
            sidecar_path="experiments/results/xi_residual_coder_20260707/xi_residual_coder_curve.json",
            reactivation_criteria=("adopt coder='delta_res' in the shipped store-nothing payload "
                                   "(byte-close + inflate inline of the decode half) to bank the "
                                   "-486 B; or an adaptive/parametric-model entropy stage if the "
                                   "~530 B gap to the (partly mirage) floor ever matters"),
            measurement_axis=_ADVISORY,
            hardware_substrate="m5_max_cpu",
        ),
    )
    return CanonicalEquation(
        equation_id=EQUATION_ID,
        name=("STORE-NOTHING-but-xi pose carrier: keyframe-payload rate collapses to ~0 (byte-close "
              "BIT-EXACT) while remaining pose-competitive (Track B, pre-residual)"),
        one_line_summary=(
            "store-nothing (warp the witness's OWN render by xi) collapses the pose-carrier section "
            "697941B->1049B (rate_term 0.5133->0.0491, byte-close BIT-EXACT) at d_pose <=4.97 pre-residual."
        ),
        latex_form=(
            r"\mathrm{bytes}_{sn}(P)=12P\ (\text{xi-only});\ "
            r"\mathrm{rate}_{sn}=\tfrac{25\cdot12P}{N}\approx0\ \ \text{vs stored-keyframe }697941\,B;\ "
            r"d_{pose}^{sn}\le4.97\ (\text{pre-residual})"
        ),
        python_callable_module_path=(
            "tac.canonical_equations.store_nothing_pose_carrier_rate_dpose_20260702:"
            "store_nothing_rate_term"
        ),
        domain_of_validity={
            "vehicle": ["levelset_witness_pose_carrier"],
            "measurement_axis": [_ADVISORY],
            "result_type": "POSITIVE rate collapse (byte-close BIT-EXACT) + pose-competitive (pre-residual)",
            "carrier_vs_sidecar": ("this is a CARRIER (warps frame0 -> MOVES d_pose), NOT a dead pose "
                                   "sidecar (which the render never reads). d_pose 'equal across pose "
                                   "charts' does NOT hold for carriers."),
            "untested": ["real_witness_render_dpose_post_trained_dxi_residual_on_converged_205",
                         "n600_store_nothing_byte_close (this session measured n6/t1)"],
        },
        units_in={"n_pairs": "count"},
        units_out={"store_nothing_rate_term": "contest_score_rate_term"},
        empirical_anchors=(anchor_rate, anchor_dpose, anchor_bspline, anchor_coder),
        predicted_vs_empirical_residual={
            "byte_close_bit_exact_n6_frozen_cpu_torch": 0.0,
            "n600_frozen_cpu_torch_posenet_classmean_proxy_preresidual": 0.0,
        },
        last_calibration_utc=_UTC,
        next_recalibration_trigger=RECALIBRATE_ON_NEW_ANCHORS,
        canonical_consumers=(
            "tac.witness_dsl.gauge",
            "tac.witness_autoconfig",
        ),
        canonical_producers=(
            "tools/levelset_byte_close_and_eval.py",
            "tools/measure_keyframe_pose_sufficiency_ladder.py",
        ),
        provenance=build_provenance_for_predicted(
            model_id="store_nothing_pose_carrier_rate_collapse.v1",
            inputs_sha256="0" * 64,
            measurement_axis=_ADVISORY,
            hardware_substrate="m5_max_cpu",
        ),
    )


__all__ = [
    "EQUATION_ID",
    "store_nothing_marginal_bytes",
    "store_nothing_rate_term",
    "build_store_nothing_pose_carrier_rate_collapse_vs_dpose_v1",
]
