# SPDX-License-Identifier: MIT
"""Modal source-mount ignore helpers.

Modal snapshots local mount trees while other tools may be running tests in the
same checkout. Generated bytecode/cache files can change mid-snapshot and abort
provider dispatch before a job is even spawned. Keep those artifacts out of all
Modal source mounts.

Two non-content classes MUST be excluded or the dispatch aborts before any paid
job is spawned:

1. ``.git`` VCS-metadata directories — never needed in a Modal runtime mount, and
   they contain volatile index/lock files plus (see #2) ephemeral IPC sockets.
2. Non-regular special files (Unix-domain sockets / FIFOs / device nodes). Modal
   cannot snapshot a socket: it aborts with ``[Errno 102] Operation not supported
   on socket``. The canonical offender is ``.git/fsmonitor--daemon.ipc`` — git's
   filesystem-monitor daemon recreates this socket on any ``git -c
   core.fsmonitor=true`` invocation (e.g. a concurrent sister-subagent ``git
   add``), so deleting it does not stick. Excluding ``.git`` + all special files
   at the mount-ignore surface is the permanent extinction (empirical anchor:
   2026-05-31 Z5 paired auth-eval dispatch crashed on a ``fsmonitor--daemon.ipc``
   socket inside a public-PR intake clone the CUDA wrapper explicitly mounts).
"""

from __future__ import annotations

import stat
from pathlib import Path

GENERATED_MOUNT_DIR_NAMES = frozenset(
    {
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
        ".git",
    }
)
GENERATED_MOUNT_FILE_NAMES = frozenset(
    {
        ".DS_Store",
        "Thumbs.db",
    }
)
GENERATED_MOUNT_SUFFIXES = frozenset({".pyc", ".pyo"})


def _is_non_regular_special_file(path: Path) -> bool:
    """Return True for sockets / FIFOs / device nodes that Modal cannot snapshot.

    Uses ``lstat`` (does not follow symlinks) and fails closed: an unreadable /
    vanished path is treated as a special file (excluded) so a racing deletion
    cannot let a half-gone socket through. Regular files, directories, and
    symlinks return False (symlink targets are evaluated by Modal separately).
    """

    try:
        mode = path.lstat().st_mode
    except OSError:
        return True
    if stat.S_ISLNK(mode) or stat.S_ISREG(mode) or stat.S_ISDIR(mode):
        return False
    # Anything else — S_ISSOCK / S_ISFIFO / S_ISCHR / S_ISBLK — is a special file.
    return True


def ignore_generated_mount_path(path: Path) -> bool:
    """Return True for generated files/dirs that must not enter Modal mounts."""

    path = Path(path)
    if any(part in GENERATED_MOUNT_DIR_NAMES for part in path.parts):
        return True
    if path.name in GENERATED_MOUNT_FILE_NAMES or path.name.startswith("._"):
        return True
    if path.suffix.lower() in GENERATED_MOUNT_SUFFIXES:
        return True
    return _is_non_regular_special_file(path)


__all__ = [
    "GENERATED_MOUNT_DIR_NAMES",
    "GENERATED_MOUNT_FILE_NAMES",
    "GENERATED_MOUNT_SUFFIXES",
    "ignore_generated_mount_path",
]
