# SPDX-License-Identifier: MIT
"""Modal source-mount ignore helpers.

Modal snapshots local mount trees while other tools may be running tests in the
same checkout. Generated bytecode/cache files can change mid-snapshot and abort
provider dispatch before a job is even spawned. Keep those artifacts out of all
Modal source mounts.
"""

from __future__ import annotations

from pathlib import Path

GENERATED_MOUNT_DIR_NAMES = frozenset(
    {
        "__pycache__",
        ".mypy_cache",
        ".pytest_cache",
        ".ruff_cache",
    }
)
GENERATED_MOUNT_FILE_NAMES = frozenset(
    {
        ".DS_Store",
        "Thumbs.db",
    }
)
GENERATED_MOUNT_SUFFIXES = frozenset({".pyc", ".pyo"})


def ignore_generated_mount_path(path: Path) -> bool:
    """Return True for generated files/dirs that must not enter Modal mounts."""

    path = Path(path)
    if any(part in GENERATED_MOUNT_DIR_NAMES for part in path.parts):
        return True
    if path.name in GENERATED_MOUNT_FILE_NAMES or path.name.startswith("._"):
        return True
    return path.suffix.lower() in GENERATED_MOUNT_SUFFIXES


__all__ = [
    "GENERATED_MOUNT_DIR_NAMES",
    "GENERATED_MOUNT_FILE_NAMES",
    "GENERATED_MOUNT_SUFFIXES",
    "ignore_generated_mount_path",
]
