# SPDX-License-Identifier: MIT
"""PHASE-RESIDUAL CARRIER — the STORE half of the appearance-phase d_seg reframe.

BACKGROUND (`.omx/research/flicker_transform_geometry_term_design_20260710.md`, DAG
FEED-flicker-term, MEMORY L85): the witness converges to the temporal-majority oracle floor
(``d_seg ≈ 0.005318`` = the GT stride-2 spike rate); sub-0.15 needs d_seg 0.0008–0.0012, which is
4.5–7× BELOW that flicker floor. The floor is pierceable ONLY by APPEARANCE-PHASE faithfulness:
the per-pair spikes are DETERMINISTIC functions of the boundary's sub-pixel phase and are per-pair
SEPARABLE in the objective (``evaluate.py:96`` — the score is a SUM of independent per-pair terms).
The train/store SPLIT:

  * TRAIN-side (T1 / #360 phase-advection lever): the witness descends the ξ-COHERENT part of the
    phase — the fraction generated by the ego-screw transport A_ξ (nearly free, amortized).
  * STORE-side (THIS module): the phase-carrier STORES the per-pair RESIDUAL the witness CANNOT
    predict — ``r = t_wit_actual − t_wit_ξ_predicted`` — entropy-coded, byte-closed into the L13
    task-space format. Most of the phase is captured by ξ-transport; only the small residual is
    COUNTED. A per-pair channel, but ξ-AMORTIZED.

THE PRIMITIVE (the store-what-doesn't-generalize half):
  * ``t_wit`` = the sub-pixel TIE COORDINATE of the φ=0 boundary at a straddle pixel
    (``Mw[p]/(Mw[p]+Mw[q])``) — the SAME quantity T1 / Force-3 compute. Imported from
    :mod:`tac.boundary_math.phase_primitives` (NO duplication — ONE tie coordinate in the repo).
  * ``t_wit_ξ_predicted`` = the ξ-transport ``A_ξ`` of the PREVIOUS scored frame's tie field
    (:func:`tac.boundary_math.phase_primitives.advect_tie_field_numpy`) — the SAME warp Force-1
    uses. The dual-use pose ξ (#140 / R1 stored twist) IS the phase's ξ; NO separate ξ is stored.
  * cross-scored-frame gap screw = :func:`phase_primitives.cross_scored_frame_xi_interp`.

CODEC (encode; deterministic, $0, numpy+stdlib):
  1. per SCORED frame p (=f1 of pair p) compute the actual tie field ``t[p]`` on the active
     straddle annulus, partitioned per GROUND class {Road=0, Lane=1, Undrivable=2}.
  2. CLOSED-LOOP predictor: ``t_pred[p] = A_ξ(t_dec[p-1])`` (advect the DECODED previous-frame full
     tie field by the cross-frame screw). ``p==0`` predicts a constant ``anchor_predict`` (no prior).
  3. residual ``r[p] = round((t[p] − t_pred[p]) / q_step)`` (int64) on the active pixels only.
  4. reconstruct ``t_dec[p] = clip(t_pred[p] + r[p]·q_step, 0, 1)`` — encoder predicts from the SAME
     values the decoder will see (no drift), exactly as ``xi_spline_residual_coder`` does.
  5. ONE integer residual stream across frames × classes → the SHARED entropy stage
     (:func:`tac.boundary_math.xi_spline_residual_coder.encode_residual_matrix`; best-of
     {varint, zlib9, rice}, self-describing id). ONE residual entropy stage in the repo.
  6. NO-FAKE self-check: encode runs the FULL decode and REFUSES (raises) unless the reconstructed
     tie fields are BIT-IDENTICAL to the closed-loop quantized reconstruction.

RULE-118 boundary (the store-what-doesn't-generalize / free-generic split):
  * COUNTED (archive.zip): the quantized per-pair phase RESIDUAL (video-derived; the part ξ-transport
    cannot predict).
  * FREE (inflate.py): the ξ-transport warp A_ξ + the tie-coordinate extraction (generic algorithm),
    and the ACTIVE STRADDLE MASK + class map are DECODER-DERIVABLE (the witness's own rendered
    partition) — never stored. Only the residual VALUES are counted; the boundary GEOMETRY is free.

DETERMINISM: numpy-fp64 CPU is the authority (same class as the shipped ξ carrier). The MLX tie
extraction (:func:`compute_tie_field_from_margins_mlx`) is a differentiable twin used to source the
train-side quantity; the codec encode/decode are numpy+stdlib ONLY so inflate stays numpy-portable.
The encoder's bit-identity self-check makes any host fp divergence FAIL CLOSED. NEVER a score
authority — this module produces BYTES; the d_seg it recovers is measured through the frozen CPU
scorer on the exact byte-closed decode, and the pointer (0.19108) moves only via
``upstream/evaluate.py``. MPS is NEVER an authority.

Default-OFF: absent a phase-carrier section the byte-close blob is BYTE-IDENTICAL to the pre-phase
grammar (the 7th optional block is manifest-gated, like the #205 pose carrier's 6th block).
"""
from __future__ import annotations

import json
import struct
from dataclasses import dataclass, field
from typing import Any

import numpy as np

from tac.boundary_math.phase_primitives import (
    advect_tie_field_numpy,
    cross_scored_frame_xi_interp,
    witness_tie_coordinate_numpy,
)
from tac.boundary_math.xi_spline_residual_coder import (
    decode_residual_matrix,
    encode_residual_matrix,
    measure_residual_schemes,
    residual_scheme_id,
)

__all__ = [
    "GROUND_CLASSES",
    "PHASE_CARRIER_MAGIC",
    "PhaseCarrierConfig",
    "PhaseCarrierError",
    "PhaseCarrierReport",
    "compute_tie_field_from_margins",
    "compute_tie_field_from_margins_mlx",
    "decode_phase_carrier",
    "encode_phase_carrier",
    "phase_carrier_report",
]

PHASE_CARRIER_MAGIC = b"PHAS1\x00"  # #205/#359 phase-residual carrier v1 (store-half of the flicker reframe)

# GROUND classes {Road, Lane, Undrivable} — the homography (ξ-transport) is valid on the ground
# plane, WRONG on Movable/MyCar (same mask as Force-1). The 68% of cracks live here (memo §2.4:
# Lane 43.6% + Road 35.5% + Undriv 7.4% of spikes). Movable/MyCar are DEFERRED (need a different chart).
GROUND_CLASSES: tuple[int, ...] = (0, 1, 2)


class PhaseCarrierError(ValueError):
    """Raised on a corrupt/inconsistent phase-carrier payload or a NO-FAKE self-check failure."""


@dataclass(frozen=True)
class PhaseCarrierConfig:
    """Phase-residual carrier config (all decoder-visible; ships in the section header)."""

    q_step: float = 1.0 / 64.0  # sub-pixel quantization of the tie coordinate in [0,1]
    residual_scheme: str = "auto"  # "auto" (best-of) | "varint" | "zlib9" | "rice"
    classes: tuple[int, ...] = GROUND_CLASSES
    anchor_predict: float = 0.5  # the p==0 no-prior predictor (mid-tie minimizes anchor residual)
    annulus_band: float = 1.0  # |margin| < band selects the annulus (the flip-prone straddle set)
    gap_xi: str = "interp"  # cross-scored-frame gap screw ("interp" = ½(ξ_p+ξ_{p+1}))
    pitch: float = 0.0  # ground-plane pitch for the warp geometry


@dataclass(frozen=True)
class PhaseCarrierReport:
    """MEASURED accounting of a phase-carrier encode (bytes + ξ-amortization + fidelity)."""

    n_frames: int
    classes: tuple[int, ...]
    total_residual_count: int
    per_frame_class_counts: list[list[int]]
    section_bytes: int
    residual_scheme: str
    q_step: float
    mean_abs_residual_q: float
    max_abs_residual_q: int
    # ξ-amortization: the residual bytes WITH the ξ-transport predictor vs WITHOUT (raw tie vs anchor).
    xi_amortized_residual_bytes: int
    raw_tie_residual_bytes: int
    amortization_ratio: float
    # fidelity: the closed-loop reconstruction is lossless-to-q_step (bit-identical self-check passed).
    reconstruction_bit_identical: bool
    tie_recon_rmse_px: float
    extras: dict[str, Any] = field(default_factory=dict)


# --------------------------------------------------------------------------- #
# 1. tie-field extraction from a scored frame's margins + argmax (cached authority)            #
# --------------------------------------------------------------------------- #
def _straddle_dir_and_mask(
    lstar: np.ndarray, margin: np.ndarray, band: float
) -> tuple[np.ndarray, np.ndarray]:
    """Derive the dominant straddle DIRECTION map + the active annulus straddle MASK.

    ``lstar`` (H,W) int = per-pixel argmax class; ``margin`` (H,W) = the GT-class signed margin.
    A pixel is an active straddle iff (a) it sits on an inter-class edge (argmax differs from its
    RIGHT or DOWN neighbor) AND (b) it is inside the annulus ``|margin| < band``. ``dir_map`` in
    {0=right, 1=down} picks the neighbor that differs (right preferred). Returns ``(dir_map, mask)``.
    This is the DECODER-DERIVABLE geometry (the witness partition) — FREE, never stored.
    """
    lstar = np.asarray(lstar)
    H, W = lstar.shape
    diff_right = np.zeros((H, W), dtype=bool)
    diff_down = np.zeros((H, W), dtype=bool)
    diff_right[:, :-1] = lstar[:, :-1] != lstar[:, 1:]
    diff_down[:-1, :] = lstar[:-1, :] != lstar[1:, :]
    straddle = diff_right | diff_down
    dir_map = np.where(diff_right, 0, 1).astype(np.float32)  # right preferred; else down
    annulus = np.abs(np.asarray(margin, dtype=np.float32)) < np.float32(band)
    mask = straddle & annulus
    return dir_map, mask


def compute_tie_field_from_margins(
    lstar: np.ndarray, margin: np.ndarray, cfg: PhaseCarrierConfig
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Numpy-fp32 REFERENCE: extract ``(tie_field, active_mask, class_map)`` for ONE scored frame.

    ``tie_field`` (H,W) in [0,1] = the sub-pixel tie coordinate (:func:`witness_tie_coordinate_numpy`
    on the signed margin) — meaningful only on ``active_mask``. ``class_map`` = ``lstar`` (the GT
    class per pixel, used to route pixels to per-class residual channels; only classes in
    ``cfg.classes`` are carried). The tie is computed everywhere (cheap) but consumed only on the mask.
    """
    dir_map, mask = _straddle_dir_and_mask(lstar, margin, cfg.annulus_band)
    tie = witness_tie_coordinate_numpy(np.asarray(margin, dtype=np.float32), dir_map)
    tie = np.clip(tie.reshape(margin.shape), 0.0, 1.0).astype(np.float64)
    return tie, mask, np.asarray(lstar)


def compute_tie_field_from_margins_mlx(lstar: Any, margin: Any, cfg: PhaseCarrierConfig) -> Any:
    """Differentiable MLX twin of the tie extraction (parity target; sources the train-side quantity).

    Returns the (1,H,W) tie field via :func:`witness_tie_coordinate_mlx` on the same straddle
    direction map. The mask/class routing stays numpy (decoder-derivable, non-differentiable).
    """
    import mlx.core as mx

    from tac.boundary_math.phase_primitives import witness_tie_coordinate_mlx

    lnp = np.asarray(lstar)
    mnp = np.asarray(margin, dtype=np.float32)
    dir_map, _ = _straddle_dir_and_mask(lnp, mnp, cfg.annulus_band)
    signed = mx.array(mnp[None].astype(np.float32))
    dmap = mx.array(dir_map[None].astype(np.float32))
    return witness_tie_coordinate_mlx(signed, dmap)


# --------------------------------------------------------------------------- #
# 2. the closed-loop ξ-transport predictor over the scored-frame sequence                       #
# --------------------------------------------------------------------------- #
def _geom_for(shape_hw: tuple[int, int], cfg: PhaseCarrierConfig) -> Any:
    from tac.boundary_math.warp_real_luma_frame0 import GroundHomographyGeom

    return GroundHomographyGeom.eon(native_hw=(int(shape_hw[0]), int(shape_hw[1])), pitch=cfg.pitch)


def _cross_xi(xi_twists: np.ndarray, p: int, gap_xi: str) -> np.ndarray:
    """The scored-frame → scored-frame twist f1(p-1) → f1(p) (advect the PREVIOUS frame forward)."""
    xi = np.asarray(xi_twists, dtype=np.float64)
    if gap_xi != "interp":
        raise PhaseCarrierError(f"gap_xi={gap_xi!r} not implemented (only 'interp'; offline_homography OWED)")
    # cross(prev→cur) uses the two adjacent within-pair screws (memo §4 T1). For the last usable
    # index we fall back to the current pair's own screw (interp needs p and p+1; clamp at the tail).
    a = xi[p - 1]
    b = xi[p] if p < xi.shape[0] else xi[p - 1]
    return cross_scored_frame_xi_interp(a, b)


def _predict_full(t_dec_prev_full: np.ndarray, xi_cross: np.ndarray, geom: Any, cfg: PhaseCarrierConfig) -> np.ndarray:
    """Advect the DECODED previous full tie field by the cross-frame screw → predicted full field."""
    pred = advect_tie_field_numpy(t_dec_prev_full, xi_cross, geom)
    return np.clip(pred.reshape(t_dec_prev_full.shape), 0.0, 1.0)


# --------------------------------------------------------------------------- #
# 3. encode / decode                                                                            #
# --------------------------------------------------------------------------- #
def _collect_residuals(
    tie_fields: list[np.ndarray],
    active_masks: list[np.ndarray],
    class_maps: list[np.ndarray],
    xi_twists: np.ndarray,
    geom: Any,
    cfg: PhaseCarrierConfig,
    *,
    use_xi_predictor: bool,
) -> tuple[np.ndarray, list[list[int]], list[np.ndarray]]:
    """Run the closed-loop and return ``(residual_1d int64, per_frame_class_counts, t_dec_fields)``.

    ``use_xi_predictor=False`` = the ξ-AMORTIZATION baseline (predictor is the constant anchor every
    frame; measures the raw-tie cost the ξ-transport saves against). The residual is class-ordered
    within each frame (classes in ``cfg.classes`` order), raster within each class.
    """
    q = np.float64(cfg.q_step)
    H, W = tie_fields[0].shape
    residuals: list[np.ndarray] = []
    per_frame_counts: list[list[int]] = []
    t_dec_fields: list[np.ndarray] = []
    t_dec_prev_full: np.ndarray | None = None
    for p, (tie, mask, cmap) in enumerate(zip(tie_fields, active_masks, class_maps, strict=True)):
        if p == 0 or not use_xi_predictor:
            pred_full = np.full((H, W), cfg.anchor_predict, dtype=np.float64)
        else:
            pred_full = _predict_full(t_dec_prev_full, _cross_xi(xi_twists, p, cfg.gap_xi), geom, cfg)
        frame_counts: list[int] = []
        t_dec_full = np.full((H, W), np.float64(cfg.anchor_predict), dtype=np.float64)
        for cls in cfg.classes:
            sel = np.asarray(mask) & (np.asarray(cmap) == cls)
            if not sel.any():
                frame_counts.append(0)
                continue
            idx = np.flatnonzero(sel.reshape(-1))
            t_act = tie.reshape(-1)[idx]
            t_pred = pred_full.reshape(-1)[idx]
            r = np.round((t_act - t_pred) / q).astype(np.int64)
            residuals.append(r)
            frame_counts.append(int(r.shape[0]))
            t_rec = np.clip(t_pred + r.astype(np.float64) * q, 0.0, 1.0)
            flat = t_dec_full.reshape(-1)
            flat[idx] = t_rec
        per_frame_counts.append(frame_counts)
        t_dec_fields.append(t_dec_full)
        t_dec_prev_full = t_dec_full
    res_1d = np.concatenate(residuals) if residuals else np.zeros(0, dtype=np.int64)
    return res_1d, per_frame_counts, t_dec_fields


def encode_phase_carrier(
    tie_fields: list[np.ndarray],
    active_masks: list[np.ndarray],
    class_maps: list[np.ndarray],
    xi_twists: np.ndarray,
    cfg: PhaseCarrierConfig | None = None,
    *,
    geom: Any | None = None,
) -> tuple[bytes, PhaseCarrierReport]:
    """Encode the phase-residual carrier section (numpy+stdlib; deterministic, $0).

    ``tie_fields``/``active_masks``/``class_maps`` = P per-scored-frame (H,W) arrays (tie in [0,1],
    mask bool, class int). ``xi_twists`` (P,6) rho-first per-pair ego twists (the dual-use pose ξ).
    Returns ``(section_bytes, report)``. The section is self-describing; decode reconstructs the tie
    fields from the DECODER-DERIVABLE masks/class-maps + the counted residual (rule-118).
    """
    cfg = cfg or PhaseCarrierConfig()
    if not tie_fields:
        raise PhaseCarrierError("no scored frames to encode")
    P = len(tie_fields)
    if not (len(active_masks) == len(class_maps) == P):
        raise PhaseCarrierError("tie_fields / active_masks / class_maps length mismatch")
    H, W = tie_fields[0].shape
    xi_twists = np.asarray(xi_twists, dtype=np.float64).reshape(-1, 6)
    if xi_twists.shape[0] < P:
        raise PhaseCarrierError(f"need >= {P} twists, got {xi_twists.shape[0]}")
    geom = geom if geom is not None else _geom_for((H, W), cfg)

    # DECODER-VISIBLE predictor discipline (closed loop; no drift): the decoder reads ξ as fp16, so
    # the encoder MUST predict from the SAME fp16-roundtripped ξ (exactly as xi_spline_residual_coder
    # predicts from the dequantized table). Otherwise the fp16 quantization of ξ makes the encoder's
    # reconstruction differ from the decoder's and the NO-FAKE self-check (correctly) fails.
    xi_dec = xi_twists[:P].astype(np.float16).astype(np.float64)

    res_1d, per_frame_counts, t_dec_fields = _collect_residuals(
        tie_fields, active_masks, class_maps, xi_dec, geom, cfg, use_xi_predictor=True
    )
    # ξ-amortization baseline (anchor predictor every frame).
    raw_res_1d, _, _ = _collect_residuals(
        tie_fields, active_masks, class_maps, xi_dec, geom, cfg, use_xi_predictor=False
    )

    # pick the residual entropy scheme (best-of unless pinned).
    res_mat = res_1d.reshape(-1, 1).astype(np.int64)
    if cfg.residual_scheme == "auto":
        sizes = measure_residual_schemes(res_mat) if res_1d.size else {"varint": 0, "zlib9": 0, "rice": 0}
        scheme = min(sizes, key=lambda k: sizes[k]) if res_1d.size else "varint"
    else:
        scheme = cfg.residual_scheme
    res_blob = encode_residual_matrix(res_mat, scheme) if res_1d.size else b""

    raw_mat = raw_res_1d.reshape(-1, 1).astype(np.int64)
    raw_bytes = (
        min(measure_residual_schemes(raw_mat).values()) if raw_res_1d.size else 0
    )

    hdr = {
        "version": 1,
        "n_frames": P,
        "height": int(H),
        "width": int(W),
        "q_step": float(cfg.q_step),
        "classes": [int(c) for c in cfg.classes],
        "anchor_predict": float(cfg.anchor_predict),
        "annulus_band": float(cfg.annulus_band),
        "gap_xi": str(cfg.gap_xi),
        "pitch": float(cfg.pitch),
        "per_frame_class_counts": per_frame_counts,
        "residual_scheme_id": residual_scheme_id(scheme),
        "residual_count": int(res_1d.shape[0]),
    }
    hj = json.dumps(hdr, separators=(",", ":")).encode("utf-8")
    buf = bytearray()
    buf += PHASE_CARRIER_MAGIC
    buf += struct.pack("<I", len(hj))
    buf += hj
    # xi twists (fp16, provenance + the decode predictor input — the SAME dual-use pose ξ).
    buf += np.asarray(xi_twists[:P], dtype=np.float16).tobytes()
    buf += struct.pack("<I", len(res_blob))
    buf += res_blob
    section = bytes(buf)

    # NO-FAKE bit-identity self-check: full decode must equal the closed-loop reconstruction.
    dec_fields = decode_phase_carrier(section, active_masks, class_maps, geom=geom)
    for t_dec, t_ref in zip(dec_fields, t_dec_fields, strict=True):
        if not np.array_equal(t_dec, t_ref):
            raise PhaseCarrierError("NO-FAKE: decode != closed-loop reconstruction (codec bug)")

    # fidelity: tie reconstruction RMSE (px) on active pixels vs the actual tie.
    sq_sum = 0.0
    n = 0
    for tie, mask, t_dec in zip(tie_fields, active_masks, t_dec_fields, strict=True):
        sel = np.asarray(mask)
        if sel.any():
            d = (np.asarray(tie)[sel] - t_dec[sel])
            sq_sum += float(np.sum(d * d))
            n += int(sel.sum())
    rmse = float(np.sqrt(sq_sum / n)) if n else 0.0

    report = PhaseCarrierReport(
        n_frames=P,
        classes=tuple(int(c) for c in cfg.classes),
        total_residual_count=int(res_1d.shape[0]),
        per_frame_class_counts=per_frame_counts,
        section_bytes=len(section),
        residual_scheme=scheme,
        q_step=float(cfg.q_step),
        mean_abs_residual_q=float(np.mean(np.abs(res_1d))) if res_1d.size else 0.0,
        max_abs_residual_q=int(np.max(np.abs(res_1d))) if res_1d.size else 0,
        xi_amortized_residual_bytes=len(res_blob),
        raw_tie_residual_bytes=int(raw_bytes),
        amortization_ratio=(float(len(res_blob)) / float(raw_bytes)) if raw_bytes else 1.0,
        reconstruction_bit_identical=True,
        tie_recon_rmse_px=rmse,
    )
    return section, report


def decode_phase_carrier(
    section: bytes,
    active_masks: list[np.ndarray],
    class_maps: list[np.ndarray],
    *,
    geom: Any | None = None,
) -> list[np.ndarray]:
    """Decode the phase-residual carrier (numpy+stdlib ONLY — inflate-portable).

    ``active_masks``/``class_maps`` are DECODER-DERIVABLE (the witness's own rendered partition) —
    passed in here; never stored in the section. Returns the reconstructed per-frame full tie fields
    (active pixels carry the reconstructed tie; the rest carry ``anchor_predict``).
    """
    if section[: len(PHASE_CARRIER_MAGIC)] != PHASE_CARRIER_MAGIC:
        raise PhaseCarrierError("bad phase-carrier magic")
    off = len(PHASE_CARRIER_MAGIC)
    (hlen,) = struct.unpack_from("<I", section, off)
    off += 4
    hdr = json.loads(section[off : off + hlen].decode("utf-8"))
    off += hlen
    P = int(hdr["n_frames"])
    H, W = int(hdr["height"]), int(hdr["width"])
    q = np.float64(hdr["q_step"])
    classes = tuple(int(c) for c in hdr["classes"])
    anchor = np.float64(hdr["anchor_predict"])
    gap_xi = str(hdr["gap_xi"])
    per_frame_counts = hdr["per_frame_class_counts"]
    xi = np.frombuffer(section[off : off + P * 6 * 2], dtype=np.float16).astype(np.float64).reshape(P, 6)
    off += P * 6 * 2
    (rlen,) = struct.unpack_from("<I", section, off)
    off += 4
    res_blob = section[off : off + rlen]
    off += rlen
    total = int(hdr["residual_count"])
    res_1d = (
        decode_residual_matrix(res_blob, int(hdr["residual_scheme_id"]), total, 1).reshape(-1)
        if total
        else np.zeros(0, dtype=np.int64)
    )

    cfg = PhaseCarrierConfig(
        q_step=float(q), classes=classes, anchor_predict=float(anchor),
        annulus_band=float(hdr["annulus_band"]), gap_xi=gap_xi, pitch=float(hdr["pitch"]),
    )
    geom = geom if geom is not None else _geom_for((H, W), cfg)

    if not (len(active_masks) == len(class_maps) == P):
        raise PhaseCarrierError("decoder masks/class_maps length != n_frames")

    out: list[np.ndarray] = []
    cursor = 0
    t_dec_prev_full: np.ndarray | None = None
    for p in range(P):
        if p == 0:
            pred_full = np.full((H, W), anchor, dtype=np.float64)
        else:
            pred_full = _predict_full(t_dec_prev_full, _cross_xi(xi, p, gap_xi), geom, cfg)
        t_dec_full = np.full((H, W), anchor, dtype=np.float64)
        mask = np.asarray(active_masks[p])
        cmap = np.asarray(class_maps[p])
        for ci, cls in enumerate(classes):
            cnt = int(per_frame_counts[p][ci])
            if cnt == 0:
                continue
            sel = mask & (cmap == cls)
            idx = np.flatnonzero(sel.reshape(-1))
            if idx.shape[0] != cnt:
                raise PhaseCarrierError(
                    f"frame {p} class {cls}: decoder mask has {idx.shape[0]} active px but header says {cnt} "
                    "(masks/class_maps must match the encoder's decoder-derivable partition)"
                )
            r = res_1d[cursor : cursor + cnt]
            cursor += cnt
            t_pred = pred_full.reshape(-1)[idx]
            t_rec = np.clip(t_pred + r.astype(np.float64) * q, 0.0, 1.0)
            t_dec_full.reshape(-1)[idx] = t_rec
        out.append(t_dec_full)
        t_dec_prev_full = t_dec_full
    if cursor != res_1d.shape[0]:
        raise PhaseCarrierError("residual stream not fully consumed (corrupt payload)")
    return out


def phase_carrier_report(
    lstars: np.ndarray,
    margins: np.ndarray,
    gt_poses: np.ndarray,
    cfg: PhaseCarrierConfig | None = None,
) -> tuple[bytes, PhaseCarrierReport]:
    """End-to-end convenience: cached ``(lstars, margins, gt_poses)`` → encoded section + report.

    ``lstars`` (P,H,W) int, ``margins`` (P,H,W) float, ``gt_poses`` (P,6). Extracts the per-frame
    tie fields + masks + class maps, calibrates ξ from the poses (the SAME
    ``xi_from_pose_calibration`` the pose carrier uses), and encodes. The scored-frame sequence is
    treated as the stride-2 f1 sequence (one tie field per pair's f1 — the memo's cross-pair support).
    """
    from tac.boundary_math.warp_real_luma_frame0 import xi_from_pose_calibration

    cfg = cfg or PhaseCarrierConfig()
    lstars = np.asarray(lstars)
    margins = np.asarray(margins, dtype=np.float32)
    P = lstars.shape[0]
    tie_fields: list[np.ndarray] = []
    active_masks: list[np.ndarray] = []
    class_maps: list[np.ndarray] = []
    for p in range(P):
        tie, mask, cmap = compute_tie_field_from_margins(lstars[p], margins[p], cfg)
        tie_fields.append(tie)
        active_masks.append(mask)
        class_maps.append(cmap)
    xi = np.stack(
        [xi_from_pose_calibration(np.asarray(gt_poses)[p], s_t=1.0, s_r=1.0, pitch=cfg.pitch) for p in range(P)]
    )
    return encode_phase_carrier(tie_fields, active_masks, class_maps, xi, cfg)
