# SPDX-License-Identifier: MIT
"""SNeRV-inspired carrier — store LF coefficients, GENERATE HF detail.

The SNeRV (Spectra-preserving NeRV, arXiv 2501.01681) carrier represents a frame as a
multi-level orthonormal 2D wavelet pyramid and:

  * **STORES** only the coarsest LF (LL approximation) subband — ~``H*W / 4^L``
    coefficients at level ``L``, quantized to a small bit budget. This is the
    dominant archive content but is itself tiny (a 384x512 frame at level 3 has
    only 48x64 = 3072 LF coefficients per channel).
  * **GENERATES** the HF detail subbands with a small per-level decoder. The
    decoder is a learned linear upsampling map (one small kernel per level) whose
    weights ARE in the archive but are byte-cheap (shared across all frames).

This is the **super-small-rate-by-design** carrier the operator asked for: the
byte-heavy detail is generated, not stored (curing the Z8 disease where the raw
wavelet detail blob was ~99.5% of the archive). Distortion is "solved" because
the LF approximation already captures the low-frequency structure SegNet's
stride-2 stem actually sees, and the L-inf pose-Fisher allocation (``allocation.py``)
spends the LF bit budget exactly where the detector is sensitive.

Decoder generation model (contest adapter, not upstream bit-exact parity): at
each pyramid level the HF detail tuple ``(LH, HL, HH)`` is GENERATED from the
current approximation ``LL`` via learned receiver-visible predictors per
subband. The default historical predictor is a 3x3 local LF patch. The
``snerv_spectra_preserving_mfu_hfr_temporal_adapter_v1`` predictor uses a
receiver-safe version of the paper's core stack: multi-resolution fusion (MFU),
high-frequency restoration (HFR), and an explicit temporal LF-delta utility
(SNeRV_T). This is still marked as a local spectra-preserving adapter until
full upstream OSS parity is proven, but it is executable, byte-priced, and
decoded by the contest runtime without hidden sidecars.

[verified-local: DWT adjoint exactness in ``dwt.py`` and deterministic receiver
roundtrip surfaces. Source-faithful SNeRV parity remains blocked until the
official OSS/paper gates pass.]

Catalog #290 (canonical-vs-unique): the DWT is ADOPTED canonical (``dwt.py`` uses
pywt). The HF-generation decoder is FORK_PRINCIPLED — SNeRV's distinguishing
feature is the generate-HF-from-LF map, which no existing substrate provides; it
must be unique to this carrier. The score-aware loss ADOPTS the canonical
bit-exact mirror (``load_score_exact_scorers``) because measurement authority must
be canonical.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final

import numpy as np

from tac.substrates.snerv_inverse_steg_carrier.dwt import (
    DEFAULT_WAVELET,
    WaveletPyramid,
    dwt2_multilevel,
    idwt2_multilevel,
)

__all__ = [
    "DEFAULT_SNERV_MODEL_SIZE",
    "SNERV_MFU_HFR_TEMPORAL_RECEIVER_PROOF",
    "SNERV_SPECTRA_PRESERVING_ADAPTER",
    "HfGenerationDecoder",
    "HighFrequencyRestorer",
    "MultiResolutionFusionUnit",
    "SnervCarrierError",
    "SnervFrameCode",
    "SnervModelSizeConfig",
    "SnervTemporalExtension",
    "decode_frame",
    "dequantize_lf",
    "encode_frame_lf",
    "fit_hf_decoder_least_squares",
    "fit_hf_decoder_weighted_least_squares",
    "generate_hf_from_lf",
    "quantize_lf",
]

# A 3x3 separable linear HF predictor per detail subband (LH, HL, HH).
_DETAIL_KEYS: Final[tuple[str, str, str]] = ("LH", "HL", "HH")
_PREDICTOR_TAPS: Final[int] = 9  # 3x3 kernel
SNERV_SPECTRA_PRESERVING_ADAPTER: Final[str] = (
    "snerv_spectra_preserving_mfu_hfr_temporal_adapter_v1"
)
SNERV_MFU_HFR_TEMPORAL_RECEIVER_PROOF: Final[str] = (
    "receiver_safe_numpy_mfu_hfr_temporal_blocks_no_torch_no_scorer"
)


class SnervCarrierError(ValueError):
    """Raised when the SNeRV carrier contract is violated."""


@dataclass(frozen=True)
class SnervModelSizeConfig:
    """Receiver-visible SNeRV decoder capacity controls.

    The spectra-preserving SNeRV stack exposes model-size controls such as
    ``fc_dim`` and ``emb_size``. These knobs are receiver-real: ``fc_dim``
    controls the number of LF-context/MFU features fitted per subband,
    ``emb_size`` adds deterministic coordinate features generated by the
    receiver, ``hfr_gain`` controls the deterministic HFR residual correction,
    and the resulting feature count changes decoder weights, payload bytes, and
    full-frame replay.
    """

    fc_dim: int = 9
    emb_size: int = 0
    patch_radius: int = 1
    mfu_scales: tuple[int, ...] = (1, 2, 4)
    hfr_gain: float = 0.0
    temporal_context: int = 0
    adapter: str = "snerv_fc_dim_emb_size_adapter_v1"

    def __post_init__(self) -> None:
        object.__setattr__(self, "fc_dim", int(self.fc_dim))
        object.__setattr__(self, "emb_size", int(self.emb_size))
        object.__setattr__(self, "patch_radius", int(self.patch_radius))
        object.__setattr__(
            self,
            "mfu_scales",
            tuple(int(v) for v in self.mfu_scales if int(v) >= 1),
        )
        object.__setattr__(self, "hfr_gain", float(self.hfr_gain))
        object.__setattr__(self, "temporal_context", int(self.temporal_context))
        if self.fc_dim < 1:
            raise SnervCarrierError("fc_dim must be >= 1")
        if self.emb_size < 0:
            raise SnervCarrierError("emb_size must be >= 0")
        if self.patch_radius < 0 or self.patch_radius > 3:
            raise SnervCarrierError("patch_radius must be in [0, 3]")
        if not self.mfu_scales:
            raise SnervCarrierError("mfu_scales must contain at least one scale")
        if self.hfr_gain < 0:
            raise SnervCarrierError("hfr_gain must be non-negative")
        if self.temporal_context < 0:
            raise SnervCarrierError("temporal_context must be non-negative")

    @property
    def feature_count(self) -> int:
        # SNeRV_T contributes two receiver-visible LF-delta channels per radius:
        # center-prev and next-center. These are generated from archived LF
        # planes, so increasing temporal_context changes both decoder payload
        # bytes and decoded pixels rather than only metadata.
        return int(self.fc_dim + self.emb_size + 2 * self.temporal_context)

    def as_jsonable(self) -> dict[str, int | str]:
        return {
            "fc_dim": int(self.fc_dim),
            "emb_size": int(self.emb_size),
            "patch_radius": int(self.patch_radius),
            "mfu_scales": [int(v) for v in self.mfu_scales],
            "hfr_gain": float(self.hfr_gain),
            "temporal_context": int(self.temporal_context),
            "feature_count": int(self.feature_count),
            "adapter": self.adapter,
        }


DEFAULT_SNERV_MODEL_SIZE = SnervModelSizeConfig()


@dataclass(frozen=True)
class MultiResolutionFusionUnit:
    """Receiver-safe MFU: fuse LF context at multiple deterministic scales.

    The upstream spectra-preserving SNeRV paper's MFU is a learned neural block.
    The contest receiver cannot depend on torch, so this adapter uses the same
    signal role with deterministic NumPy features: local LF patches, pooled
    LF context at multiple scales, and first-order gradients. The fitted decoder
    still learns the per-subband weights; this block only defines the receiver
    feature basis and byte-visible capacity.
    """

    scales: tuple[int, ...] = (1, 2, 4)
    include_gradients: bool = True

    def features(
        self,
        field: np.ndarray,
        *,
        feature_count: int,
        patch_radius: int,
    ) -> np.ndarray:
        field = np.asarray(field, dtype=np.float64)
        if field.ndim != 2:
            raise SnervCarrierError(f"MFU field must be 2D; got {field.shape}")
        if feature_count < 1:
            raise SnervCarrierError("MFU feature_count must be >= 1")
        bank: list[np.ndarray] = []
        for scale in self.scales:
            pooled = _box_pool_upsample(field, int(scale))
            bank.append(pooled)
            if int(scale) > 1:
                bank.append(field - pooled)
        if self.include_gradients:
            gy, gx = _central_gradients(field)
            bank.extend((gy, gx, np.hypot(gy, gx)))
        if feature_count < len(bank):
            raise SnervCarrierError(
                "fc_dim is too small to consume requested MFU scales and "
                f"gradients: need >= {len(bank)}, got {feature_count}"
            )
        local = _patch_features(
            field,
            patch_radius=patch_radius,
            feature_count=(2 * patch_radius + 1) ** 2,
        )
        bank.extend(local[:, :, i] for i in range(local.shape[-1]))
        return _select_feature_bank(bank, feature_count)


@dataclass(frozen=True)
class HighFrequencyRestorer:
    """Receiver-safe HFR: deterministic LF-edge residual added to HF details."""

    gain: float = 0.0

    def correction(
        self,
        context: np.ndarray,
        *,
        subband: str,
        target_hw: tuple[int, int],
    ) -> np.ndarray:
        context = np.asarray(context, dtype=np.float64)
        if self.gain <= 0:
            return np.zeros(target_hw, dtype=np.float64)
        edge = context - _box_pool_upsample(context, 3)
        edge = _resize_nn(edge, target_hw)
        if subband == "LH":
            gy, _gx = _central_gradients(edge)
            basis = gy
        elif subband == "HL":
            _gy, gx = _central_gradients(edge)
            basis = gx
        elif subband == "HH":
            gy, gx = _central_gradients(edge)
            basis = 0.5 * (gy + gx)
        else:
            raise SnervCarrierError(f"unknown HFR subband {subband!r}")
        scale = float(np.std(basis)) + 1e-6
        return (float(self.gain) * basis / scale).astype(np.float64)

    def restore(
        self,
        details: tuple[np.ndarray, np.ndarray, np.ndarray],
        context: np.ndarray,
    ) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
        out = []
        for subband, detail in zip(_DETAIL_KEYS, details, strict=True):
            corr = self.correction(
                context,
                subband=subband,
                target_hw=tuple(int(v) for v in detail.shape),
            )
            out.append(np.asarray(detail, dtype=np.float64) + corr)
        return tuple(out)  # type: ignore[return-value]


@dataclass(frozen=True)
class SnervTemporalExtension:
    """Receiver-safe SNeRV_T utility over an ordered LF sequence.

    It exposes pair/window LF deltas as deterministic features. The current
    archive grammar still stores per-frame LF planes, so this class is a
    training/allocation primitive rather than hidden receiver state.
    """

    radius: int = 1

    def sequence_delta_features(
        self,
        lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...],
        *,
        index: int,
        target_hw: tuple[int, int] | None = None,
    ) -> np.ndarray:
        if self.radius < 1:
            raise SnervCarrierError("temporal radius must be >= 1")
        if not lf_sequence:
            raise SnervCarrierError("lf_sequence must be non-empty")
        idx = int(index)
        if idx < 0 or idx >= len(lf_sequence):
            raise SnervCarrierError("temporal index out of range")
        center = np.asarray(lf_sequence[idx], dtype=np.float64)
        target = target_hw or center.shape
        bank = []
        for offset in range(1, self.radius + 1):
            prev = np.asarray(lf_sequence[max(0, idx - offset)], dtype=np.float64)
            nxt = np.asarray(lf_sequence[min(len(lf_sequence) - 1, idx + offset)], dtype=np.float64)
            bank.append(_resize_nn(center - prev, target))
            bank.append(_resize_nn(nxt - center, target))
        return np.stack(bank, axis=-1).astype(np.float64)


@dataclass(frozen=True)
class HfGenerationDecoder:
    """The small SNeRV decoder that GENERATES HF detail from the LF approximation.

    ``kernels[level][subband]`` is a (3, 3) linear predictor that maps a local
    3x3 patch of the (upsampled) approximation to the predicted detail coefficient
    at that position. Byte cost = ``levels * 3 subbands * 9 taps * 4 bytes`` per
    channel (fp32) — shared across ALL frames, so amortized to ~0 per frame.

    The decoder is GENERATIVE: at inflate time the receiver has only the stored LF
    + these kernels and reconstructs HF deterministically (no scorer, no torch).
    """

    kernels: dict  # {level_idx: {subband: (3,3) or (feature_count,) np.ndarray}}
    levels: int
    model_size: SnervModelSizeConfig = field(default_factory=SnervModelSizeConfig)

    def byte_cost(self) -> int:
        n = 0
        for lvl in self.kernels.values():
            for k in lvl.values():
                n += int(np.asarray(k).size) * 4  # fp32
        return n

    @staticmethod
    def zeros(
        levels: int,
        *,
        model_size: SnervModelSizeConfig | None = None,
    ) -> HfGenerationDecoder:
        model_size = model_size or DEFAULT_SNERV_MODEL_SIZE
        kernels = {
            i: {
                sb: np.zeros(_kernel_storage_shape(model_size), dtype=np.float64)
                for sb in _DETAIL_KEYS
            }
            for i in range(levels)
        }
        return HfGenerationDecoder(
            kernels=kernels,
            levels=int(levels),
            model_size=model_size,
        )


@dataclass(frozen=True)
class SnervFrameCode:
    """The per-frame stored code: quantized LF + the dequant scale/zero-point.

    The HF detail is NOT stored — it is regenerated from ``lf_quant`` + the shared
    decoder at decode time. This is the entire per-frame rate.
    """

    lf_quant: np.ndarray  # (h_lf, w_lf) int (quantized LF coefficients)
    lf_scale: float  # per-coefficient dequant step (or per-element via steps)
    lf_zero: float  # zero-point (subtracted before quant)
    lf_shape: tuple[int, int]
    levels: int
    wavelet: str
    orig_hw: tuple[int, int]
    per_element_steps: np.ndarray | None = None  # L-inf allocation steps (or None)

    def stored_coeff_count(self) -> int:
        return int(self.lf_quant.size)


def _upsample_nn(approx: np.ndarray, target_hw: tuple[int, int]) -> np.ndarray:
    """Nearest-neighbour upsample the approximation to a detail subband's shape.

    The detail subband at a level has the SAME shape as that level's
    approximation. ``pywt`` keeps LH/HL/HH the same shape as the LL produced at
    the same decomposition step, so we upsample the *coarser* approximation to it.
    """
    th, tw = target_hw
    ah, aw = approx.shape
    ri = (np.arange(th) * ah // th).clip(0, ah - 1)
    ci = (np.arange(tw) * aw // tw).clip(0, aw - 1)
    return approx[np.ix_(ri, ci)]


def _resize_nn(field: np.ndarray, target_hw: tuple[int, int]) -> np.ndarray:
    field = np.asarray(field, dtype=np.float64)
    th, tw = int(target_hw[0]), int(target_hw[1])
    if field.shape == (th, tw):
        return field.copy()
    return _upsample_nn(field, (th, tw))


def _box_pool_upsample(field: np.ndarray, scale: int) -> np.ndarray:
    """Average-pool by ``scale`` then nearest-upsample back to input shape."""

    field = np.asarray(field, dtype=np.float64)
    scale = int(scale)
    if scale <= 1:
        return field.copy()
    h, w = field.shape
    ph = ((h + scale - 1) // scale) * scale
    pw = ((w + scale - 1) // scale) * scale
    padded = np.pad(field, ((0, ph - h), (0, pw - w)), mode="reflect")
    pooled = padded.reshape(ph // scale, scale, pw // scale, scale).mean(axis=(1, 3))
    return np.repeat(np.repeat(pooled, scale, axis=0), scale, axis=1)[:h, :w]


def _central_gradients(field: np.ndarray) -> tuple[np.ndarray, np.ndarray]:
    field = np.asarray(field, dtype=np.float64)
    gy = 0.5 * (np.roll(field, -1, axis=0) - np.roll(field, 1, axis=0))
    gx = 0.5 * (np.roll(field, -1, axis=1) - np.roll(field, 1, axis=1))
    gy[0, :] = field[min(1, field.shape[0] - 1), :] - field[0, :]
    gy[-1, :] = field[-1, :] - field[max(0, field.shape[0] - 2), :]
    gx[:, 0] = field[:, min(1, field.shape[1] - 1)] - field[:, 0]
    gx[:, -1] = field[:, -1] - field[:, max(0, field.shape[1] - 2)]
    return gy, gx


def _select_feature_bank(bank: list[np.ndarray], feature_count: int) -> np.ndarray:
    if not bank:
        raise SnervCarrierError("feature bank must be non-empty")
    h, w = bank[0].shape
    normalized = []
    for feature in bank:
        arr = np.asarray(feature, dtype=np.float64)
        if arr.shape != (h, w):
            raise SnervCarrierError("feature bank shapes must match")
        mean = float(np.mean(arr))
        std = float(np.std(arr))
        normalized.append((arr - mean) / (std + 1e-6))
    out = [normalized[i % len(normalized)] for i in range(int(feature_count))]
    return np.stack(out, axis=-1).astype(np.float64)


def _kernel_storage_shape(model_size: SnervModelSizeConfig) -> tuple[int, ...]:
    if model_size == DEFAULT_SNERV_MODEL_SIZE:
        return (3, 3)
    return (model_size.feature_count,)


def _kernel_vector(kernel: np.ndarray, model_size: SnervModelSizeConfig) -> np.ndarray:
    vec = np.asarray(kernel, dtype=np.float64).reshape(-1)
    if vec.size != model_size.feature_count:
        raise SnervCarrierError(
            f"decoder kernel has {vec.size} values, expected "
            f"{model_size.feature_count} for {model_size.as_jsonable()}"
        )
    return vec


def _patch_features(
    field: np.ndarray,
    *,
    patch_radius: int = 1,
    feature_count: int | None = None,
) -> np.ndarray:
    """Stack deterministic LF-context features -> ``(H, W, feature_count)``.

    Edge-padded (reflect) so every position has a full 3x3 context. This is the
    feature matrix the linear HF predictor consumes. The default path preserves
    the historical 3x3 feature order; larger ``fc_dim`` values append local
    nonlinear context features, and smaller values truncate the deterministic
    order.
    """
    patch_radius = int(patch_radius)
    field = np.asarray(field, dtype=np.float64)
    padded = np.pad(field, patch_radius, mode="reflect")
    h, w = field.shape
    offsets = [
        (di, dj)
        for di in range(-patch_radius, patch_radius + 1)
        for dj in range(-patch_radius, patch_radius + 1)
    ]
    base = np.empty((h, w, len(offsets)), dtype=np.float64)
    for idx, (di, dj) in enumerate(offsets):
        row = patch_radius + di
        col = patch_radius + dj
        base[:, :, idx] = padded[row : row + h, col : col + w]
    wanted = int(feature_count if feature_count is not None else base.shape[-1])
    if wanted <= base.shape[-1]:
        return base[:, :, :wanted]
    extras = _extra_context_features(field, wanted - base.shape[-1])
    return np.concatenate([base, extras], axis=-1)


def _extra_context_features(field: np.ndarray, count: int) -> np.ndarray:
    h, w = field.shape
    if count <= 0:
        return np.empty((h, w, 0), dtype=np.float64)
    norm = (field.astype(np.float64) - float(np.mean(field))) / (
        float(np.std(field)) + 1e-6
    )
    bank = (
        norm * norm,
        np.tanh(norm),
        np.sin(norm),
        np.cos(norm),
        norm * np.roll(norm, 1, axis=0),
        norm * np.roll(norm, 1, axis=1),
    )
    out = [bank[i % len(bank)] for i in range(count)]
    return np.stack(out, axis=-1).astype(np.float64)


def _coordinate_embedding_features(
    target_hw: tuple[int, int],
    emb_size: int,
) -> np.ndarray:
    h, w = int(target_hw[0]), int(target_hw[1])
    if emb_size <= 0:
        return np.empty((h, w, 0), dtype=np.float64)
    yy, xx = np.mgrid[0:h, 0:w].astype(np.float64)
    y = (2.0 * yy / max(h - 1, 1)) - 1.0
    x = (2.0 * xx / max(w - 1, 1)) - 1.0
    bank = (
        y,
        x,
        y * x,
        y * y,
        x * x,
        np.sin(np.pi * y),
        np.cos(np.pi * y),
        np.sin(np.pi * x),
        np.cos(np.pi * x),
    )
    out = [bank[i % len(bank)] for i in range(int(emb_size))]
    return np.stack(out, axis=-1).astype(np.float64)


def _temporal_context_features(
    *,
    target_hw: tuple[int, int],
    model_size: SnervModelSizeConfig,
    lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...] | None,
    sequence_index: int | None,
) -> np.ndarray:
    h, w = int(target_hw[0]), int(target_hw[1])
    radius = int(model_size.temporal_context)
    if radius <= 0:
        return np.empty((h, w, 0), dtype=np.float64)
    if lf_sequence is None or sequence_index is None:
        raise SnervCarrierError(
            "temporal_context>0 requires receiver-visible lf_sequence and sequence_index"
        )
    return SnervTemporalExtension(radius=radius).sequence_delta_features(
        lf_sequence,
        index=int(sequence_index),
        target_hw=(h, w),
    )


def _flat_temporal_group(
    lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...],
    *,
    flat_index: int,
    group_count: int,
) -> tuple[list[np.ndarray], int]:
    """Return same-group LF timeline for a flat pair/frame/channel index."""

    if group_count < 1:
        raise SnervCarrierError("temporal group_count must be >= 1")
    idx = int(flat_index)
    if idx < 0 or idx >= len(lf_sequence):
        raise SnervCarrierError("temporal flat_index out of range")
    group = idx % int(group_count)
    sequence = [np.asarray(v, dtype=np.float64) for v in lf_sequence[group::group_count]]
    sequence_index = idx // int(group_count)
    if sequence_index >= len(sequence):
        raise SnervCarrierError("temporal sequence_index out of range")
    return sequence, sequence_index


def _decoder_features(
    field: np.ndarray,
    model_size: SnervModelSizeConfig,
    *,
    lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...] | None = None,
    sequence_index: int | None = None,
) -> np.ndarray:
    if model_size.adapter == SNERV_SPECTRA_PRESERVING_ADAPTER:
        context = MultiResolutionFusionUnit(scales=model_size.mfu_scales).features(
            field,
            feature_count=model_size.fc_dim,
            patch_radius=model_size.patch_radius,
        )
    else:
        context = _patch_features(
            field,
            patch_radius=model_size.patch_radius,
            feature_count=model_size.fc_dim,
        )
    coord = _coordinate_embedding_features(field.shape, model_size.emb_size)
    temporal = _temporal_context_features(
        target_hw=tuple(int(v) for v in field.shape),
        model_size=model_size,
        lf_sequence=lf_sequence,
        sequence_index=sequence_index,
    )
    return np.concatenate([context, coord, temporal], axis=-1)


def _hfr_for_model_size(model_size: SnervModelSizeConfig) -> HighFrequencyRestorer:
    return HighFrequencyRestorer(gain=model_size.hfr_gain)


def generate_hf_from_lf(
    lf: np.ndarray,
    decoder: HfGenerationDecoder,
    pyramid_template: WaveletPyramid,
    *,
    lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...] | None = None,
    sequence_index: int | None = None,
) -> list:
    """Generate the HF detail tuples from the LF approximation + decoder.

    Returns a ``pywt`` coefficient list ``[lf, (LH, HL, HH), ...]`` reconstructing
    the pyramid with GENERATED detail. The detail shapes are taken from
    ``pyramid_template`` (the analysis of the original frame) so the synthesis is
    well-formed; only their VALUES are generated.

    Generation runs coarsest-first: each level's detail is predicted from the
    running approximation, then synthesis lifts to the next finer approximation.
    """
    coeffs: list = [np.asarray(lf, dtype=np.float64)]
    approx = coeffs[0]
    detail_templates = pyramid_template.details  # coarsest-first
    if len(detail_templates) != decoder.levels:
        raise SnervCarrierError(
            f"decoder levels {decoder.levels} != template detail levels "
            f"{len(detail_templates)}"
        )
    for lvl, (lh_t, _hl_t, _hh_t) in enumerate(detail_templates):
        target_hw = (int(lh_t.shape[0]), int(lh_t.shape[1]))
        up = _upsample_nn(approx, target_hw)
        feats = _decoder_features(
            up,
            decoder.model_size,
            lf_sequence=lf_sequence,
            sequence_index=sequence_index,
        )
        kern = decoder.kernels[lvl]
        raw_details = (
            feats @ _kernel_vector(kern["LH"], decoder.model_size),
            feats @ _kernel_vector(kern["HL"], decoder.model_size),
            feats @ _kernel_vector(kern["HH"], decoder.model_size),
        )
        lh, hl, hh = _hfr_for_model_size(decoder.model_size).restore(raw_details, up)
        coeffs.append((lh, hl, hh))
        # Lift approx one level for the next (finer) detail prediction.
        approx = idwt2_multilevel(
            WaveletPyramid(
                coeffs=[approx, (lh, hl, hh)],
                levels=1,
                wavelet=pyramid_template.wavelet,
                orig_hw=(target_hw[0] * 2, target_hw[1] * 2),
            )
        )
    return coeffs


def fit_hf_decoder_least_squares(
    pyramids: list[WaveletPyramid],
    levels: int,
    *,
    model_size: SnervModelSizeConfig | None = None,
    temporal_group_count: int = 1,
) -> HfGenerationDecoder:
    """Fit the HF-generation decoder by per-level ridge least squares (the "train").

    For each level and subband we solve ``min_k ||F k - d||^2 + 1e-6||k||^2`` where
    ``F`` are the 3x3 patch features of the upsampled approximation and ``d`` are
    the TRUE detail coefficients (from the analysis of real frames). This is the
    closed-form, deterministic, $0-CPU fit of the generative decoder — the
    faithful (not toy) training: it learns to predict real HF detail from real LF
    on real video frames. Ridge is the canonical least-squares regularizer.
    """
    return fit_hf_decoder_weighted_least_squares(
        pyramids,
        levels=levels,
        detail_weight_pyramids=None,
        model_size=model_size,
        temporal_group_count=temporal_group_count,
    )


def fit_hf_decoder_weighted_least_squares(
    pyramids: list[WaveletPyramid],
    levels: int,
    *,
    detail_weight_pyramids: list[WaveletPyramid] | None = None,
    weight_floor: float = 1e-3,
    saliency_gain: float = 1.0,
    model_size: SnervModelSizeConfig | None = None,
    temporal_group_count: int = 1,
) -> HfGenerationDecoder:
    """Fit the HF decoder with optional score/saliency weights.

    ``detail_weight_pyramids`` carries one DWT-domain cotangent pyramid per
    training pyramid. Its detail subbands weight the HF prediction residuals, so
    detector-sensitive coefficients pull harder on the shared decoder weights.
    With ``detail_weight_pyramids=None`` this exactly reduces to ordinary ridge
    least squares.
    """

    if not pyramids:
        raise SnervCarrierError("need >=1 training pyramid")
    if detail_weight_pyramids is not None and len(detail_weight_pyramids) != len(pyramids):
        raise SnervCarrierError("detail_weight_pyramids length must match pyramids")
    if weight_floor <= 0:
        raise SnervCarrierError("weight_floor must be positive")
    if saliency_gain < 0:
        raise SnervCarrierError("saliency_gain must be non-negative")
    model_size = model_size or DEFAULT_SNERV_MODEL_SIZE
    temporal_group_count = int(temporal_group_count)
    if temporal_group_count < 1:
        raise SnervCarrierError("temporal_group_count must be >= 1")
    feature_count = int(model_size.feature_count)
    lf_sequence_all = [np.asarray(pyr.lf, dtype=np.float64) for pyr in pyramids]
    # Accumulate normal equations per (level, subband).
    accum: dict = {
        lvl: {
            sb: (
                np.zeros((feature_count, feature_count)),
                np.zeros(feature_count),
            )
            for sb in _DETAIL_KEYS
        }
        for lvl in range(levels)
    }
    for pyr_idx, pyr in enumerate(pyramids):
        temporal_sequence = None
        temporal_index = None
        if int(model_size.temporal_context) > 0:
            temporal_sequence, temporal_index = _flat_temporal_group(
                lf_sequence_all,
                flat_index=pyr_idx,
                group_count=temporal_group_count,
            )
        approx = pyr.lf
        for lvl, (lh, hl, hh) in enumerate(pyr.details):
            target_hw = (int(lh.shape[0]), int(lh.shape[1]))
            up = _upsample_nn(approx, target_hw)
            feats = _decoder_features(
                up,
                model_size,
                lf_sequence=temporal_sequence,
                sequence_index=temporal_index,
            ).reshape(-1, feature_count)
            for sb, d in (("LH", lh), ("HL", hl), ("HH", hh)):
                ata, atb = accum[lvl][sb]
                correction = _hfr_for_model_size(model_size).correction(
                    up,
                    subband=sb,
                    target_hw=tuple(int(v) for v in d.shape),
                )
                target = np.asarray(d, dtype=np.float64) - correction
                weights = _detail_weights_for_subband(
                    detail_weight_pyramids,
                    pyramid_index=pyr_idx,
                    level=lvl,
                    subband=sb,
                    expected_shape=d.shape,
                    floor=weight_floor,
                    saliency_gain=saliency_gain,
                ).reshape(-1)
                weighted_feats = feats * weights[:, None]
                ata += feats.T @ weighted_feats
                atb += feats.T @ (weights * target.reshape(-1))
            # Lift approx for next level (TRUE detail, the encoder path).
            approx = idwt2_multilevel(
                WaveletPyramid(
                    coeffs=[approx, (lh, hl, hh)],
                    levels=1,
                    wavelet=pyr.wavelet,
                    orig_hw=(target_hw[0] * 2, target_hw[1] * 2),
                )
            )
    kernels: dict = {}
    ridge = 1e-6
    for lvl in range(levels):
        kernels[lvl] = {}
        for sb in _DETAIL_KEYS:
            ata, atb = accum[lvl][sb]
            k = np.linalg.solve(ata + ridge * np.eye(feature_count), atb)
            kernels[lvl][sb] = k.reshape(_kernel_storage_shape(model_size))
    return HfGenerationDecoder(
        kernels=kernels,
        levels=int(levels),
        model_size=model_size,
    )


def _detail_weights_for_subband(
    detail_weight_pyramids: list[WaveletPyramid] | None,
    *,
    pyramid_index: int,
    level: int,
    subband: str,
    expected_shape: tuple[int, ...],
    floor: float,
    saliency_gain: float,
) -> np.ndarray:
    if detail_weight_pyramids is None:
        return np.ones(expected_shape, dtype=np.float64)
    subband_idx = _DETAIL_KEYS.index(subband)
    try:
        raw = np.asarray(
            detail_weight_pyramids[pyramid_index].details[level][subband_idx],
            dtype=np.float64,
        )
    except IndexError as exc:
        raise SnervCarrierError("detail weight pyramid shape/level mismatch") from exc
    if raw.shape != expected_shape:
        raise SnervCarrierError(
            f"detail weight shape {raw.shape} != expected {expected_shape}"
        )
    raw = np.abs(raw)
    finite = np.isfinite(raw)
    if not np.all(finite):
        raise SnervCarrierError("detail weights must be finite")
    positive = raw[raw > 0]
    if positive.size == 0 or saliency_gain == 0:
        return np.ones(expected_shape, dtype=np.float64)
    scale = float(np.mean(positive))
    if scale <= 0:
        return np.ones(expected_shape, dtype=np.float64)
    return floor + saliency_gain * (raw / scale)


def encode_frame_lf(
    frame_gray: np.ndarray,
    *,
    levels: int = 3,
    wavelet: str = DEFAULT_WAVELET,
) -> WaveletPyramid:
    """Analyze a single-channel frame into a wavelet pyramid (the carrier encoder)."""
    return dwt2_multilevel(frame_gray, levels=levels, wavelet=wavelet)


def quantize_lf(
    lf: np.ndarray,
    *,
    n_levels: int = 256,
    per_element_steps: np.ndarray | None = None,
) -> tuple[np.ndarray, float, float]:
    """Quantize the LF subband to integers (the stored rate).

    Two modes:
      * uniform: a single step solved from ``n_levels`` over the LF range.
      * per-element: ``per_element_steps`` (the L-inf allocation step map, one step
        per LF coefficient) — the inverse-steganalysis allocation pushed into the
        LF domain. Each coefficient is quantized at its OWN step.

    Returns ``(lf_quant_int, scale, zero)``. For per-element steps, ``scale`` is
    returned as 1.0 and the steps travel with the code (the dequant uses them).
    """
    lf = np.asarray(lf, dtype=np.float64)
    zero = float(lf.min())
    if per_element_steps is not None:
        steps = np.asarray(per_element_steps, dtype=np.float64).reshape(lf.shape)
        if np.any(steps <= 0):
            raise SnervCarrierError("per_element_steps must be strictly positive")
        q = np.round((lf - zero) / steps).astype(np.int64)
        return q, 1.0, zero
    rng = float(lf.max() - lf.min())
    scale = max(rng / max(n_levels - 1, 1), 1e-9)
    q = np.round((lf - zero) / scale).astype(np.int64)
    return q, scale, zero


def dequantize_lf(
    lf_quant: np.ndarray,
    scale: float,
    zero: float,
    *,
    per_element_steps: np.ndarray | None = None,
) -> np.ndarray:
    """Inverse of :func:`quantize_lf`."""
    q = np.asarray(lf_quant, dtype=np.float64)
    if per_element_steps is not None:
        steps = np.asarray(per_element_steps, dtype=np.float64).reshape(q.shape)
        return q * steps + zero
    return q * scale + zero


def decode_frame(
    code: SnervFrameCode,
    decoder: HfGenerationDecoder,
    *,
    lf_sequence: list[np.ndarray] | tuple[np.ndarray, ...] | None = None,
    sequence_index: int | None = None,
) -> np.ndarray:
    """Decode one frame: dequantize LF, GENERATE HF, synthesize (the inflate path).

    This is the receiver-side reconstruction: numpy-only, no scorer, no torch.
    The HF detail is generated from the stored LF by the decoder; the orthonormal
    synthesis lifts back to the pixel frame.
    """
    lf = dequantize_lf(
        code.lf_quant, code.lf_scale, code.lf_zero, per_element_steps=code.per_element_steps
    )
    # Build a template pyramid (shapes only) by analyzing a zero frame of orig size.
    template = dwt2_multilevel(
        np.zeros(code.orig_hw, dtype=np.float64), levels=code.levels, wavelet=code.wavelet
    )
    if lf.shape != template.lf.shape:
        raise SnervCarrierError(
            f"decoded LF shape {lf.shape} != template LF shape {template.lf.shape}"
        )
    coeffs = generate_hf_from_lf(
        lf,
        decoder,
        template,
        lf_sequence=lf_sequence,
        sequence_index=sequence_index,
    )
    pyr = WaveletPyramid(
        coeffs=coeffs, levels=code.levels, wavelet=code.wavelet, orig_hw=code.orig_hw
    )
    return idwt2_multilevel(pyr)
