# SPDX-License-Identifier: MIT
"""Lossless sparse custody for deterministic-support auxiliary training state.

The level-set trainer has optional trainable auxiliaries whose dense tensors are
large but whose legal update support is a small, deterministic subset of the
video grid.  Resume checkpoints must preserve those tensors and their optimizer
state without turning every preserved stage checkpoint into a multi-gigabyte
artifact.

This module stores spatial tensors in canonical row-major support order and
stores all non-spatial state losslessly.  The support itself is regenerated by
the trainer from counted/source-bound inputs; a SHA-256 over its exact indices
and non-zero float32 values makes that regeneration fail closed.
"""

from __future__ import annotations

import hashlib
import json
from collections.abc import Mapping
from dataclasses import dataclass

import numpy as np

SCHEMA = "tac.sparse_auxiliary_resume.v1"


@dataclass(frozen=True)
class PackedAuxiliaryState:
    """NPZ-ready packed arrays plus their canonical manifest."""

    live: dict[str, np.ndarray]
    optimizer: dict[str, np.ndarray]
    manifest_json: str
    support_count: int
    support_geometry_sha256: str


@dataclass(frozen=True)
class SelectedStateLeaf:
    """One host-safe leaf gathered before crossing the device/NumPy boundary.

    ``value`` is either the already-selected support rows or a genuinely small
    non-spatial leaf.  In particular, a caller must never pass the dense
    ``logical_shape`` value with ``encoding="support_rows"``.
    """

    value: np.ndarray
    logical_shape: tuple[int, ...]
    dtype: str
    encoding: str


@dataclass(frozen=True)
class ValidatedPackedAuxiliaryState:
    """Packed rows whose manifest/support/key/shape/dtype contract is proven."""

    live: dict[str, np.ndarray]
    optimizer: dict[str, np.ndarray]
    live_entries: tuple[dict[str, object], ...]
    optimizer_entries: tuple[dict[str, object], ...]
    support_indices: np.ndarray
    dense_shape: tuple[int, ...]


@dataclass(frozen=True)
class SparseSupportGeometry:
    """Canonical sparse support without a dense host mask."""

    indices: np.ndarray
    values: np.ndarray
    spatial_shape: tuple[int, ...]


def _canonical_support(
    support_mask: np.ndarray | SparseSupportGeometry,
    *,
    dense_shape: tuple[int, ...],
) -> tuple[np.ndarray, str]:
    """Return canonical flat support indices and exact support-geometry hash."""

    if len(dense_shape) < 2 or int(dense_shape[-1]) <= 0:
        raise ValueError(f"dense_shape must end in a positive channel axis, got {dense_shape}")
    spatial_shape = tuple(int(v) for v in dense_shape[:-1])
    if isinstance(support_mask, SparseSupportGeometry):
        declared_shape = tuple(int(v) for v in support_mask.spatial_shape)
        if declared_shape != spatial_shape:
            raise ValueError(
                f"sparse support shape {declared_shape} does not match dense "
                f"spatial shape {spatial_shape}"
            )
        indices64 = np.asarray(support_mask.indices, dtype=np.int64).reshape(-1)
        values32 = np.asarray(support_mask.values, dtype=np.float32).reshape(-1)
        if indices64.size != values32.size:
            raise ValueError("sparse support indices/value count differs")
        if indices64.size == 0:
            raise ValueError("support must contain at least one active row")
        grid_size = int(np.prod(spatial_shape, dtype=np.int64))
        if (
            np.any(indices64 < 0)
            or np.any(indices64 >= grid_size)
            or (
                indices64.size > 1
                and np.any(indices64[1:] <= indices64[:-1])
            )
        ):
            raise ValueError(
                "sparse support indices must be unique, strictly increasing, and in range"
            )
        if not np.isfinite(values32).all() or np.any(values32 == 0.0):
            raise ValueError(
                "sparse support values must be finite and non-zero"
            )
        if grid_size > np.iinfo(np.uint32).max:
            raise ValueError("support grid exceeds canonical uint32 index range")
        indices = np.asarray(indices64, dtype="<u4")
        values = np.asarray(values32, dtype="<f4")
        digest = hashlib.sha256()
        digest.update(SCHEMA.encode("ascii"))
        digest.update(np.asarray(spatial_shape, dtype="<u8").tobytes(order="C"))
        digest.update(indices.tobytes(order="C"))
        digest.update(values.tobytes(order="C"))
        return indices, digest.hexdigest()

    mask = np.asarray(support_mask)
    if mask.shape == (*spatial_shape, 1):
        mask = mask[..., 0]
    if tuple(mask.shape) != spatial_shape:
        raise ValueError(
            f"support mask shape {mask.shape} does not match dense spatial shape {spatial_shape}"
        )
    mask32 = np.asarray(mask, dtype=np.float32)
    if not np.isfinite(mask32).all():
        raise ValueError("support mask contains non-finite values")
    flat = mask32.reshape(-1)
    indices64 = np.flatnonzero(flat != 0.0)
    if indices64.size == 0:
        raise ValueError("support must contain at least one active row")
    if flat.size > np.iinfo(np.uint32).max:
        raise ValueError("support grid exceeds canonical uint32 index range")
    indices = np.asarray(indices64, dtype="<u4")
    values = np.asarray(flat[indices64], dtype="<f4")
    digest = hashlib.sha256()
    digest.update(SCHEMA.encode("ascii"))
    digest.update(np.asarray(spatial_shape, dtype="<u8").tobytes(order="C"))
    digest.update(indices.tobytes(order="C"))
    digest.update(values.tobytes(order="C"))
    return indices, digest.hexdigest()


def _pack_tree(
    state: Mapping[str, np.ndarray],
    *,
    support_indices: np.ndarray,
    dense_shape: tuple[int, ...],
) -> tuple[dict[str, np.ndarray], list[dict[str, object]]]:
    if not state:
        raise ValueError("auxiliary state tree must not be empty")
    packed: dict[str, np.ndarray] = {}
    entries: list[dict[str, object]] = []
    row_count = int(np.prod(dense_shape[:-1], dtype=np.int64))
    channel_shape = tuple(int(v) for v in dense_shape[len(dense_shape) - 1 :])
    index64 = np.asarray(support_indices, dtype=np.int64)
    for key in sorted(str(k) for k in state):
        arr = np.asarray(state[key])
        if arr.dtype.kind not in "fiub":
            raise ValueError(f"unsupported auxiliary state dtype for {key!r}: {arr.dtype}")
        if tuple(arr.shape) == dense_shape:
            rows = arr.reshape((row_count, *channel_shape))
            support_rows = np.asarray(rows[index64]).copy()
            if int(np.count_nonzero(arr)) != int(np.count_nonzero(support_rows)):
                raise ValueError(
                    f"auxiliary tensor {key!r} has non-zero values outside deterministic support"
                )
            packed[key] = support_rows
            encoding = "support_rows"
        else:
            packed[key] = arr.copy()
            encoding = "full"
        entries.append(
            {
                "key": key,
                "logical_shape": [int(v) for v in arr.shape],
                "dtype": arr.dtype.str,
                "encoding": encoding,
            }
        )
    return packed, entries


def pack_sparse_auxiliary_state(
    *,
    component: str,
    live_state: Mapping[str, np.ndarray],
    optimizer_state: Mapping[str, np.ndarray],
    support_mask: np.ndarray,
    dense_shape: tuple[int, ...],
    optimizer_family: str = "adamw",
) -> PackedAuxiliaryState:
    """Pack live and optimizer state without losing a single represented value."""

    component_name = str(component).strip()
    if not component_name:
        raise ValueError("component name must be non-empty")
    normalized_shape = tuple(int(v) for v in dense_shape)
    support_indices, support_sha = _canonical_support(
        support_mask, dense_shape=normalized_shape
    )
    live, live_entries = _pack_tree(
        live_state,
        support_indices=support_indices,
        dense_shape=normalized_shape,
    )
    optimizer, optimizer_entries = _pack_tree(
        optimizer_state,
        support_indices=support_indices,
        dense_shape=normalized_shape,
    )
    manifest = {
        "schema": SCHEMA,
        "component": component_name,
        "dense_shape": list(normalized_shape),
        "support_count": int(support_indices.size),
        "support_geometry_sha256": support_sha,
        "optimizer_family": str(optimizer_family),
        "live": live_entries,
        "optimizer": optimizer_entries,
    }
    return PackedAuxiliaryState(
        live=live,
        optimizer=optimizer,
        manifest_json=json.dumps(
            manifest, sort_keys=True, separators=(",", ":"), allow_nan=False
        ),
        support_count=int(support_indices.size),
        support_geometry_sha256=support_sha,
    )


def _pack_selected_tree(
    state: Mapping[str, SelectedStateLeaf],
    *,
    support_count: int,
    dense_shape: tuple[int, ...],
) -> tuple[dict[str, np.ndarray], list[dict[str, object]]]:
    """Validate leaves that were gathered on-device and build their manifest."""

    if not state:
        raise ValueError("selected auxiliary state tree must not be empty")
    channel_shape = tuple(int(v) for v in dense_shape[-1:])
    packed: dict[str, np.ndarray] = {}
    entries: list[dict[str, object]] = []
    for key in sorted(str(name) for name in state):
        leaf = state[key]
        if not isinstance(leaf, SelectedStateLeaf):
            raise TypeError(
                f"selected auxiliary state {key!r} is not a SelectedStateLeaf"
            )
        value = np.asarray(leaf.value)
        logical_shape = tuple(int(v) for v in leaf.logical_shape)
        try:
            logical_dtype = np.dtype(str(leaf.dtype))
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"selected auxiliary state dtype is malformed for {key!r}"
            ) from exc
        if value.dtype != logical_dtype:
            raise ValueError(
                f"selected auxiliary state dtype mismatch for {key!r}: "
                f"{value.dtype} != {logical_dtype}"
            )
        if value.dtype.kind in "fc" and not np.isfinite(value).all():
            raise ValueError(
                f"selected auxiliary state contains non-finite values for {key!r}"
            )
        encoding = str(leaf.encoding)
        if encoding == "support_rows":
            if logical_shape != dense_shape:
                raise ValueError(
                    f"support-row logical shape mismatch for {key!r}: "
                    f"{logical_shape} != {dense_shape}"
                )
            expected_shape = (int(support_count), *channel_shape)
            if tuple(value.shape) != expected_shape:
                raise ValueError(
                    f"selected support-row shape mismatch for {key!r}: "
                    f"{value.shape} != {expected_shape}"
                )
        elif encoding == "full":
            if tuple(value.shape) != logical_shape:
                raise ValueError(
                    f"selected full-state shape mismatch for {key!r}: "
                    f"{value.shape} != {logical_shape}"
                )
        else:
            raise ValueError(
                f"unknown selected auxiliary state encoding for {key!r}: "
                f"{encoding!r}"
            )
        packed[key] = value.copy()
        entries.append(
            {
                "key": key,
                "logical_shape": list(logical_shape),
                "dtype": logical_dtype.str,
                "encoding": encoding,
            }
        )
    return packed, entries


def pack_sparse_auxiliary_selected_state(
    *,
    component: str,
    live_state: Mapping[str, SelectedStateLeaf],
    optimizer_state: Mapping[str, SelectedStateLeaf],
    support_mask: np.ndarray,
    dense_shape: tuple[int, ...],
    optimizer_family: str = "adamw",
) -> PackedAuxiliaryState:
    """Pack a sparse auxiliary without ever accepting its dense host tensors.

    The trainer gathers support rows in MLX first, then converts only those
    selected rows to NumPy and calls this function.  This API intentionally
    accepts :class:`SelectedStateLeaf` rather than arbitrary array-likes so an
    accidental dense ``np.asarray(device_tensor)`` cannot hide inside packing.
    """

    component_name = str(component).strip()
    if not component_name:
        raise ValueError("component name must be non-empty")
    normalized_shape = tuple(int(v) for v in dense_shape)
    support_indices, support_sha = _canonical_support(
        support_mask, dense_shape=normalized_shape
    )
    live, live_entries = _pack_selected_tree(
        live_state,
        support_count=int(support_indices.size),
        dense_shape=normalized_shape,
    )
    optimizer, optimizer_entries = _pack_selected_tree(
        optimizer_state,
        support_count=int(support_indices.size),
        dense_shape=normalized_shape,
    )
    manifest = {
        "schema": SCHEMA,
        "component": component_name,
        "dense_shape": list(normalized_shape),
        "support_count": int(support_indices.size),
        "support_geometry_sha256": support_sha,
        "optimizer_family": str(optimizer_family),
        "live": live_entries,
        "optimizer": optimizer_entries,
    }
    return PackedAuxiliaryState(
        live=live,
        optimizer=optimizer,
        manifest_json=json.dumps(
            manifest, sort_keys=True, separators=(",", ":"), allow_nan=False
        ),
        support_count=int(support_indices.size),
        support_geometry_sha256=support_sha,
    )


def _restore_tree(
    packed: Mapping[str, np.ndarray],
    entries: list[dict[str, object]],
    *,
    support_indices: np.ndarray,
    dense_shape: tuple[int, ...],
) -> dict[str, np.ndarray]:
    expected_keys = [str(entry.get("key", "")) for entry in entries]
    if not all(expected_keys) or len(set(expected_keys)) != len(expected_keys):
        raise ValueError("auxiliary manifest has missing or duplicate state keys")
    if set(packed) != set(expected_keys):
        raise ValueError(
            "auxiliary state keyset mismatch "
            f"(missing={sorted(set(expected_keys) - set(packed))}, "
            f"extra={sorted(set(packed) - set(expected_keys))})"
        )
    row_count = int(np.prod(dense_shape[:-1], dtype=np.int64))
    channel_shape = tuple(int(v) for v in dense_shape[len(dense_shape) - 1 :])
    index64 = np.asarray(support_indices, dtype=np.int64)
    restored: dict[str, np.ndarray] = {}
    for entry in entries:
        key = str(entry["key"])
        logical_shape = tuple(int(v) for v in entry.get("logical_shape", []))
        dtype = np.dtype(str(entry.get("dtype", "")))
        encoding = str(entry.get("encoding", ""))
        value = np.asarray(packed[key])
        if value.dtype != dtype:
            raise ValueError(
                f"auxiliary state dtype mismatch for {key!r}: {value.dtype} != {dtype}"
            )
        if value.dtype.kind in "fc" and not np.isfinite(value).all():
            raise ValueError(
                f"auxiliary state contains non-finite values for {key!r}"
            )
        if encoding == "support_rows":
            if logical_shape != dense_shape:
                raise ValueError(
                    f"support-row logical shape mismatch for {key!r}: "
                    f"{logical_shape} != {dense_shape}"
                )
            expected_packed_shape = (int(index64.size), *channel_shape)
            if tuple(value.shape) != expected_packed_shape:
                raise ValueError(
                    f"packed support-row shape mismatch for {key!r}: "
                    f"{value.shape} != {expected_packed_shape}"
                )
            rows = np.zeros((row_count, *channel_shape), dtype=dtype)
            rows[index64] = value
            restored[key] = rows.reshape(dense_shape)
        elif encoding == "full":
            if tuple(value.shape) != logical_shape:
                raise ValueError(
                    f"full auxiliary state shape mismatch for {key!r}: "
                    f"{value.shape} != {logical_shape}"
                )
            restored[key] = value.copy()
        else:
            raise ValueError(f"unknown auxiliary state encoding for {key!r}: {encoding!r}")
    return restored


def _validate_packed_tree(
    packed: Mapping[str, np.ndarray],
    entries: list[dict[str, object]],
    *,
    support_count: int,
    dense_shape: tuple[int, ...],
) -> dict[str, np.ndarray]:
    """Validate packed leaves without allocating their dense logical tensors."""

    expected_keys = [str(entry.get("key", "")) for entry in entries]
    if not all(expected_keys) or len(set(expected_keys)) != len(expected_keys):
        raise ValueError("auxiliary manifest has missing or duplicate state keys")
    if set(packed) != set(expected_keys):
        raise ValueError(
            "auxiliary state keyset mismatch "
            f"(missing={sorted(set(expected_keys) - set(packed))}, "
            f"extra={sorted(set(packed) - set(expected_keys))})"
        )
    channel_shape = tuple(int(v) for v in dense_shape[-1:])
    validated: dict[str, np.ndarray] = {}
    for entry in entries:
        key = str(entry["key"])
        try:
            logical_shape = tuple(int(v) for v in entry.get("logical_shape", []))
            dtype = np.dtype(str(entry.get("dtype", "")))
        except (TypeError, ValueError) as exc:
            raise ValueError(
                f"auxiliary manifest entry is malformed for {key!r}"
            ) from exc
        encoding = str(entry.get("encoding", ""))
        value = np.asarray(packed[key])
        if value.dtype != dtype:
            raise ValueError(
                f"auxiliary state dtype mismatch for {key!r}: {value.dtype} != {dtype}"
            )
        if value.dtype.kind in "fc" and not np.isfinite(value).all():
            raise ValueError(
                f"auxiliary state contains non-finite values for {key!r}"
            )
        if encoding == "support_rows":
            if logical_shape != dense_shape:
                raise ValueError(
                    f"support-row logical shape mismatch for {key!r}: "
                    f"{logical_shape} != {dense_shape}"
                )
            expected_shape = (int(support_count), *channel_shape)
            if tuple(value.shape) != expected_shape:
                raise ValueError(
                    f"packed support-row shape mismatch for {key!r}: "
                    f"{value.shape} != {expected_shape}"
                )
        elif encoding == "full":
            if tuple(value.shape) != logical_shape:
                raise ValueError(
                    f"full auxiliary state shape mismatch for {key!r}: "
                    f"{value.shape} != {logical_shape}"
                )
        else:
            raise ValueError(
                f"unknown auxiliary state encoding for {key!r}: {encoding!r}"
            )
        validated[key] = value
    return validated


def validate_sparse_auxiliary_packed_state(
    *,
    component: str,
    packed_live: Mapping[str, np.ndarray],
    packed_optimizer: Mapping[str, np.ndarray],
    manifest_json: str,
    support_mask: np.ndarray,
    expected_optimizer_family: str | None = None,
) -> ValidatedPackedAuxiliaryState:
    """Prove a packed state before a device-side sparse scatter restore."""

    try:
        manifest = json.loads(str(manifest_json))
    except (TypeError, ValueError, json.JSONDecodeError) as exc:
        raise ValueError("malformed auxiliary state manifest") from exc
    if manifest.get("schema") != SCHEMA:
        raise ValueError(f"unsupported auxiliary state schema: {manifest.get('schema')!r}")
    if manifest.get("component") != str(component):
        raise ValueError(
            f"auxiliary component mismatch: {manifest.get('component')!r} != {component!r}"
        )
    optimizer_family = str(manifest.get("optimizer_family", ""))
    if not optimizer_family:
        raise ValueError("auxiliary optimizer family is missing")
    if (
        expected_optimizer_family is not None
        and optimizer_family != str(expected_optimizer_family)
    ):
        raise ValueError(
            "auxiliary optimizer family changed on restore: "
            f"{optimizer_family!r} != {expected_optimizer_family!r}"
        )
    dense_shape = tuple(int(v) for v in manifest.get("dense_shape", []))
    support_indices, support_sha = _canonical_support(
        support_mask, dense_shape=dense_shape
    )
    support_count = int(support_indices.size)
    if int(manifest.get("support_count", -1)) != support_count:
        raise ValueError("auxiliary deterministic support count changed on restore")
    if str(manifest.get("support_geometry_sha256", "")) != support_sha:
        raise ValueError("auxiliary deterministic support geometry changed on restore")
    live_entries = manifest.get("live")
    optimizer_entries = manifest.get("optimizer")
    if not isinstance(live_entries, list) or not isinstance(optimizer_entries, list):
        raise ValueError("auxiliary manifest state inventories must be lists")
    live = _validate_packed_tree(
        packed_live,
        live_entries,
        support_count=support_count,
        dense_shape=dense_shape,
    )
    optimizer = _validate_packed_tree(
        packed_optimizer,
        optimizer_entries,
        support_count=support_count,
        dense_shape=dense_shape,
    )
    return ValidatedPackedAuxiliaryState(
        live=live,
        optimizer=optimizer,
        live_entries=tuple(dict(entry) for entry in live_entries),
        optimizer_entries=tuple(dict(entry) for entry in optimizer_entries),
        support_indices=support_indices,
        dense_shape=dense_shape,
    )


def restore_sparse_auxiliary_state(
    *,
    component: str,
    packed_live: Mapping[str, np.ndarray],
    packed_optimizer: Mapping[str, np.ndarray],
    manifest_json: str,
    support_mask: np.ndarray,
    expected_optimizer_family: str | None = None,
) -> tuple[dict[str, np.ndarray], dict[str, np.ndarray]]:
    """Reinflate exact dense state after proving regenerated support identity."""

    validated = validate_sparse_auxiliary_packed_state(
        component=component,
        packed_live=packed_live,
        packed_optimizer=packed_optimizer,
        manifest_json=manifest_json,
        support_mask=support_mask,
        expected_optimizer_family=expected_optimizer_family,
    )
    return (
        _restore_tree(
            validated.live,
            list(validated.live_entries),
            support_indices=validated.support_indices,
            dense_shape=validated.dense_shape,
        ),
        _restore_tree(
            validated.optimizer,
            list(validated.optimizer_entries),
            support_indices=validated.support_indices,
            dense_shape=validated.dense_shape,
        ),
    )
