"""Witness behavior/curriculum DSL (operator riff 2026-06-28, task #189).

A declarative, recursion+math front-end for the level-set witness training program.
It does NOT reimplement training — it COMPILES to the proven trainer CLI
(``experiments/train_levelset_witness_realized_through_R_mlx.py``), VALIDATES every
emitted flag against the trainer's real argparse (never-invent-flags, structural),
and ENFORCES the desired-behavior clauses (preserve / contain / authority) so every
A/B arm and the composed theta* program is auto-checkpointed, memory-bounded, and
authority-tagged BY CONSTRUCTION.

This is Layer 0 ("the rails") of the here->theta* bridge (DAG FEED-gv): every A/B
arm is ``BASELINE.with_lever(...)`` and theta* is the composition of the winning
fragments — each a term/relaxation of the SAME contest energy S.
"""

from tac.witness_dsl.curriculum_dsl import (
    Anneal,
    Authority,
    Contain,
    Freeze,
    Lever,
    Preserve,
    Regularizer,
    Stage,
    WitnessProgram,
    real_trainer_flags,
    real_store_true_flags,
    BASELINE,
    PoseDecouple,
    Muon,
    DirectionalBasis,
    TauFrozen,
    SoftBoundary,
    FiLMFix,
    LanePrior,
    AnalyticLaneRenderBand,
    StiefelW,
    CodeSpectralEntropy,
    DM1Minimal,
    MarginSaliency,
    UniWARD,
    openpilot_seeded_opening,
)
from tac.witness_dsl.campaign import (
    Arm,
    ArmResult,
    Cycle,
    PrimingContext,
    ScalePass,
    StageDecision,
    StagePolicy,
    SynergyResult,
    advance_to_l7,
    advance_to_muon,
    compose_theta_star,
    curvelet_scale_passes,
    decide_next_stage,
    expand_cycles,
    extend_stage,
    harvest_arm,
    measure_synergy,
    plan_adaptive_step,
    plan_campaign,
    priming_chain,
    rerun_stage_new_config,
    scale_progression,
    select_synergistic_combos,
    select_winners,
    stack_next_program,
    stage_trajectory,
    synergy_map,
)
from tac.witness_dsl.gauge import (
    CANONICAL_GAUGE,
    COMPONENT_GAUGES,
    POLY_BASE_DSEG_FLOOR,
    CarrierGauge,
    GaugeChoice,
    GaugeComponent,
    GaugeCost,
    GaugeCostError,
    GaugeCostTable,
    GaugeVerdict,
    GaugeViolation,
    GenerationGauge,
    TopologyLossGauge,
    MovablesGauge,
    PoseGauge,
    ResidualGauge,
    WarpGauge,
    compose_gauged_program,
    component_of,
    default_cost_table,
    fix_gauge,
)

__all__ = [
    "Anneal",
    "Authority",
    "Contain",
    "Freeze",
    "Lever",
    "Preserve",
    "Regularizer",
    "Stage",
    "WitnessProgram",
    "real_trainer_flags",
    "real_store_true_flags",
    "BASELINE",
    "PoseDecouple",
    "Muon",
    "DirectionalBasis",
    "TauFrozen",
    "SoftBoundary",
    "FiLMFix",
    "LanePrior",
    "AnalyticLaneRenderBand",
    "StiefelW",
    "CodeSpectralEntropy",
    "DM1Minimal",
    "MarginSaliency",
    "UniWARD",
    "openpilot_seeded_opening",
    # campaign engine
    "Arm",
    "ArmResult",
    "Cycle",
    "PrimingContext",
    "ScalePass",
    "StageDecision",
    "StagePolicy",
    "SynergyResult",
    "advance_to_l7",
    "advance_to_muon",
    "compose_theta_star",
    "curvelet_scale_passes",
    "decide_next_stage",
    "expand_cycles",
    "extend_stage",
    "harvest_arm",
    "measure_synergy",
    "plan_adaptive_step",
    "plan_campaign",
    "priming_chain",
    "rerun_stage_new_config",
    "scale_progression",
    "select_synergistic_combos",
    "select_winners",
    "stack_next_program",
    "stage_trajectory",
    "synergy_map",
    # gauge meta-layer (FEED-ji): the equations→GAUGE→DSL→DAG bridge
    "CANONICAL_GAUGE",
    "COMPONENT_GAUGES",
    "POLY_BASE_DSEG_FLOOR",
    "CarrierGauge",
    "GaugeChoice",
    "GaugeComponent",
    "GaugeCost",
    "GaugeCostError",
    "GaugeCostTable",
    "GaugeVerdict",
    "GaugeViolation",
    "GenerationGauge",
    "TopologyLossGauge",
    "MovablesGauge",
    "PoseGauge",
    "ResidualGauge",
    "WarpGauge",
    "compose_gauged_program",
    "component_of",
    "default_cost_table",
    "fix_gauge",
]
