# SPDX-License-Identifier: MIT
"""HPRC: Hierarchical Predictive Receiver Codec.

HPRC is the rate-first substrate lane that turns PR95/HNeRV control lessons,
Z8/HPC teacher surfaces, learned residual tokenization, and scorer-conditioned
allocation into one byte-closed archive contract.
"""

from __future__ import annotations

from tac.substrates.hprc.archive import (
    HPRC_MAGIC,
    HPRC_SCHEMA_VERSION,
    HprcPacket,
    HprcPacketConfig,
    HprcSection,
    HprcSectionKind,
    pack_hprc_packet,
    parse_hprc_packet,
)
from tac.substrates.hprc.archive_candidate import (
    HPRC_ARCHIVE_BOUND_ADAPTER_ID,
    HPRC_ARCHIVE_CANDIDATE_FAMILY,
    HPRC_ARCHIVE_TRANSFORM_KIND,
    build_hprc_section_mutation_proof,
    build_minimal_hprc_v0_packet,
    export_hprc_archive_bytes,
)
from tac.substrates.hprc.campaign import (
    HPRC_CAMPAIGN_MANIFEST_SCHEMA,
    HPRC_EXACT_READINESS_REFUSAL_SCHEMA,
    HPRC_V0_EXACT_READINESS_BLOCKERS,
    HprcCampaignRunResult,
    build_hprc_campaign_manifest,
    build_hprc_exact_readiness_refusal,
    materialize_minimal_hprc_campaign,
)
from tac.substrates.hprc.exact_gate import (
    HPRC_INCREMENTAL_EXACT_GATE_BRIDGE_SCHEMA,
    build_hprc_incremental_exact_gate_bridge,
    write_hprc_incremental_exact_gate_bridge,
)
from tac.substrates.hprc.lineage import (
    HPRC_FAMILY_BINDINGS,
    HPRC_OPTIMIZATION_LEVERS,
    HprcFamilyBinding,
    HprcOptimizationLever,
    HprcRole,
    get_binding,
    hprc_campaign_manifest,
    primary_rate_collapse_candidates,
    residual_sidecar_candidates,
)
from tac.substrates.hprc.pr95_adapter import (
    PR95_HNERV_DECODER_FAMILY_ID,
    PR95_RGB_COLOR_TRANSFORM_ID,
    Pr95HprcControlPacket,
    build_pr95_hprc_control_packet,
    parse_pr95_hnerv_payload,
)
from tac.substrates.hprc.rate_collapse import (
    DEFAULT_RATE_COLLAPSE_SECTIONS,
    DEFAULT_RESIDUAL_TOKEN_COLLAPSE_SPECS,
    HPRC_RATE_COLLAPSE_EXACT_EXECUTION_SCHEMA,
    HPRC_RATE_COLLAPSE_REPORT_SCHEMA,
    HPRC_RATE_COLLAPSE_VARIANT_SCHEMA,
    ResidualTokenCollapseSpec,
    build_rate_collapse_exact_execution_report,
    collapse_residual_tokens,
    parse_rate_collapse_sections,
    parse_residual_token_collapse_specs,
    rate_collapse_variant_groups,
    transcode_compact_receiver_residual_tokens,
    transcode_compact_receiver_sections,
)
from tac.substrates.hprc.representation_spine import (
    HPRC_REPRESENTATION_SPINE_MANIFEST_SCHEMA,
    HPRC_REPRESENTATION_SPINE_PROJECTION_SCHEMA,
    HPRC_REPRESENTATION_SPINE_SCHEMA,
    PACT_NERV_LEN_PREFIXED_HEADER_FMT,
    PACT_NERV_LEN_PREFIXED_HEADER_SIZE,
    REPRESENTATION_FAMILY_IDS,
    HprcRepresentationFamily,
    HprcRepresentationSpineError,
    HprcRepresentationSpinePacket,
    build_generic_neural_spine_packet,
    build_packed_hnerv_spine_from_archive,
    build_pact_nerv_len_prefixed_spine_from_archive,
    build_pact_nerv_len_prefixed_spine_from_archive_payload,
    build_pact_nerv_vq_spine_from_archive,
    build_pact_nerv_vq_spine_from_archive_payload,
    build_pr95_hnerv_spine_from_archive,
    build_representation_spine_packet,
    write_representation_spine_projection,
)
from tac.substrates.hprc.resolution_contract import (
    CONTEST_FRAME_COUNT,
    CONTEST_PAIR_COUNT,
    HPRC_RESOLUTION_CONTRACT_SCHEMA,
    POSENET_PAIR_FRAME_COUNT,
    POSENET_YUV6_CHANNEL_COUNT,
    RGB_CHANNEL_COUNT,
    hprc_resolution_contract,
)
from tac.substrates.hprc.spine_acquisition import (
    DEFAULT_BASE_RENDERER_BYTE_CEILINGS,
    HPRC_SPINE_ACQUISITION_REPORT_SCHEMA,
    build_spine_acquisition_report,
)
from tac.substrates.hprc.training_adapter import (
    HPRC_LONG_TRAINING_ARCHIVE_EXPORT_SCHEMA,
    HPRC_LONG_TRAINING_SUBSTRATE_ID,
    HprcCompactReceiverLongTrainingAdapter,
    HprcCompactReceiverTrainingModel,
    HprcGainBounds,
)

__all__ = [
    "CONTEST_FRAME_COUNT",
    "CONTEST_PAIR_COUNT",
    "DEFAULT_BASE_RENDERER_BYTE_CEILINGS",
    "DEFAULT_RATE_COLLAPSE_SECTIONS",
    "DEFAULT_RESIDUAL_TOKEN_COLLAPSE_SPECS",
    "HPRC_ARCHIVE_BOUND_ADAPTER_ID",
    "HPRC_ARCHIVE_CANDIDATE_FAMILY",
    "HPRC_ARCHIVE_TRANSFORM_KIND",
    "HPRC_CAMPAIGN_MANIFEST_SCHEMA",
    "HPRC_EXACT_READINESS_REFUSAL_SCHEMA",
    "HPRC_FAMILY_BINDINGS",
    "HPRC_INCREMENTAL_EXACT_GATE_BRIDGE_SCHEMA",
    "HPRC_LONG_TRAINING_ARCHIVE_EXPORT_SCHEMA",
    "HPRC_LONG_TRAINING_SUBSTRATE_ID",
    "HPRC_MAGIC",
    "HPRC_OPTIMIZATION_LEVERS",
    "HPRC_RATE_COLLAPSE_EXACT_EXECUTION_SCHEMA",
    "HPRC_RATE_COLLAPSE_REPORT_SCHEMA",
    "HPRC_RATE_COLLAPSE_VARIANT_SCHEMA",
    "HPRC_REPRESENTATION_SPINE_MANIFEST_SCHEMA",
    "HPRC_REPRESENTATION_SPINE_PROJECTION_SCHEMA",
    "HPRC_REPRESENTATION_SPINE_SCHEMA",
    "HPRC_RESOLUTION_CONTRACT_SCHEMA",
    "HPRC_SCHEMA_VERSION",
    "HPRC_SPINE_ACQUISITION_REPORT_SCHEMA",
    "HPRC_V0_EXACT_READINESS_BLOCKERS",
    "PACT_NERV_LEN_PREFIXED_HEADER_FMT",
    "PACT_NERV_LEN_PREFIXED_HEADER_SIZE",
    "POSENET_PAIR_FRAME_COUNT",
    "POSENET_YUV6_CHANNEL_COUNT",
    "PR95_HNERV_DECODER_FAMILY_ID",
    "PR95_RGB_COLOR_TRANSFORM_ID",
    "REPRESENTATION_FAMILY_IDS",
    "RGB_CHANNEL_COUNT",
    "HprcCampaignRunResult",
    "HprcCompactReceiverLongTrainingAdapter",
    "HprcCompactReceiverTrainingModel",
    "HprcFamilyBinding",
    "HprcGainBounds",
    "HprcOptimizationLever",
    "HprcPacket",
    "HprcPacketConfig",
    "HprcRepresentationFamily",
    "HprcRepresentationSpineError",
    "HprcRepresentationSpinePacket",
    "HprcRole",
    "HprcSection",
    "HprcSectionKind",
    "Pr95HprcControlPacket",
    "ResidualTokenCollapseSpec",
    "build_generic_neural_spine_packet",
    "build_hprc_campaign_manifest",
    "build_hprc_exact_readiness_refusal",
    "build_hprc_incremental_exact_gate_bridge",
    "build_hprc_section_mutation_proof",
    "build_minimal_hprc_v0_packet",
    "build_packed_hnerv_spine_from_archive",
    "build_pact_nerv_len_prefixed_spine_from_archive",
    "build_pact_nerv_len_prefixed_spine_from_archive_payload",
    "build_pact_nerv_vq_spine_from_archive",
    "build_pact_nerv_vq_spine_from_archive_payload",
    "build_pr95_hnerv_spine_from_archive",
    "build_pr95_hprc_control_packet",
    "build_rate_collapse_exact_execution_report",
    "build_representation_spine_packet",
    "build_spine_acquisition_report",
    "collapse_residual_tokens",
    "export_hprc_archive_bytes",
    "get_binding",
    "hprc_campaign_manifest",
    "hprc_resolution_contract",
    "materialize_minimal_hprc_campaign",
    "pack_hprc_packet",
    "parse_hprc_packet",
    "parse_pr95_hnerv_payload",
    "parse_rate_collapse_sections",
    "parse_residual_token_collapse_specs",
    "primary_rate_collapse_candidates",
    "rate_collapse_variant_groups",
    "residual_sidecar_candidates",
    "transcode_compact_receiver_residual_tokens",
    "transcode_compact_receiver_sections",
    "write_hprc_incremental_exact_gate_bridge",
    "write_representation_spine_projection",
]
