# SPDX-License-Identifier: MIT
# ruff: noqa: F401
"""Reusable packet-compiler byte grammar primitives.

This package is intentionally narrow. It exposes only implemented, tested
transducers; broader PacketIR APIs remain roadmap items until their identity
vectors and strict no-op proofs land.
"""

from __future__ import annotations

from tac.packet_compiler.pr81_quantizr import (
    PR81_POS_LEVELS,
    FP4Codebook,
    decode_router_actions,
    encode_router_actions,
    pack_nibbles,
    unpack_nibbles,
)
from tac.packet_compiler.pr84_adaptive_mask import (
    AdaptiveContextSpec,
    decode_adaptive_context_stream,
    encode_adaptive_context_stream,
)
from tac.packet_compiler.pr91_hpac_grammar import (
    MAGIC_QH0,
    MAGIC_QM0,
    QMQHHeader,
    decode_categorical_stream,
    emit_qmqh_header,
    encode_categorical_stream,
    pack_hi_lo_split,
    parse_qmqh_header,
    unpack_hi_lo_split,
)
from tac.packet_compiler.pr92_joint_stream import (
    MAGIC_RMC1,
    MAGIC_RSA1,
    MAGIC_RSB1,
    RMC1Composite,
    RSA1Side,
    RSB1Side,
    pack_rmc1_composite,
    pack_rsa1_side,
    pack_rsb1_side,
    unpack_rmc1_composite,
    unpack_rsa1_side,
    unpack_rsb1_side,
)
from tac.packet_compiler.pr93_lowpass_luma import (
    LUMA_BT601_COEFFS,
    LowpassLumaResidual,
    decode_lowpass_luma_residual,
    deserialize_lowpass_luma_residual,
    encode_lowpass_luma_residual,
    serialize_lowpass_luma_residual,
)
from tac.packet_compiler.pr93_pose_codec import (
    MAGIC_MODEL_COMPACT,
    MAGIC_POSE_DV,
    DeltaVarintPoseStream,
    QZMB1Block,
    decode_delta_varint_pose,
    encode_delta_varint_pose,
    pack_qzmb1_block,
    unpack_qzmb1_block,
)
from tac.packet_compiler.pr98_cd1_compact_format import (
    CD1_MAGIC,
    SUPPORTED_SCALE_BITS,
    CD1CompactFormat,
    ScaleBits,
    decode_cd1_compact,
    encode_cd1_compact,
)
from tac.packet_compiler.pr100_schema_driven_decoder import (
    SchemaDrivenPayload,
    decode_schema_driven,
    encode_schema_driven,
)
from tac.packet_compiler.pr105_packed_state_schema import (
    PackedStateSchemaEntry,
    pack_state_schema_size_sorted,
)
from tac.packet_compiler.pr106_sidecar_packet import (
    PR106_ALLOWED_SINGLE_MEMBER_NAMES,
    PR106_DEFAULT_MEMBER_NAME,
    PR106_LATENT_N_DIMS,
    PR106_LATENT_N_PAIRS,
    PR106_NO_OP_DIM,
    PR106_PR101_FIXED_META_DIM_BYTES,
    PR106_PR101_FIXED_META_NOOP_COUNT,
    PR106_PR101_FIXED_META_NOOP_RANK_BYTES,
    PR106_PR101_FIXED_META_PAYLOAD_BYTES,
    PR106_PR101_FIXED_META_FIELDS,
    PR106_PR101_FIXED_META_RANK_BYTE,
    PR106_PR101_FIXED_META_RANK_BYTES,
    PR106_PR101_RANKED_SCHEMA,
    PR106_HDM8_HLM2_DECODER_MAGIC,
    PR106_HDM8_HLM2_DECODER_PAYLOAD_BYTES,
    PR106_HDM8_HLM2_LATENT_MAGIC,
    PR106_HDM8_HLM2_LATENT_PAYLOAD_BYTES,
    PR106_HEADERLESS_INNER_FIRST_BYTE,
    PR106_SIDECAR_FORMAT_BROTLI,
    PR106_SIDECAR_FORMAT_PR101_FIXED_META_RANK_ELIDED,
    PR106_SIDECAR_FORMAT_PR101_HEADERLESS_IMPLICIT_LEN_FIXED_META_RANK_ELIDED,
    PR106_SIDECAR_FORMAT_PR101_HDM8_HLM2_INNER_HEADERLESS_FIXED_META_RANK_ELIDED,
    PR106_SIDECAR_FORMAT_PR101_IMPLICIT_LEN_FIXED_META_RANK_ELIDED,
    PR106_SIDECAR_FORMAT_PR101_GRAMMAR,
    PR106_SIDECAR_FORMAT_PR101_RANK_ELIDED,
    PR106_SIDECAR_MAGIC,
    PR106_SUPPORTED_SIDECAR_FORMATS,
    PR106SidecarRecodeCandidate,
    PR106SidecarMutation,
    PR106SidecarPacket,
    StoredZipMember,
    build_pr106_sidecar_recode_candidate_packet,
    canonicalize_brotli_dim_delta_sidecar_arrays,
    decode_brotli_dim_delta_sidecar_payload,
    decode_pr101_fixed_meta_rank_elided_sidecar_payload_to_dim_delta,
    decode_pr101_ranked_sidecar_payload_to_dim_delta,
    decode_pr101_rank_elided_sidecar_payload_to_dim_delta,
    decode_pr106_sidecar_packet_dim_delta,
    emit_pr106_sidecar_packet,
    emit_pr106_sidecar_recode_candidate_archive,
    emit_single_stored_member_archive,
    encode_brotli_dim_delta_sidecar_payload,
    encode_pr101_ranked_sidecar_payload,
    lossless_pr106_sidecar_recode_candidates,
    mutate_pr106_sidecar_semantic_correction,
    parse_pr106_sidecar_packet,
    prove_pr106_sidecar_packet_ir_identity,
    pr106_sidecar_consumed_byte_proof,
    pr106_sidecar_manifest,
    pr106_sidecar_mutation_manifest,
    pr106_sidecar_recode_candidate_manifest,
    read_single_stored_member_archive,
    reexpand_pr101_fixed_meta_rank_elided_sidecar_payload,
    reexpand_pr101_rank_elided_sidecar_payload,
)
from tac.packet_compiler.pr106_latent_sidecar_selection import (
    build_latent_candidate_grid as build_pr106_latent_candidate_grid,
    choose_latent_corrections_from_score_table_file,
    choose_latent_corrections_from_scores,
    latent_candidate_grid_npy_sha256 as pr106_latent_candidate_grid_npy_sha256,
    profile_latent_sidecar_topk_pareto,
    validate_score_table_manifest as validate_pr106_latent_score_table_manifest,
)
from tac.packet_compiler.pr106_fixed_latent_recode import (
    HLM1_MAGIC,
    PR106FixedLatentRecode,
    PR106FixedLatentRecodeError,
    decode_hlm1_fixed_latent_raw,
    decode_pr106_fixed_latent_raw,
    encode_hlm1_fixed_latents_from_brotli,
    split_pr106_fixed_latent_raw,
)
from tac.packet_compiler.pr106_runtime_consumption import (
    dumps_runtime_consumption_manifest,
    load_pr106_runtime_codec,
    load_pr106_runtime_module,
    load_pr106_sidecar_runtime,
    pr106_runtime_source_manifest,
    prove_pr106_same_runtime_full_frame_parity,
    prove_pr106_sidecar_runtime_decode_consumption,
    runtime_framing_meta_consumption_probe,
    runtime_full_frame_streaming_digest,
    runtime_sidecar_correction_digest,
)
from tac.packet_compiler.pr97_h3_grammar import (
    LengthPrefixedSectionPayload,
    TileBandStreamPayload,
    decode_length_prefixed_sections,
    decode_tile_band_streams,
    encode_length_prefixed_sections,
    encode_tile_band_streams,
)
from tac.packet_compiler.pr63_qpose14_codec import (
    PR63_QPOSE14_N_DIMS,
    PR63_SIGNED_SCALE,
    PR63_VEL_BIAS,
    PR63_VEL_SCALE,
    QPose14PackedPayload,
    QPose14Uint16Int16Stream,
    decode_qpose14_uint16_view_int16,
    encode_qpose14_uint16_view_int16,
    pack_qpose14_packed_payload,
    unpack_qpose14_packed_payload,
)
from tac.packet_compiler.pr64_unified_brotli_pose_velocity import (
    UnifiedBrotliPoseVelocityStream,
    decode_unified_brotli_pose_velocity,
    encode_unified_brotli_pose_velocity,
)
from tac.packet_compiler.pr65_pq12_pose_codec import (
    MAGIC_PQ12,
    PQ12_MAX_QUANTUM,
    PQ12PoseStream,
    decode_pq12_pose,
    encode_pq12_pose,
)
from tac.packet_compiler.pr101_sidecar_grammar import (
    CenteredDeltaUint8Stream,
    RankedSidecarSchema,
    SplitBrotliStream,
    decode_centered_delta_uint8,
    decode_ranked_no_op_sidecar,
    encode_centered_delta_uint8,
    encode_ranked_no_op_sidecar,
    parse_split_brotli_self_delimiting,
    split_brotli_self_delimiting,
)
from tac.packet_compiler.pr101_decoder_storage_order import (
    PR101_DECODER_STORAGE_ORDER,
    PR101_DECODER_STREAM_ENDS,
    DecoderStorageOrderSchema,
    partition_buffer_by_stream_ends,
    reorder_tensors_for_storage,
    restore_tensor_order_from_storage,
)
from tac.packet_compiler.pr101_conv4_storage_perms import (
    PR101_CONV4_STORAGE_PERMS,
    Conv4StoragePermSchema,
    apply_inverse_perm,
    apply_storage_perm,
    compute_inverse_perm,
    compute_inverse_perms,
)
from tac.packet_compiler.pr101_decoder_byte_maps import (
    PR101_DECODER_BYTE_MAPS,
    VALID_BYTE_MAP_STRATEGIES,
    ByteMapStrategy,
    DecoderByteMapsSchema,
    decode_byte_map,
    encode_byte_map,
)
from tac.packet_compiler.sign_encoding import (
    VALID_SIGN_ENCODING_STRATEGIES,
    SignEncodingStrategy,
    StrategySelection,
    decode_sign,
    encode_sign,
    select_optimal_strategy,
)
from tac.packet_compiler.pr103_arithmetic_coding import (
    AdaptiveBrotliResult,
    MergedRangeStream,
    WeightTensorACSpec,
    adaptive_brotli_param_search,
    decode_latent_hi_arithmetic,
    decode_merged_range_stream,
    encode_latent_hi_arithmetic,
    encode_merged_range_stream,
)
from tac.packet_compiler.sparse_packet_ir import (
    SPARSE_AC_MAGIC,
    SPARSE_AC_SCHEMA,
    SPARSE_RLE_MAGIC,
    SPARSE_RLE_SCHEMA,
    SPARSE_TEMPORAL_MAGIC,
    SPARSE_TEMPORAL_SCHEMA,
    SUPPORTED_RLE_NONZERO_DTYPES,
    ArithmeticCodedCoefficientStream,
    RleOfZerosStream,
    SparsePacketIRError,
    TemporalSubsampledResidualStream,
    decode_arithmetic_coefficients,
    decode_rle_of_zeros,
    decode_temporal_subsampled,
    deserialize_arithmetic_coefficients,
    deserialize_rle_of_zeros,
    deserialize_temporal_subsampled,
    encode_arithmetic_coefficients,
    encode_rle_of_zeros,
    encode_temporal_subsampled,
    pad_per_frame_to_uniform_size_with_length_prefix,
    serialize_arithmetic_coefficients,
    serialize_rle_of_zeros,
    serialize_temporal_subsampled,
)
from tac.packet_compiler.balle_hyperprior import (
    BALLE_HYPERPRIOR_VERSION,
    MAGIC_BALLE_HYPERPRIOR,
    VARIANT_JOINT_AR,
    VARIANT_MEANSCALE,
    VARIANT_SCALE,
    BalleHyperpriorError,
    BalleHyperpriorPayload,
    decode_balle_hyperprior,
    deserialize_balle_hyperprior,
    encode_balle_hyperprior,
    serialize_balle_hyperprior,
)
from tac.packet_compiler.cheng2020 import (
    CHENG2020_VERSION,
    MAGIC_CHENG2020,
    VARIANT_ANCHOR,
    VARIANT_ATTENTION,
    Cheng2020Error,
    Cheng2020Payload,
    decode_cheng2020,
    deserialize_cheng2020,
    encode_cheng2020,
    serialize_cheng2020,
)
from tac.packet_compiler.factorized_prior import (
    FACTORIZED_PRIOR_VERSION,
    MAGIC_FACTORIZED_PRIOR,
    FactorizedPriorError,
    FactorizedPriorPayload,
    decode_factorized_prior,
    deserialize_factorized_prior,
    encode_factorized_prior,
    serialize_factorized_prior,
)
from tac.packet_compiler.magic_codec_dense_streams import (
    CODEC_BROTLI,
    CODEC_LZMA,
    CODEC_MAGIC_CLASSIC,
    CodecCandidate,
    DENSE_STREAMS_VERSION,
    DenseStreamInput,
    DenseStreamsEnvelopeHeader,
    DenseStreamsResult,
    MAGIC_DENSE_STREAMS,
    MagicCodecDenseStreamsError,
    StreamSelection,
    decode_magic_codec_dense_streams,
    encode_magic_codec_dense_streams,
    parse_magic_codec_dense_streams_envelope,
)
from tac.packet_compiler.magic_codec import (
    MAGIC_CODEC_ENVELOPE,
    PRIMITIVE_ARITHMETIC_COEFFICIENTS,
    PRIMITIVE_CATEGORICAL_STREAM,
    PRIMITIVE_CENTERED_DELTA_UINT8,
    PRIMITIVE_DELTA_VARINT_POSE,
    PRIMITIVE_LOWPASS_LUMA_RESIDUAL,
    PRIMITIVE_RLE_OF_ZEROS,
    CandidateResult,
    MagicCodecEnvelopeHeader,
    MagicCodecError,
    MagicCodecResult,
    SelectionStrategy,
    StreamHint,
    StreamType,
    candidate_primitives_for,
    decode_magic_codec,
    encode_magic_codec,
    parse_magic_codec_envelope,
    recommendation_for,
    shannon_entropy_estimate_bits,
)
from tac.packet_compiler.deterministic_compiler import (
    COMPILER_MODES as DETERMINISTIC_COMPILER_MODES,
    TARGET_PROFILE_POLICIES as DETERMINISTIC_TARGET_PROFILE_POLICIES,
    TARGET_PROFILES as DETERMINISTIC_TARGET_PROFILES,
    DeterministicPacketCompilerError,
    DeterministicPacketResult,
    compile_packet as compile_deterministic_packet,
    inspect_packet_oracle as inspect_deterministic_packet,
)

__all__ = [
    # Canonical deterministic submission-packet compiler (2026-05-12, Catalog #158)
    "DETERMINISTIC_COMPILER_MODES",
    "DETERMINISTIC_TARGET_PROFILES",
    "DETERMINISTIC_TARGET_PROFILE_POLICIES",
    "DeterministicPacketCompilerError",
    "DeterministicPacketResult",
    "compile_deterministic_packet",
    "inspect_deterministic_packet",
    # PR81 — FP4 codebook + ROUTER_ACTION packing
    "FP4Codebook",
    "PR81_POS_LEVELS",
    "decode_router_actions",
    "encode_router_actions",
    "pack_nibbles",
    "unpack_nibbles",
    # PR84 — adaptive-context range coder
    "AdaptiveContextSpec",
    "decode_adaptive_context_stream",
    "encode_adaptive_context_stream",
    # PR91 — universal AC wrapper + QM0/QH0 grammar
    "MAGIC_QH0",
    "MAGIC_QM0",
    "QMQHHeader",
    "decode_categorical_stream",
    "emit_qmqh_header",
    "encode_categorical_stream",
    "pack_hi_lo_split",
    "parse_qmqh_header",
    "unpack_hi_lo_split",
    # PR92 — RMC1 / RSA1 / RSB1 joint-stream grammar
    "MAGIC_RMC1",
    "MAGIC_RSA1",
    "MAGIC_RSB1",
    "RMC1Composite",
    "RSA1Side",
    "RSB1Side",
    "pack_rmc1_composite",
    "pack_rsa1_side",
    "pack_rsb1_side",
    "unpack_rmc1_composite",
    "unpack_rsa1_side",
    "unpack_rsb1_side",
    # PR63 — qpose14 uint16-view int16 codec + packed-payload single-zip-member grammar
    "PR63_QPOSE14_N_DIMS",
    "PR63_SIGNED_SCALE",
    "PR63_VEL_BIAS",
    "PR63_VEL_SCALE",
    "QPose14PackedPayload",
    "QPose14Uint16Int16Stream",
    "decode_qpose14_uint16_view_int16",
    "encode_qpose14_uint16_view_int16",
    "pack_qpose14_packed_payload",
    "unpack_qpose14_packed_payload",
    # PR64 — unified-brotli pose-velocity-only codec
    "UnifiedBrotliPoseVelocityStream",
    "decode_unified_brotli_pose_velocity",
    "encode_unified_brotli_pose_velocity",
    # PR65 — PQ12 12-bit / 3-byte / 2-value packed pose codec
    "MAGIC_PQ12",
    "PQ12_MAX_QUANTUM",
    "PQ12PoseStream",
    "decode_pq12_pose",
    "encode_pq12_pose",
    # PR98 — CD1 compact decoder-format (schema-elision V1)
    "CD1CompactFormat",
    "CD1_MAGIC",
    "SUPPORTED_SCALE_BITS",
    "ScaleBits",
    "decode_cd1_compact",
    "encode_cd1_compact",
    # PR100 — schema-driven decoder storage grammar (schema-elision V2)
    "SchemaDrivenPayload",
    "decode_schema_driven",
    "encode_schema_driven",
    # PR105 — kitchen_sink packed-state-schema size-sorted helper
    "PackedStateSchemaEntry",
    "pack_state_schema_size_sorted",
    # PR106 — sidecar wrapper PacketIR identity parser/emitter
    "PR106_ALLOWED_SINGLE_MEMBER_NAMES",
    "PR106_DEFAULT_MEMBER_NAME",
    "PR106_LATENT_N_DIMS",
    "PR106_LATENT_N_PAIRS",
    "PR106_NO_OP_DIM",
    "PR106_HDM8_HLM2_DECODER_MAGIC",
    "PR106_HDM8_HLM2_DECODER_PAYLOAD_BYTES",
    "PR106_HDM8_HLM2_LATENT_MAGIC",
    "PR106_HDM8_HLM2_LATENT_PAYLOAD_BYTES",
    "PR106_HEADERLESS_INNER_FIRST_BYTE",
    "PR106_PR101_RANKED_SCHEMA",
    "PR106_SIDECAR_FORMAT_BROTLI",
    "PR106_SIDECAR_FORMAT_PR101_FIXED_META_RANK_ELIDED",
    "PR106_SIDECAR_FORMAT_PR101_GRAMMAR",
    "PR106_SIDECAR_FORMAT_PR101_HEADERLESS_IMPLICIT_LEN_FIXED_META_RANK_ELIDED",
    "PR106_SIDECAR_FORMAT_PR101_HDM8_HLM2_INNER_HEADERLESS_FIXED_META_RANK_ELIDED",
    "PR106_SIDECAR_FORMAT_PR101_IMPLICIT_LEN_FIXED_META_RANK_ELIDED",
    "PR106_SIDECAR_FORMAT_PR101_RANK_ELIDED",
    "PR106_SIDECAR_MAGIC",
    "PR106_SUPPORTED_SIDECAR_FORMATS",
    "PR106SidecarRecodeCandidate",
    "PR106SidecarMutation",
    "PR106SidecarPacket",
    "StoredZipMember",
    "build_pr106_sidecar_recode_candidate_packet",
    "canonicalize_brotli_dim_delta_sidecar_arrays",
    "decode_brotli_dim_delta_sidecar_payload",
    "decode_pr101_ranked_sidecar_payload_to_dim_delta",
    "decode_pr106_sidecar_packet_dim_delta",
    "dumps_runtime_consumption_manifest",
    "emit_pr106_sidecar_packet",
    "emit_pr106_sidecar_recode_candidate_archive",
    "emit_single_stored_member_archive",
    "encode_brotli_dim_delta_sidecar_payload",
    "encode_pr101_ranked_sidecar_payload",
    "load_pr106_runtime_codec",
    "load_pr106_runtime_module",
    "load_pr106_sidecar_runtime",
    "lossless_pr106_sidecar_recode_candidates",
    "mutate_pr106_sidecar_semantic_correction",
    "parse_pr106_sidecar_packet",
    "prove_pr106_sidecar_packet_ir_identity",
    "prove_pr106_same_runtime_full_frame_parity",
    "prove_pr106_sidecar_runtime_decode_consumption",
    "pr106_runtime_source_manifest",
    "pr106_sidecar_consumed_byte_proof",
    "pr106_sidecar_manifest",
    "pr106_sidecar_mutation_manifest",
    "pr106_sidecar_recode_candidate_manifest",
    "runtime_framing_meta_consumption_probe",
    "build_pr106_latent_candidate_grid",
    "choose_latent_corrections_from_score_table_file",
    "choose_latent_corrections_from_scores",
    "pr106_latent_candidate_grid_npy_sha256",
    "profile_latent_sidecar_topk_pareto",
    "validate_pr106_latent_score_table_manifest",
    "HLM1_MAGIC",
    "PR106FixedLatentRecode",
    "PR106FixedLatentRecodeError",
    "decode_hlm1_fixed_latent_raw",
    "decode_pr106_fixed_latent_raw",
    "encode_hlm1_fixed_latents_from_brotli",
    "split_pr106_fixed_latent_raw",
    "read_single_stored_member_archive",
    "runtime_full_frame_streaming_digest",
    "runtime_sidecar_correction_digest",
    # PR93 — delta-varint pose codec + QZMB1 grammar
    "DeltaVarintPoseStream",
    "MAGIC_MODEL_COMPACT",
    "MAGIC_POSE_DV",
    "QZMB1Block",
    "decode_delta_varint_pose",
    "encode_delta_varint_pose",
    "pack_qzmb1_block",
    "unpack_qzmb1_block",
    # PR93 — lowpass-luma residual codec (3 or 6 fp32 coeffs)
    "LUMA_BT601_COEFFS",
    "LowpassLumaResidual",
    "decode_lowpass_luma_residual",
    "deserialize_lowpass_luma_residual",
    "encode_lowpass_luma_residual",
    "serialize_lowpass_luma_residual",
    # PR97 — H3 wire-format grammar (length-prefixed sections + tile-band streams)
    "LengthPrefixedSectionPayload",
    "TileBandStreamPayload",
    "decode_length_prefixed_sections",
    "decode_tile_band_streams",
    "encode_length_prefixed_sections",
    "encode_tile_band_streams",
    # PR101 — sidecar grammar
    "CenteredDeltaUint8Stream",
    "RankedSidecarSchema",
    "SplitBrotliStream",
    "decode_centered_delta_uint8",
    "decode_ranked_no_op_sidecar",
    "encode_centered_delta_uint8",
    "encode_ranked_no_op_sidecar",
    "parse_split_brotli_self_delimiting",
    "split_brotli_self_delimiting",
    # PR101 GOLD — decoder storage order + stream boundaries (2026-05-12)
    "DecoderStorageOrderSchema",
    "PR101_DECODER_STORAGE_ORDER",
    "PR101_DECODER_STREAM_ENDS",
    "partition_buffer_by_stream_ends",
    "reorder_tensors_for_storage",
    "restore_tensor_order_from_storage",
    # PR101 GOLD — conv4 storage perms (2026-05-12)
    "Conv4StoragePermSchema",
    "PR101_CONV4_STORAGE_PERMS",
    "apply_inverse_perm",
    "apply_storage_perm",
    "compute_inverse_perm",
    "compute_inverse_perms",
    # PR101 GOLD — decoder byte maps (sign-encoding strategy) (2026-05-12)
    "ByteMapStrategy",
    "DecoderByteMapsSchema",
    "PR101_DECODER_BYTE_MAPS",
    "VALID_BYTE_MAP_STRATEGIES",
    "decode_byte_map",
    "encode_byte_map",
    # Sign-encoding 5-strategy unified taxonomy (2026-05-12)
    "SignEncodingStrategy",
    "StrategySelection",
    "VALID_SIGN_ENCODING_STRATEGIES",
    "decode_sign",
    "encode_sign",
    "select_optimal_strategy",
    # PR103 — arithmetic coding
    "AdaptiveBrotliResult",
    "MergedRangeStream",
    "WeightTensorACSpec",
    "adaptive_brotli_param_search",
    "decode_latent_hi_arithmetic",
    "decode_merged_range_stream",
    "encode_latent_hi_arithmetic",
    "encode_merged_range_stream",
    # Sparse PacketIR codec — RLE-of-zeros + AC coefficient + temporal-subsampled
    "ArithmeticCodedCoefficientStream",
    "RleOfZerosStream",
    "SPARSE_AC_MAGIC",
    "SPARSE_AC_SCHEMA",
    "SPARSE_RLE_MAGIC",
    "SPARSE_RLE_SCHEMA",
    "SPARSE_TEMPORAL_MAGIC",
    "SPARSE_TEMPORAL_SCHEMA",
    "SUPPORTED_RLE_NONZERO_DTYPES",
    "SparsePacketIRError",
    "TemporalSubsampledResidualStream",
    "decode_arithmetic_coefficients",
    "decode_rle_of_zeros",
    "decode_temporal_subsampled",
    "deserialize_arithmetic_coefficients",
    "deserialize_rle_of_zeros",
    "deserialize_temporal_subsampled",
    "encode_arithmetic_coefficients",
    "encode_rle_of_zeros",
    "encode_temporal_subsampled",
    "pad_per_frame_to_uniform_size_with_length_prefix",
    "serialize_arithmetic_coefficients",
    "serialize_rle_of_zeros",
    "serialize_temporal_subsampled",
    # Magic codec — per-stream auto-selector over the 19 primitives
    "MAGIC_CODEC_ENVELOPE",
    "MagicCodecEnvelopeHeader",
    "MagicCodecError",
    "MagicCodecResult",
    "PRIMITIVE_ARITHMETIC_COEFFICIENTS",
    "PRIMITIVE_CATEGORICAL_STREAM",
    "PRIMITIVE_CENTERED_DELTA_UINT8",
    "PRIMITIVE_DELTA_VARINT_POSE",
    "PRIMITIVE_LOWPASS_LUMA_RESIDUAL",
    "PRIMITIVE_RLE_OF_ZEROS",
    "CandidateResult",
    "SelectionStrategy",
    "StreamHint",
    "StreamType",
    "candidate_primitives_for",
    "decode_magic_codec",
    "encode_magic_codec",
    "parse_magic_codec_envelope",
    "recommendation_for",
    "shannon_entropy_estimate_bits",
    # Magic codec dense streams — per-stream codec auto-selection over a typed bundle (2026-05-12)
    "CODEC_BROTLI",
    "CODEC_LZMA",
    "CODEC_MAGIC_CLASSIC",
    "CodecCandidate",
    "DENSE_STREAMS_VERSION",
    "DenseStreamInput",
    "DenseStreamsEnvelopeHeader",
    "DenseStreamsResult",
    "MAGIC_DENSE_STREAMS",
    "MagicCodecDenseStreamsError",
    "StreamSelection",
    "decode_magic_codec_dense_streams",
    "encode_magic_codec_dense_streams",
    "parse_magic_codec_dense_streams_envelope",
    # CompressAI FactorizedPrior (Ballé 2018 baseline) — packet-compiler adapter (2026-05-12)
    "FACTORIZED_PRIOR_VERSION",
    "FactorizedPriorError",
    "FactorizedPriorPayload",
    "MAGIC_FACTORIZED_PRIOR",
    "decode_factorized_prior",
    "deserialize_factorized_prior",
    "encode_factorized_prior",
    "serialize_factorized_prior",
    # CompressAI Ballé hyperprior family (Scale / MeanScale / JointAR) — packet-compiler adapter (2026-05-12)
    "BALLE_HYPERPRIOR_VERSION",
    "BalleHyperpriorError",
    "BalleHyperpriorPayload",
    "MAGIC_BALLE_HYPERPRIOR",
    "VARIANT_JOINT_AR",
    "VARIANT_MEANSCALE",
    "VARIANT_SCALE",
    "decode_balle_hyperprior",
    "deserialize_balle_hyperprior",
    "encode_balle_hyperprior",
    "serialize_balle_hyperprior",
    # CompressAI Cheng-2020 (anchor + attention) — packet-compiler adapter (2026-05-12)
    "CHENG2020_VERSION",
    "Cheng2020Error",
    "Cheng2020Payload",
    "MAGIC_CHENG2020",
    "VARIANT_ANCHOR",
    "VARIANT_ATTENTION",
    "decode_cheng2020",
    "deserialize_cheng2020",
    "encode_cheng2020",
    "serialize_cheng2020",
]
