"""Reusable packet-compiler byte grammar primitives.

This package is intentionally narrow. It exposes only implemented, tested
transducers; broader PacketIR APIs remain roadmap items until their identity
vectors and strict no-op proofs land.
"""

from __future__ import annotations

from tac.packet_compiler.pr81_quantizr import (
    PR81_POS_LEVELS,
    FP4Codebook,
    decode_router_actions,
    encode_router_actions,
    pack_nibbles,
    unpack_nibbles,
)
from tac.packet_compiler.pr84_adaptive_mask import (
    AdaptiveContextSpec,
    decode_adaptive_context_stream,
    encode_adaptive_context_stream,
)
from tac.packet_compiler.pr91_hpac_grammar import (
    MAGIC_QH0,
    MAGIC_QM0,
    QMQHHeader,
    decode_categorical_stream,
    emit_qmqh_header,
    encode_categorical_stream,
    pack_hi_lo_split,
    parse_qmqh_header,
    unpack_hi_lo_split,
)
from tac.packet_compiler.pr92_joint_stream import (
    MAGIC_RMC1,
    MAGIC_RSA1,
    MAGIC_RSB1,
    RMC1Composite,
    RSA1Side,
    RSB1Side,
    pack_rmc1_composite,
    pack_rsa1_side,
    pack_rsb1_side,
    unpack_rmc1_composite,
    unpack_rsa1_side,
    unpack_rsb1_side,
)
from tac.packet_compiler.pr93_lowpass_luma import (
    LUMA_BT601_COEFFS,
    LowpassLumaResidual,
    decode_lowpass_luma_residual,
    deserialize_lowpass_luma_residual,
    encode_lowpass_luma_residual,
    serialize_lowpass_luma_residual,
)
from tac.packet_compiler.pr93_pose_codec import (
    MAGIC_MODEL_COMPACT,
    MAGIC_POSE_DV,
    DeltaVarintPoseStream,
    QZMB1Block,
    decode_delta_varint_pose,
    encode_delta_varint_pose,
    pack_qzmb1_block,
    unpack_qzmb1_block,
)
from tac.packet_compiler.pr105_packed_state_schema import (
    PackedStateSchemaEntry,
    pack_state_schema_size_sorted,
)
from tac.packet_compiler.pr106_sidecar_packet import (
    PR106_DEFAULT_MEMBER_NAME,
    PR106_SIDECAR_FORMAT_BROTLI,
    PR106_SIDECAR_FORMAT_PR101_GRAMMAR,
    PR106_SIDECAR_MAGIC,
    PR106_SUPPORTED_SIDECAR_FORMATS,
    PR106SidecarPacket,
    StoredZipMember,
    emit_pr106_sidecar_packet,
    emit_single_stored_member_archive,
    parse_pr106_sidecar_packet,
    pr106_sidecar_consumed_byte_proof,
    pr106_sidecar_manifest,
    read_single_stored_member_archive,
)
from tac.packet_compiler.pr97_h3_grammar import (
    LengthPrefixedSectionPayload,
    TileBandStreamPayload,
    decode_length_prefixed_sections,
    decode_tile_band_streams,
    encode_length_prefixed_sections,
    encode_tile_band_streams,
)
from tac.packet_compiler.pr63_qpose14_codec import (
    PR63_QPOSE14_N_DIMS,
    PR63_SIGNED_SCALE,
    PR63_VEL_BIAS,
    PR63_VEL_SCALE,
    QPose14PackedPayload,
    QPose14Uint16Int16Stream,
    decode_qpose14_uint16_view_int16,
    encode_qpose14_uint16_view_int16,
    pack_qpose14_packed_payload,
    unpack_qpose14_packed_payload,
)
from tac.packet_compiler.pr64_unified_brotli_pose_velocity import (
    UnifiedBrotliPoseVelocityStream,
    decode_unified_brotli_pose_velocity,
    encode_unified_brotli_pose_velocity,
)
from tac.packet_compiler.pr65_pq12_pose_codec import (
    MAGIC_PQ12,
    PQ12_MAX_QUANTUM,
    PQ12PoseStream,
    decode_pq12_pose,
    encode_pq12_pose,
)
from tac.packet_compiler.pr101_sidecar_grammar import (
    CenteredDeltaUint8Stream,
    RankedSidecarSchema,
    SplitBrotliStream,
    decode_centered_delta_uint8,
    decode_ranked_no_op_sidecar,
    encode_centered_delta_uint8,
    encode_ranked_no_op_sidecar,
    parse_split_brotli_self_delimiting,
    split_brotli_self_delimiting,
)
from tac.packet_compiler.pr103_arithmetic_coding import (
    AdaptiveBrotliResult,
    MergedRangeStream,
    WeightTensorACSpec,
    adaptive_brotli_param_search,
    decode_latent_hi_arithmetic,
    decode_merged_range_stream,
    encode_latent_hi_arithmetic,
    encode_merged_range_stream,
)
from tac.packet_compiler.sparse_packet_ir import (
    SPARSE_AC_MAGIC,
    SPARSE_AC_SCHEMA,
    SPARSE_RLE_MAGIC,
    SPARSE_RLE_SCHEMA,
    SPARSE_TEMPORAL_MAGIC,
    SPARSE_TEMPORAL_SCHEMA,
    SUPPORTED_RLE_NONZERO_DTYPES,
    ArithmeticCodedCoefficientStream,
    RleOfZerosStream,
    SparsePacketIRError,
    TemporalSubsampledResidualStream,
    decode_arithmetic_coefficients,
    decode_rle_of_zeros,
    decode_temporal_subsampled,
    deserialize_arithmetic_coefficients,
    deserialize_rle_of_zeros,
    deserialize_temporal_subsampled,
    encode_arithmetic_coefficients,
    encode_rle_of_zeros,
    encode_temporal_subsampled,
    pad_per_frame_to_uniform_size_with_length_prefix,
    serialize_arithmetic_coefficients,
    serialize_rle_of_zeros,
    serialize_temporal_subsampled,
)
from tac.packet_compiler.magic_codec import (
    MAGIC_CODEC_ENVELOPE,
    PRIMITIVE_ARITHMETIC_COEFFICIENTS,
    PRIMITIVE_CATEGORICAL_STREAM,
    PRIMITIVE_CENTERED_DELTA_UINT8,
    PRIMITIVE_DELTA_VARINT_POSE,
    PRIMITIVE_LOWPASS_LUMA_RESIDUAL,
    PRIMITIVE_RLE_OF_ZEROS,
    CandidateResult,
    MagicCodecEnvelopeHeader,
    MagicCodecError,
    MagicCodecResult,
    SelectionStrategy,
    StreamHint,
    StreamType,
    candidate_primitives_for,
    decode_magic_codec,
    encode_magic_codec,
    parse_magic_codec_envelope,
    recommendation_for,
    shannon_entropy_estimate_bits,
)

__all__ = [
    # PR81 — FP4 codebook + ROUTER_ACTION packing
    "FP4Codebook",
    "PR81_POS_LEVELS",
    "decode_router_actions",
    "encode_router_actions",
    "pack_nibbles",
    "unpack_nibbles",
    # PR84 — adaptive-context range coder
    "AdaptiveContextSpec",
    "decode_adaptive_context_stream",
    "encode_adaptive_context_stream",
    # PR91 — universal AC wrapper + QM0/QH0 grammar
    "MAGIC_QH0",
    "MAGIC_QM0",
    "QMQHHeader",
    "decode_categorical_stream",
    "emit_qmqh_header",
    "encode_categorical_stream",
    "pack_hi_lo_split",
    "parse_qmqh_header",
    "unpack_hi_lo_split",
    # PR92 — RMC1 / RSA1 / RSB1 joint-stream grammar
    "MAGIC_RMC1",
    "MAGIC_RSA1",
    "MAGIC_RSB1",
    "RMC1Composite",
    "RSA1Side",
    "RSB1Side",
    "pack_rmc1_composite",
    "pack_rsa1_side",
    "pack_rsb1_side",
    "unpack_rmc1_composite",
    "unpack_rsa1_side",
    "unpack_rsb1_side",
    # PR63 — qpose14 uint16-view int16 codec + packed-payload single-zip-member grammar
    "PR63_QPOSE14_N_DIMS",
    "PR63_SIGNED_SCALE",
    "PR63_VEL_BIAS",
    "PR63_VEL_SCALE",
    "QPose14PackedPayload",
    "QPose14Uint16Int16Stream",
    "decode_qpose14_uint16_view_int16",
    "encode_qpose14_uint16_view_int16",
    "pack_qpose14_packed_payload",
    "unpack_qpose14_packed_payload",
    # PR64 — unified-brotli pose-velocity-only codec
    "UnifiedBrotliPoseVelocityStream",
    "decode_unified_brotli_pose_velocity",
    "encode_unified_brotli_pose_velocity",
    # PR65 — PQ12 12-bit / 3-byte / 2-value packed pose codec
    "MAGIC_PQ12",
    "PQ12_MAX_QUANTUM",
    "PQ12PoseStream",
    "decode_pq12_pose",
    "encode_pq12_pose",
    # PR105 — kitchen_sink packed-state-schema size-sorted helper
    "PackedStateSchemaEntry",
    "pack_state_schema_size_sorted",
    # PR106 — sidecar wrapper PacketIR identity parser/emitter
    "PR106_DEFAULT_MEMBER_NAME",
    "PR106_SIDECAR_FORMAT_BROTLI",
    "PR106_SIDECAR_FORMAT_PR101_GRAMMAR",
    "PR106_SIDECAR_MAGIC",
    "PR106_SUPPORTED_SIDECAR_FORMATS",
    "PR106SidecarPacket",
    "StoredZipMember",
    "emit_pr106_sidecar_packet",
    "emit_single_stored_member_archive",
    "parse_pr106_sidecar_packet",
    "pr106_sidecar_consumed_byte_proof",
    "pr106_sidecar_manifest",
    "read_single_stored_member_archive",
    # PR93 — delta-varint pose codec + QZMB1 grammar
    "DeltaVarintPoseStream",
    "MAGIC_MODEL_COMPACT",
    "MAGIC_POSE_DV",
    "QZMB1Block",
    "decode_delta_varint_pose",
    "encode_delta_varint_pose",
    "pack_qzmb1_block",
    "unpack_qzmb1_block",
    # PR93 — lowpass-luma residual codec (3 or 6 fp32 coeffs)
    "LUMA_BT601_COEFFS",
    "LowpassLumaResidual",
    "decode_lowpass_luma_residual",
    "deserialize_lowpass_luma_residual",
    "encode_lowpass_luma_residual",
    "serialize_lowpass_luma_residual",
    # PR97 — H3 wire-format grammar (length-prefixed sections + tile-band streams)
    "LengthPrefixedSectionPayload",
    "TileBandStreamPayload",
    "decode_length_prefixed_sections",
    "decode_tile_band_streams",
    "encode_length_prefixed_sections",
    "encode_tile_band_streams",
    # PR101 — sidecar grammar
    "CenteredDeltaUint8Stream",
    "RankedSidecarSchema",
    "SplitBrotliStream",
    "decode_centered_delta_uint8",
    "decode_ranked_no_op_sidecar",
    "encode_centered_delta_uint8",
    "encode_ranked_no_op_sidecar",
    "parse_split_brotli_self_delimiting",
    "split_brotli_self_delimiting",
    # PR103 — arithmetic coding
    "AdaptiveBrotliResult",
    "MergedRangeStream",
    "WeightTensorACSpec",
    "adaptive_brotli_param_search",
    "decode_latent_hi_arithmetic",
    "decode_merged_range_stream",
    "encode_latent_hi_arithmetic",
    "encode_merged_range_stream",
    # Sparse PacketIR codec — RLE-of-zeros + AC coefficient + temporal-subsampled
    "ArithmeticCodedCoefficientStream",
    "RleOfZerosStream",
    "SPARSE_AC_MAGIC",
    "SPARSE_AC_SCHEMA",
    "SPARSE_RLE_MAGIC",
    "SPARSE_RLE_SCHEMA",
    "SPARSE_TEMPORAL_MAGIC",
    "SPARSE_TEMPORAL_SCHEMA",
    "SUPPORTED_RLE_NONZERO_DTYPES",
    "SparsePacketIRError",
    "TemporalSubsampledResidualStream",
    "decode_arithmetic_coefficients",
    "decode_rle_of_zeros",
    "decode_temporal_subsampled",
    "deserialize_arithmetic_coefficients",
    "deserialize_rle_of_zeros",
    "deserialize_temporal_subsampled",
    "encode_arithmetic_coefficients",
    "encode_rle_of_zeros",
    "encode_temporal_subsampled",
    "pad_per_frame_to_uniform_size_with_length_prefix",
    "serialize_arithmetic_coefficients",
    "serialize_rle_of_zeros",
    "serialize_temporal_subsampled",
    # Magic codec — per-stream auto-selector over the 19 primitives
    "MAGIC_CODEC_ENVELOPE",
    "MagicCodecEnvelopeHeader",
    "MagicCodecError",
    "MagicCodecResult",
    "PRIMITIVE_ARITHMETIC_COEFFICIENTS",
    "PRIMITIVE_CATEGORICAL_STREAM",
    "PRIMITIVE_CENTERED_DELTA_UINT8",
    "PRIMITIVE_DELTA_VARINT_POSE",
    "PRIMITIVE_LOWPASS_LUMA_RESIDUAL",
    "PRIMITIVE_RLE_OF_ZEROS",
    "CandidateResult",
    "SelectionStrategy",
    "StreamHint",
    "StreamType",
    "candidate_primitives_for",
    "decode_magic_codec",
    "encode_magic_codec",
    "parse_magic_codec_envelope",
    "recommendation_for",
    "shannon_entropy_estimate_bits",
]
