# SPDX-License-Identifier: MIT
"""Canonical upstream-snapshot drift-detection helper.

Per the 12-month strategic-foresight premortem
(`.omx/research/12_month_frustration_premortem_and_recommendations_20260516.md`
item #2): every empirical anchor (continual-learning posterior, Modal call_id
ledger, cost-band posterior) MUST carry an ``upstream_snapshot_sha256`` field
so we can structurally detect when an anchor was scored against a different
upstream/ snapshot than the one currently checked out. Without the field, a
silent upstream rotation (e.g. Yousfi swaps SegNet weights) invalidates every
prior score claim with no operator-visible signal.

This module exports ONE canonical entry point — :func:`compute_upstream_snapshot_sha256` —
that walks ``upstream/`` deterministically, skips Python cache + bytecode
artifacts, and returns a stable hex SHA-256 of the (path, content) ordered
tuple. The same anchor written by two different commits with byte-identical
``upstream/`` snapshots will share an ``upstream_snapshot_sha256``; a single
upstream byte mutation will produce a different hash.

Per CLAUDE.md "Apples-to-apples evidence discipline": anchor consumers can
read the stamped hash from the JSONL row and refuse to compare anchors whose
upstream snapshots differ (or downgrade the cross-snapshot comparison to
advisory). The helper deliberately returns ``None`` when ``upstream/`` is
missing so call sites in ephemeral CI / test environments without the upstream
clone do not break — but a missing hash MUST be surfaced upstream as
``None`` rather than silently falling through.
"""

from __future__ import annotations

import hashlib
from pathlib import Path
from typing import Iterable

# Paths under ``upstream/`` to skip when hashing. These directories carry
# transient bytecode / cache state that is not part of the upstream contest
# snapshot's canonical content.
_SKIP_DIR_NAMES: frozenset[str] = frozenset(
    {"__pycache__", ".git", ".pytest_cache", ".mypy_cache", "node_modules"}
)

# Suffixes to skip — generated bytecode that legitimately changes per-host
# without representing a real upstream snapshot change.
_SKIP_SUFFIXES: frozenset[str] = frozenset({".pyc", ".pyo"})


def _iter_upstream_files(upstream_dir: Path) -> Iterable[Path]:
    """Yield every regular file under ``upstream_dir`` in sorted-path order.

    Excludes ``_SKIP_DIR_NAMES`` and ``_SKIP_SUFFIXES`` per the canonical
    upstream-snapshot contract. Symlinks are followed only when they point
    inside ``upstream_dir`` — out-of-tree symlinks would make the hash
    machine-dependent.
    """
    if not upstream_dir.exists():
        return
    upstream_resolved = upstream_dir.resolve()
    # Pre-collect to enable stable sorted order. rglob does not guarantee
    # ordering across filesystems.
    candidates: list[Path] = []
    for path in upstream_dir.rglob("*"):
        if not path.is_file():
            continue
        rel_parts = path.relative_to(upstream_dir).parts
        if any(part in _SKIP_DIR_NAMES for part in rel_parts):
            continue
        if path.suffix in _SKIP_SUFFIXES:
            continue
        if path.is_symlink():
            target = path.resolve()
            try:
                target.relative_to(upstream_resolved)
            except ValueError:
                # Out-of-tree symlink; skip rather than allow host-specific
                # state to leak into the hash.
                continue
        candidates.append(path)
    candidates.sort(key=lambda p: p.relative_to(upstream_dir).as_posix())
    yield from candidates


def compute_upstream_snapshot_sha256(
    repo_root: Path | str | None = None,
    *,
    upstream_subdir: str = "upstream",
) -> str | None:
    """Compute a deterministic SHA-256 of the ``upstream/`` directory tree.

    Returns the hex digest, or ``None`` when ``upstream/`` does not exist at
    ``repo_root / upstream_subdir``. The digest is invariant under filesystem
    iteration order (paths are sorted) and host-local bytecode artifacts
    (``__pycache__`` / ``*.pyc`` / ``*.pyo`` are skipped).

    Each contributing file appears in the hash as the byte sequence
    ``"<posix-relative-path>\\n<size>\\n<sha256-of-content>\\n"`` so a rename
    that preserves bytes still mutates the snapshot hash (canonical filename
    is part of the contract per ``upstream/`` being the contest's
    source-of-truth for evaluate.py / scorer modules / video bytes).
    """
    if repo_root is None:
        # Default to the repository root (this file lives at
        # ``src/tac/contest_compliance.py`` so the repo root is 3 parents
        # up). Test fixtures pass an explicit repo_root.
        repo_root = Path(__file__).resolve().parent.parent.parent
    else:
        repo_root = Path(repo_root)
    upstream_dir = repo_root / upstream_subdir
    if not upstream_dir.exists():
        return None

    outer = hashlib.sha256()
    found_any = False
    for path in _iter_upstream_files(upstream_dir):
        found_any = True
        rel = path.relative_to(upstream_dir).as_posix()
        size = path.stat().st_size
        inner = hashlib.sha256()
        with path.open("rb") as fh:
            for chunk in iter(lambda: fh.read(1 << 20), b""):
                inner.update(chunk)
        outer.update(rel.encode("utf-8"))
        outer.update(b"\n")
        outer.update(str(size).encode("ascii"))
        outer.update(b"\n")
        outer.update(inner.hexdigest().encode("ascii"))
        outer.update(b"\n")
    if not found_any:
        # The directory exists but contains no regular files — distinguish
        # this from "no upstream/" by returning a stable sentinel rather
        # than None so consumers can detect the degenerate case.
        return hashlib.sha256(b"<empty-upstream-tree>").hexdigest()
    return outer.hexdigest()


__all__ = ["compute_upstream_snapshot_sha256"]
