"""Deterministic codec for generated-schema HNeRV state dicts.

This is the runtime-payload contract for architecture-shrink planning:
arbitrary HNeRV schemas generated by :mod:`tac.hnerv_arch_schema` can be packed
into a single deterministic blob and decoded back into a quantized state dict.

The codec is intentionally conservative:

- per-tensor symmetric int8 quantization;
- one Brotli stream per tensor with explicit byte lengths in the header;
- schema fingerprint in the header;
- fail-closed parsing and shape validation.

It is not a score claim and it is not yet wired into a contest inflate packet.
It exists so generated-schema training can produce auditable byte artifacts
before any GPU dispatch.
"""
from __future__ import annotations

import hashlib
import json
import math
import struct
from dataclasses import dataclass
from typing import Any

import brotli
import numpy as np
import torch

from tac.hnerv_arch_schema import (
    Schema,
    compare_schema_shapes,
    schema_fingerprint,
    schema_numel,
    schema_to_jsonable,
    state_dict_schema_rows,
)

MAGIC_HNGS = b"HNGS"
HEADER = struct.Struct("<4sI")
N_QUANT = 127


class HNeRVGeneratedSchemaCodecError(ValueError):
    """Raised when a generated-schema HNeRV payload is malformed."""


@dataclass(frozen=True)
class EncodedGeneratedSchemaState:
    """Encoded generated-schema state dict and structured manifest."""

    blob: bytes
    manifest: dict[str, Any]


def _canonical_json(payload: dict[str, Any]) -> bytes:
    return json.dumps(payload, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _validate_schema(schema: Schema) -> None:
    seen: set[str] = set()
    for name, shape in schema:
        if not name:
            raise HNeRVGeneratedSchemaCodecError("schema contains empty tensor name")
        if name in seen:
            raise HNeRVGeneratedSchemaCodecError(f"schema duplicates tensor {name!r}")
        seen.add(name)
        if any(int(dim) <= 0 for dim in shape):
            raise HNeRVGeneratedSchemaCodecError(
                f"schema tensor {name!r} has nonpositive shape {shape!r}"
            )


def validate_state_dict_matches_schema(
    state_dict: dict[str, torch.Tensor],
    schema: Schema,
) -> None:
    _validate_schema(schema)
    findings = compare_schema_shapes(schema, state_dict_schema_rows(state_dict))
    if findings:
        raise HNeRVGeneratedSchemaCodecError(
            "state_dict does not match generated HNeRV schema: "
            + ", ".join(findings[:10])
        )


def _quantize_tensor(tensor: torch.Tensor) -> tuple[np.ndarray, float]:
    arr = tensor.detach().cpu().to(torch.float32).numpy()
    max_abs = float(np.max(np.abs(arr))) if arr.size else 0.0
    scale = max(max_abs / N_QUANT, 1e-12)
    q = np.rint(arr / scale).clip(-N_QUANT, N_QUANT).astype(np.int8)
    return q, scale


def _encode_i8_as_u8(q: np.ndarray) -> np.ndarray:
    return (q.astype(np.int16) + 127).astype(np.uint8)


def _decode_u8_as_i8(raw: bytes, shape: tuple[int, ...]) -> np.ndarray:
    expected = math.prod(shape)
    arr = np.frombuffer(raw, dtype=np.uint8)
    if arr.size != expected:
        raise HNeRVGeneratedSchemaCodecError(
            f"decoded tensor raw symbol count {arr.size} != expected {expected}"
        )
    return (arr.astype(np.int16) - 127).astype(np.int8).reshape(shape)


def encode_generated_schema_state_dict(
    state_dict: dict[str, torch.Tensor],
    *,
    schema: Schema,
    brotli_quality: int = 11,
    brotli_lgwin: int | None = None,
    brotli_lgblock: int | None = None,
    codec_label: str = "hnerv_generated_schema_int8_brotli",
) -> EncodedGeneratedSchemaState:
    """Encode ``state_dict`` according to ``schema`` into one deterministic blob."""

    validate_state_dict_matches_schema(state_dict, schema)
    brotli_kwargs: dict[str, int] = {"quality": int(brotli_quality)}
    if brotli_lgwin is not None:
        brotli_kwargs["lgwin"] = int(brotli_lgwin)
    if brotli_lgblock is not None:
        brotli_kwargs["lgblock"] = int(brotli_lgblock)

    streams: list[bytes] = []
    rows: list[dict[str, Any]] = []
    for idx, (name, shape) in enumerate(schema):
        q, scale = _quantize_tensor(state_dict[name])
        raw = _encode_i8_as_u8(q).tobytes(order="C")
        compressed = brotli.compress(raw, **brotli_kwargs)
        rows.append(
            {
                "idx": idx,
                "name": name,
                "shape": list(shape),
                "scale": scale,
                "raw_symbols": int(q.size),
                "raw_bytes": len(raw),
                "brotli_bytes": len(compressed),
                "brotli_sha256": _sha256_bytes(compressed),
            }
        )
        streams.append(compressed)

    header_payload = {
        "schema": "hnerv_generated_schema_codec.v1",
        "codec_label": codec_label,
        "magic": MAGIC_HNGS.decode("ascii"),
        "n_quant": N_QUANT,
        "brotli": {
            "quality": brotli_quality,
            "lgwin": brotli_lgwin,
            "lgblock": brotli_lgblock,
        },
        "schema_fingerprint": schema_fingerprint(schema),
        "n_state_elements": schema_numel(schema),
        "state_schema": schema_to_jsonable(schema),
        "streams": rows,
    }
    header_bytes = _canonical_json(header_payload)
    blob = HEADER.pack(MAGIC_HNGS, len(header_bytes)) + header_bytes + b"".join(streams)
    manifest = {
        "schema": "hnerv_generated_schema_codec_manifest.v1",
        "score_claim": False,
        "promotion_eligible": False,
        "ready_for_exact_eval_dispatch": False,
        "codec_label": codec_label,
        "blob_bytes": len(blob),
        "blob_sha256": _sha256_bytes(blob),
        "header_bytes": len(header_bytes),
        "payload_bytes": sum(len(item) for item in streams),
        "schema_fingerprint": header_payload["schema_fingerprint"],
        "n_state_elements": schema_numel(schema),
        "stream_count": len(rows),
        "stream_total_brotli_bytes": sum(row["brotli_bytes"] for row in rows),
        "dispatch_blockers": [
            "codec_blob_not_integrated_into_submission_runtime_loader",
            "no_inflate_output_parity",
            "no_exact_cuda_auth_eval",
        ],
        "header": header_payload,
    }
    return EncodedGeneratedSchemaState(blob=blob, manifest=manifest)


def decode_generated_schema_blob(blob: bytes) -> tuple[dict[str, torch.Tensor], dict[str, Any]]:
    """Decode a blob produced by :func:`encode_generated_schema_state_dict`."""

    if len(blob) < HEADER.size:
        raise HNeRVGeneratedSchemaCodecError("payload too short for HNGS header")
    magic, header_len = HEADER.unpack_from(blob, 0)
    if magic != MAGIC_HNGS:
        raise HNeRVGeneratedSchemaCodecError(f"bad HNGS magic: {magic!r}")
    header_start = HEADER.size
    header_end = header_start + int(header_len)
    if header_end > len(blob):
        raise HNeRVGeneratedSchemaCodecError("truncated HNGS JSON header")
    try:
        header = json.loads(blob[header_start:header_end].decode("utf-8"))
    except json.JSONDecodeError as exc:
        raise HNeRVGeneratedSchemaCodecError("invalid HNGS JSON header") from exc
    if header.get("schema") != "hnerv_generated_schema_codec.v1":
        raise HNeRVGeneratedSchemaCodecError(
            f"unsupported HNGS schema: {header.get('schema')!r}"
        )

    pos = header_end
    state_dict: dict[str, torch.Tensor] = {}
    for row in header.get("streams", []):
        name = str(row["name"])
        shape = tuple(int(v) for v in row["shape"])
        n_bytes = int(row["brotli_bytes"])
        end = pos + n_bytes
        if end > len(blob):
            raise HNeRVGeneratedSchemaCodecError(f"truncated stream for {name!r}")
        compressed = blob[pos:end]
        if _sha256_bytes(compressed) != row.get("brotli_sha256"):
            raise HNeRVGeneratedSchemaCodecError(f"stream sha256 mismatch for {name!r}")
        raw = brotli.decompress(compressed)
        q = _decode_u8_as_i8(raw, shape)
        scale = float(row["scale"])
        state_dict[name] = torch.from_numpy(q.astype(np.float32) * scale)
        pos = end
    if pos != len(blob):
        raise HNeRVGeneratedSchemaCodecError(
            f"trailing bytes after HNGS streams: {len(blob) - pos}"
        )

    schema: Schema = tuple(
        (str(row["name"]), tuple(int(v) for v in row["shape"]))
        for row in header.get("state_schema", [])
    )
    validate_state_dict_matches_schema(state_dict, schema)
    if schema_fingerprint(schema) != header.get("schema_fingerprint"):
        raise HNeRVGeneratedSchemaCodecError("decoded schema fingerprint mismatch")

    manifest = {
        "schema": "hnerv_generated_schema_decode_manifest.v1",
        "score_claim": False,
        "blob_bytes": len(blob),
        "blob_sha256": _sha256_bytes(blob),
        "schema_fingerprint": header.get("schema_fingerprint"),
        "n_tensors": len(state_dict),
        "n_state_elements": schema_numel(schema),
        "header": header,
    }
    return state_dict, manifest


def manifest_without_header(encoded: EncodedGeneratedSchemaState) -> dict[str, Any]:
    """Return a compact manifest view suitable for ledgers."""

    payload = dict(encoded.manifest)
    payload.pop("header", None)
    return payload
