# SPDX-License-Identifier: MIT
"""Per-candidate authority packets for procedural codebook generation.

The lower-level authority classifier says which carriers are theoretically
admissible. This module ties that classifier to concrete archive evidence:
charged seed bytes must mutate generated bytes, and weight-derived codebooks
must cite a frozen source-member hash plus a no-new-bytes proof.
"""

from __future__ import annotations

import hashlib
import zipfile
from collections.abc import Sequence
from pathlib import Path
from typing import Any

from tac.authority_contract import apply_false_authority_contract

from .authority import (
    AuthorityMode,
    LiteralPayloadKind,
    build_procedural_seed_authority_packet,
)
from .hash_seed_codebook_generator import verify_generator_seed_mutation_smoke
from .weight_derived_codebook_generator import (
    freeze_source_member_sha256,
    verify_no_new_bytes_added,
)

SCHEMA = "procedural_codebook_candidate_authority_v1"


def build_procedural_codebook_candidate_authority(
    candidate_id: str,
    *,
    archive_path: Path,
    seed_member: str | None = None,
    source_member: str | None = None,
    before_archive: Path | None = None,
    after_archive: Path | None = None,
    include_runtime_constant: bool = False,
    runtime_constant_kind: LiteralPayloadKind = "per_video_payload",
    mutation_offsets: Sequence[int] = (0,),
    score_affecting: bool = True,
    runtime_consumption_proof: bool = False,
    self_contained_archive_proof: bool = False,
    scorer_free_inflate_proof: bool = False,
    no_external_state_proof: bool = False,
    packet_compiler_target_declared: bool = False,
    exact_eval_validated: bool = False,
) -> dict[str, Any]:
    """Return fail-closed candidate metadata with concrete authority proofs."""

    archive = Path(archive_path)
    modes = _requested_modes(
        seed_member=seed_member,
        source_member=source_member,
        include_runtime_constant=include_runtime_constant,
    )
    authority_packet = build_procedural_seed_authority_packet(
        candidate_id,
        modes=modes,
        runtime_constant_kind=runtime_constant_kind,
        score_affecting=score_affecting,
        runtime_consumption_proof=runtime_consumption_proof,
        self_contained_archive_proof=self_contained_archive_proof,
        scorer_free_inflate_proof=scorer_free_inflate_proof,
        no_external_state_proof=no_external_state_proof,
        packet_compiler_target_declared=packet_compiler_target_declared,
        exact_eval_validated=exact_eval_validated,
    )

    mode_proofs: dict[str, dict[str, Any]] = {}
    if seed_member is not None:
        seed_summary = _archive_member_summary(archive, seed_member)
        mutation_smoke = {
            "passed": verify_generator_seed_mutation_smoke(
                Path(seed_member),
                archive,
                tuple(mutation_offsets),
            ),
            "mutation_offsets": [int(offset) for offset in mutation_offsets],
            "provenance_kind": "archive_seed_mutation_smoke",
        }
        archive_proofs = {
            "seed_member": seed_summary,
            "seed_mutation_smoke": mutation_smoke,
        }
        authority_packet["modes"]["archive_seeded"]["proofs"] = archive_proofs
        mode_proofs["archive_seeded"] = archive_proofs

    if source_member is not None:
        source_sha256 = freeze_source_member_sha256(archive, source_member)
        no_new_bytes_proof = _no_new_bytes_proof(
            before_archive=before_archive,
            after_archive=after_archive,
        )
        weight_proofs = {
            "source_member": _archive_member_summary(archive, source_member),
            "no_new_bytes_added": no_new_bytes_proof,
        }
        weight_record = authority_packet["modes"]["weight_derived"]
        weight_record["source_member_sha256"] = source_sha256
        weight_record["proofs"] = weight_proofs
        mode_proofs["weight_derived"] = weight_proofs

    row: dict[str, Any] = {
        "schema": SCHEMA,
        "candidate_id": str(candidate_id),
        "archive_custody": _archive_custody(archive),
        "procedural_seed_authority_packet": authority_packet,
        "mode_proofs": mode_proofs,
        "research_only": True,
    }
    return apply_false_authority_contract(
        row,
        preserve_dispatch_ready=False,
        reason="procedural_codebook_candidate_authority_requires_exact_eval_result",
    )


def _requested_modes(
    *,
    seed_member: str | None,
    source_member: str | None,
    include_runtime_constant: bool,
) -> tuple[AuthorityMode, ...]:
    modes: list[AuthorityMode] = []
    if seed_member is not None:
        modes.append("archive_seeded")
    if source_member is not None:
        modes.append("weight_derived")
    if include_runtime_constant:
        modes.append("runtime_constant")
    if not modes:
        raise ValueError(
            "at least one of seed_member, source_member, or include_runtime_constant "
            "is required"
        )
    return tuple(modes)


def _archive_custody(archive_path: Path) -> dict[str, Any]:
    archive = Path(archive_path)
    payload = archive.read_bytes()
    with zipfile.ZipFile(archive) as zf:
        member_count = sum(1 for info in zf.infolist() if not info.is_dir())
    return {
        "archive_path": str(archive),
        "archive_bytes": archive.stat().st_size,
        "archive_sha256": hashlib.sha256(payload).hexdigest(),
        "member_count": member_count,
        "provenance_kind": "archive_zip_custody",
    }


def _archive_member_summary(archive_path: Path, member_name: str) -> dict[str, Any]:
    member = _normalize_member_name(member_name)
    with zipfile.ZipFile(archive_path) as zf:
        matches = [info for info in zf.infolist() if info.filename == member and not info.is_dir()]
        if len(matches) != 1:
            raise KeyError(f"expected exactly one archive member {member!r}")
        info = matches[0]
        payload = zf.read(info)
    return {
        "member": member,
        "bytes": len(payload),
        "compressed_bytes": int(info.compress_size),
        "crc32": f"{int(info.CRC):08x}",
        "sha256": hashlib.sha256(payload).hexdigest(),
        "provenance_kind": "charged_archive_member",
    }


def _no_new_bytes_proof(
    *,
    before_archive: Path | None,
    after_archive: Path | None,
) -> dict[str, Any]:
    if before_archive is None or after_archive is None:
        return {
            "passed": False,
            "reason": "before_archive_or_after_archive_missing",
            "provenance_kind": "weight_derived_no_new_bytes_proof",
        }
    return {
        "passed": verify_no_new_bytes_added(Path(before_archive), Path(after_archive)),
        "before_archive": str(before_archive),
        "after_archive": str(after_archive),
        "provenance_kind": "weight_derived_no_new_bytes_proof",
    }


def _normalize_member_name(member_name: str) -> str:
    member = str(member_name).lstrip("/")
    if (
        not member
        or member in {".", ".."}
        or member.startswith("../")
        or "/../" in member
        or "\\" in member
        or ":" in member
    ):
        raise ValueError(f"unsafe archive member path: {member_name!r}")
    return member


__all__ = [
    "SCHEMA",
    "build_procedural_codebook_candidate_authority",
]
