"""Deterministic information-geometry primitives."""

from tac.information_geometry.bregman_v9_surfaces import (
    DELTA_ETA_CONSISTENCY_ATOL,
    DELTA_ETA_CONSISTENCY_RTOL,
    GeometryValidationError,
    affine_legendre_logsumexp_summary,
    bregman_divergence,
    categorical_bregman_sigma_propagation,
    categorical_kl_from_logits,
    categorical_left_data_centroid,
    categorical_log_partition_hessian,
    categorical_negative_entropy_bregman,
    categorical_right_data_centroid,
    categorical_softmax,
    deterministic_bregman_application_fixture,
    exponential_family_sigma_kl_error,
    fisher_natural_cotangent_quadratic,
    local_hessian_dual_geometry_summary,
    logsumexp_bregman,
    logsumexp_bregman_closed_form_summary,
    positive_unscented_sigma_points,
    primal_hessian_quadratic,
    raw_dual_euclidean_quadratic,
    require_nonnegative_bregman,
    solve_fisher_natural_cotangent,
    squared_hessian_quadratic,
    stable_logsumexp,
)

__all__ = [
    "DELTA_ETA_CONSISTENCY_ATOL",
    "DELTA_ETA_CONSISTENCY_RTOL",
    "GeometryValidationError",
    "affine_legendre_logsumexp_summary",
    "bregman_divergence",
    "categorical_bregman_sigma_propagation",
    "categorical_kl_from_logits",
    "categorical_left_data_centroid",
    "categorical_log_partition_hessian",
    "categorical_negative_entropy_bregman",
    "categorical_right_data_centroid",
    "categorical_softmax",
    "deterministic_bregman_application_fixture",
    "exponential_family_sigma_kl_error",
    "fisher_natural_cotangent_quadratic",
    "local_hessian_dual_geometry_summary",
    "logsumexp_bregman",
    "logsumexp_bregman_closed_form_summary",
    "positive_unscented_sigma_points",
    "primal_hessian_quadratic",
    "raw_dual_euclidean_quadratic",
    "require_nonnegative_bregman",
    "solve_fisher_natural_cotangent",
    "squared_hessian_quadratic",
    "stable_logsumexp",
]
