# SPDX-License-Identifier: MIT
"""Finite genuine-frame inverse for decoded analytic Lane-mask residuals.

This module is a representation-fidelity primitive.  It does not run a scorer
and makes no score claim.  Learned state is restricted to a finite signed-int8
coefficient tensor plus its small program header; the literal polar curvelet,
compact shearlet, chart-coordinate construction, and renderer are generic
decoder algorithms.
"""

from __future__ import annotations

import hashlib
import json
import math
import struct
from collections.abc import Sequence
from dataclasses import asdict, dataclass
from typing import Any, Literal

import numpy as np

from tac.boundary_math.compact_shearlet_frame import (
    CompactShearletConfig,
    compact_shearlet_feats,
    shearlet_atom_index,
)
from tac.boundary_math.lane_sdf_component import _CAM_H, _FX, _FY, _V_HORIZON, LaneLine
from tac.boundary_math.localized_basis_frames import (
    ATOM_SPEC_SHA256,
    atom_feature_numpy,
    basis_features_numpy,
    deterministic_atom_specs,
)
from tac.boundary_math.localized_basis_frames import (
    FEATURE_WIDTH as CURVELET_WIDTH,
)
from tac.optimization.arith_selfcomp_rate_coders import (
    decode_spatial_context_arithmetic,
    encode_spatial_context_arithmetic,
)

SCHEMA = "boundary_inverse_custody.v1"
MAGIC = b"BIC1"
VERSION = 1
RATE_PRICE_S_PER_BYTE = 25.0 / 37_545_489.0
CoordinateMode = Literal["generic_2d", "dash_arc_phase"]

# Fixed and video-independent.  It is regenerated by the interpreter and is
# therefore not counted learned state.
SHEARLET_CONFIG = CompactShearletConfig(
    n_scales=2,
    n_shear=1,
    two_cones=True,
    shear_step=0.5,
    f0=2.0,
    base=2.0,
    w0=0.5,
    width_ratio=2.0,
    n_trans=3,
    coord_margin=0.15,
    min_sigma=0.02,
    aniso=1.0,
)
SHEARLET_ATOMS = shearlet_atom_index(SHEARLET_CONFIG)
SHEARLET_COMPLEX_WIDTH = 2 * len(SHEARLET_ATOMS)
DICTIONARY_WIDTH = CURVELET_WIDTH + SHEARLET_COMPLEX_WIDTH
_HEADER_PREFIX = struct.Struct("<4sHI")
_PAYLOAD_LENGTH = struct.Struct("<I")
_GL_NODES, _GL_WEIGHTS = np.polynomial.legendre.leggauss(8)


class BoundaryInverseError(ValueError):
    """Raised when a sparse inverse program or its custody is invalid."""


@dataclass(frozen=True)
class CorrectionDomain:
    """Sparse receiver domain in flattened image order."""

    flat_indices: np.ndarray
    coords: np.ndarray
    phase_bins: np.ndarray


@dataclass(frozen=True)
class SparseInverseProgram:
    """Decoded counted state for one finite inverse treatment."""

    coordinate_mode: CoordinateMode
    phase_bin_count: int
    qstep: float
    threshold: float
    qcoeff: np.ndarray

    def __post_init__(self) -> None:
        if self.coordinate_mode not in {"generic_2d", "dash_arc_phase"}:
            raise BoundaryInverseError(f"unknown coordinate mode {self.coordinate_mode!r}")
        if (
            isinstance(self.phase_bin_count, bool)
            or not isinstance(self.phase_bin_count, (int, np.integer))
            or self.phase_bin_count <= 0
        ):
            raise BoundaryInverseError("phase_bin_count must be a positive integer")
        if self.coordinate_mode == "generic_2d" and self.phase_bin_count != 1:
            raise BoundaryInverseError("generic_2d requires exactly one coefficient row")
        if not math.isfinite(self.qstep) or self.qstep <= 0.0:
            raise BoundaryInverseError("qstep must be finite and positive")
        if not math.isfinite(self.threshold) or self.threshold <= 0.0:
            raise BoundaryInverseError("threshold must be finite and positive")
        values = np.asarray(self.qcoeff)
        if values.dtype != np.int8:
            raise BoundaryInverseError("qcoeff must be int8")
        if values.shape != (self.phase_bin_count, DICTIONARY_WIDTH):
            raise BoundaryInverseError(
                f"qcoeff shape must be {(self.phase_bin_count, DICTIONARY_WIDTH)}, got {values.shape}"
            )

    @property
    def atom_count(self) -> int:
        return int(np.count_nonzero(self.qcoeff))

    @property
    def selected_curvelet_count(self) -> int:
        return int(np.count_nonzero(self.qcoeff[:, :CURVELET_WIDTH]))

    @property
    def selected_shearlet_count(self) -> int:
        return int(np.count_nonzero(self.qcoeff[:, CURVELET_WIDTH:]))


@dataclass(frozen=True)
class SparseSolveResult:
    program: SparseInverseProgram
    selected_atom_ids_by_bin: tuple[tuple[int, ...], ...]
    sample_count_by_bin: tuple[int, ...]
    residual_count_by_bin: tuple[int, ...]


def dictionary_metadata() -> dict[str, Any]:
    shear_payload = json.dumps(asdict(SHEARLET_CONFIG), sort_keys=True, separators=(",", ":"), allow_nan=False).encode(
        "utf-8"
    )
    return {
        "dictionary_width": DICTIONARY_WIDTH,
        "literal_polar_curvelet_columns": CURVELET_WIDTH,
        "compact_shearlet_columns": SHEARLET_COMPLEX_WIDTH,
        "literal_polar_curvelet_atom_spec_sha256": ATOM_SPEC_SHA256,
        "compact_shearlet_config": asdict(SHEARLET_CONFIG),
        "compact_shearlet_config_sha256": hashlib.sha256(shear_payload).hexdigest(),
        "families": ["literal_polar_curvelet", "compact_shearlet"],
        "forbidden_substitute": "Fourier",
    }


def _all_features(coords: np.ndarray) -> np.ndarray:
    xy = np.asarray(coords, dtype=np.float64)
    if xy.ndim != 2 or xy.shape[1] != 2:
        raise BoundaryInverseError(f"coords must have shape (N,2), got {xy.shape}")
    curvelet = basis_features_numpy(xy)
    shearlet = compact_shearlet_feats(xy, SHEARLET_CONFIG)
    return np.concatenate((curvelet, shearlet), axis=1).astype(np.float32, copy=False)


def _selected_features(coords: np.ndarray, atom_ids: np.ndarray) -> np.ndarray:
    xy = np.asarray(coords, dtype=np.float64)
    ids = np.asarray(atom_ids, dtype=np.int64).reshape(-1)
    if ids.size == 0:
        return np.zeros((xy.shape[0], 0), dtype=np.float32)
    if int(ids.min()) < 0 or int(ids.max()) >= DICTIONARY_WIDTH:
        raise BoundaryInverseError("selected atom id is outside the finite dictionary")
    out = np.empty((xy.shape[0], ids.size), dtype=np.float32)
    curve_specs = deterministic_atom_specs()
    shear_count = len(SHEARLET_ATOMS)
    x, y = xy[:, 0], xy[:, 1]
    for output_column, atom_id in enumerate(ids.tolist()):
        if atom_id < CURVELET_WIDTH:
            out[:, output_column] = atom_feature_numpy(xy, curve_specs[atom_id])
            continue
        local = atom_id - CURVELET_WIDTH
        imag = local >= shear_count
        atom = SHEARLET_ATOMS[local - shear_count if imag else local]
        dx = x - atom.cx
        dy = y - atom.cy
        if atom.cone == 0:
            xi, eta = dx + atom.shear_k * dy, dy
        else:
            xi, eta = dy + atom.shear_k * dx, dx
        envelope = np.exp(-0.5 * ((xi / atom.sigma_n) ** 2 + (eta / atom.sigma_t) ** 2))
        phase = 2.0 * math.pi * atom.freq * xi
        values = envelope * (np.sin(phase) if imag else np.cos(phase))
        out[:, output_column] = np.asarray(values, dtype=np.float32)
    return out


def _arc_length_from_zero(line: LaneLine, forward: np.ndarray) -> np.ndarray:
    """Deterministic eight-node quadrature of the polynomial centerline arc."""

    f = np.asarray(forward, dtype=np.float64)
    midpoint = 0.5 * f
    halfspan = 0.5 * f
    samples = midpoint[..., None] + halfspan[..., None] * _GL_NODES
    derivative = np.polyval(np.polyder(np.asarray(line.centerline_coeffs, np.float64)), samples)
    integrand = np.sqrt(1.0 + derivative * derivative)
    return halfspan * np.sum(integrand * _GL_WEIGHTS, axis=-1, dtype=np.float64)


def chart_correction_domain(
    lines: Sequence[LaneLine],
    *,
    height: int,
    width: int,
    coordinate_mode: CoordinateMode,
    phase_bin_count: int,
    corridor_halfwidths: float = 3.0,
) -> CorrectionDomain:
    """Build a deterministic decoded-chart support and coordinate system.

    The generic arm uses image coordinates.  The treatment arm uses normalized
    cross-line displacement and local centerline arc-length dash phase, and
    refuses undashed lines rather than attaching a phase label after the fact.
    """

    if coordinate_mode not in {"generic_2d", "dash_arc_phase"}:
        raise BoundaryInverseError(f"unknown coordinate mode {coordinate_mode!r}")
    if phase_bin_count <= 0 or (coordinate_mode == "generic_2d" and phase_bin_count != 1):
        raise BoundaryInverseError("invalid phase_bin_count for coordinate mode")
    if not math.isfinite(corridor_halfwidths) or corridor_halfwidths <= 0.0:
        raise BoundaryInverseError("corridor_halfwidths must be finite and positive")
    h, w = int(height), int(width)
    rows = np.arange(h, dtype=np.float64)
    columns = np.arange(w, dtype=np.float64)[None, :]
    forward = _CAM_H * _FY / np.maximum(rows - _V_HORIZON, 1e-3)
    best = np.full((h, w), np.inf, dtype=np.float64)
    best_normal = np.zeros((h, w), dtype=np.float64)
    best_phase = np.zeros((h, w), dtype=np.float64)
    for line in lines:
        if coordinate_mode == "dash_arc_phase" and line.dash_period_m <= 0.0:
            continue
        f0, f1 = line.forward_range
        geometry_forward = np.clip(forward, max(f0 - 1.0, 1e-3), f1 + 5.0)
        lateral = line.lateral_of_forward(geometry_forward)
        center = width / 2.0 - lateral * _FX / geometry_forward
        halfwidth = np.maximum(line.halfwidth_of_v(rows), 0.5)
        valid_row = (rows > _V_HORIZON + 1.0) & (forward >= f0 - 1.0) & (forward <= f1 + 5.0)
        normal = (columns - center[:, None]) / (float(corridor_halfwidths) * halfwidth[:, None])
        distance = np.abs(normal)
        candidate = valid_row[:, None] & (distance <= 1.0) & (distance < best)
        if not np.any(candidate):
            continue
        best[candidate] = distance[candidate]
        best_normal[candidate] = normal[candidate]
        if coordinate_mode == "dash_arc_phase":
            arc = _arc_length_from_zero(line, geometry_forward)
            anchor = float(_arc_length_from_zero(line, np.asarray([line.dash_phase_m], np.float64))[0])
            phase = np.mod(arc - anchor, float(line.dash_period_m)) / float(line.dash_period_m)
            phase_grid = np.broadcast_to(phase[:, None], (h, w))
            best_phase[candidate] = phase_grid[candidate]
    support = np.isfinite(best)
    flat_indices = np.flatnonzero(support.reshape(-1)).astype(np.int64)
    if flat_indices.size == 0:
        return CorrectionDomain(
            flat_indices=flat_indices,
            coords=np.zeros((0, 2), dtype=np.float32),
            phase_bins=np.zeros(0, dtype=np.int16),
        )
    if coordinate_mode == "generic_2d":
        vv, uu = np.unravel_index(flat_indices, (h, w))
        coords = np.stack(
            (
                2.0 * uu.astype(np.float64) / max(w - 1, 1) - 1.0,
                2.0 * vv.astype(np.float64) / max(h - 1, 1) - 1.0,
            ),
            axis=1,
        )
        bins = np.zeros(flat_indices.size, dtype=np.int16)
    else:
        phase = np.minimum(best_phase.reshape(-1)[flat_indices], np.nextafter(1.0, 0.0))
        bins = np.floor(phase * phase_bin_count).astype(np.int16)
        local_phase = 2.0 * (phase * phase_bin_count - bins.astype(np.float64)) - 1.0
        coords = np.stack((best_normal.reshape(-1)[flat_indices], local_phase), axis=1)
    return CorrectionDomain(
        flat_indices=flat_indices,
        coords=np.asarray(coords, dtype=np.float32),
        phase_bins=bins,
    )


def deterministic_training_indices(
    residual: np.ndarray,
    *,
    max_per_residual_sign: int = 192,
    max_zero: int = 192,
) -> np.ndarray:
    """Take bounded, order-stable samples of add/remove/dead-zone targets."""

    if max_per_residual_sign < 0 or max_zero < 0:
        raise BoundaryInverseError("training sample caps must be non-negative")
    values = np.asarray(residual, dtype=np.int8).reshape(-1)
    selected: list[np.ndarray] = []
    for target, cap in ((-1, max_per_residual_sign), (0, max_zero), (1, max_per_residual_sign)):
        positions = np.flatnonzero(values == target)
        if positions.size > cap:
            take = np.linspace(0, positions.size - 1, cap, dtype=np.int64)
            positions = positions[take]
        selected.append(positions)
    if not selected:
        return np.zeros(0, dtype=np.int64)
    return np.sort(np.concatenate(selected)).astype(np.int64, copy=False)


def _screen_atom_order(features: np.ndarray, target: np.ndarray, limit: int) -> np.ndarray:
    values = features.astype(np.float64)
    target64 = target.astype(np.float64)
    energy = np.einsum("ij,ij->j", values, values, optimize=False) + 1e-12
    correlation = np.einsum("ij,i->j", values, target64, optimize=False)
    merit = np.abs(correlation) / np.sqrt(energy)
    ranked = np.lexsort((np.arange(merit.size), -merit))
    forced = [
        int(np.argmax(merit[:CURVELET_WIDTH])),
        int(CURVELET_WIDTH + np.argmax(merit[CURVELET_WIDTH:])),
    ]
    order: list[int] = []
    for atom_id in forced + ranked.tolist():
        if atom_id not in order:
            order.append(atom_id)
        if len(order) >= limit:
            break
    return np.asarray(order, dtype=np.int64)


def fit_sparse_program(
    *,
    coords: np.ndarray,
    phase_bins: np.ndarray,
    residual: np.ndarray,
    coordinate_mode: CoordinateMode,
    phase_bin_count: int,
    atoms_per_bin: int,
    qstep: float = 1.0 / 64.0,
    threshold: float = 0.25,
    ridge: float = 1e-4,
) -> SparseSolveResult:
    """Fit a deterministic screened finite inverse and quantize it to int8."""

    return fit_sparse_program_sweep(
        coords=coords,
        phase_bins=phase_bins,
        residual=residual,
        coordinate_mode=coordinate_mode,
        phase_bin_count=phase_bin_count,
        atoms_per_bin_values=(atoms_per_bin,),
        qstep=qstep,
        threshold=threshold,
        ridge=ridge,
    )[int(atoms_per_bin)]


def fit_sparse_program_sweep(
    *,
    coords: np.ndarray,
    phase_bins: np.ndarray,
    residual: np.ndarray,
    coordinate_mode: CoordinateMode,
    phase_bin_count: int,
    atoms_per_bin_values: Sequence[int],
    qstep: float = 1.0 / 64.0,
    threshold: float = 0.25,
    ridge: float = 1e-4,
) -> dict[int, SparseSolveResult]:
    """Fit multiple prefixes while evaluating the full finite frame once per bin."""

    xy = np.asarray(coords, dtype=np.float32)
    bins = np.asarray(phase_bins, dtype=np.int64).reshape(-1)
    target = np.asarray(residual, dtype=np.float64).reshape(-1)
    if coordinate_mode not in {"generic_2d", "dash_arc_phase"}:
        raise BoundaryInverseError(f"unknown coordinate mode {coordinate_mode!r}")
    if isinstance(phase_bin_count, bool) or not isinstance(phase_bin_count, (int, np.integer)) or phase_bin_count <= 0:
        raise BoundaryInverseError("phase_bin_count must be a positive integer")
    if coordinate_mode == "generic_2d" and phase_bin_count != 1:
        raise BoundaryInverseError("generic_2d requires exactly one coefficient row")
    if not math.isfinite(qstep) or qstep <= 0.0:
        raise BoundaryInverseError("qstep must be finite and positive")
    if not math.isfinite(threshold) or threshold <= 0.0:
        raise BoundaryInverseError("threshold must be finite and positive")
    if not math.isfinite(ridge) or ridge <= 0.0:
        raise BoundaryInverseError("ridge must be finite and positive")
    if xy.shape != (target.size, 2) or bins.shape != (target.size,):
        raise BoundaryInverseError("training coords, bins, and residual must align")
    if bins.size and (int(bins.min()) < 0 or int(bins.max()) >= phase_bin_count):
        raise BoundaryInverseError("training phase bin is out of range")
    prefixes = tuple(sorted({int(value) for value in atoms_per_bin_values}))
    if not prefixes or prefixes[0] < 2 or prefixes[-1] > DICTIONARY_WIDTH:
        raise BoundaryInverseError("atom prefixes must be in [2, dictionary width]")
    if not set(np.unique(target).tolist()).issubset({-1.0, 0.0, 1.0}):
        raise BoundaryInverseError("residual targets must be in {-1,0,+1}")
    qcoeff_by_prefix = {prefix: np.zeros((phase_bin_count, DICTIONARY_WIDTH), dtype=np.int8) for prefix in prefixes}
    orders_by_prefix: dict[int, list[tuple[int, ...]]] = {prefix: [] for prefix in prefixes}
    sample_counts: list[int] = []
    residual_counts: list[int] = []
    for phase_bin in range(phase_bin_count):
        chosen_rows = bins == phase_bin
        sample_counts.append(int(np.count_nonzero(chosen_rows)))
        residual_counts.append(int(np.count_nonzero(target[chosen_rows])))
        if not np.any(chosen_rows) or not np.any(target[chosen_rows]):
            for prefix in prefixes:
                orders_by_prefix[prefix].append(())
            continue
        features = _all_features(xy[chosen_rows])
        if not np.all(np.isfinite(features)):
            raise BoundaryInverseError(f"non-finite frame feature in phase bin {phase_bin}")
        order = _screen_atom_order(features, target[chosen_rows], prefixes[-1])
        for prefix in prefixes:
            prefix_order = order[:prefix]
            selected = features[:, prefix_order].astype(np.float64)
            gram = np.einsum("ni,nj->ij", selected, selected, optimize=False)
            rhs = np.einsum("ni,n->i", selected, target[chosen_rows].astype(np.float64), optimize=False)
            coefficients = np.linalg.solve(gram + float(ridge) * np.eye(prefix_order.size, dtype=np.float64), rhs)
            if not np.all(np.isfinite(coefficients)):
                raise BoundaryInverseError(f"non-finite sparse coefficients in phase bin {phase_bin}, prefix {prefix}")
            quantized = np.clip(np.rint(coefficients / qstep), -127, 127).astype(np.int8)
            for forced_index in range(min(2, quantized.size)):
                if quantized[forced_index] == 0:
                    quantized[forced_index] = 1 if coefficients[forced_index] >= 0.0 else -1
            qcoeff_by_prefix[prefix][phase_bin, prefix_order] = quantized
            orders_by_prefix[prefix].append(tuple(int(value) for value in prefix_order.tolist()))
    return {
        prefix: SparseSolveResult(
            program=SparseInverseProgram(
                coordinate_mode=coordinate_mode,
                phase_bin_count=phase_bin_count,
                qstep=float(qstep),
                threshold=float(threshold),
                qcoeff=qcoeff_by_prefix[prefix],
            ),
            selected_atom_ids_by_bin=tuple(orders_by_prefix[prefix]),
            sample_count_by_bin=tuple(sample_counts),
            residual_count_by_bin=tuple(residual_counts),
        )
        for prefix in prefixes
    }


def _program_header(program: SparseInverseProgram) -> bytes:
    payload = {
        "schema": SCHEMA,
        "coordinate_mode": program.coordinate_mode,
        "phase_bin_count": program.phase_bin_count,
        "qstep": program.qstep,
        "threshold": program.threshold,
        "qcoeff_shape": list(program.qcoeff.shape),
        "qcoeff_dtype": "int8",
        "codec": "repository_spatial_context_arithmetic_557",
    }
    return json.dumps(payload, sort_keys=True, separators=(",", ":"), allow_nan=False).encode("utf-8")


def encode_program(program: SparseInverseProgram, *, verify: bool = True) -> bytes:
    """Encode all selected IDs and coefficients in a strict counted container."""

    header = _program_header(program)
    framed = encode_spatial_context_arithmetic(program.qcoeff[None, :, :, None])
    blob = _HEADER_PREFIX.pack(MAGIC, VERSION, len(header)) + header + _PAYLOAD_LENGTH.pack(len(framed)) + framed
    if verify:
        restored = decode_program(blob, verify_reencode=False)
        if not np.array_equal(restored.qcoeff, program.qcoeff):
            raise BoundaryInverseError("program encoder failed exact qcoeff parseback")
        if encode_program(restored, verify=False) != blob:
            raise BoundaryInverseError("program encoder failed byte-identical re-encode")
    return blob


def decode_program(blob: bytes, *, verify_reencode: bool = True) -> SparseInverseProgram:
    """Strict inverse of :func:`encode_program`, including trailing-byte refusal."""

    data = bytes(blob)
    if len(data) < _HEADER_PREFIX.size + _PAYLOAD_LENGTH.size:
        raise BoundaryInverseError("truncated boundary inverse program")
    magic, version, header_length = _HEADER_PREFIX.unpack_from(data, 0)
    if magic != MAGIC or version != VERSION:
        raise BoundaryInverseError("bad boundary inverse magic or version")
    offset = _HEADER_PREFIX.size
    header_stop = offset + int(header_length)
    if header_stop + _PAYLOAD_LENGTH.size > len(data):
        raise BoundaryInverseError("truncated boundary inverse header")
    try:
        header = json.loads(data[offset:header_stop].decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise BoundaryInverseError("invalid boundary inverse header JSON") from exc
    offset = header_stop
    (payload_length,) = _PAYLOAD_LENGTH.unpack_from(data, offset)
    offset += _PAYLOAD_LENGTH.size
    payload_stop = offset + int(payload_length)
    if payload_stop != len(data):
        label = "truncated" if payload_stop > len(data) else "trailing"
        raise BoundaryInverseError(f"{label} boundary inverse payload")
    required = {
        "schema",
        "coordinate_mode",
        "phase_bin_count",
        "qstep",
        "threshold",
        "qcoeff_shape",
        "qcoeff_dtype",
        "codec",
    }
    if set(header) != required or header["schema"] != SCHEMA:
        raise BoundaryInverseError("boundary inverse header schema/keys mismatch")
    if header["qcoeff_dtype"] != "int8" or header["codec"] != ("repository_spatial_context_arithmetic_557"):
        raise BoundaryInverseError("boundary inverse dtype/codec mismatch")
    restored = decode_spatial_context_arithmetic(data[offset:payload_stop])
    if not isinstance(header["qcoeff_shape"], list) or len(header["qcoeff_shape"]) != 2:
        raise BoundaryInverseError("boundary inverse qcoeff shape header must have rank two")
    shape = tuple(int(value) for value in header["qcoeff_shape"])
    expected_codec_shape = (1, shape[0], shape[1], 1)
    if restored.dtype != np.int8 or restored.shape != expected_codec_shape:
        raise BoundaryInverseError(f"decoded qcoeff shape/dtype mismatch: {restored.shape}/{restored.dtype}")
    program = SparseInverseProgram(
        coordinate_mode=header["coordinate_mode"],
        phase_bin_count=int(header["phase_bin_count"]),
        qstep=float(header["qstep"]),
        threshold=float(header["threshold"]),
        qcoeff=np.asarray(restored[0, :, :, 0], dtype=np.int8),
    )
    if tuple(program.qcoeff.shape) != shape:
        raise BoundaryInverseError("header qcoeff shape does not match decoded program")
    if verify_reencode and encode_program(program, verify=False) != data:
        raise BoundaryInverseError("boundary inverse program is not canonically encoded")
    return program


def apply_sparse_program(
    baseline: np.ndarray,
    lines: Sequence[LaneLine],
    program: SparseInverseProgram,
    *,
    corridor_halfwidths: float = 3.0,
) -> tuple[np.ndarray, dict[str, int]]:
    """Render and apply a decoded finite correction without truth access."""

    base = np.asarray(baseline, dtype=bool)
    if base.ndim != 2:
        raise BoundaryInverseError("baseline must be a 2-D boolean mask")
    domain = chart_correction_domain(
        lines,
        height=base.shape[0],
        width=base.shape[1],
        coordinate_mode=program.coordinate_mode,
        phase_bin_count=program.phase_bin_count,
        corridor_halfwidths=corridor_halfwidths,
    )
    corrected = base.copy().reshape(-1)
    score = np.zeros(domain.flat_indices.size, dtype=np.float32)
    for phase_bin in range(program.phase_bin_count):
        rows = domain.phase_bins == phase_bin
        atom_ids = np.flatnonzero(program.qcoeff[phase_bin]).astype(np.int64)
        if not np.any(rows) or atom_ids.size == 0:
            continue
        features = _selected_features(domain.coords[rows], atom_ids)
        coefficients = program.qcoeff[phase_bin, atom_ids].astype(np.float32) * program.qstep
        rendered = np.einsum(
            "ij,j->i",
            features.astype(np.float64),
            coefficients.astype(np.float64),
            optimize=False,
        )
        if not np.all(np.isfinite(rendered)):
            raise BoundaryInverseError(f"non-finite rendered correction in phase bin {phase_bin}")
        score[rows] = rendered.astype(np.float32)
    current = corrected[domain.flat_indices]
    add = (~current) & (score >= program.threshold)
    remove = current & (score <= -program.threshold)
    current[add] = True
    current[remove] = False
    corrected[domain.flat_indices] = current
    return corrected.reshape(base.shape), {
        "support_pixels": int(domain.flat_indices.size),
        "added_pixels": int(np.count_nonzero(add)),
        "removed_pixels": int(np.count_nonzero(remove)),
    }


def flip_accounting(
    baseline: np.ndarray,
    corrected: np.ndarray,
    truth: np.ndarray,
    selector: np.ndarray | None = None,
) -> dict[str, int]:
    """Report beneficial/harmful changes and the exact uneaten residual."""

    base = np.asarray(baseline, dtype=bool)
    out = np.asarray(corrected, dtype=bool)
    target = np.asarray(truth, dtype=bool)
    if base.shape != out.shape or base.shape != target.shape:
        raise BoundaryInverseError("flip-accounting masks must have identical shape")
    chosen = np.ones(base.shape, dtype=bool) if selector is None else np.asarray(selector, bool)
    if chosen.shape != base.shape:
        raise BoundaryInverseError("flip-accounting selector shape mismatch")
    before_error = base != target
    after_error = out != target
    changed = (base != out) & chosen
    return {
        "pixels": int(np.count_nonzero(chosen)),
        "changed": int(np.count_nonzero(changed)),
        "beneficial": int(np.count_nonzero(changed & before_error & ~after_error)),
        "harmful": int(np.count_nonzero(changed & ~before_error & after_error)),
        "remaining_false_negative": int(np.count_nonzero(chosen & ~out & target)),
        "remaining_false_positive": int(np.count_nonzero(chosen & out & ~target)),
    }


def authority_labels() -> dict[str, Any]:
    return {
        "axis": "[macOS-CPU advisory]",
        "score_claim": False,
        "promotion_eligible": False,
        "pointer": "0.19108 [contest-CPU] UNMOVED",
        "mask_f1_is_dseg": False,
        "waterfill_status_without_through_r_recovery": "FORMALIZATION_PENDING",
    }


__all__ = [
    "CURVELET_WIDTH",
    "DICTIONARY_WIDTH",
    "RATE_PRICE_S_PER_BYTE",
    "SHEARLET_COMPLEX_WIDTH",
    "BoundaryInverseError",
    "CorrectionDomain",
    "SparseInverseProgram",
    "SparseSolveResult",
    "apply_sparse_program",
    "authority_labels",
    "chart_correction_domain",
    "decode_program",
    "deterministic_training_indices",
    "dictionary_metadata",
    "encode_program",
    "fit_sparse_program",
    "fit_sparse_program_sweep",
    "flip_accounting",
]
