# SPDX-License-Identifier: MIT
"""Research-source bindings for planning-only optimization math.

The objects here are not evidence of contest score movement. They bind paper
ideas to local variables, charged-byte contracts, and fail-closed blockers so
math-inspired planners cannot silently turn citations into dispatch authority.
"""

from __future__ import annotations

from collections.abc import Iterable, Mapping
from typing import Any

SCHEMA_VERSION = 1
TOOL_NAME = "tac.optimization.research_basis"


class ResearchBasisError(ValueError):
    """Raised when a research-basis request is malformed."""


REQUIRED_SOURCE_FIELDS = (
    "title",
    "authors",
    "year",
    "venue_or_status",
    "url",
    "lineage",
    "local_paradigms",
    "local_variables",
    "contest_terms",
    "charged_byte_contract",
    "hardening_blockers",
)

RESEARCH_SOURCE_ALIASES: dict[str, str] = {
    "balle_2018": "balle_hyperprior_2018",
    "rao_ballard1999": "rao_ballard_1999",
    "rao-ballard1999": "rao_ballard_1999",
    "dreamerv3": "dreamerv3_2023",
    "dvc_2019": "lu_dvc_2019",
    "ha_schmidhuber_2018": "ha_schmidhuber_world_models_2018",
    "rissanen1978": "rissanen_mdl_1978",
    "mackay2003": "mackay_itila_2003",
    "wyner_ziv": "wyner_ziv_1976",
    "tishby_zaslavsky": "tishby_zaslavsky_2015",
    "pnvc": "pnvc_2025",
    "snerv_spectra": "snerv_spectra_2025",
    "metanerv": "metanerv_2025",
    "dcvc_rt": "dcvc_rt_2025",
    "unified_intra_inter": "unified_intra_inter_nvc_2025",
    "glvc": "glvc_2025",
    "gnvc_vd": "gnvc_vd_2025",
}


RESEARCH_SOURCES: dict[str, dict[str, Any]] = {
    "balle_e2e_2017": {
        "title": "End-to-end Optimized Image Compression",
        "authors": ["Johannes Balle", "Valero Laparra", "Eero P. Simoncelli"],
        "year": 2017,
        "venue_or_status": "ICLR 2017 / arXiv:1611.01704",
        "url": "https://arxiv.org/abs/1611.01704",
        "lineage": ["learned_compression", "variational_rate_distortion"],
        "local_paradigms": ["field_equations", "mdl", "joint_codec_stack"],
        "local_variables": [
            "variational_action_delta",
            "description_length_delta_bytes",
            "d_score_d_epsilon",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Any learned decoder, latent, hyperparameter, or selector that affects inflate output must be inside archive.zip or fixed contest code.",
        "hardening_blockers": [
            "deterministic_quantization_contract",
            "byte_closed_archive_manifest",
            "exact_cuda_auth_eval",
        ],
    },
    "balle_hyperprior_2018": {
        "title": "Variational image compression with a scale hyperprior",
        "authors": [
            "Johannes Balle",
            "David Minnen",
            "Saurabh Singh",
            "Sung Jin Hwang",
            "Nick Johnston",
        ],
        "year": 2018,
        "venue_or_status": "ICLR 2018 / arXiv:1802.01436",
        "url": "https://arxiv.org/abs/1802.01436",
        "lineage": ["learned_compression", "hyperprior_entropy_model"],
        "local_paradigms": ["entropy_rate", "joint_codec_stack", "mdl"],
        "local_variables": [
            "conditional_entropy_floor_bits",
            "best_conditional_model_label",
            "model_byte_delta",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "Hyperprior side information is charged unless it is fixed contest runtime code.",
        "hardening_blockers": [
            "cross_platform_entropy_parameter_determinism",
            "runtime_parity_proof",
            "exact_cuda_auth_eval",
        ],
    },
    "fridrich_pq_wetpaper_2004": {
        "title": "Perturbed Quantization Steganography with Wet Paper Codes",
        "authors": ["Jessica Fridrich", "Miroslav Goljan", "David Soukal"],
        "year": 2004,
        "venue_or_status": "ACM Multimedia and Security Workshop 2004",
        "url": "https://doi.org/10.1145/1022431.1022435",
        "lineage": ["fridrich_lab", "wet_paper_codes", "sender_side_information"],
        "local_paradigms": ["categorical_masks", "field_equations", "entropy_rate"],
        "local_variables": [
            "atom_amplitude_epsilon",
            "selector_logits",
            "interaction_kernel",
            "conditional_groups",
        ],
        "contest_terms": ["archive_bytes", "seg_dist"],
        "charged_byte_contract": "Selection channels and side information must be reproducible from charged archive payload or fixed contest code.",
        "hardening_blockers": [
            "selection_channel_custody",
            "decoder_roundtrip_parity",
            "exact_stacked_archive_cuda_eval",
        ],
    },
    "fridrich_stc_2011": {
        "title": "Minimizing Additive Distortion in Steganography Using Syndrome-Trellis Codes",
        "authors": ["Tomas Filler", "Jan Judas", "Jessica Fridrich"],
        "year": 2011,
        "venue_or_status": "IEEE TIFS 2011",
        "url": "https://doi.org/10.1109/TIFS.2011.2134094",
        "lineage": ["fridrich_lab", "additive_distortion", "syndrome_trellis_codes"],
        "local_paradigms": ["field_equations", "meta_lagrangian", "pareto_kkt"],
        "local_variables": [
            "expected_total_score_delta",
            "expected_seg_dist_delta",
            "expected_pose_dist_delta",
            "byte_delta",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Per-atom distortion costs are planning weights until encoded in a byte-closed archive and scored exactly.",
        "hardening_blockers": [
            "measured_atom_response",
            "nonadditive_interaction_review",
            "exact_cuda_auth_eval",
        ],
    },
    "yousfi_onehot_jpeg_2020": {
        "title": "An Intriguing Struggle of CNNs in JPEG Steganalysis and the OneHot Solution",
        "authors": ["Yassine Yousfi", "Jessica Fridrich"],
        "year": 2020,
        "venue_or_status": "IEEE Signal Processing Letters 2020",
        "url": "https://doi.org/10.1109/LSP.2020.2993959",
        "lineage": ["fridrich_lab", "yousfi", "categorical_dct_statistics"],
        "local_paradigms": ["categorical_masks", "openpilot_labels", "entropy_rate"],
        "local_variables": [
            "symbol_counts",
            "conditional_groups",
            "family_group",
            "pareto_scope",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Categorical labels or DCT-style one-hot codes must be either derived by fixed inflate code or carried as charged bytes.",
        "hardening_blockers": [
            "label_source_custody",
            "deterministic_decoder_contract",
            "exact_cuda_auth_eval",
        ],
    },
    "yousfi_cost_polarization_2023": {
        "title": "Cost polarization by dequantizing for JPEG steganography",
        "authors": ["Edgar Kaziakhmedov", "Yassine Yousfi", "Eli Dworetzky", "Jessica Fridrich"],
        "year": 2023,
        "venue_or_status": "Electronic Imaging 2023",
        "url": "https://doi.org/10.2352/EI.2023.35.4.MWSF-374",
        "lineage": ["fridrich_lab", "yousfi", "cost_polarization"],
        "local_paradigms": ["field_equations", "categorical_masks", "entropy_rate"],
        "local_variables": [
            "frechet_derivatives",
            "selector_logits",
            "confidence",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Any dequantized or reconstructed precover signal used for selection must be reproducible from contest-legal inputs.",
        "hardening_blockers": [
            "precover_proxy_nonpromotable_until_archive_consumed",
            "atom_response_calibration",
            "exact_cuda_auth_eval",
        ],
    },
    "lapose_2026": {
        "title": "LA-Pose: Latent Action Pretraining Meets Pose Estimation",
        "authors": [
            "Zhengqing Wang",
            "Saurabh Nair",
            "Prajwal Chidananda",
            "Pujith Kachana",
            "Samuel Li",
            "Matthew Brown",
            "Yasutaka Furukawa",
        ],
        "year": 2026,
        "venue_or_status": "CVPR 2026 / arXiv:2604.27448",
        "url": "https://arxiv.org/abs/2604.27448",
        "lineage": ["latent_action_pretraining", "driving_video_pose"],
        "local_paradigms": ["la_pose", "pose", "optimal_transport"],
        "local_variables": [
            "expected_pose_dist_delta",
            "pose_atom",
            "family_group",
            "d_pose_dist_d_epsilon",
        ],
        "contest_terms": ["pose_dist"],
        "charged_byte_contract": "Latent-action priors may rank compression-time atoms, but any scored pose stream or model output must be byte-closed and deterministic.",
        "hardening_blockers": [
            "pose_target_custody",
            "deterministic_init_pose_cli",
            "exact_cuda_auth_eval",
        ],
    },
    "foveated_telepresence_2025": {
        "title": "Foveated Compression for Immersive Telepresence Visualization",
        "authors": ["Max Schwarz", "Sven Behnke"],
        "year": 2025,
        "venue_or_status": "IEEE TELEPRESENCE 2025 / arXiv:2510.19848",
        "url": "https://arxiv.org/abs/2510.19848",
        "lineage": ["foveated_video_compression", "spatial_rate_allocation"],
        "local_paradigms": ["telescopic_foveation", "field_equations", "meta_lagrangian"],
        "local_variables": [
            "byte_allocator_lambdas",
            "expected_seg_dist_delta",
            "expected_pose_dist_delta",
            "interaction_assumptions",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Foveation fields or gaze/center policies must be derivable from fixed contest code or charged archive payload.",
        "hardening_blockers": [
            "foveation_field_manifest",
            "pose_seg_component_gate",
            "exact_cuda_auth_eval",
        ],
    },
    "foveated_diffusion_2026": {
        "title": "Foveated Diffusion: Efficient Spatially Adaptive Image and Video Generation",
        "authors": ["Brian Chao", "Lior Yariv", "Howard Xiao", "Gordon Wetzstein"],
        "year": 2026,
        "venue_or_status": "arXiv:2603.23491",
        "url": "https://arxiv.org/abs/2603.23491",
        "lineage": ["foveated_generation", "mixed_resolution_tokens", "spatial_rate_allocation"],
        "local_paradigms": ["foveation", "telescopic_foveation", "field_equations", "meta_lagrangian"],
        "local_variables": [
            "foveation_token_density",
            "byte_allocator_lambdas",
            "expected_seg_dist_delta",
            "interaction_assumptions",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Mixed-resolution token or foveation-density policies are planning priors until their selectors and payload effects are byte-closed in archive.zip.",
        "hardening_blockers": [
            "mixed_resolution_token_runtime_contract",
            "archive_byte_accounting_required",
            "exact_cuda_auth_eval",
        ],
    },
    "nerv_2021": {
        "title": "NeRV: Neural Representations for Videos",
        "authors": ["Hao Chen", "Bo He", "Hanyu Wang", "Yixuan Ren", "Ser-Nam Lim", "Abhinav Shrivastava"],
        "year": 2021,
        "venue_or_status": "NeurIPS 2021 / arXiv:2110.13903",
        "url": "https://arxiv.org/abs/2110.13903",
        "lineage": ["neural_video_representation", "inr_video_compression"],
        "local_paradigms": ["alpha", "hnerv", "mask_payload"],
        "local_variables": [
            "decoder_entrypoint",
            "bytes_charged",
            "expected_seg_dist_delta",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Any NeRV decoder weights and mask latents used at inflate must be charged in the archive.",
        "hardening_blockers": [
            "decode_validation_required",
            "inflate_budget_required",
            "exact_cuda_auth_eval",
        ],
    },
    "hinerv_2023": {
        "title": "HiNeRV: Video Compression with Hierarchical Encoding-based Neural Representation",
        "authors": ["HiNeRV authors"],
        "year": 2023,
        "venue_or_status": "NeurIPS 2023 / arXiv:2306.09818",
        "url": "https://arxiv.org/abs/2306.09818",
        "lineage": ["neural_video_representation", "hierarchical_inr"],
        "local_paradigms": ["alpha", "hnerv", "mask_payload"],
        "local_variables": [
            "family_group",
            "expected_seg_dist_delta",
            "interaction_assumptions",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Hierarchical embeddings and side information are charged unless fixed in contest code.",
        "hardening_blockers": [
            "hierarchy_decode_roundtrip",
            "side_info_byte_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "geometric_visual_servo_ot_2026": {
        "title": "Geometric Visual Servo Via Optimal Transport",
        "authors": ["Ethan Canzini", "Simon Pope", "Ashutosh Tiwari"],
        "year": 2026,
        "venue_or_status": "Control Engineering Practice 2026 / arXiv:2506.02768v2",
        "url": "https://arxiv.org/abs/2506.02768",
        "lineage": ["optimal_transport", "se3_geodesic_flow", "visual_servoing"],
        "local_paradigms": ["pose", "optimal_transport", "field_equations", "meta_lagrangian"],
        "local_variables": [
            "geodesic_transport_cost",
            "expected_pose_dist_delta",
            "interaction_assumptions",
            "pareto_scope",
        ],
        "contest_terms": ["pose_dist", "archive_bytes"],
        "charged_byte_contract": "Geometric transport costs can rank pose/foveation atoms, but any pose stream, flow field, or selector consumed by inflate must be deterministic and charged.",
        "hardening_blockers": [
            "se3_transport_units_required",
            "runtime_pose_consumption_proof",
            "exact_cuda_auth_eval",
        ],
    },
    "telescope_2026": {
        "title": "Telescope: Long-Range Object Detection via Learnable Hyperbolic Foveation",
        "authors": ["Telescope authors"],
        "year": 2026,
        "venue_or_status": "arXiv:2604.06332",
        "url": "https://arxiv.org/abs/2604.06332",
        "lineage": ["hyperbolic_foveation", "spatial_rate_allocation"],
        "local_paradigms": ["telescopic_foveation", "field_equations", "mask_payload"],
        "local_variables": [
            "geometry_priors",
            "byte_allocator_lambdas",
            "expected_seg_dist_delta",
            "expected_pose_dist_delta",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Foveation parameters and inverse-warp policy must be deterministic and charged when used at inflate.",
        "hardening_blockers": [
            "foveation_archive_runtime_proof",
            "component_gate_required",
            "exact_cuda_auth_eval",
        ],
    },
    "lyra2_2026": {
        "title": "Lyra 2.0 long-horizon video synthesis mechanisms",
        "authors": ["NVIDIA Lyra 2.0 authors"],
        "year": 2026,
        "venue_or_status": "arXiv:2604.13036",
        "url": "https://arxiv.org/abs/2604.13036",
        "lineage": ["self_augmentation", "framepack", "canonical_coordinate_warping"],
        "local_paradigms": ["field_equations", "foveation", "pose", "mask_payload"],
        "local_variables": [
            "interaction_assumptions",
            "geometry_priors",
            "expected_pose_dist_delta",
            "expected_seg_dist_delta",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Self-augmentation may train selectors, but any coordinate warps or framepack policies consumed at inflate must be charged.",
        "hardening_blockers": [
            "roundtrip_aug_manifest",
            "coordinate_warp_decode_parity",
            "exact_cuda_auth_eval",
        ],
    },
    "mae_2021": {
        "title": "Masked Autoencoders Are Scalable Vision Learners",
        "authors": ["Kaiming He", "Xinlei Chen", "Saining Xie", "Yanghao Li", "Piotr Dollar", "Ross Girshick"],
        "year": 2021,
        "venue_or_status": "CVPR 2022 / arXiv:2111.06377",
        "url": "https://arxiv.org/abs/2111.06377",
        "lineage": ["masked_modeling", "asymmetric_encoder_decoder"],
        "local_paradigms": ["alpha", "mask_payload", "self_augmentation"],
        "local_variables": [
            "decoder_entrypoint",
            "bytes_charged",
            "expected_seg_dist_delta",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Sparse-visible-mask policies are charged payload decisions unless fixed and derivable at inflate.",
        "hardening_blockers": [
            "mask_sparsity_decode_parity",
            "pose_seg_component_gate",
            "exact_cuda_auth_eval",
        ],
    },
    "awq_2024": {
        "title": "AWQ: Activation-aware Weight Quantization",
        "authors": ["Ji Lin", "Jiaming Tang", "Haotian Tang", "Shang Yang", "Xingyu Dang", "Song Han"],
        "year": 2024,
        "venue_or_status": "MLSys 2024 / arXiv:2306.00978",
        "url": "https://arxiv.org/abs/2306.00978",
        "lineage": ["activation_aware_quantization", "mixed_precision"],
        "local_paradigms": ["sensitivity", "entropy_rate", "joint_codec_stack"],
        "local_variables": [
            "score_per_byte_marginal",
            "scorer_term_targeted",
            "byte_allocator_lambdas",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Protected-channel scales, masks, and quantization metadata must be charged or fixed.",
        "hardening_blockers": [
            "score_sensitivity_map_required",
            "deterministic_quantized_decode",
            "exact_cuda_auth_eval",
        ],
    },
    "hawq_v3_2020": {
        "title": "HAWQ-V3: Dyadic Neural Network Quantization",
        "authors": ["HAWQ-V3 authors"],
        "year": 2020,
        "venue_or_status": "arXiv:2011.10680",
        "url": "https://arxiv.org/abs/2011.10680",
        "lineage": ["hessian_aware_quantization", "mixed_precision"],
        "local_paradigms": ["sensitivity", "meta_lagrangian", "joint_codec_stack"],
        "local_variables": [
            "score_per_byte_marginal",
            "confidence",
            "pareto_objectives",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Mixed-precision decisions and scales must be deterministic archive payload or fixed code.",
        "hardening_blockers": [
            "hessian_or_fisher_custody",
            "byte_measured_quantized_stream",
            "exact_cuda_auth_eval",
        ],
    },
    "compressai": {
        "title": "CompressAI entropy-model and learned-compression reference implementation",
        "authors": ["InterDigital AI Lab contributors"],
        "year": 2020,
        "venue_or_status": "OSS reference / CompressAI documentation",
        "url": "https://interdigitalinc.github.io/CompressAI/",
        "lineage": ["learned_compression_oss", "entropy_models"],
        "local_paradigms": ["entropy_rate", "joint_codec_stack", "alpha"],
        "local_variables": [
            "conditional_entropy_floor_bits",
            "codec_kind",
            "bytes_charged",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "Reference entropy models may guide compression-time tooling; runtime dependencies and side info must be contest-legal and charged.",
        "hardening_blockers": [
            "dependency_policy_review",
            "deterministic_runtime_contract",
            "exact_cuda_auth_eval",
        ],
    },
    "constriction_ans": {
        "title": "constriction entropy coders",
        "authors": ["Bamler Lab contributors"],
        "year": 2022,
        "venue_or_status": "OSS entropy-coding library",
        "url": "https://github.com/bamler-lab/constriction",
        "lineage": ["ans_range_coding", "entropy_coder_implementation"],
        "local_paradigms": ["entropy_rate", "aq_huffman", "joint_codec_stack"],
        "local_variables": [
            "entropy_floor_bits",
            "gap_to_best_conditional_floor_bytes",
            "bytes_charged",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "Coder tables and compressed streams are charged; external libraries cannot be sidecar dependencies.",
        "hardening_blockers": [
            "rust_or_python_runtime_policy",
            "bit_exact_cross_platform_roundtrip",
            "exact_cuda_auth_eval",
        ],
    },
    "dworetzky_fridrich_detector_batch_2025": {
        "title": "Secure Payload Scaling in Detector-Informed Batch Steganography: The Mismatched Detectors Case",
        "authors": ["Eli Dworetzky", "Jessica Fridrich"],
        "year": 2025,
        "venue_or_status": "IH&MMSec 2025",
        "url": "https://doi.org/10.1145/3733102.3733134",
        "lineage": ["fridrich_lab", "detector_informed_batch_steganography", "mismatched_detectors"],
        "local_paradigms": ["meta_lagrangian", "bayesian_experimental_design", "field_equations"],
        "local_variables": [
            "expected_information_gain_nats",
            "confidence",
            "interaction_assumptions",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Detector-informed allocation can rank atoms, but the selected archive payload and any detector-derived tables must be charged or fixed.",
        "hardening_blockers": [
            "scorer_detector_mismatch_measurement",
            "candidate_archive_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "kaziakhmedov_fridrich_lies_2025": {
        "title": "Effect of Acquisition Noise Outliers on Steganalysis",
        "authors": ["Edgar Kaziakhmedov", "Jessica Fridrich", "Patrick Bas"],
        "year": 2025,
        "venue_or_status": "IH&MMSec 2025",
        "url": "https://ws2.binghamton.edu/fridrich/Research/LIEs_final_v2_pdfa.pdf",
        "lineage": ["fridrich_lab", "acquisition_noise_outliers", "local_influence"],
        "local_paradigms": ["sensitivity", "field_equations", "categorical_masks"],
        "local_variables": [
            "score_per_byte_marginal",
            "hard_pair_support",
            "selector_logits",
        ],
        "contest_terms": ["seg_dist", "pose_dist"],
        "charged_byte_contract": "Outlier-aware selection maps are planning priors until their chosen edits are encoded in a charged archive.",
        "hardening_blockers": [
            "contest_video_noise_proxy_required",
            "component_sensitivity_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "flavc_2025": {
        "title": "FLAVC: Learned Video Compression with Feature Level Attention",
        "authors": ["FLAVC authors"],
        "year": 2025,
        "venue_or_status": "CVPR 2025",
        "url": "https://openaccess.thecvf.com/content/CVPR2025/html/Zhang_FLAVC_Learned_Video_Compression_with_Feature_Level_Attention_CVPR_2025_paper.html",
        "lineage": ["learned_video_compression", "feature_level_attention"],
        "local_paradigms": ["entropy_rate", "joint_codec_stack", "field_equations"],
        "local_variables": [
            "codec_kind",
            "conditional_entropy_floor_bits",
            "score_per_byte_marginal",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Feature attention latents, entropy tables, and decoder weights must be charged if consumed by inflate.",
        "hardening_blockers": [
            "feature_latent_byte_accounting",
            "decoder_runtime_budget",
            "exact_cuda_auth_eval",
        ],
    },
    "lu_dvc_2019": {
        "title": "DVC: An End-To-End Deep Video Compression Framework",
        "authors": [
            "Guo Lu",
            "Wanli Ouyang",
            "Dong Xu",
            "Xiaoyun Zhang",
            "Chunlei Cai",
            "Zhiyong Gao",
        ],
        "year": 2019,
        "venue_or_status": "CVPR 2019",
        "url": "https://openaccess.thecvf.com/content_CVPR_2019/html/Lu_DVC_An_End-To-End_Deep_Video_Compression_Framework_CVPR_2019_paper.html",
        "lineage": ["learned_video_compression", "motion_compensation", "residual_coding"],
        "local_paradigms": ["time_traveler_l5", "predictive_receiver", "entropy_rate"],
        "local_variables": [
            "motion_compensation_state",
            "residual_entropy_delta",
            "learned_video_codec_payload",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Motion, residual, entropy-model, and decoder bytes are planning priors until emitted in the contest archive and consumed by inflate.",
        "hardening_blockers": [
            "motion_residual_payload_custody",
            "runtime_consumption_proof",
            "paired_cpu_cuda_empirical_anchor",
            "exact_cuda_auth_eval",
        ],
    },
    "msnerv_2025": {
        "title": "MSNeRV: Neural Video Representation with Multi-Scale Feature Fusion",
        "authors": ["MSNeRV authors"],
        "year": 2025,
        "venue_or_status": "arXiv:2506.15276",
        "url": "https://arxiv.org/abs/2506.15276",
        "lineage": ["neural_video_representation", "multi_scale_feature_fusion"],
        "local_paradigms": ["hnerv", "alpha", "joint_codec_stack"],
        "local_variables": [
            "family_group",
            "codec_kind",
            "expected_seg_dist_delta",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Multi-scale feature tensors and fusion weights are charged archive payload unless fixed in contest runtime.",
        "hardening_blockers": [
            "multi_scale_decode_parity",
            "inflate_budget_required",
            "exact_cuda_auth_eval",
        ],
    },
    "balle_overfitted_wasserstein_2025": {
        "title": "Good, Cheap, and Fast: Overfitted Image Compression with Wasserstein Distortion",
        "authors": ["Johannes Balle", "Fabian Versari", "Emilien Dupont", "Hyunjik Kim", "Matthias Bauer"],
        "year": 2025,
        "venue_or_status": "CVPR 2025",
        "url": "https://www.openaccess.thecvf.com/content/CVPR2025/html/Balle_Good_Cheap_and_Fast_Overfitted_Image_Compression_with_Wasserstein_Distortion_CVPR_2025_paper.html",
        "lineage": ["overfitted_compression", "wasserstein_distortion", "per_instance_codec"],
        "local_paradigms": ["mdl", "self_compressing_nn", "foveation"],
        "local_variables": [
            "description_length_delta_bytes",
            "expected_seg_dist_delta",
            "expected_pose_dist_delta",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Overfitted model parameters are archive payload; perceptual Wasserstein losses are only priors until mapped to SegNet/PoseNet.",
        "hardening_blockers": [
            "contest_distortion_mapping_required",
            "charged_model_bytes_required",
            "exact_cuda_auth_eval",
        ],
    },
    "compression_as_adaptation_2026": {
        "title": "Compression as Adaptation",
        "authors": ["Compression as Adaptation authors"],
        "year": 2026,
        "venue_or_status": "arXiv:2603.07615",
        "url": "https://arxiv.org/abs/2603.07615",
        "lineage": ["adaptation_as_compression", "per_instance_model_adaptation"],
        "local_paradigms": ["self_compressing_nn", "mdl", "bayesian_experimental_design"],
        "local_variables": [
            "model_byte_delta",
            "data_byte_delta",
            "expected_information_gain_nats",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Adapted parameters and any frozen model dependence must be contest-legal and charged or fixed.",
        "hardening_blockers": [
            "sidecar_model_forbidden",
            "runtime_budget_required",
            "exact_cuda_auth_eval",
        ],
    },
    "rdc_universal_2025": {
        "title": "Universal Rate-Distortion-Classification Representations",
        "authors": ["RDC authors"],
        "year": 2025,
        "venue_or_status": "arXiv:2504.09025",
        "url": "https://arxiv.org/abs/2504.09025",
        "lineage": ["rate_distortion_classification", "task_oriented_compression"],
        "local_paradigms": ["categorical_masks", "semantic_labels", "meta_lagrangian"],
        "local_variables": [
            "class_support",
            "expected_seg_dist_delta",
            "byte_delta",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Class representations, label maps, and codebooks must be charged or derived from fixed contest code.",
        "hardening_blockers": [
            "five_class_contract_instantiation",
            "label_codebook_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "rdc_bernoulli_2026": {
        "title": "RDC Representation Theory for Bernoulli Sources",
        "authors": ["RDC Bernoulli authors"],
        "year": 2026,
        "venue_or_status": "arXiv:2601.11919",
        "url": "https://arxiv.org/abs/2601.11919",
        "lineage": ["rate_distortion_classification", "bernoulli_sources"],
        "local_paradigms": ["categorical_masks", "entropy_rate", "field_equations"],
        "local_variables": [
            "symbol_counts",
            "conditional_groups",
            "entropy_floor_bits",
        ],
        "contest_terms": ["seg_dist", "archive_bytes"],
        "charged_byte_contract": "Bernoulli/categorical abstractions must be instantiated on contest class streams with charged codebooks.",
        "hardening_blockers": [
            "contest_class_distribution_custody",
            "charged_codebook_required",
            "exact_cuda_auth_eval",
        ],
    },
    "rao_ballard_1999": {
        "title": "Predictive coding in the visual cortex: a functional interpretation of some extra-classical receptive-field effects",
        "authors": ["Rajesh P. N. Rao", "Dana H. Ballard"],
        "year": 1999,
        "venue_or_status": "Nature Neuroscience 2, 79-87",
        "url": "https://www.nature.com/articles/nn0199_79",
        "lineage": ["predictive_coding", "visual_cortex", "residual_prediction"],
        "local_paradigms": ["time_traveler_l5", "world_model", "predictive_receiver"],
        "local_variables": [
            "expected_residual_entropy_delta",
            "latent_prediction_error",
            "temporal_residual_score_delta",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Predictive residuals and latent dynamics are planning priors until the predictor, residual stream, and decoder contract are byte-closed.",
        "hardening_blockers": [
            "prediction_residual_custody",
            "paired_cpu_cuda_empirical_anchor",
            "exact_cuda_auth_eval",
        ],
    },
    "friston_free_energy_2010": {
        "title": "The free-energy principle: a unified brain theory?",
        "authors": ["Karl Friston"],
        "year": 2010,
        "venue_or_status": "Nature Reviews Neuroscience 11, 127-138",
        "url": "https://www.nature.com/articles/nrn2787",
        "lineage": ["free_energy_principle", "predictive_processing", "variational_inference"],
        "local_paradigms": ["time_traveler_l5", "world_model", "meta_lagrangian"],
        "local_variables": [
            "variational_free_energy_proxy",
            "latent_prior_kl",
            "prediction_error_precision",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Free-energy or KL terms are objective priors; any posterior, prior, or precision table consumed by inflate must be charged or fixed.",
        "hardening_blockers": [
            "objective_to_contest_component_mapping",
            "posterior_prior_payload_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "dreamerv3_2023": {
        "title": "Mastering Diverse Domains through World Models",
        "authors": ["Danijar Hafner", "Jurgis Pasukonis", "Jimmy Ba", "Timothy Lillicrap"],
        "year": 2023,
        "venue_or_status": "arXiv:2301.04104",
        "url": "https://arxiv.org/abs/2301.04104",
        "lineage": ["world_models", "rssm", "latent_imagination"],
        "local_paradigms": ["time_traveler_l5", "c1_world_model", "predictive_receiver"],
        "local_variables": [
            "rssm_prior_kl",
            "posterior_prior_residual",
            "latent_rollout_error",
        ],
        "contest_terms": ["pose_dist", "seg_dist", "archive_bytes"],
        "charged_byte_contract": "Dreamer-style RSSM modules are analogy and architecture priors until the trained dynamics, latents, and decoder are byte-closed for contest inflate.",
        "hardening_blockers": [
            "rssm_byte_closed_archive",
            "frame_pair_component_ablation",
            "exact_cuda_auth_eval",
        ],
    },
    "ha_schmidhuber_world_models_2018": {
        "title": "World Models",
        "authors": ["David Ha", "Jurgen Schmidhuber"],
        "year": 2018,
        "venue_or_status": "arXiv:1803.10122",
        "url": "https://arxiv.org/abs/1803.10122",
        "lineage": ["world_models", "latent_dynamics", "compact_controller"],
        "local_paradigms": ["time_traveler_l5", "world_model", "predictive_receiver"],
        "local_variables": [
            "latent_dynamics_state",
            "recurrent_world_model_state",
            "controller_conditioning_payload",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "World-model weights, latent states, and controller state are architecture priors until byte-closed inside the contest archive or fixed runtime.",
        "hardening_blockers": [
            "world_model_state_custody",
            "runtime_decode_budget_anchor",
            "exact_cuda_auth_eval",
        ],
    },
    "atick_redlich_1990": {
        "title": "Towards a Theory of Early Visual Processing",
        "authors": ["Joseph J. Atick", "A. Norman Redlich"],
        "year": 1990,
        "venue_or_status": "Neural Computation 2(3), 308-320",
        "url": "https://doi.org/10.1162/neco.1990.2.3.308",
        "lineage": ["efficient_coding", "natural_image_statistics", "decorrelation"],
        "local_paradigms": ["atw_codec", "world_model", "entropy_rate"],
        "local_variables": [
            "natural_image_redundancy_delta",
            "decorrelation_filter",
            "expected_entropy_delta_bits",
        ],
        "contest_terms": ["archive_bytes", "seg_dist"],
        "charged_byte_contract": "Efficient-coding filters are planning priors unless their transform, inverse, and transmitted residuals are deterministic and byte-closed.",
        "hardening_blockers": [
            "transform_inverse_runtime_parity",
            "entropy_model_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "tishby_information_bottleneck_1999": {
        "title": "The Information Bottleneck Method",
        "authors": ["Naftali Tishby", "Fernando C. Pereira", "William Bialek"],
        "year": 2000,
        "venue_or_status": "arXiv:physics/0004057",
        "url": "https://arxiv.org/abs/physics/0004057",
        "lineage": ["information_bottleneck", "rate_distortion", "representation_learning"],
        "local_paradigms": ["atw_codec", "ib_lagrangian", "meta_lagrangian"],
        "local_variables": [
            "ib_beta",
            "mutual_information_proxy",
            "task_relevant_rate_delta",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "IB objectives are rank priors until the learned representation and entropy model are charged in archive bytes.",
        "hardening_blockers": [
            "mutual_information_proxy_calibration",
            "task_relevance_component_mapping",
            "exact_cuda_auth_eval",
        ],
    },
    "tishby_zaslavsky_2015": {
        "title": "Deep Learning and the Information Bottleneck Principle",
        "authors": ["Naftali Tishby", "Noga Zaslavsky"],
        "year": 2015,
        "venue_or_status": "IEEE Information Theory Workshop 2015 / arXiv:1503.02406",
        "url": "https://arxiv.org/abs/1503.02406",
        "lineage": ["information_bottleneck", "deep_learning", "representation_compression"],
        "local_paradigms": ["ib_lagrangian", "mdl", "time_traveler_l5"],
        "local_variables": [
            "ib_phase_transition_proxy",
            "representation_compression_term",
            "task_relevant_rate_delta",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Deep-IB arguments are objective priors; contest authority requires byte-closed representation payloads and exact component deltas.",
        "hardening_blockers": [
            "ib_proxy_to_contest_metric_calibration",
            "representation_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "wyner_ziv_1976": {
        "title": "The rate-distortion function for source coding with side information at the decoder",
        "authors": ["Aaron D. Wyner", "Jacob Ziv"],
        "year": 1976,
        "venue_or_status": "IEEE Transactions on Information Theory 22(1), 1-10",
        "url": "https://doi.org/10.1109/TIT.1976.1055508",
        "lineage": ["distributed_source_coding", "decoder_side_information", "rate_distortion"],
        "local_paradigms": ["wyner_ziv", "cooperative_receiver", "frame0_side_information"],
        "local_variables": [
            "decoder_side_information",
            "conditional_rate_delta_bits",
            "cooperative_receiver_residual",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Decoder side information must be derived from fixed contest inputs or carried as charged archive payload.",
        "hardening_blockers": [
            "side_information_derivation_proof",
            "paired_cpu_cuda_empirical_anchor",
            "exact_cuda_auth_eval",
        ],
    },
    "slepian_wolf_1973": {
        "title": "Noiseless coding of correlated information sources",
        "authors": ["David Slepian", "Jack K. Wolf"],
        "year": 1973,
        "venue_or_status": "IEEE Transactions on Information Theory 19(4), 471-480",
        "url": "https://www.itsoc.org/publications/papers/noiseless-coding-of-correlated-information-sources",
        "lineage": ["distributed_source_coding", "correlated_sources", "conditional_entropy"],
        "local_paradigms": ["wyner_ziv", "cooperative_receiver", "entropy_rate"],
        "local_variables": [
            "conditional_entropy_floor_bits",
            "correlated_source_partition",
            "syndrome_or_bin_index",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "Binning, syndrome, or correlation metadata must be charged unless deterministically derived from fixed contest runtime and inputs.",
        "hardening_blockers": [
            "correlation_model_custody",
            "bin_index_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "shannon_rate_distortion_1959": {
        "title": "Coding Theorems for a Discrete Source With a Fidelity Criterion",
        "authors": ["Claude E. Shannon"],
        "year": 1959,
        "venue_or_status": "IRE National Convention Record 7(4), 142-163",
        "url": "https://ieeexplore.ieee.org/document/5311476",
        "lineage": ["rate_distortion", "source_coding", "fidelity_criterion"],
        "local_paradigms": ["meta_lagrangian", "entropy_rate", "pareto_kkt"],
        "local_variables": [
            "rate_distortion_function",
            "fidelity_constraint",
            "description_length_delta_bytes",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Rate-distortion lower bounds are theory priors; contest movement requires byte-closed archives and exact eval.",
        "hardening_blockers": [
            "component_distortion_mapping",
            "archive_byte_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "rissanen_mdl_1978": {
        "title": "Modeling by Shortest Data Description",
        "authors": ["Jorma Rissanen"],
        "year": 1978,
        "venue_or_status": "Automatica 14(5), 465-471",
        "url": "https://research.ibm.com/publications/modeling-by-shortest-data-description",
        "lineage": ["minimum_description_length", "model_selection", "statistical_inference"],
        "local_paradigms": ["mdl", "time_traveler_l5", "ibps"],
        "local_variables": [
            "model_description_length_bits",
            "residual_description_length_bits",
            "aggregate_mdl_estimate",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "MDL estimates are planning and ablation evidence until the chosen model plus residual stream are byte-closed and exactly evaluated.",
        "hardening_blockers": [
            "mdl_estimate_to_archive_bytes_reconciliation",
            "residual_payload_custody",
            "exact_cuda_auth_eval",
        ],
    },
    "mackay_itila_2003": {
        "title": "Information Theory, Inference, and Learning Algorithms",
        "authors": ["David J. C. MacKay"],
        "year": 2003,
        "venue_or_status": "Cambridge University Press",
        "url": "https://www.inference.org.uk/itila/book.html",
        "lineage": ["information_theory", "inference", "coding"],
        "local_paradigms": ["entropy_rate", "mdl", "time_traveler_l5"],
        "local_variables": [
            "bits_back_intuition",
            "arithmetic_code_length_bits",
            "description_length_delta_bytes",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Information-theoretic code-length arguments must reconcile with emitted archive bytes, deterministic decoder state, and exact scorer deltas.",
        "hardening_blockers": [
            "entropy_code_payload_accounting",
            "deterministic_decoder_contract",
            "exact_cuda_auth_eval",
        ],
    },
    "pnvc_2025": {
        "title": "PNVC: Towards Practical INR-based Video Compression",
        "authors": ["Ge Gao", "Ho Man Kwan", "Fan Zhang", "David Bull"],
        "year": 2025,
        "venue_or_status": "AAAI 2025",
        "url": "https://doi.org/10.1609/aaai.v39i3.32315",
        "lineage": [
            "inr_video_compression",
            "practical_neural_codec",
            "entropy_modeling",
            "decode_complexity",
        ],
        "local_paradigms": [
            "time_traveler_l5",
            "nerv_family",
            "stack_of_stacks",
            "entropy",
        ],
        "local_variables": [
            "structural_reparameterization",
            "hierarchical_quality_control",
            "modulation_entropy_payload",
            "scale_aware_positional_embedding",
            "decode_wallclock_seconds",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "PNVC-style entropy tables, modulation signals, quality layers, and reparameterized weights are planning priors until all bytes are emitted inside the contest archive and consumed by scorer-free inflate.",
        "hardening_blockers": [
            "byte_closed_entropy_payload",
            "t4_decode_timing_smoke",
            "same_axis_pr95_pr101_baseline",
            "paired_cpu_cuda_exact_eval",
        ],
    },
    "dcvc_rt_2025": {
        "title": "Towards Practical Real-Time Neural Video Compression",
        "authors": [
            "Zhaoyang Jia",
            "Bin Li",
            "Jiahao Li",
            "Wenxuan Xie",
            "Linfeng Qi",
            "Houqiang Li",
            "Yan Lu",
        ],
        "year": 2025,
        "venue_or_status": "CVPR 2025 / arXiv:2502.20762",
        "url": "https://arxiv.org/abs/2502.20762",
        "lineage": [
            "neural_video_compression",
            "real_time_codec",
            "implicit_temporal_modeling",
            "operational_cost_reduction",
        ],
        "local_paradigms": [
            "time_traveler_l5",
            "predictive_receiver",
            "runtime_efficiency",
        ],
        "local_variables": [
            "implicit_temporal_model",
            "single_low_resolution_latent",
            "module_bank_rate_control",
            "cross_device_integerized_decode",
            "decode_wallclock_seconds",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "DCVC-RT-style temporal state, module-bank choices, and integerized model parameters are planning priors until they are byte-closed in archive.zip and decoded scorer-free inside the contest runtime budget.",
        "hardening_blockers": [
            "runtime_budget_t4_timing_smoke",
            "integerized_decode_cross_device_parity",
            "paired_cpu_cuda_exact_eval",
        ],
    },
    "unified_intra_inter_nvc_2025": {
        "title": "Real-Time Neural Video Compression with Unified Intra and Inter Coding",
        "authors": [
            "Hui Xiang",
            "Yifan Bian",
            "Li Li",
            "Jingran Wu",
            "Xianguo Zhang",
            "Dong Liu",
        ],
        "year": 2025,
        "venue_or_status": "arXiv:2510.14431",
        "url": "https://arxiv.org/abs/2510.14431",
        "lineage": [
            "neural_video_compression",
            "adaptive_intra_inter_coding",
            "bidirectional_temporal_context",
        ],
        "local_paradigms": [
            "time_traveler_l5",
            "predictive_receiver",
            "stack_of_stacks",
        ],
        "local_variables": [
            "adaptive_intra_inter_selector",
            "disocclusion_refresh_budget",
            "simultaneous_two_frame_context",
            "interframe_error_reset",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Adaptive intra/inter selectors, refresh maps, and bidirectional context state are charged bytes unless deterministically derived from already decoded frames and fixed runtime code.",
        "hardening_blockers": [
            "selector_payload_custody",
            "bidirectional_runtime_order_proof",
            "paired_cpu_cuda_exact_eval",
        ],
    },
    "glvc_2025": {
        "title": "Generative Latent Video Compression",
        "authors": [
            "Zongyu Guo",
            "Zhaoyang Jia",
            "Jiahao Li",
            "Xiaoyi Zhang",
            "Bin Li",
            "Yan Lu",
        ],
        "year": 2025,
        "venue_or_status": "arXiv:2510.09987",
        "url": "https://arxiv.org/abs/2510.09987",
        "lineage": [
            "generative_video_compression",
            "latent_tokenizer",
            "recurrent_memory",
            "perceptual_codec",
        ],
        "local_paradigms": [
            "world_model",
            "time_traveler_l5",
            "generative_prior",
        ],
        "local_variables": [
            "continuous_tokenizer_payload",
            "latent_domain_codec_state",
            "recurrent_memory_state",
            "perceptual_metric_gap",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Tokenizer weights, latent-domain codec state, and recurrent memory are charged unless fixed in contest runtime; perceptual wins are proxy-only until mapped to SegNet/PoseNet deltas.",
        "hardening_blockers": [
            "contest_metric_mapping_required",
            "tokenizer_weight_custody",
            "paired_cpu_cuda_exact_eval",
        ],
    },
    "gnvc_vd_2025": {
        "title": "Generative Neural Video Compression via Video Diffusion Prior",
        "authors": ["Qi Mao", "Hao Cheng", "Tinghan Yang", "Libiao Jin", "Siwei Ma"],
        "year": 2025,
        "venue_or_status": "arXiv:2512.05016",
        "url": "https://arxiv.org/abs/2512.05016",
        "lineage": [
            "generative_video_compression",
            "video_diffusion_prior",
            "sequence_level_latent_refinement",
        ],
        "local_paradigms": [
            "world_model",
            "time_traveler_l5",
            "diffusion_prior",
        ],
        "local_variables": [
            "flow_matching_refinement_state",
            "compression_aware_conditioning",
            "sequence_latent_consistency",
            "diffusion_decode_budget",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Diffusion-prior weights, conditioning adapters, and sequence-level refinement state are planning priors until byte-closed and proven within the contest inflate budget.",
        "hardening_blockers": [
            "diffusion_runtime_budget_probe",
            "metric_and_temporal_consistency_mapping",
            "paired_cpu_cuda_exact_eval",
        ],
    },
    "snerv_scalable_2024": {
        "title": "SNeRV: Scalable Neural Representations for Video Coding",
        "authors": ["SNeRV scalable authors"],
        "year": 2024,
        "venue_or_status": "OpenReview",
        "url": "https://openreview.net/forum?id=ZqN4bnXSSY",
        "lineage": ["neural_video_representation", "scalable_coding", "multi_resolution"],
        "local_paradigms": ["hnerv", "nerv_family", "stack_of_stacks"],
        "local_variables": [
            "multi_resolution_layer_stack",
            "quality_scalable_payload",
            "decode_cost_per_layer",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Scalable layers are charged unless omitted; each layer must have runtime-consumption proof and component delta.",
        "hardening_blockers": [
            "snerv_name_collision_disambiguated",
            "layer_consumption_proof",
            "exact_cuda_auth_eval",
        ],
    },
    "snerv_spectra_2025": {
        "title": "SNeRV: Spectra-preserving Neural Representation for Video",
        "authors": ["SNeRV spectra-preserving authors"],
        "year": 2025,
        "venue_or_status": "arXiv:2501.01681",
        "url": "https://arxiv.org/abs/2501.01681",
        "lineage": ["neural_video_representation", "spectral_preservation", "frequency_domain"],
        "local_paradigms": ["hnerv", "wavelet", "frequency_residual"],
        "local_variables": [
            "spectral_loss_weight",
            "frequency_residual_delta",
            "high_frequency_payload_bytes",
        ],
        "contest_terms": ["seg_dist", "pose_dist", "archive_bytes"],
        "charged_byte_contract": "Spectral residual payloads and frequency-domain metadata must be charged or derived deterministically.",
        "hardening_blockers": [
            "snerv_name_collision_disambiguated",
            "spectral_metric_to_contest_mapping",
            "exact_cuda_auth_eval",
        ],
    },
    "hnerv_2023": {
        "title": "HNeRV: A Hybrid Neural Representation for Videos",
        "authors": ["Hao Chen", "Matthew Gwilliam", "Ser-Nam Lim", "Abhinav Shrivastava"],
        "year": 2023,
        "venue_or_status": "CVPR 2023",
        "url": "https://openaccess.thecvf.com/content/CVPR2023/html/Chen_HNeRV_A_Hybrid_Neural_Representation_for_Videos_CVPR_2023_paper.html",
        "lineage": ["neural_video_representation", "hybrid_inr", "content_adaptive_embedding"],
        "local_paradigms": ["hnerv", "nerv_family", "time_traveler_l5"],
        "local_variables": [
            "content_adaptive_embedding",
            "decoder_weight_payload",
            "temporal_representation_capacity",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "HNeRV embeddings and decoder weights are charged payload unless fixed by contest runtime; paper compression ratios are not contest score evidence.",
        "hardening_blockers": [
            "source_runtime_replay_or_parity",
            "archive_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "metanerv_2025": {
        "title": "MetaNeRV: Meta Neural Representations for Videos with Spatial-Temporal Guidance",
        "authors": ["MetaNeRV authors"],
        "year": 2025,
        "venue_or_status": "arXiv:2501.02427",
        "url": "https://arxiv.org/abs/2501.02427",
        "lineage": ["neural_video_representation", "meta_learning", "spatiotemporal_guidance"],
        "local_paradigms": ["hnerv", "nerv_family", "time_traveler_l5"],
        "local_variables": [
            "meta_initialization_payload",
            "spatiotemporal_guidance_signal",
            "per_video_adaptation_steps",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Meta initialization and adaptation state are charged unless fixed in contest runtime; guidance signals require archive custody.",
        "hardening_blockers": [
            "meta_init_license_and_custody",
            "adaptation_runtime_budget",
            "exact_cuda_auth_eval",
        ],
    },
    "c3_neural_compression_2024": {
        "title": "C3: High-Performance and Low-Complexity Neural Compression from a Single Image or Video",
        "authors": ["Hyunjik Kim", "Matthias Bauer", "Lucas Theis", "Jonathan Richard Schwarz", "Emilien Dupont"],
        "year": 2024,
        "venue_or_status": "CVPR 2024",
        "url": "https://openaccess.thecvf.com/content/CVPR2024/html/Kim_C3_High-Performance_and_Low-Complexity_Neural_Compression_from_a_Single_Image_CVPR_2024_paper.html",
        "lineage": ["neural_compression", "low_complexity_decode", "overfitted_codec"],
        "local_paradigms": ["cool_chic", "c3", "self_compressing_nn"],
        "local_variables": [
            "decoder_macs_per_pixel",
            "overfitted_latent_payload",
            "rate_distortion_delta",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Overfitted latents, model parameters, and any entropy model must be charged in archive.zip and decoded inside budget.",
        "hardening_blockers": [
            "decode_complexity_anchor",
            "byte_closed_archive_manifest",
            "exact_cuda_auth_eval",
        ],
    },
    "cool_chic_2023": {
        "title": "COOL-CHIC: Coordinate-based Low Complexity Hierarchical Image Codec",
        "authors": ["COOL-CHIC authors"],
        "year": 2023,
        "venue_or_status": "ICCV 2023",
        "url": "https://openaccess.thecvf.com/content/ICCV2023/papers/Ladune_COOL-CHIC_Coordinate-based_Low_Complexity_Hierarchical_Image_Codec_ICCV_2023_paper.pdf",
        "lineage": ["coordinate_codec", "low_complexity_decode", "hierarchical_latents"],
        "local_paradigms": ["cool_chic", "c3", "coordinate_mlp_residual"],
        "local_variables": [
            "coordinate_grid_payload",
            "hierarchical_latent_entropy",
            "decoder_complexity_budget",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Coordinate networks and hierarchical latents are charged archive payload unless fixed by contest runtime.",
        "hardening_blockers": [
            "hierarchical_latent_custody",
            "decode_complexity_anchor",
            "exact_cuda_auth_eval",
        ],
    },
    "cool_chic_5_2026": {
        "title": "Cool-chic 5.0: Faster Encoding and Inter-Feature Entropy Modeling for Overfitted Image Compression",
        "authors": [
            "Theo Ladune",
            "Pierrick Philippe",
            "Pierre Jaffuer",
            "Theophile Blard",
            "Sylvain Kervadec",
            "Felix Henry",
            "Gordon Clare",
        ],
        "year": 2026,
        "venue_or_status": "arXiv:2605.02726",
        "url": "https://arxiv.org/abs/2605.02726",
        "lineage": ["coordinate_codec", "overfitted_codec", "inter_feature_entropy_model"],
        "local_paradigms": ["cool_chic", "c3", "production_runtime"],
        "local_variables": [
            "inter_feature_entropy_context",
            "encoder_iteration_budget",
            "decoder_complexity_budget",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Inter-feature context models, decoder weights, and latent grids must be charged in the contest archive before they can influence score claims.",
        "hardening_blockers": [
            "cool_chic_versioned_runtime_contract",
            "inter_feature_context_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "vqvae_2017": {
        "title": "Neural Discrete Representation Learning",
        "authors": ["Aaron van den Oord", "Oriol Vinyals", "Koray Kavukcuoglu"],
        "year": 2017,
        "venue_or_status": "NeurIPS 2017 / arXiv:1711.00937",
        "url": "https://arxiv.org/abs/1711.00937",
        "lineage": ["discrete_latent_models", "vector_quantization", "autoregressive_prior"],
        "local_paradigms": ["vqvae", "discrete_codebook", "renderer_replacement"],
        "local_variables": [
            "codebook_payload_bytes",
            "discrete_latent_indices",
            "autoregressive_prior_bits",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Codebooks, latent indices, and priors are charged payload unless fixed by contest runtime and must prove inflate consumption.",
        "hardening_blockers": [
            "codebook_custody_required",
            "latent_index_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "siren_2020": {
        "title": "Implicit Neural Representations with Periodic Activation Functions",
        "authors": [
            "Vincent Sitzmann",
            "Julien N. P. Martel",
            "Alexander W. Bergman",
            "David B. Lindell",
            "Gordon Wetzstein",
        ],
        "year": 2020,
        "venue_or_status": "NeurIPS 2020 / arXiv:2006.09661",
        "url": "https://arxiv.org/abs/2006.09661",
        "lineage": ["implicit_neural_representation", "periodic_activation", "coordinate_mlp"],
        "local_paradigms": ["siren", "coordinate_mlp_residual", "inr"],
        "local_variables": [
            "coordinate_mlp_weight_payload",
            "spectral_bias_control",
            "derivative_sensitive_residual",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "SIREN weights and any coordinate-conditioning payload must be inside the archive and decoder runtime budget.",
        "hardening_blockers": [
            "coordinate_decoder_runtime_budget",
            "weight_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "fourier_features_2020": {
        "title": "Fourier Features Let Networks Learn High Frequency Functions in Low Dimensional Domains",
        "authors": [
            "Matthew Tancik",
            "Pratul P. Srinivasan",
            "Ben Mildenhall",
            "Sara Fridovich-Keil",
            "Nithin Raghavan",
            "Utkarsh Singhal",
            "Ravi Ramamoorthi",
            "Jonathan T. Barron",
            "Ren Ng",
        ],
        "year": 2020,
        "venue_or_status": "NeurIPS 2020 / arXiv:2006.10739",
        "url": "https://arxiv.org/abs/2006.10739",
        "lineage": ["implicit_neural_representation", "fourier_features", "spectral_bias"],
        "local_paradigms": ["siren", "coordinate_mlp_residual", "frequency_residual"],
        "local_variables": [
            "fourier_feature_matrix",
            "frequency_bandwidth",
            "high_frequency_payload_bytes",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Fourier feature matrices and frequency selectors are charged unless they are fixed deterministic runtime constants.",
        "hardening_blockers": [
            "frequency_selector_custody",
            "spectral_metric_to_contest_mapping",
            "exact_cuda_auth_eval",
        ],
    },
    "finer_2024": {
        "title": "FINER: Flexible Spectral-bias Tuning in Implicit NEural Representation by Variable-periodic Activation Functions",
        "authors": [
            "Zhen Liu",
            "Hao Zhu",
            "Qi Zhang",
            "Jingde Fu",
            "Weibing Deng",
            "Zhan Ma",
            "Yanwen Guo",
            "Xun Cao",
        ],
        "year": 2024,
        "venue_or_status": "CVPR 2024 / arXiv:2312.02434",
        "url": "https://arxiv.org/abs/2312.02434",
        "lineage": ["implicit_neural_representation", "variable_periodic_activation", "spectral_bias"],
        "local_paradigms": ["siren", "coordinate_mlp_residual", "frequency_residual"],
        "local_variables": [
            "activation_period_payload",
            "frequency_support_set",
            "coordinate_mlp_weight_payload",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Activation periods, biases, and decoder weights are charged payload unless fixed as deterministic contest runtime code.",
        "hardening_blockers": [
            "activation_parameter_payload_accounting",
            "frequency_component_ablation",
            "exact_cuda_auth_eval",
        ],
    },
    "bacon_2022": {
        "title": "BACON: Band-limited Coordinate Networks for Multiscale Scene Representation",
        "authors": ["David B. Lindell", "Dave Van Veen", "Jeong Joon Park", "Gordon Wetzstein"],
        "year": 2022,
        "venue_or_status": "CVPR 2022 / arXiv:2112.04645",
        "url": "https://arxiv.org/abs/2112.04645",
        "lineage": ["implicit_neural_representation", "band_limited_coordinate_networks", "multiscale"],
        "local_paradigms": ["siren", "coordinate_mlp_residual", "multiscale_renderer"],
        "local_variables": [
            "bandlimit_schedule",
            "multiscale_decoder_layers",
            "coordinate_mlp_weight_payload",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Multiscale coordinate-network weights and bandlimit choices are charged archive payload unless fixed by runtime.",
        "hardening_blockers": [
            "multiscale_payload_manifest",
            "decode_budget_per_scale",
            "exact_cuda_auth_eval",
        ],
    },
    "wire_2023": {
        "title": "WIRE: Wavelet Implicit Neural Representations",
        "authors": [
            "Vishwanath Saragadam",
            "Daniel LeJeune",
            "Jasper Tan",
            "Guha Balakrishnan",
            "Ashok Veeraraghavan",
            "Richard G. Baraniuk",
        ],
        "year": 2023,
        "venue_or_status": "CVPR 2023 / arXiv:2301.05187",
        "url": "https://arxiv.org/abs/2301.05187",
        "lineage": ["implicit_neural_representation", "wavelet_activation", "space_frequency"],
        "local_paradigms": ["wavelet", "siren", "coordinate_mlp_residual"],
        "local_variables": [
            "wavelet_activation_parameters",
            "space_frequency_payload",
            "coordinate_mlp_weight_payload",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Wavelet activation parameters and decoder weights are charged unless they are fixed deterministic runtime constants.",
        "hardening_blockers": [
            "wavelet_activation_payload_accounting",
            "runtime_consumption_proof",
            "exact_cuda_auth_eval",
        ],
    },
    "raft_2020": {
        "title": "RAFT: Recurrent All-Pairs Field Transforms for Optical Flow",
        "authors": ["Zachary Teed", "Jia Deng"],
        "year": 2020,
        "venue_or_status": "ECCV 2020 / arXiv:2003.12039",
        "url": "https://arxiv.org/abs/2003.12039",
        "lineage": ["optical_flow", "all_pairs_correlation", "recurrent_refinement"],
        "local_paradigms": ["raft", "ego_motion", "predictive_receiver"],
        "local_variables": [
            "flow_field_payload",
            "ego_motion_prior",
            "temporal_residual_score_delta",
        ],
        "contest_terms": ["pose_dist", "seg_dist", "archive_bytes"],
        "charged_byte_contract": "Flow fields, correlation summaries, or RAFT-derived selectors must be charged or deterministically recomputed inside the runtime budget.",
        "hardening_blockers": [
            "flow_payload_custody",
            "pose_seg_component_gate",
            "exact_cuda_auth_eval",
        ],
    },
    "mallat_mra_1989": {
        "title": "A Theory for Multiresolution Signal Decomposition: The Wavelet Representation",
        "authors": ["Stephane G. Mallat"],
        "year": 1989,
        "venue_or_status": "IEEE TPAMI 11(7), 674-693",
        "url": "https://doi.org/10.1109/34.192463",
        "lineage": ["wavelet", "multiresolution_analysis", "pyramid_transform"],
        "local_paradigms": ["wavelet", "frequency_residual", "multiscale_renderer"],
        "local_variables": [
            "wavelet_basis_id",
            "multiresolution_coefficients",
            "high_frequency_payload_bytes",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Wavelet basis choices and coefficients are charged unless fixed by deterministic runtime and reconstructed from charged payload.",
        "hardening_blockers": [
            "wavelet_basis_runtime_contract",
            "coefficient_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "ans_duda_2009": {
        "title": "Asymmetric numeral systems",
        "authors": ["Jarek Duda"],
        "year": 2009,
        "venue_or_status": "arXiv:0902.0271",
        "url": "https://arxiv.org/abs/0902.0271",
        "lineage": ["ans", "entropy_coding", "numeral_systems"],
        "local_paradigms": ["entropy_rate", "aq_huffman", "ans_range_coding"],
        "local_variables": [
            "symbol_cdf_payload",
            "entropy_floor_bits",
            "coded_stream_bytes",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "ANS tables, probability models, and streams are charged payload unless fixed deterministic code derives them from the archive.",
        "hardening_blockers": [
            "coder_table_payload_accounting",
            "bit_exact_roundtrip",
            "exact_cuda_auth_eval",
        ],
    },
    "rans_duda_2013": {
        "title": "Asymmetric numeral systems: entropy coding combining speed of Huffman coding with compression rate of arithmetic coding",
        "authors": ["Jarek Duda"],
        "year": 2013,
        "venue_or_status": "arXiv:1311.2540",
        "url": "https://arxiv.org/abs/1311.2540",
        "lineage": ["ans", "rans", "entropy_coding"],
        "local_paradigms": ["entropy_rate", "aq_huffman", "ans_range_coding"],
        "local_variables": [
            "rans_state",
            "symbol_cdf_payload",
            "coded_stream_bytes",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "rANS state, tables, and streams must be byte-closed and deterministic across CPU/CUDA scoring environments.",
        "hardening_blockers": [
            "rans_cross_platform_roundtrip",
            "coder_table_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "minnen_joint_priors_2018": {
        "title": "Joint Autoregressive and Hierarchical Priors for Learned Image Compression",
        "authors": ["David Minnen", "Johannes Balle", "George Toderici"],
        "year": 2018,
        "venue_or_status": "NeurIPS 2018 / arXiv:1809.02736",
        "url": "https://arxiv.org/abs/1809.02736",
        "lineage": ["learned_compression", "autoregressive_prior", "hyperprior_entropy_model"],
        "local_paradigms": ["entropy_rate", "joint_codec_stack", "balle_hyperprior"],
        "local_variables": [
            "autoregressive_context_payload",
            "hyperprior_sideinfo_bytes",
            "conditional_entropy_floor_bits",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Autoregressive context, hyperprior side information, and decoder weights must be charged or fixed contest runtime code.",
        "hardening_blockers": [
            "context_model_runtime_budget",
            "hyperprior_payload_accounting",
            "exact_cuda_auth_eval",
        ],
    },
    "tensorflow_compression": {
        "title": "TensorFlow Compression learned data-compression library",
        "authors": ["TensorFlow Compression contributors"],
        "year": 2019,
        "venue_or_status": "OSS reference implementation and documentation",
        "url": "https://tensorflow.github.io/compression/",
        "lineage": ["learned_compression_oss", "entropy_models", "range_coding"],
        "local_paradigms": ["entropy_rate", "joint_codec_stack", "balle_hyperprior"],
        "local_variables": [
            "entropy_model_tables",
            "range_coded_stream",
            "codec_runtime_dependency",
        ],
        "contest_terms": ["archive_bytes"],
        "charged_byte_contract": "TensorFlow Compression can guide compress-time tooling, but contest runtime dependencies and entropy tables must be vendored, deterministic, and charged.",
        "hardening_blockers": [
            "dependency_policy_review",
            "range_coder_runtime_contract",
            "exact_cuda_auth_eval",
        ],
    },
    "dcvc_rt_2025": {
        "title": "Towards Practical Real-Time Neural Video Compression",
        "authors": ["Zhaoyang Jia", "Bin Li", "Jiahao Li", "Wenxuan Xie", "Linfeng Qi", "Houqiang Li", "Yan Lu"],
        "year": 2025,
        "venue_or_status": "arXiv:2502.20762",
        "url": "https://arxiv.org/abs/2502.20762",
        "lineage": ["neural_video_compression", "real_time_decode", "integerization"],
        "local_paradigms": ["learned_video_compression", "decode_complexity", "production_runtime"],
        "local_variables": [
            "decode_fps_anchor",
            "integerized_model_delta",
            "latent_resolution_policy",
        ],
        "contest_terms": ["archive_bytes", "seg_dist", "pose_dist"],
        "charged_byte_contract": "Runtime speed and integerization are production priors; any model bank, latent, or rate-control metadata consumed by inflate is charged.",
        "hardening_blockers": [
            "runtime_dependency_closure",
            "t4_decode_budget_anchor",
            "exact_cuda_auth_eval",
        ],
    },
}

DEFAULT_RESEARCH_BASIS_IDS = [
    "fridrich_stc_2011",
    "fridrich_pq_wetpaper_2004",
    "balle_e2e_2017",
    "balle_hyperprior_2018",
]

FAMILY_RESEARCH_BASIS_IDS: dict[str, list[str]] = {
    "alpha": ["fridrich_stc_2011", "fridrich_pq_wetpaper_2004", "yousfi_onehot_jpeg_2020"],
    "aq_huffman": ["constriction_ans", "ans_duda_2009", "rans_duda_2013", "balle_hyperprior_2018"],
    "bayesian_experimental_design": ["dworetzky_fridrich_detector_batch_2025", "compression_as_adaptation_2026"],
    "categorical": ["rdc_universal_2025", "rdc_bernoulli_2026", "yousfi_onehot_jpeg_2020", "yousfi_cost_polarization_2023"],
    "cool_chic": ["cool_chic_5_2026", "cool_chic_2023", "c3_neural_compression_2024"],
    "c3": ["c3_neural_compression_2024", "cool_chic_5_2026", "cool_chic_2023"],
    "coordinate_mlp_residual": ["siren_2020", "fourier_features_2020", "finer_2024", "bacon_2022", "wire_2023"],
    "entropy": ["flavc_2025", "minnen_joint_priors_2018", "balle_hyperprior_2018", "compressai", "tensorflow_compression", "constriction_ans", "ans_duda_2009", "rans_duda_2013", "yousfi_onehot_jpeg_2020"],
    "foveation": ["telescope_2026", "foveated_diffusion_2026", "foveated_telepresence_2025", "lyra2_2026"],
    "gamma": ["balle_e2e_2017", "balle_hyperprior_2018", "minnen_joint_priors_2018", "compressai"],
    "hnerv": ["hnerv_2023", "msnerv_2025", "nerv_2021", "hinerv_2023", "balle_hyperprior_2018", "minnen_joint_priors_2018", "fridrich_stc_2011"],
    "ib_lagrangian": ["tishby_information_bottleneck_1999", "tishby_zaslavsky_2015", "balle_hyperprior_2018"],
    "inr": ["siren_2020", "fourier_features_2020", "wire_2023", "finer_2024", "bacon_2022"],
    "lapose": ["lapose_2026", "geometric_visual_servo_ot_2026"],
    "mask_payload": ["nerv_2021", "hinerv_2023", "mae_2021", "fridrich_pq_wetpaper_2004"],
    "meta_lagrangian": ["dworetzky_fridrich_detector_batch_2025", "geometric_visual_servo_ot_2026", "fridrich_stc_2011", "hawq_v3_2020", "awq_2024"],
    "mdl": ["rissanen_mdl_1978", "mackay_itila_2003", "balle_overfitted_wasserstein_2025", "compression_as_adaptation_2026"],
    "optimal_transport": ["geometric_visual_servo_ot_2026", "balle_overfitted_wasserstein_2025"],
    "pose": ["lapose_2026", "geometric_visual_servo_ot_2026", "foveated_telepresence_2025"],
    "predictive_receiver": ["rao_ballard_1999", "friston_free_energy_2010", "dreamerv3_2023", "ha_schmidhuber_world_models_2018", "raft_2020"],
    "raft": ["raft_2020"],
    "self_augmentation": ["mae_2021", "lyra2_2026"],
    "semantic_labels": ["rdc_universal_2025", "yousfi_onehot_jpeg_2020"],
    "self_compressing_nn": ["compression_as_adaptation_2026", "balle_overfitted_wasserstein_2025"],
    "sensitivity": ["kaziakhmedov_fridrich_lies_2025", "awq_2024", "hawq_v3_2020"],
    "siren": ["siren_2020", "fourier_features_2020", "finer_2024", "bacon_2022", "wire_2023"],
    "telescopic_foveation": ["telescope_2026", "foveated_diffusion_2026", "foveated_telepresence_2025"],
    "time_traveler_l5": [
        "rao_ballard_1999",
        "friston_free_energy_2010",
        "dreamerv3_2023",
        "ha_schmidhuber_world_models_2018",
        "rissanen_mdl_1978",
        "mackay_itila_2003",
        "hnerv_2023",
    ],
    "time_traveler_l5_v2": [
        "rao_ballard_1999",
        "friston_free_energy_2010",
        "dreamerv3_2023",
        "ha_schmidhuber_world_models_2018",
        "pnvc_2025",
        "dcvc_rt_2025",
        "unified_intra_inter_nvc_2025",
        "glvc_2025",
        "gnvc_vd_2025",
        "snerv_spectra_2025",
        "metanerv_2025",
        "c3_neural_compression_2024",
        "atick_redlich_1990",
        "wyner_ziv_1976",
        "lu_dvc_2019",
        "rissanen_mdl_1978",
        "mackay_itila_2003",
        "tishby_information_bottleneck_1999",
        "tishby_zaslavsky_2015",
        "balle_hyperprior_2018",
        "hnerv_2023",
    ],
    "vqvae": ["vqvae_2017", "balle_hyperprior_2018", "minnen_joint_priors_2018"],
    "wavelet": ["mallat_mra_1989", "wire_2023", "fridrich_stc_2011", "fridrich_pq_wetpaper_2004"],
    "world_model": ["glvc_2025", "gnvc_vd_2025", "ha_schmidhuber_world_models_2018", "dreamerv3_2023", "friston_free_energy_2010", "rao_ballard_1999"],
}


def canonical_research_basis_id(raw_id: str) -> str:
    """Return the canonical source id for a persisted or legacy alias."""

    basis_id = str(raw_id or "").strip()
    if not basis_id:
        raise ResearchBasisError("research basis id must be nonempty")
    return RESEARCH_SOURCE_ALIASES.get(basis_id, RESEARCH_SOURCE_ALIASES.get(basis_id.lower(), basis_id))


def research_basis_ids_for_family(*family_values: str) -> list[str]:
    """Return deterministic research-basis ids for one or more family labels."""

    out: list[str] = []
    for family in family_values:
        key = str(family or "").lower()
        for basis_id in FAMILY_RESEARCH_BASIS_IDS.get(key, []):
            canonical_id = canonical_research_basis_id(basis_id)
            if canonical_id not in out:
                out.append(canonical_id)
    if not out:
        out.extend(DEFAULT_RESEARCH_BASIS_IDS)
    return out


def research_basis_manifest(ids: Iterable[str] | None = None) -> dict[str, Any]:
    """Return a deterministic, score-neutral manifest for research sources."""

    resolved_ids = list(ids or DEFAULT_RESEARCH_BASIS_IDS)
    if not resolved_ids:
        raise ResearchBasisError("research basis ids must be nonempty")
    seen: set[str] = set()
    sources = []
    for raw_id in resolved_ids:
        basis_id = canonical_research_basis_id(str(raw_id or ""))
        if basis_id in seen:
            continue
        if basis_id not in RESEARCH_SOURCES:
            raise ResearchBasisError(f"unknown research basis id: {basis_id}")
        seen.add(basis_id)
        source = _validated_source(basis_id, RESEARCH_SOURCES[basis_id])
        source["basis_id"] = basis_id
        sources.append(source)
    sources.sort(key=lambda source: (int(source["year"]), str(source["basis_id"])))
    return {
        "schema_version": SCHEMA_VERSION,
        "tool": TOOL_NAME,
        "planning_only": True,
        "score_claim": False,
        "promotion_eligible": False,
        "source_count": len(sources),
        "sources": sources,
        "contract": (
            "Research priors may shape planning, features, and atom ranking, "
            "but they cannot promote, rank, or claim contest score without "
            "byte-closed exact CUDA archive evidence."
        ),
        "global_hardening_blockers": [
            "paper_claim_not_score_evidence",
            "charged_byte_contract_required",
            "deterministic_reproducibility_required",
            "exact_cuda_auth_eval_required",
        ],
    }


def _validated_source(basis_id: str, source: Mapping[str, Any]) -> dict[str, Any]:
    missing = [field for field in REQUIRED_SOURCE_FIELDS if field not in source]
    if missing:
        raise ResearchBasisError(
            f"{basis_id}: research source missing required fields: {', '.join(missing)}"
        )
    out = dict(source)
    if not str(out["title"]):
        raise ResearchBasisError(f"{basis_id}: title must be nonempty")
    if not isinstance(out["authors"], list) or not out["authors"]:
        raise ResearchBasisError(f"{basis_id}: authors must be a nonempty list")
    year = out["year"]
    if isinstance(year, bool) or not isinstance(year, int) or year < 1900:
        raise ResearchBasisError(f"{basis_id}: year must be a valid integer")
    if not str(out["url"]).startswith("https://"):
        raise ResearchBasisError(f"{basis_id}: url must be https")
    for field in ("lineage", "local_paradigms", "local_variables", "contest_terms", "hardening_blockers"):
        if not isinstance(out[field], list) or not out[field]:
            raise ResearchBasisError(f"{basis_id}: {field} must be a nonempty list")
    if not str(out["charged_byte_contract"]):
        raise ResearchBasisError(f"{basis_id}: charged_byte_contract must be nonempty")
    return out


__all__ = [
    "DEFAULT_RESEARCH_BASIS_IDS",
    "FAMILY_RESEARCH_BASIS_IDS",
    "REQUIRED_SOURCE_FIELDS",
    "RESEARCH_SOURCES",
    "RESEARCH_SOURCE_ALIASES",
    "SCHEMA_VERSION",
    "TOOL_NAME",
    "ResearchBasisError",
    "canonical_research_basis_id",
    "research_basis_ids_for_family",
    "research_basis_manifest",
]
