# SPDX-License-Identifier: MIT
"""Exact V9 HOSC dual-head counted Y1 program and public NumPy receiver.

This module is an architecture-specific ``SemanticRootY1`` variant.  It does
not reinterpret the G103 ``ORIGINAL_COORDINR_FILM_MLP_V1`` model.  Its counted
packet contains:

* the exact public runtime configuration for the deterministic positional
  Fourier basis and ``tanh(beta * sin(omega * x))`` activation;
* power-of-two-quantized shared V9 ``in_proj`` / ``film`` / ``hidden`` /
  ``out_sdf`` / ``out_tex`` / ``palette`` tensors;
* optional, explicitly typed ``film_pl`` and ``concat_pl`` tensors; and
* only the 600 odd ``code[2*p+1]`` Y1 rows.

The even Y0 rows never enter this packet. The typed G110 generated-Y1
conditional is the exclusive Y0 owner; legacy G94-V2 is not this product.
Phase advection is a training force which shapes these counted weights; it is
external encoder evidence, not a fictitious inflate-time operand.

The public plugin ABI is ``VARIANT_ID`` + ``accepts_packet`` +
``parse_packet`` + ``render_scorer_y1``.  This file intentionally contains
only scorer-free receiver logic; checkpoint intake and source custody remain
encoder-side and are never candidate bytes.
"""
from __future__ import annotations

import json
import math
import struct
import zlib
from dataclasses import dataclass, field, replace
from enum import IntEnum
from typing import Any, Final

import numpy as np

VARIANT_ID: Final = "tac.semantic_root_y1.v9_hosc_dual_head_odd_y1.v1"
MAGIC: Final = b"SV9Y1V1\0"
VERSION: Final = 1
PAIR_COUNT_N600: Final = 600
SCORER_H: Final = 384
SCORER_W: Final = 512
SCORER_CHANNELS: Final = 3
N_CLASSES: Final = 5
MAX_PACKET_BYTES: Final = 2_000_000
MAX_TENSORS: Final = 16
MAX_TENSOR_RANK: Final = 4
MAX_RUNTIME_FEATURE_CACHE_BYTES: Final = 512 * 1024 * 1024
_HEADER = struct.Struct(">8sBBHIII")
_SECTION = struct.Struct(">4sI")
_MODEL_HEADER = struct.Struct(">4sH")
_TENSOR_HEADER = struct.Struct(">BBbB4HI")
_Y1_HEADER = struct.Struct(">4sHHbBBxI")
_SECTION_ORDER: Final = (b"CONF", b"MODL", b"Y1CD")
_MODEL_MAGIC: Final = b"V9M1"
_Y1_MAGIC: Final = b"Y1R1"
_Y1_CODEC_RAW_I16_LE: Final = 0
_Y1_CODEC_DELTA_RICE: Final = 1
_FLAG_FILM_PL: Final = 1 << 0
_FLAG_CONCAT_PL: Final = 1 << 1
_FLAG_CHROMA: Final = 1 << 2
_KNOWN_FLAGS: Final = _FLAG_FILM_PL | _FLAG_CONCAT_PL | _FLAG_CHROMA
class ExactV9SemanticRootError(ValueError):
    """An exact V9 packet or receiver invariant failed closed."""


class Y1WireCodecV1(IntEnum):
    """Canonical-within-family Y1 wire alternatives selected by outer ZIP."""

    RAW_I16_LE = _Y1_CODEC_RAW_I16_LE
    DELTA_RICE_BEST_K = _Y1_CODEC_DELTA_RICE


class V9TensorDTypeV1(IntEnum):
    INT8 = 0
    INT16_LE = 1


def accepts_packet(packet: bytes) -> bool:
    """Select only the exact self-describing V9 packet family."""

    return type(packet) is bytes and packet.startswith(MAGIC)
def _canonical_json(value: Any) -> bytes:
    try:
        return json.dumps(
            value,
            sort_keys=True,
            separators=(",", ":"),
            ensure_ascii=True,
            allow_nan=False,
        ).encode("ascii")
    except (TypeError, ValueError, UnicodeEncodeError) as exc:
        raise ExactV9SemanticRootError("value is not finite canonical ASCII JSON") from exc
@dataclass(frozen=True, slots=True)
class V9PolarFourierConfigV1:
    """The exact generic positional basis regenerated by the public receiver."""

    n_scales: int
    n_orient0: int
    f0: float
    base: float
    n_iso: int
    max_freq: float | None

    def __post_init__(self) -> None:
        if type(self.n_scales) is not int or not 1 <= self.n_scales <= 16:
            raise ExactV9SemanticRootError("n_scales must be an exact integer in [1,16]")
        if type(self.n_orient0) is not int or not 1 <= self.n_orient0 <= 64:
            raise ExactV9SemanticRootError("n_orient0 must be an exact integer in [1,64]")
        if type(self.n_iso) is not int or not 0 <= self.n_iso <= 64:
            raise ExactV9SemanticRootError("n_iso must be an exact integer in [0,64]")
        for name, value in (("f0", self.f0), ("base", self.base)):
            if type(value) is not float or not math.isfinite(value) or value <= 0.0:
                raise ExactV9SemanticRootError(f"{name} must be a finite positive float")
        if self.max_freq is not None and (
            type(self.max_freq) is not float
            or not math.isfinite(self.max_freq)
            or self.max_freq <= 0.0
        ):
            raise ExactV9SemanticRootError("max_freq must be None or a finite positive float")

    def to_dict(self) -> dict[str, Any]:
        return {
            "kind": "polar_directional_fourier.v1",
            "n_scales": self.n_scales,
            "n_orient0": self.n_orient0,
            "f0": self.f0,
            "base": self.base,
            "n_iso": self.n_iso,
            "max_freq": self.max_freq,
        }

    @classmethod
    def from_dict(cls, value: object) -> V9PolarFourierConfigV1:
        if type(value) is not dict or set(value) != {
            "kind",
            "n_scales",
            "n_orient0",
            "f0",
            "base",
            "n_iso",
            "max_freq",
        }:
            raise ExactV9SemanticRootError("basis config has a noncanonical key set")
        if value["kind"] != "polar_directional_fourier.v1":
            raise ExactV9SemanticRootError("only the exact polar-directional V9 basis is implemented")
        if (
            type(value["n_scales"]) is not int
            or type(value["n_orient0"]) is not int
            or type(value["n_iso"]) is not int
            or type(value["f0"]) not in {int, float}
            or type(value["base"]) not in {int, float}
            or (value["max_freq"] is not None and type(value["max_freq"]) not in {int, float})
        ):
            raise ExactV9SemanticRootError("basis config scalar types are not canonical")
        maximum = value["max_freq"]
        return cls(
            n_scales=int(value["n_scales"]),
            n_orient0=int(value["n_orient0"]),
            f0=float(value["f0"]),
            base=float(value["base"]),
            n_iso=int(value["n_iso"]),
            max_freq=None if maximum is None else float(maximum),
        )

    @property
    def input_dim(self) -> int:
        return 2 * _polar_fourier_b(self).shape[1]


@dataclass(frozen=True, slots=True)
class V9RuntimeConfigV1:
    """Every non-tensor operand consumed by the public V9 Y1 receiver."""

    input_dim: int
    hidden_dim: int
    hidden_layer_count: int
    modulation_dim: int
    softmax_temp: float
    hosc_beta: float
    hosc_omega: float
    chroma: bool
    film_per_layer: bool
    film_concat_code: bool
    basis: V9PolarFourierConfigV1

    def __post_init__(self) -> None:
        for name, value, lower, upper in (
            ("input_dim", self.input_dim, 2, 4096),
            ("hidden_dim", self.hidden_dim, 1, 1024),
            ("hidden_layer_count", self.hidden_layer_count, 1, 8),
            ("modulation_dim", self.modulation_dim, 1, 256),
        ):
            if type(value) is not int or not lower <= value <= upper:
                raise ExactV9SemanticRootError(f"{name} must be an exact integer in [{lower},{upper}]")
        for name, value in (
            ("softmax_temp", self.softmax_temp),
            ("hosc_beta", self.hosc_beta),
            ("hosc_omega", self.hosc_omega),
        ):
            if type(value) is not float or not math.isfinite(value) or value <= 0.0:
                raise ExactV9SemanticRootError(f"{name} must be a finite positive float")
        if type(self.chroma) is not bool:
            raise ExactV9SemanticRootError("chroma must be bool")
        if type(self.film_per_layer) is not bool or type(self.film_concat_code) is not bool:
            raise ExactV9SemanticRootError("optional FiLM route flags must be bool")
        if type(self.basis) is not V9PolarFourierConfigV1:
            raise ExactV9SemanticRootError("basis must be V9PolarFourierConfigV1")
        if self.input_dim != self.basis.input_dim:
            raise ExactV9SemanticRootError("input_dim disagrees with the exact positional basis width")

    @property
    def flags(self) -> int:
        return (
            (_FLAG_FILM_PL if self.film_per_layer else 0)
            | (_FLAG_CONCAT_PL if self.film_concat_code else 0)
            | (_FLAG_CHROMA if self.chroma else 0)
        )

    def to_dict(self) -> dict[str, Any]:
        return {
            "variant_id": VARIANT_ID,
            "activation": "hosc_tanh_beta_sin.v1",
            "pair_count": PAIR_COUNT_N600,
            "scorer_shape": [SCORER_H, SCORER_W, SCORER_CHANNELS],
            "n_classes": N_CLASSES,
            "input_dim": self.input_dim,
            "hidden_dim": self.hidden_dim,
            "hidden_layer_count": self.hidden_layer_count,
            "modulation_dim": self.modulation_dim,
            "softmax_temp": self.softmax_temp,
            "hosc_beta": self.hosc_beta,
            "hosc_omega": self.hosc_omega,
            "chroma": self.chroma,
            "film_per_layer": self.film_per_layer,
            "film_concat_code": self.film_concat_code,
            "basis": self.basis.to_dict(),
            "y1_projection": "code[2*p+1]",
            "y1_temporal_codec": (
                "raw_i16le_or_delta_rice_best_k_outer_archive_selected_v1"
            ),
            "y0_owner": "G110_GENERATED_Y1_CONDITIONAL",
        }

    @classmethod
    def from_dict(cls, value: object) -> V9RuntimeConfigV1:
        if type(value) is not dict:
            raise ExactV9SemanticRootError("runtime config must be an object")
        expected = {
            "variant_id",
            "activation",
            "pair_count",
            "scorer_shape",
            "n_classes",
            "input_dim",
            "hidden_dim",
            "hidden_layer_count",
            "modulation_dim",
            "softmax_temp",
            "hosc_beta",
            "hosc_omega",
            "chroma",
            "film_per_layer",
            "film_concat_code",
            "basis",
            "y1_projection",
            "y1_temporal_codec",
            "y0_owner",
        }
        if set(value) != expected:
            raise ExactV9SemanticRootError("runtime config has a noncanonical key set")
        if (
            value["variant_id"] != VARIANT_ID
            or value["activation"] != "hosc_tanh_beta_sin.v1"
            or value["pair_count"] != PAIR_COUNT_N600
            or value["scorer_shape"] != [SCORER_H, SCORER_W, SCORER_CHANNELS]
            or value["n_classes"] != N_CLASSES
            or value["y1_projection"] != "code[2*p+1]"
            or value["y1_temporal_codec"]
            != "raw_i16le_or_delta_rice_best_k_outer_archive_selected_v1"
            or value["y0_owner"] != "G110_GENERATED_Y1_CONDITIONAL"
        ):
            raise ExactV9SemanticRootError("runtime config changes a sealed V9/Y1 contract")
        if (
            type(value["input_dim"]) is not int
            or type(value["hidden_dim"]) is not int
            or type(value["hidden_layer_count"]) is not int
            or type(value["modulation_dim"]) is not int
            or type(value["softmax_temp"]) not in {int, float}
            or type(value["hosc_beta"]) not in {int, float}
            or type(value["hosc_omega"]) not in {int, float}
            or type(value["chroma"]) is not bool
            or type(value["film_per_layer"]) is not bool
            or type(value["film_concat_code"]) is not bool
        ):
            raise ExactV9SemanticRootError("runtime config scalar types are not canonical")
        return cls(
            input_dim=int(value["input_dim"]),
            hidden_dim=int(value["hidden_dim"]),
            hidden_layer_count=int(value["hidden_layer_count"]),
            modulation_dim=int(value["modulation_dim"]),
            softmax_temp=float(value["softmax_temp"]),
            hosc_beta=float(value["hosc_beta"]),
            hosc_omega=float(value["hosc_omega"]),
            chroma=value["chroma"],
            film_per_layer=value["film_per_layer"],
            film_concat_code=value["film_concat_code"],
            basis=V9PolarFourierConfigV1.from_dict(value["basis"]),
        )


@dataclass(frozen=True, slots=True)
class V9CountedTensorV1:
    name: str
    dtype: V9TensorDTypeV1
    shape: tuple[int, ...]
    scale_exponent: int
    data: bytes = field(repr=False)

    def __post_init__(self) -> None:
        if (
            type(self.name) is not str
            or not self.name
            or not self.name.isascii()
            or len(self.name.encode("ascii")) > 255
        ):
            raise ExactV9SemanticRootError("tensor name must be nonempty bounded ASCII")
        if type(self.dtype) is not V9TensorDTypeV1:
            raise ExactV9SemanticRootError("tensor dtype is not typed")
        if type(self.shape) is not tuple or not 1 <= len(self.shape) <= MAX_TENSOR_RANK:
            raise ExactV9SemanticRootError("tensor shape rank must be in [1,4]")
        if any(type(value) is not int or not 1 <= value <= 0xFFFF for value in self.shape):
            raise ExactV9SemanticRootError("tensor dimensions must be exact positive uint16 values")
        if type(self.scale_exponent) is not int or not -64 <= self.scale_exponent <= 63:
            raise ExactV9SemanticRootError("tensor scale_exponent must be an exact int8-range exponent")
        if type(self.data) is not bytes:
            raise ExactV9SemanticRootError("tensor data must be exact bytes")
        count = math.prod(self.shape)
        itemsize = 1 if self.dtype is V9TensorDTypeV1.INT8 else 2
        if len(self.data) != count * itemsize:
            raise ExactV9SemanticRootError("tensor data length disagrees with shape and dtype")

    @property
    def quantized(self) -> np.ndarray:
        dtype = np.dtype("i1") if self.dtype is V9TensorDTypeV1.INT8 else np.dtype("<i2")
        return np.frombuffer(self.data, dtype=dtype).reshape(self.shape).copy()

    @property
    def dequantized(self) -> np.ndarray:
        return np.ldexp(self.quantized.astype(np.float32), self.scale_exponent).astype(np.float32)


@dataclass(frozen=True, slots=True)
class ExactV9SemanticRootY1ProgramV1:
    config: V9RuntimeConfigV1
    tensors: tuple[V9CountedTensorV1, ...]
    y1_code_scale_exponent: int
    y1_code_q: np.ndarray = field(repr=False)
    y1_wire_codec: Y1WireCodecV1 | None = None
    _runtime_features_f64: np.ndarray = field(
        init=False,
        repr=False,
        compare=False,
    )
    _runtime_params_f64: dict[str, np.ndarray] = field(
        init=False,
        repr=False,
        compare=False,
    )
    _runtime_y1_code_f64: np.ndarray = field(
        init=False,
        repr=False,
        compare=False,
    )

    def __post_init__(self) -> None:
        if type(self.config) is not V9RuntimeConfigV1:
            raise ExactV9SemanticRootError("program config is not V9RuntimeConfigV1")
        if type(self.tensors) is not tuple or not self.tensors:
            raise ExactV9SemanticRootError("program tensors must be a nonempty tuple")
        if len(self.tensors) > MAX_TENSORS or any(
            type(tensor) is not V9CountedTensorV1 for tensor in self.tensors
        ):
            raise ExactV9SemanticRootError("program tensor tuple is malformed")
        if type(self.y1_code_scale_exponent) is not int or not -64 <= self.y1_code_scale_exponent <= 63:
            raise ExactV9SemanticRootError("Y1 code scale exponent is invalid")
        if self.y1_wire_codec is not None and type(self.y1_wire_codec) is not Y1WireCodecV1:
            raise ExactV9SemanticRootError(
                "Y1 wire codec must be typed or unresolved"
            )
        code = np.asarray(self.y1_code_q)
        if code.dtype != np.dtype("<i2") or code.shape != (
            PAIR_COUNT_N600,
            self.config.modulation_dim,
        ):
            raise ExactV9SemanticRootError("Y1 code must be canonical little-endian int16[600,mod_dim]")
        if not code.flags.c_contiguous:
            raise ExactV9SemanticRootError("Y1 code must be C-contiguous")
        _validate_tensor_abi(self.config, self.tensors)
        feature_cache_bytes = (
            SCORER_H
            * SCORER_W
            * self.config.input_dim
            * np.dtype(np.float64).itemsize
        )
        if feature_cache_bytes > MAX_RUNTIME_FEATURE_CACHE_BYTES:
            raise ExactV9SemanticRootError(
                "runtime Fourier cache exceeds the bounded receiver envelope"
            )
        features_f64 = np.ascontiguousarray(
            build_runtime_features(self.config),
            dtype=np.float64,
        )
        params_f64 = {
            name: np.ascontiguousarray(value, dtype=np.float64)
            for name, value in self.params.items()
        }
        y1_code_f64 = np.ascontiguousarray(
            self.y1_code,
            dtype=np.float64,
        )
        features_f64.setflags(write=False)
        y1_code_f64.setflags(write=False)
        for value in params_f64.values():
            value.setflags(write=False)
        object.__setattr__(self, "_runtime_features_f64", features_f64)
        object.__setattr__(self, "_runtime_params_f64", params_f64)
        object.__setattr__(self, "_runtime_y1_code_f64", y1_code_f64)

    @property
    def params(self) -> dict[str, np.ndarray]:
        """Expand the typed stacked wire tensors into repository V9 parameter keys."""

        stored = {tensor.name: tensor.dequantized for tensor in self.tensors}
        result = {
            "in_proj.weight": stored["in_proj.weight"],
            "in_proj.bias": stored["in_proj.bias"],
            "film.weight": stored["film.weight"],
            "film.bias": stored["film.bias"],
            "out_sdf.weight": stored["out_sdf.weight"],
            "out_sdf.bias": stored["out_sdf.bias"],
            "out_tex.weight": stored["out_tex.weight"],
            "out_tex.bias": stored["out_tex.bias"],
            "palette": stored["palette"],
        }
        for index in range(self.config.hidden_layer_count):
            result[f"hidden.{index}.weight"] = stored["hidden.weight"][index]
            result[f"hidden.{index}.bias"] = stored["hidden.bias"][index]
            if self.config.film_per_layer:
                result[f"film_pl.{index}.weight"] = stored["film_pl.weight"][index]
                result[f"film_pl.{index}.bias"] = stored["film_pl.bias"][index]
            if self.config.film_concat_code:
                result[f"concat_pl.{index}.weight"] = stored["concat_pl.weight"][index]
                result[f"concat_pl.{index}.bias"] = stored["concat_pl.bias"][index]
        return result

    @property
    def y1_code(self) -> np.ndarray:
        return np.ldexp(
            np.asarray(self.y1_code_q, dtype=np.float32),
            self.y1_code_scale_exponent,
        ).astype(np.float32)
def _polar_fourier_b(config: V9PolarFourierConfigV1) -> np.ndarray:
    columns: list[np.ndarray] = []
    for scale_index in range(config.n_scales):
        frequency = config.f0 * (config.base**scale_index)
        orientation_count = config.n_orient0 * (2 ** (scale_index // 2))
        for orientation_index in range(orientation_count):
            theta = np.pi * orientation_index / orientation_count
            columns.append(
                np.array(
                    [frequency * np.cos(theta), frequency * np.sin(theta)],
                    dtype=np.float32,
                )
            )
    for index in range(config.n_iso):
        theta = np.pi * index / max(config.n_iso, 1)
        frequency = config.f0 * 0.5
        columns.append(
            np.array(
                [frequency * np.cos(theta), frequency * np.sin(theta)],
                dtype=np.float32,
            )
        )
    if not columns:
        raise ExactV9SemanticRootError("positional basis cannot be empty")
    result = np.stack(columns, axis=1).astype(np.float32)
    if config.max_freq is not None:
        norms = np.sqrt((result.astype(np.float64) ** 2).sum(axis=0))
        keep = norms <= config.max_freq + 1e-6
        if not keep.any():
            keep = norms <= float(norms.min()) + 1e-6
        result = result[:, keep]
    return result


def build_runtime_features(config: V9RuntimeConfigV1) -> np.ndarray:
    """Regenerate the exact free positional feature grid for the public receiver."""

    ys = np.linspace(-1.0, 1.0, SCORER_H, dtype=np.float32)
    xs = np.linspace(-1.0, 1.0, SCORER_W, dtype=np.float32)
    grid_y, grid_x = np.meshgrid(ys, xs, indexing="ij")
    coords = np.stack([grid_x.ravel(), grid_y.ravel()], axis=-1).astype(np.float32)
    basis = _polar_fourier_b(config.basis)
    with np.errstate(all="ignore"):
        projection = (2.0 * np.pi) * (
            np.asarray(coords, np.float64) @ np.asarray(basis, np.float64)
        )
        features = np.concatenate(
            [np.sin(projection), np.cos(projection)],
            axis=-1,
        ).astype(np.float32)
    if features.shape != (SCORER_H * SCORER_W, config.input_dim):
        raise ExactV9SemanticRootError("regenerated positional features disagree with runtime input_dim")
    return features


def _hosc(values: np.ndarray, *, beta: float, omega: float) -> np.ndarray:
    """Op-for-op activation mirror, including repository float32 stage casts."""

    return np.tanh(beta * np.sin(omega * np.asarray(values, np.float64))).astype(np.float32)


def forward_float32(
    program: ExactV9SemanticRootY1ProgramV1,
    pair_id: int,
) -> tuple[np.ndarray, np.ndarray]:
    """Independent deterministic NumPy mirror of the repository V9 dual-head forward."""

    if type(program) is not ExactV9SemanticRootY1ProgramV1:
        raise ExactV9SemanticRootError("forward requires ExactV9SemanticRootY1ProgramV1")
    if type(pair_id) is not int or not 0 <= pair_id < PAIR_COUNT_N600:
        raise ExactV9SemanticRootError("pair_id must be an exact integer in [0,599]")
    config = program.config
    params = program._runtime_params_f64
    features = program._runtime_features_f64
    code = program._runtime_y1_code_f64[pair_id]
    with np.errstate(over="ignore", invalid="ignore", divide="ignore"):
        hidden = _hosc(
            features @ params["in_proj.weight"].T + params["in_proj.bias"],
            beta=config.hosc_beta,
            omega=config.hosc_omega,
        )
        film = (
            code @ params["film.weight"].T + params["film.bias"]
        ).reshape(config.hidden_layer_count, 2, config.hidden_dim)
        for index in range(config.hidden_layer_count):
            scale = 1.0 + film[index, 0]
            shift = film[index, 1]
            if config.film_per_layer:
                per_layer = (
                    code @ params[f"film_pl.{index}.weight"].T
                    + params[f"film_pl.{index}.bias"]
                ).reshape(2, config.hidden_dim)
                scale = scale + per_layer[0]
                shift = shift + per_layer[1]
            preactivation = (
                hidden @ params[f"hidden.{index}.weight"].T
                + params[f"hidden.{index}.bias"]
            ) * scale + shift
            if config.film_concat_code:
                preactivation = (
                    preactivation
                    + code @ params[f"concat_pl.{index}.weight"].T
                    + params[f"concat_pl.{index}.bias"]
                )
            hidden = _hosc(
                preactivation,
                beta=config.hosc_beta,
                omega=config.hosc_omega,
            )
        phi = hidden @ params["out_sdf.weight"].T + params["out_sdf.bias"]
        texture = hidden @ params["out_tex.weight"].T + params["out_tex.bias"]
        logits = phi / config.softmax_temp
        logits = logits - logits.max(axis=-1, keepdims=True)
        soft = np.exp(logits)
        soft = soft / soft.sum(axis=-1, keepdims=True)
        base = soft @ params["palette"]
        rgb = (1.0 / (1.0 + np.exp(-(base + texture)))) * 255.0
        if not config.chroma:
            luma = (
                0.299 * rgb[:, 0:1]
                + 0.587 * rgb[:, 1:2]
                + 0.114 * rgb[:, 2:3]
            )
            rgb = np.concatenate([luma, luma, luma], axis=-1)
    return rgb.astype(np.float32), phi.astype(np.float32)


def render_scorer_y1(
    parsed: ExactV9SemanticRootY1ProgramV1,
    pair_id: int,
) -> np.ndarray:
    """Public plugin ABI: render scorer-grid Y1 as deterministic uint8 RGB."""

    rgb, _ = forward_float32(parsed, pair_id)
    return np.clip(np.rint(rgb), 0.0, 255.0).astype(np.uint8).reshape(
        SCORER_H,
        SCORER_W,
        SCORER_CHANNELS,
    )


def _expected_tensor_shapes(config: V9RuntimeConfigV1) -> tuple[tuple[str, tuple[int, ...]], ...]:
    hidden = config.hidden_dim
    layers = config.hidden_layer_count
    modulation = config.modulation_dim
    expected: list[tuple[str, tuple[int, ...]]] = [
        ("in_proj.weight", (hidden, config.input_dim)),
        ("in_proj.bias", (hidden,)),
        ("film.weight", (2 * hidden * layers, modulation)),
        ("film.bias", (2 * hidden * layers,)),
        ("hidden.weight", (layers, hidden, hidden)),
        ("hidden.bias", (layers, hidden)),
    ]
    if config.film_per_layer:
        expected.extend(
            [
                ("film_pl.weight", (layers, 2 * hidden, modulation)),
                ("film_pl.bias", (layers, 2 * hidden)),
            ]
        )
    if config.film_concat_code:
        expected.extend(
            [
                ("concat_pl.weight", (layers, hidden, modulation)),
                ("concat_pl.bias", (layers, hidden)),
            ]
        )
    expected.extend(
        [
            ("out_sdf.weight", (N_CLASSES, hidden)),
            ("out_sdf.bias", (N_CLASSES,)),
            ("out_tex.weight", (SCORER_CHANNELS, hidden)),
            ("out_tex.bias", (SCORER_CHANNELS,)),
            ("palette", (N_CLASSES, SCORER_CHANNELS)),
        ]
    )
    return tuple(expected)


def _validate_tensor_abi(
    config: V9RuntimeConfigV1,
    tensors: tuple[V9CountedTensorV1, ...],
) -> None:
    observed = tuple((tensor.name, tensor.shape) for tensor in tensors)
    expected = _expected_tensor_shapes(config)
    if observed != expected:
        raise ExactV9SemanticRootError("counted tensor order/shapes disagree with exact V9 ABI")
    for tensor in tensors:
        expected_dtype = (
            V9TensorDTypeV1.INT8
            if tensor.name.endswith(".weight")
            else V9TensorDTypeV1.INT16_LE
        )
        if tensor.dtype is not expected_dtype:
            raise ExactV9SemanticRootError(f"{tensor.name} dtype disagrees with exact V9 ABI")
def _encode_model(tensors: tuple[V9CountedTensorV1, ...]) -> bytes:
    rows = [_MODEL_HEADER.pack(_MODEL_MAGIC, len(tensors))]
    for tensor in tensors:
        name = tensor.name.encode("ascii")
        padded = tensor.shape + (0,) * (MAX_TENSOR_RANK - len(tensor.shape))
        rows.append(
            bytes([len(name)])
            + name
            + _TENSOR_HEADER.pack(
                int(tensor.dtype),
                len(tensor.shape),
                tensor.scale_exponent,
                0,
                *padded,
                len(tensor.data),
            )
            + tensor.data
        )
    return b"".join(rows)


def _decode_model(payload: bytes) -> tuple[V9CountedTensorV1, ...]:
    if len(payload) < _MODEL_HEADER.size:
        raise ExactV9SemanticRootError("model section is truncated")
    magic, count = _MODEL_HEADER.unpack_from(payload)
    if magic != _MODEL_MAGIC or not 1 <= count <= MAX_TENSORS:
        raise ExactV9SemanticRootError("model section header is invalid")
    cursor = _MODEL_HEADER.size
    result = []
    for _ in range(count):
        if cursor >= len(payload):
            raise ExactV9SemanticRootError("model tensor name length is truncated")
        name_length = payload[cursor]
        cursor += 1
        if not name_length or cursor + name_length + _TENSOR_HEADER.size > len(payload):
            raise ExactV9SemanticRootError("model tensor header is truncated")
        try:
            name = payload[cursor : cursor + name_length].decode("ascii")
        except UnicodeDecodeError as exc:
            raise ExactV9SemanticRootError("model tensor name is not ASCII") from exc
        cursor += name_length
        row = _TENSOR_HEADER.unpack_from(payload, cursor)
        cursor += _TENSOR_HEADER.size
        dtype_raw, rank, exponent, reserved, *tail = row
        dimensions = tuple(int(value) for value in tail[:4])
        byte_length = int(tail[4])
        if (
            reserved != 0
            or not 1 <= rank <= MAX_TENSOR_RANK
            or any(dimensions[index] <= 0 for index in range(rank))
            or any(dimensions[index] != 0 for index in range(rank, MAX_TENSOR_RANK))
            or cursor + byte_length > len(payload)
        ):
            raise ExactV9SemanticRootError("model tensor shape/length metadata is invalid")
        try:
            dtype = V9TensorDTypeV1(dtype_raw)
        except ValueError as exc:
            raise ExactV9SemanticRootError("model tensor dtype is unknown") from exc
        result.append(
            V9CountedTensorV1(
                name=name,
                dtype=dtype,
                shape=dimensions[:rank],
                scale_exponent=int(exponent),
                data=payload[cursor : cursor + byte_length],
            )
        )
        cursor += byte_length
    if cursor != len(payload):
        raise ExactV9SemanticRootError("model section has hidden/trailing bytes")
    return tuple(result)


class _BitWriter:
    def __init__(self) -> None:
        self.data = bytearray()
        self.byte = 0
        self.used = 0

    def bit(self, value: int) -> None:
        self.byte = (self.byte << 1) | (value & 1)
        self.used += 1
        if self.used == 8:
            self.data.append(self.byte)
            self.byte = 0
            self.used = 0

    def finish(self) -> bytes:
        if self.used:
            self.data.append(self.byte << (8 - self.used))
        return bytes(self.data)


class _BitReader:
    def __init__(self, payload: bytes) -> None:
        self.payload = payload
        self.offset = 0

    def bit(self) -> int:
        if self.offset >= len(self.payload) * 8:
            raise ExactV9SemanticRootError("temporal Rice stream is truncated")
        value = (
            self.payload[self.offset // 8] >> (7 - self.offset % 8)
        ) & 1
        self.offset += 1
        return value

    def zero_padding(self) -> None:
        while self.offset < len(self.payload) * 8:
            if self.bit():
                raise ExactV9SemanticRootError(
                    "temporal Rice stream has noncanonical trailing bits"
                )


def _rice_encode_signed(values: np.ndarray, rice_k: int) -> bytes:
    writer = _BitWriter()
    previous = np.zeros(values.shape[1], dtype=np.int64)
    for row in values.astype(np.int64, copy=False):
        for column, current in enumerate(row):
            delta = int(current - previous[column])
            previous[column] = current
            unsigned = 2 * delta if delta >= 0 else -2 * delta - 1
            quotient = unsigned >> rice_k
            if quotient > 0xFFFF:
                raise ExactV9SemanticRootError(
                    "temporal Rice quotient exceeds closed decoder bound"
                )
            for _ in range(quotient):
                writer.bit(1)
            writer.bit(0)
            for shift in range(rice_k - 1, -1, -1):
                writer.bit((unsigned >> shift) & 1)
    return writer.finish()


def _rice_decode_signed(
    payload: bytes,
    *,
    pair_count: int,
    latent_dim: int,
    rice_k: int,
) -> np.ndarray:
    reader = _BitReader(payload)
    output = np.empty((pair_count, latent_dim), dtype=np.int16)
    previous = np.zeros(latent_dim, dtype=np.int64)
    for pair_id in range(pair_count):
        for column in range(latent_dim):
            quotient = 0
            while reader.bit():
                quotient += 1
                if quotient > 0xFFFF:
                    raise ExactV9SemanticRootError(
                        "temporal Rice unary quotient exceeds decoder bound"
                    )
            remainder = 0
            for _ in range(rice_k):
                remainder = (remainder << 1) | reader.bit()
            unsigned = (quotient << rice_k) | remainder
            delta = (
                unsigned // 2
                if unsigned % 2 == 0
                else -(unsigned // 2) - 1
            )
            value = int(previous[column]) + delta
            if not -0x8000 <= value <= 0x7FFF:
                raise ExactV9SemanticRootError(
                    "temporal latent delta leaves the int16 range"
                )
            output[pair_id, column] = value
            previous[column] = value
    reader.zero_padding()
    return np.ascontiguousarray(output)


def _best_temporal_y1(values: np.ndarray) -> tuple[int, bytes]:
    canonical = np.asarray(values, dtype=np.int64)
    previous = np.vstack(
        [
            np.zeros((1, canonical.shape[1]), dtype=np.int64),
            canonical[:-1],
        ]
    )
    delta = canonical - previous
    unsigned = np.where(delta >= 0, 2 * delta, -2 * delta - 1)
    candidates: list[tuple[int, int]] = []
    for rice_k in range(16):
        quotient = unsigned >> rice_k
        if int(quotient.max(initial=0)) > 0xFFFF:
            continue
        bit_count = int(quotient.sum()) + int(unsigned.size) * (1 + rice_k)
        byte_count = (bit_count + 7) // 8
        if byte_count <= MAX_PACKET_BYTES:
            candidates.append((byte_count, rice_k))
    if not candidates:
        raise ExactV9SemanticRootError(
            "no bounded temporal Rice code can represent the Y1 trajectory"
        )
    _, rice_k = min(candidates)
    return rice_k, _rice_encode_signed(canonical, rice_k)


def _canonical_y1_payload(
    values: np.ndarray,
    codec: Y1WireCodecV1,
) -> tuple[int, int, bytes]:
    if type(codec) is not Y1WireCodecV1:
        raise ExactV9SemanticRootError("Y1 wire codec is not typed")
    if codec is Y1WireCodecV1.RAW_I16_LE:
        return (
            int(codec),
            0,
            np.asarray(values, dtype="<i2").tobytes(order="C"),
        )
    rice_k, encoded = _best_temporal_y1(values)
    return int(codec), rice_k, encoded


def _best_y1_payload(values: np.ndarray) -> tuple[int, int, bytes]:
    choices = tuple(
        _canonical_y1_payload(values, codec)
        for codec in Y1WireCodecV1
    )
    return min(choices, key=lambda item: (len(item[2]), item[0], item[1]))


def _encode_y1(program: ExactV9SemanticRootY1ProgramV1) -> bytes:
    if program.y1_wire_codec is None:
        codec, rice_k, data = _best_y1_payload(program.y1_code_q)
    else:
        codec, rice_k, data = _canonical_y1_payload(
            program.y1_code_q,
            program.y1_wire_codec,
        )
    return _Y1_HEADER.pack(
        _Y1_MAGIC,
        PAIR_COUNT_N600,
        program.config.modulation_dim,
        program.y1_code_scale_exponent,
        codec,
        rice_k,
        len(data),
    ) + data


def _decode_y1(
    payload: bytes,
    *,
    modulation_dim: int,
) -> tuple[int, np.ndarray, Y1WireCodecV1]:
    if len(payload) < _Y1_HEADER.size:
        raise ExactV9SemanticRootError("Y1 code section is truncated")
    (
        magic,
        pair_count,
        inner_modulation_dim,
        exponent,
        codec,
        rice_k,
        byte_length,
    ) = _Y1_HEADER.unpack_from(payload)
    if (
        magic != _Y1_MAGIC
        or pair_count != PAIR_COUNT_N600
        or inner_modulation_dim != modulation_dim
        or codec not in {_Y1_CODEC_RAW_I16_LE, _Y1_CODEC_DELTA_RICE}
        or not 0 <= rice_k <= 15
        or len(payload) != _Y1_HEADER.size + byte_length
    ):
        raise ExactV9SemanticRootError("Y1 code header disagrees with the exact odd-row contract")
    encoded = payload[_Y1_HEADER.size :]
    if codec == _Y1_CODEC_RAW_I16_LE:
        if rice_k != 0 or byte_length != PAIR_COUNT_N600 * modulation_dim * 2:
            raise ExactV9SemanticRootError("raw Y1 code header is noncanonical")
        code = np.frombuffer(encoded, dtype="<i2").reshape(
            PAIR_COUNT_N600,
            modulation_dim,
        )
    else:
        code = _rice_decode_signed(
            encoded,
            pair_count=PAIR_COUNT_N600,
            latent_dim=modulation_dim,
            rice_k=int(rice_k),
        )
    wire_codec = Y1WireCodecV1(codec)
    canonical_codec, canonical_k, canonical_bytes = _canonical_y1_payload(
        code,
        wire_codec,
    )
    if (canonical_codec, canonical_k, canonical_bytes) != (codec, rice_k, encoded):
        raise ExactV9SemanticRootError(
            "Y1 stream is not canonical within its selected wire family"
        )
    return int(exponent), np.ascontiguousarray(code), wire_codec


def encode_packet(program: ExactV9SemanticRootY1ProgramV1) -> bytes:
    if type(program) is not ExactV9SemanticRootY1ProgramV1:
        raise ExactV9SemanticRootError("encode requires ExactV9SemanticRootY1ProgramV1")
    sections = (
        _canonical_json(program.config.to_dict()),
        _encode_model(program.tensors),
        _encode_y1(program),
    )
    body = b"".join(
        _SECTION.pack(tag, len(section)) + section
        for tag, section in zip(_SECTION_ORDER, sections, strict=True)
    )
    payload = _HEADER.pack(
        MAGIC,
        VERSION,
        program.config.flags,
        len(sections),
        len(body),
        zlib.crc32(body) & 0xFFFFFFFF,
        0,
    ) + body
    if len(payload) > MAX_PACKET_BYTES:
        raise ExactV9SemanticRootError("exact V9 semantic-root packet exceeds the bounded ABI")
    return payload


def encode_packet_y1_variant(
    program: ExactV9SemanticRootY1ProgramV1,
    codec: Y1WireCodecV1,
) -> bytes:
    if type(program) is not ExactV9SemanticRootY1ProgramV1:
        raise ExactV9SemanticRootError(
            "Y1 variant encode requires ExactV9SemanticRootY1ProgramV1"
        )
    if type(codec) is not Y1WireCodecV1:
        raise ExactV9SemanticRootError("Y1 variant codec is not typed")
    return encode_packet(replace(program, y1_wire_codec=codec))


def _split_sections(payload: bytes) -> tuple[int, dict[bytes, bytes]]:
    if type(payload) is not bytes or len(payload) < _HEADER.size:
        raise ExactV9SemanticRootError("packet must be exact nontruncated bytes")
    magic, version, flags, count, body_length, checksum, reserved = _HEADER.unpack_from(payload)
    body = payload[_HEADER.size :]
    if (
        magic != MAGIC
        or version != VERSION
        or flags & ~_KNOWN_FLAGS
        or count != len(_SECTION_ORDER)
        or reserved != 0
        or body_length != len(body)
        or len(payload) > MAX_PACKET_BYTES
        or zlib.crc32(body) & 0xFFFFFFFF != checksum
    ):
        raise ExactV9SemanticRootError("packet header, length, flags, or CRC is invalid")
    cursor = 0
    sections: dict[bytes, bytes] = {}
    for expected_tag in _SECTION_ORDER:
        if cursor + _SECTION.size > len(body):
            raise ExactV9SemanticRootError("packet section directory is truncated")
        tag, length = _SECTION.unpack_from(body, cursor)
        cursor += _SECTION.size
        if tag != expected_tag or tag in sections or cursor + length > len(body):
            raise ExactV9SemanticRootError("packet sections are unknown, duplicate, reordered, or truncated")
        sections[tag] = body[cursor : cursor + length]
        cursor += length
    if cursor != len(body):
        raise ExactV9SemanticRootError("packet has hidden/trailing bytes")
    return int(flags), sections


def parse_packet(payload: bytes) -> ExactV9SemanticRootY1ProgramV1:
    """Public plugin ABI: strict parse with exact canonical re-encode identity."""

    flags, sections = _split_sections(payload)
    try:
        config_value = json.loads(sections[b"CONF"].decode("ascii"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ExactV9SemanticRootError("runtime config is not ASCII JSON") from exc
    if _canonical_json(config_value) != sections[b"CONF"]:
        raise ExactV9SemanticRootError("runtime config changed under canonical parse/re-emit")
    config = V9RuntimeConfigV1.from_dict(config_value)
    if config.flags != flags:
        raise ExactV9SemanticRootError("packet flags disagree with runtime config")
    tensors = _decode_model(sections[b"MODL"])
    exponent, y1_code, y1_wire_codec = _decode_y1(
        sections[b"Y1CD"],
        modulation_dim=config.modulation_dim,
    )
    program = ExactV9SemanticRootY1ProgramV1(
        config=config,
        tensors=tensors,
        y1_code_scale_exponent=exponent,
        y1_code_q=y1_code,
        y1_wire_codec=y1_wire_codec,
    )
    if encode_packet(program) != payload:
        raise ExactV9SemanticRootError("packet changed under strict parse/re-emit")
    return program
