"""Tests for Lane Q-FAITHFUL: 1:1 Quantizr PR #55 architecture replica.

Per Round 26 convention, every test asserts a magnitude/sign anchor —
not just "doesn't crash". The architectural invariants are pinned so
silent regressions (e.g. someone adding a motion module back, or
breaking the unconditional/FiLM split) become impossible.
"""
from __future__ import annotations

import pytest
import torch
import torch.nn as nn

from tac.quantizr_faithful_renderer import (
    FiLMFrameHead,
    FiLMSepResBlock,
    Frame2StaticHead,
    FrameHead,
    JointFrameGenerator,
    SepConvGNAct,
    SepResBlock,
    SharedMaskDecoder,
    build_quantizr_faithful_renderer,
    make_coord_grid,
)


# ────────────────────────────────────────────────────────────────────────────
# Architectural invariants (the user's audit said these MUST hold)
# ────────────────────────────────────────────────────────────────────────────


def test_param_count_within_88k_target_band() -> None:
    """Quantizr PR #55: '88k params and 64kb when compressed'.

    Faithful port should land within ±2K of that target. If this drifts
    we either have an extra layer (regression) or are missing one.
    """
    model = build_quantizr_faithful_renderer()
    n_params = sum(p.numel() for p in model.parameters())
    assert 86_000 < n_params < 90_000, (
        f"param count {n_params:,} outside 86K-90K band; Quantizr target "
        f"is 88K. Either an extra module was added or one was dropped."
    )


def test_no_motion_module_present() -> None:
    """The whole point: Quantizr REMOVED the motion module.

    State dict keys must contain ZERO references to motion/warp/flow
    (case-insensitive). The audit
    (.omx/research/quantizr_replica_audit_20260428.md) calls this out as
    delta #1.
    """
    model = build_quantizr_faithful_renderer()
    forbidden_substrings = ("motion", "warp", "flow", "ego_flow", "zoom")
    keys = list(model.state_dict().keys())
    bad = [
        k
        for k in keys
        if any(sub in k.lower() for sub in forbidden_substrings)
    ]
    assert not bad, (
        f"Found motion-related state_dict keys {bad}; Quantizr's "
        f"architecture has NONE. PR body verbatim: 'dropping optical flow'."
    )


def test_forward_shape() -> None:
    """forward(mask2, pose6) -> (frame1, frame2) each (B, 3, H, W)."""
    model = build_quantizr_faithful_renderer()
    B = 2
    mask2 = torch.zeros(B, 384, 512, dtype=torch.long)
    pose6 = torch.zeros(B, 6)
    frame1, frame2 = model(mask2, pose6)
    assert frame1.shape == (B, 3, 384, 512), frame1.shape
    assert frame2.shape == (B, 3, 384, 512), frame2.shape
    # sigmoid * 255 -> outputs must lie within [0, 255] inclusive
    assert frame1.min().item() >= 0.0 and frame1.max().item() <= 255.0
    assert frame2.min().item() >= 0.0 and frame2.max().item() <= 255.0


def test_frame2_unconditional_invariant_to_pose() -> None:
    """frame2 is generated by Frame2StaticHead — NO pose conditioning.

    Varying pose6 must leave frame2 EXACTLY unchanged (not approximately —
    bit-identical, since pose6 doesn't enter the frame2_head graph at all).
    """
    model = build_quantizr_faithful_renderer().eval()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)

    pose_a = torch.zeros(B, 6)
    pose_b = torch.randn(B, 6) * 5.0  # large perturbation

    with torch.no_grad():
        _, f2_a = model(mask2, pose_a)
        _, f2_b = model(mask2, pose_b)

    diff = (f2_a - f2_b).abs().max().item()
    assert diff == 0.0, (
        f"frame2 is supposed to be UNCONDITIONAL on pose, but max abs "
        f"diff under pose perturbation = {diff}. Bug: pose leaked into "
        f"frame2_head somewhere."
    )


def test_frame1_changes_with_pose() -> None:
    """frame1 is FiLM-conditioned on pose — varying pose6 must MEASURABLY
    change frame1. Magnitude anchor: > 1e-3 (small — even one FiLM gamma
    change should dominate).
    """
    model = build_quantizr_faithful_renderer().eval()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)

    pose_a = torch.zeros(B, 6)
    pose_b = torch.randn(B, 6) * 5.0

    with torch.no_grad():
        f1_a, _ = model(mask2, pose_a)
        f1_b, _ = model(mask2, pose_b)

    diff = (f1_a - f1_b).abs().max().item()
    assert diff > 1e-3, (
        f"frame1 should respond to pose via FiLM, but max abs diff under "
        f"pose perturbation = {diff:.6e}. Bug: FiLM modulation isn't "
        f"reaching frame1_head (e.g. cond_emb is zero, or the FiLM gamma "
        f"scales were initialized to exactly zero with no bias)."
    )


def test_film_gradient_flows_to_pose_mlp() -> None:
    """Backward pass through frame1 loss must produce non-zero, finite
    gradient on pose_mlp parameters. If grads are None or zero, FiLM is
    effectively disconnected.
    """
    model = build_quantizr_faithful_renderer().train()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose6 = torch.randn(B, 6, requires_grad=True)

    f1, _ = model(mask2, pose6)
    loss = f1.mean()
    loss.backward()

    for name, param in model.pose_mlp.named_parameters():
        assert param.grad is not None, f"pose_mlp.{name}.grad is None"
        assert torch.isfinite(param.grad).all(), (
            f"pose_mlp.{name} has non-finite grad"
        )
        nz = (param.grad != 0).any().item()
        assert nz, (
            f"pose_mlp.{name}.grad is identically zero; FiLM disconnected"
        )


def test_5_step_training_loss_decreases() -> None:
    """5-step Adam optimization: loss must STRICTLY decrease across the run.

    Magnitude anchor: final_loss < initial_loss * 0.99 (any fitting at all).
    """
    torch.manual_seed(0)
    model = build_quantizr_faithful_renderer().train()
    B = 2
    mask2 = torch.randint(0, 5, (B, 384, 512), dtype=torch.long)
    pose6 = torch.randn(B, 6)
    target_f1 = torch.randn(B, 3, 384, 512) * 30.0 + 127.5
    target_f2 = torch.randn(B, 3, 384, 512) * 30.0 + 127.5

    optim = torch.optim.Adam(model.parameters(), lr=1e-3)
    losses: list[float] = []
    for step in range(5):
        optim.zero_grad()
        f1, f2 = model(mask2, pose6)
        loss = (f1 - target_f1).abs().mean() + (f2 - target_f2).abs().mean()
        loss.backward()
        optim.step()
        losses.append(loss.item())

    # Each subsequent step should not increase loss; final should be lower.
    assert losses[-1] < losses[0] * 0.99, (
        f"loss did not decrease over 5 steps: {losses}. "
        f"Optimization signal is broken."
    )


def test_film_layer_dimensions_match_quantizr() -> None:
    """pose_mlp: Linear(6, 48) -> SiLU -> Linear(48, 48), exact match
    to Quantizr's `compress.py:204-205`.

    Wrong dims here = silent architectural drift like our prior
    pose_dim=6 (no MLP expansion) bug.
    """
    model = build_quantizr_faithful_renderer()
    seq = model.pose_mlp
    # Should be Sequential(Linear, SiLU, Linear)
    children = list(seq.children())
    assert len(children) == 3, f"expected 3-layer pose_mlp, got {len(children)}"
    l0, act, l1 = children
    assert isinstance(l0, nn.Linear), type(l0)
    assert isinstance(act, nn.SiLU), type(act)
    assert isinstance(l1, nn.Linear), type(l1)
    assert l0.in_features == 6 and l0.out_features == 48, (
        f"pose_mlp[0] expected Linear(6, 48), got "
        f"Linear({l0.in_features}, {l0.out_features})"
    )
    assert l1.in_features == 48 and l1.out_features == 48, (
        f"pose_mlp[2] expected Linear(48, 48), got "
        f"Linear({l1.in_features}, {l1.out_features})"
    )

    # And verify the FiLM projection inside frame1_head consumes 48-dim
    # cond_emb and produces 2*in_ch (= 2*56 = 112) features.
    film = model.frame1_head.block1.film_proj
    assert isinstance(film, nn.Linear)
    assert film.in_features == 48, (
        f"FiLM input dim should be cond_dim=48, got {film.in_features}"
    )
    assert film.out_features == 56 * 2, (
        f"FiLM output dim should be 2*in_ch = 112, got {film.out_features}"
    )


# ────────────────────────────────────────────────────────────────────────────
# Sub-module sanity (the building blocks are individually correct)
# ────────────────────────────────────────────────────────────────────────────


def test_make_coord_grid_layout_matches_quantizr() -> None:
    """make_coord_grid returns (B, 2, H, W) in [-1, 1] (xx, yy)."""
    grid = make_coord_grid(3, 384, 512, "cpu", torch.float32)
    assert grid.shape == (3, 2, 384, 512), grid.shape
    # Should span [-1, 1] in both axes (within the +0.5 cell-center offset)
    xx, yy = grid[0, 0], grid[0, 1]
    assert -1.0 <= xx.min().item() < -0.99
    assert 0.99 < xx.max().item() <= 1.0
    assert -1.0 <= yy.min().item() < -0.99
    assert 0.99 < yy.max().item() <= 1.0


def test_film_block_modulates_proportional_to_cond() -> None:
    """Smoke: FiLMSepResBlock output magnitude scales when cond is large."""
    block = FiLMSepResBlock(ch=8, cond_dim=4, depth_mult=1).eval()
    x = torch.randn(2, 8, 16, 16)
    cond_zero = torch.zeros(2, 4)
    cond_big = torch.randn(2, 4) * 10.0
    with torch.no_grad():
        y_zero = block(x, cond_zero)
        y_big = block(x, cond_big)
    # Both should differ — even cond_zero produces a non-zero film_proj.bias
    # contribution. The point is they aren't IDENTICAL.
    assert (y_zero - y_big).abs().max().item() > 0.0


def test_frame2_static_head_stable_under_input_perturbation() -> None:
    """Sanity that the frame2 head returns finite, in-range output."""
    head = Frame2StaticHead(in_ch=56, hidden=52, depth_mult=1).eval()
    feat = torch.randn(2, 56, 384, 512)
    with torch.no_grad():
        out = head(feat)
    assert out.shape == (2, 3, 384, 512)
    assert torch.isfinite(out).all()
    assert 0.0 <= out.min().item() and out.max().item() <= 255.0


# ────────────────────────────────────────────────────────────────────────────
# Builder smoke
# ────────────────────────────────────────────────────────────────────────────


def test_builder_returns_jointframegenerator() -> None:
    model = build_quantizr_faithful_renderer()
    assert isinstance(model, JointFrameGenerator)
    # default cond_dim=48, pose_dim=6, num_classes=5
    assert model.cond_dim == 48
    assert model.pose_dim == 6
    assert model.num_classes == 5
    # FrameHead alias matches FiLMFrameHead
    assert FrameHead is FiLMFrameHead


if __name__ == "__main__":
    pytest.main([__file__, "-v"])
