#!/usr/bin/env python3
"""Build a consolidated release surface for the PR103 AC hidden-gem candidate.

The source artifact was intentionally local-only: archive/report at the root,
runtime files under ``runtime/``.  Exact-readiness tooling needs one directory
containing the scored archive, executable inflate wrapper, report, and a
candidate-first archive manifest.  This builder performs only that custody
consolidation; it does not run scorers or claim a score.
"""

from __future__ import annotations

import argparse
import os
import shutil
import stat
from pathlib import Path
from typing import Any, Mapping

try:
    from tools.tool_bootstrap import ensure_repo_imports, repo_root_from_tool
except ModuleNotFoundError:  # pragma: no cover
    from tool_bootstrap import ensure_repo_imports, repo_root_from_tool

REPO_ROOT = repo_root_from_tool(__file__)
ensure_repo_imports(REPO_ROOT)

from tac.repo_io import json_text, read_json, repo_relative, sha256_file, write_json  # noqa: E402

TOOL_NAME = "tools/build_pr103_hidden_gem_release_surface.py"
SCHEMA = "pr103_hidden_gem_release_surface_manifest_v1"
DEFAULT_SOURCE_DIR = Path("experiments/results/hnerv_hidden_gem_pr103_ac_candidate_20260510_agent")
FALSE_AUTHORITY = {
    "score_claim": False,
    "ready_for_exact_eval_dispatch": False,
    "dispatch_attempted": False,
    "exact_auth_eval_performed": False,
    "contest_cuda_auth_eval": False,
}


class HiddenGemReleaseSurfaceError(ValueError):
    """Raised when the hidden-gem release surface cannot be built safely."""


def _repo_path(path: Path) -> Path:
    return path if path.is_absolute() else REPO_ROOT / path


def _repo_rel(path: Path) -> str:
    return repo_relative(_repo_path(path), REPO_ROOT)


def _require_mapping(value: Any, field: str) -> Mapping[str, Any]:
    if not isinstance(value, Mapping):
        raise HiddenGemReleaseSurfaceError(f"{field} must be a JSON object")
    return value


def _file_record(path: Path, *, relpath: str) -> dict[str, Any]:
    return {
        "path": relpath,
        "bytes": path.stat().st_size,
        "sha256": sha256_file(path),
        "mode": f"{stat.S_IMODE(path.stat().st_mode):04o}",
    }


def _copy_file(src: Path, dst: Path, *, executable: bool = False) -> None:
    dst.parent.mkdir(parents=True, exist_ok=True)
    shutil.copyfile(src, dst)
    os.chmod(dst, 0o755 if executable else 0o644)


def _write_portable_inflate_wrapper(path: Path) -> None:
    path.write_text(
        """#!/usr/bin/env bash
# Generated by tools/build_pr103_hidden_gem_release_surface.py.
# Self-contained contest wrapper: no repo-root or virtualenv path assumptions.
set -euo pipefail

HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DATA_DIR="${1:?archive data dir required}"
OUTPUT_DIR="${2:?output dir required}"
FILE_LIST="${3:?file list required}"

if [ -n "${PYTHON:-}" ]; then
  PYBIN="$PYTHON"
elif command -v python >/dev/null 2>&1; then
  PYBIN="python"
else
  PYBIN="python3"
fi

"$PYBIN" "$HERE/inflate.py" --dependency-check
mkdir -p "$OUTPUT_DIR"

while IFS= read -r line; do
  [ -z "$line" ] && continue
  BASE="${line%.*}"
  BASE_BIN="${DATA_DIR}/${BASE}.bin"
  X_MEMBER="${DATA_DIR}/x"

  if [ -f "$BASE_BIN" ] && [ -f "$X_MEMBER" ]; then
    echo "FATAL: ambiguous PR103-ac payload members; both ${BASE_BIN} and ${X_MEMBER} exist" >&2
    exit 5
  fi
  if [ -f "$BASE_BIN" ]; then
    SRC="$BASE_BIN"
  elif [ -f "$X_MEMBER" ]; then
    SRC="$X_MEMBER"
  else
    echo "FATAL: neither ${BASE_BIN} nor ${X_MEMBER} exists" >&2
    exit 3
  fi

  DST="${OUTPUT_DIR}/${BASE}.raw"
  echo "[pr103-ac-hidden-gem] inflating ${SRC} -> ${DST}"
  "$PYBIN" "$HERE/inflate.py" "$SRC" "$DST"
done < "$FILE_LIST"
""",
        encoding="utf-8",
    )
    os.chmod(path, 0o755)


def build_release_surface(
    *,
    source_dir: Path = DEFAULT_SOURCE_DIR,
    output_dir: Path | None = None,
    force: bool = False,
) -> dict[str, Any]:
    source_dir = _repo_path(source_dir)
    output_dir = _repo_path(output_dir) if output_dir is not None else source_dir / "release_surface"
    manifest_path = source_dir / "manifest.json"
    if not manifest_path.is_file():
        raise FileNotFoundError(f"source manifest missing: {manifest_path}")
    source_manifest = _require_mapping(read_json(manifest_path), "manifest")
    candidate_archive = _require_mapping(source_manifest.get("candidate_archive"), "candidate_archive")
    source_archive = _require_mapping(source_manifest.get("source_archive"), "source_archive")
    candidate_id = source_manifest.get("candidate_id")
    if not isinstance(candidate_id, str) or not candidate_id:
        raise HiddenGemReleaseSurfaceError("candidate_id missing")
    for field, expected in FALSE_AUTHORITY.items():
        if source_manifest.get(field, False) is not expected:
            raise HiddenGemReleaseSurfaceError(f"{field} must be {expected!r}")

    if output_dir.exists() and any(output_dir.iterdir()):
        if not force:
            raise HiddenGemReleaseSurfaceError(f"output exists; pass --force: {output_dir}")
        shutil.rmtree(output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    archive_src = _repo_path(Path(str(candidate_archive["path"])))
    report_src = source_dir / "report.txt"
    runtime_dir = source_dir / "runtime"
    for required in (archive_src, report_src, runtime_dir / "inflate.sh", runtime_dir / "inflate.py"):
        if not required.exists():
            raise FileNotFoundError(f"required source missing: {required}")

    _copy_file(archive_src, output_dir / "archive.zip")
    _copy_file(report_src, output_dir / "report.txt")
    _copy_file(runtime_dir / "inflate.py", output_dir / "inflate.py")
    _write_portable_inflate_wrapper(output_dir / "inflate.sh")

    archive_dst = output_dir / "archive.zip"
    if sha256_file(archive_dst) != candidate_archive.get("archive_sha256"):
        raise HiddenGemReleaseSurfaceError("copied archive SHA mismatch")

    manifest = {
        "schema": SCHEMA,
        "tool": TOOL_NAME,
        "candidate_id": candidate_id,
        "lane_id": "pr103_ac_hidden_gem",
        "source_manifest": _repo_rel(manifest_path),
        "source_runtime_dir": _repo_rel(runtime_dir),
        "submission_dir": _repo_rel(output_dir),
        "score_claim": False,
        "ready_for_exact_eval_dispatch": False,
        "dispatch_attempted": False,
        "exact_auth_eval_performed": False,
        "contest_cuda_auth_eval": False,
        "score_affecting_payload_changed": True,
        "charged_bits_changed": True,
        "candidate_archive": {
            **dict(candidate_archive),
            "path": "archive.zip",
        },
        "source_archive": dict(source_archive),
        "charged_byte_proof": source_manifest.get("charged_byte_proof"),
        "section_sha256_proof": source_manifest.get("section_sha256_proof"),
        "runtime_consumption_no_op_proof": source_manifest.get("runtime_consumption_no_op_proof"),
        "files": {
            "archive": _file_record(output_dir / "archive.zip", relpath="archive.zip"),
            "inflate_sh": _file_record(output_dir / "inflate.sh", relpath="inflate.sh"),
            "inflate_py": _file_record(output_dir / "inflate.py", relpath="inflate.py"),
            "report": _file_record(output_dir / "report.txt", relpath="report.txt"),
        },
        "remaining_for_score_or_dispatch": [
            "active_level2_lane_dispatch_claim",
            "exact_cuda_auth_eval",
            "contest_auth_eval_adjudication",
            "operator_score_claim_review",
        ],
    }
    write_json(output_dir / "archive_manifest.json", manifest)
    return manifest


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--source-dir", type=Path, default=DEFAULT_SOURCE_DIR)
    parser.add_argument("--output-dir", type=Path, default=None)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> int:
    args = parse_args(argv)
    manifest = build_release_surface(
        source_dir=args.source_dir,
        output_dir=args.output_dir,
        force=args.force,
    )
    print(json_text({
        "schema": "pr103_hidden_gem_release_surface_stdout_v1",
        "candidate_id": manifest["candidate_id"],
        "submission_dir": manifest["submission_dir"],
        "archive_sha256": manifest["candidate_archive"]["archive_sha256"],
        "archive_bytes": manifest["candidate_archive"]["archive_bytes"],
        "score_claim": False,
        "ready_for_exact_eval_dispatch": False,
    }), end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
