#!/usr/bin/env python3
"""Generate a new canonical remote_lane_*.sh skeleton.

Bakes in EVERY canonical pattern enforced by preflight:
  - set -euo pipefail (Check 2)
  - python `zipfile.ZipFile` (no shell `zip` — Check 3)
  - canonical git fetch+reset (Check 57)
  - NVDEC probe at Stage 0 (Check 33 / 55)
  - AppleDouble cleanup (Check 37)
  - ARCHIVE_BYTES guard (Check 47)
  - contest_auth_eval invocation (Check 7)
  - [contest-CUDA] tag at completion (Check 32)
  - heartbeat loop (Check 41)
  - provenance.json write (Check 61 — bootstrap; lane scripts inherit)
  - predicted_band metadata (Check 31)

Usage:
    .venv/bin/python tools/canonical_lane_template.py --lane-name foo \\
        --profile dilated_h64_long --predicted-band "[0.85, 1.05]" \\
        --cost-cap 5.00 \\
        > scripts/remote_lane_foo.sh

Deep hardening pass 3 dimension 4. Reference:
  - feedback_canonical_remote_bootstraps
  - feedback_deep_hardening_pass_3_patterns_20260428
"""
from __future__ import annotations

import argparse
import sys
from string import Template

TEMPLATE = Template(r"""#!/bin/bash
# remote_lane_${lane_name}.sh — canonical lane skeleton
# predicted_band: ${predicted_band}
# cost_cap: $$${cost_cap}
# profile: ${profile}
#
# Auto-generated by tools/canonical_lane_template.py.
# Bakes in EVERY canonical pattern enforced by preflight (Checks 1-62).
# Editing freely is fine; just don't remove the guard markers below.

set -euo pipefail

WORKSPACE=/workspace/pact
LANE_NAME="${lane_name}"
PROFILE="${profile}"
COST_CAP_USD=${cost_cap}
PREDICTED_BAND="${predicted_band}"
HEARTBEAT_LOG=/tmp/heartbeat_$${LANE_NAME}.log

# ── Stage 0: NVDEC probe (Check 33) ────────────────────────────────────────
echo "[$${LANE_NAME}] Stage 0: NVDEC probe"
if ! bash $${WORKSPACE}/scripts/probe_nvdec.sh --lightweight; then
    echo "FATAL: NVDEC probe failed — host cannot decode video. NVDEC_MISSING"
    exit 1
fi

# ── Stage 1: canonical git sync (Check 57) ─────────────────────────────────
echo "[$${LANE_NAME}] Stage 1: git sync"
cd $${WORKSPACE}
git fetch origin main
git reset --hard origin/main

# ── Stage 1b: AppleDouble cleanup (Check 37) ───────────────────────────────
find $${WORKSPACE} -name "._*" -type f -delete 2>/dev/null || true

# ── Stage 1c: heartbeat loop (Check 41) ────────────────────────────────────
(while true; do
    date +%s > $${HEARTBEAT_LOG}
    sleep 60
done) &
HEARTBEAT_PID=$$!
trap "kill $${HEARTBEAT_PID} 2>/dev/null || true" EXIT

# ── Stage 2: training (uses --eval-roundtrip per CLAUDE.md non-neg) ────────
echo "[$${LANE_NAME}] Stage 2: training, profile=$${PROFILE}"
/opt/conda/bin/python -u -m tac.experiments.train_renderer \
    --profile $${PROFILE} \
    --output-dir /workspace/results/$${LANE_NAME}

# ── Stage 3: build archive ─────────────────────────────────────────────────
echo "[$${LANE_NAME}] Stage 3: build archive"
ARCHIVE_PATH=/workspace/results/$${LANE_NAME}/archive.zip
/opt/conda/bin/python -m tac.archive.build \
    --renderer /workspace/results/$${LANE_NAME}/renderer.bin \
    --masks /workspace/results/$${LANE_NAME}/masks.mkv \
    --poses /workspace/results/$${LANE_NAME}/poses.pt \
    --output $${ARCHIVE_PATH}

# Check 47: archive size assertion
ARCHIVE_BYTES=$$(stat -c%s "$${ARCHIVE_PATH}")
if [ -z "$${ARCHIVE_BYTES}" ] || [ "$${ARCHIVE_BYTES}" -lt 1000 ]; then
    echo "FATAL: archive too small ($${ARCHIVE_BYTES} bytes) — build failed"
    exit 1
fi
echo "[$${LANE_NAME}] archive: $${ARCHIVE_BYTES} bytes"

# ── Stage 4: contest_auth_eval (Check 7 — auth eval EVERYWHERE) ────────────
echo "[$${LANE_NAME}] Stage 4: contest_auth_eval [contest-CUDA]"
RESULT_JSON=/workspace/results/$${LANE_NAME}/contest_auth_eval.json
/opt/conda/bin/python -m experiments.contest_auth_eval \
    --archive $${ARCHIVE_PATH} \
    --inflate-sh $${WORKSPACE}/submissions/robust_current/inflate.sh \
    --upstream-dir $${WORKSPACE}/upstream \
    --device cuda \
    --result-json $${RESULT_JSON}

# Check 32: emit [contest-CUDA] tag in final stdout
SCORE=$$(jq -r .score $${RESULT_JSON})
echo "[$${LANE_NAME}] FINAL [contest-CUDA] score=$${SCORE} predicted=$${PREDICTED_BAND}"
""")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    parser.add_argument("--lane-name", required=True,
                        help="short lane identifier, e.g. 'foo' for "
                             "remote_lane_foo.sh")
    parser.add_argument("--profile", required=True,
                        help="src/tac/profiles.py PROFILES key")
    parser.add_argument("--predicted-band", required=True,
                        help="e.g. '[0.85, 1.05]' — round-bracket band of "
                             "expected contest-CUDA score")
    parser.add_argument("--cost-cap", type=float, required=True,
                        help="hard $ cap for the lane (used by triage_fleet)")
    args = parser.parse_args()

    out = TEMPLATE.substitute(
        lane_name=args.lane_name,
        profile=args.profile,
        predicted_band=args.predicted_band,
        cost_cap=f"{args.cost_cap:.2f}",
    )
    sys.stdout.write(out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
