#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
"""Cluster-summarize a memory category into a 1-paragraph compressed memo.

Per CLAUDE.md "Memory file rotation discipline" non-negotiable: every 90
days, group feedback memos by topic (substrate-bug-class / META-meta-gate /
strategic-deliberation / operator-decision) and produce a single
`MEMORY_CLUSTER_<category>_<YYYYQQ>.md` that compresses the cluster's
learnings into 2-3 paragraphs. The detail stays in originals; the cluster
is the new top-of-mind summary.

Premortem #6 anchor (`.omx/research/12_month_frustration_premortem_and_
recommendations_20260516.md` Category D + Section 3 #6).

This tool does NOT auto-summarize semantically (that's an LLM call); it
prepares the cluster manifest — a deterministic listing of files in the
category, their headlines, sizes, dates — and writes a SKELETON cluster
memo that the operator (or an LLM-using subagent) fills in.

Usage:
    # Preview the cluster manifest for `feedback_grand_council_*`:
    .venv/bin/python tools/cluster_summarize_memory_category.py \\
        --category feedback_grand_council_

    # Write the skeleton cluster memo:
    .venv/bin/python tools/cluster_summarize_memory_category.py \\
        --category feedback_grand_council_ \\
        --write-skeleton \\
        --quarter 2026Q2

    # Quarter defaults to current quarter from today's date.
"""
from __future__ import annotations

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_MEMORY_DIR = (
    Path.home() / ".claude" / "projects"
    / "-Users-adpena-Projects-pact" / "memory"
)


def _current_quarter(now: datetime | None = None) -> str:
    now = now or datetime.now(timezone.utc)
    q = (now.month - 1) // 3 + 1
    return f"{now.year}Q{q}"


def _extract_headline(path: Path) -> str:
    """Return the first non-empty header (line starting with `#`) or
    the first non-empty line."""
    try:
        text = path.read_text(encoding="utf-8", errors="replace")
    except OSError:
        return ""
    for line in text.splitlines():
        stripped = line.strip()
        if stripped.startswith("#"):
            return stripped.lstrip("#").strip()[:120]
    for line in text.splitlines():
        stripped = line.strip()
        if stripped:
            return stripped[:120]
    return ""


def build_cluster_manifest(
    memory_dir: Path,
    category: str,
) -> dict:
    """Build a deterministic manifest of files matching `category`
    prefix or glob."""
    if not memory_dir.is_dir():
        return {
            "memory_dir": str(memory_dir),
            "category": category,
            "error": f"memory_dir does not exist: {memory_dir}",
            "files": [],
        }

    # `category` is a prefix glob; honor literal `*` if user passed it.
    if "*" in category:
        pattern = category if category.endswith(".md") else category + "*.md"
    else:
        pattern = category + "*.md"

    files = sorted(memory_dir.glob(pattern))
    file_entries = []
    for p in files:
        try:
            stat = p.stat()
        except OSError:
            continue
        entry = {
            "filename": p.name,
            "size_bytes": stat.st_size,
            "mtime_iso": datetime.fromtimestamp(
                stat.st_mtime, tz=timezone.utc
            ).isoformat(),
            "headline": _extract_headline(p),
        }
        file_entries.append(entry)

    return {
        "memory_dir": str(memory_dir),
        "category": category,
        "pattern": pattern,
        "file_count": len(file_entries),
        "total_bytes": sum(e["size_bytes"] for e in file_entries),
        "files": file_entries,
    }


def write_cluster_skeleton(
    manifest: dict,
    quarter: str,
    *,
    repo_root: Path | None = None,
) -> Path:
    """Write a skeleton MEMORY_CLUSTER_<category>_<quarter>.md memo."""
    repo = repo_root or Path(__file__).resolve().parent.parent
    out_dir = repo / ".omx" / "research"
    out_dir.mkdir(parents=True, exist_ok=True)
    cat_slug = manifest["category"].rstrip("_*").strip("_") or "uncategorized"
    out_path = out_dir / f"MEMORY_CLUSTER_{cat_slug}_{quarter}.md"

    lines = [
        f"# MEMORY_CLUSTER: {cat_slug} — {quarter}",
        "",
        f"**Generated by:** `tools/cluster_summarize_memory_category.py`",
        f"**Memory dir:** `{manifest['memory_dir']}`",
        f"**Category pattern:** `{manifest['pattern']}`",
        f"**File count:** {manifest['file_count']}",
        f"**Total bytes:** {manifest['total_bytes']:,}",
        "",
        "## Cluster summary (FILL IN — 2-3 paragraphs)",
        "",
        "[Operator or LLM-using subagent: write 2-3 paragraphs compressing",
        "the learnings across the files below. Cite specific files by name.",
        "The detail stays in the originals; this paragraph is the new",
        "top-of-mind summary that replaces N individual MEMORY.md index",
        "entries.]",
        "",
        "## Files in this cluster",
        "",
    ]
    for entry in sorted(manifest["files"], key=lambda e: e["mtime_iso"]):
        ts = entry["mtime_iso"][:10]
        lines.append(
            f"- `{entry['filename']}` ({ts}, "
            f"{entry['size_bytes']:,} bytes) — {entry['headline']}"
        )
    lines.append("")
    lines.append("## Action")
    lines.append("")
    lines.append(
        "Once this cluster summary is written, the MEMORY.md index "
        "entries for the constituent files can be replaced by a single "
        "index line pointing to THIS cluster memo. Originals remain on "
        "disk for grep / forensic search; the index gets the compressed "
        "summary."
    )
    lines.append("")
    out_path.write_text("\n".join(lines), encoding="utf-8")
    return out_path


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--category", type=str, required=True,
        help="Filename prefix (e.g. `feedback_grand_council_`) or glob",
    )
    parser.add_argument(
        "--memory-dir", type=Path, default=DEFAULT_MEMORY_DIR,
    )
    parser.add_argument(
        "--quarter", type=str, default=None,
        help="Quarter slug (e.g. `2026Q2`). Default: current quarter.",
    )
    parser.add_argument(
        "--write-skeleton", action="store_true",
        help="Write the .omx/research/MEMORY_CLUSTER_<>_<>.md skeleton",
    )
    parser.add_argument(
        "--json", action="store_true",
        help="Emit JSON manifest instead of human-readable preview",
    )
    args = parser.parse_args()

    manifest = build_cluster_manifest(args.memory_dir, args.category)
    if args.json:
        print(json.dumps(manifest, indent=2))
    else:
        print(f"Category: {manifest['category']}")
        print(f"Pattern:  {manifest['pattern']}")
        print(f"Files:    {manifest['file_count']}")
        print(f"Total:    {manifest['total_bytes']:,} bytes")
        print()
        for entry in sorted(
            manifest["files"], key=lambda e: e["mtime_iso"]
        )[:25]:
            ts = entry["mtime_iso"][:10]
            print(
                f"  {ts}  {entry['size_bytes']:>8,}b  {entry['filename']}"
            )
        if manifest["file_count"] > 25:
            print(f"  ... +{manifest['file_count'] - 25} more")

    if args.write_skeleton:
        quarter = args.quarter or _current_quarter()
        out_path = write_cluster_skeleton(manifest, quarter)
        print(f"\nSkeleton cluster memo written: {out_path}")
        print(
            "Fill in the `## Cluster summary` section, then update "
            "MEMORY.md to replace the N constituent index entries with "
            "a single pointer to this cluster memo."
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
