#!/usr/bin/env python3
"""Operator briefing: runs the dispatch trio in sequence — one command, full state.

Phases:
  1. Pre-dispatch (Pareto frontier + dispatch one-liners per non-dominated bits)
  2. Post-dispatch general (sorted view of every contest_auth_eval.json on disk)
  3. Post-dispatch apogee_intN (predicted-vs-actual reconciliation)

Use cases:
  - Start of session: see what's ready to dispatch + what's already landed
  - After a dispatch lands: see the new score in dashboard + reconciler verdict
  - Quick "where am I?" between deep work blocks

Usage:
  .venv/bin/python tools/operator_briefing.py                   # all 3 phases
  .venv/bin/python tools/operator_briefing.py --top 10           # cap dashboard rows
  .venv/bin/python tools/operator_briefing.py --skip-pareto      # only dashboard + reconciler
  .venv/bin/python tools/operator_briefing.py --json             # machine-readable composite
"""
from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
TOOLS = REPO_ROOT / "tools"

PARETO = TOOLS / "apogee_intN_pareto.py"
DASHBOARD = TOOLS / "score_dashboard.py"
RECONCILER = TOOLS / "predicted_vs_actual_reconciler.py"


# Phase-1 supplementary lanes: pre-registered dispatches that don't fit the
# apogee_intN Pareto matrix but are operator-launchable now. Each entry is
# (lane_id, predicted_band, estimated_cost, council_priority, one-liner).
PHASE_1_SUPPLEMENTARY_LANES = [
    {
        "lane_id": "lane_pr106_latent_sidecar",
        "name": "PR106 + per-pair latent-correction sidecar (PR100 hnerv_lc_v2 pattern)",
        "predicted_band": (0.205, 0.208),
        "estimated_cost_usd": 0.60,
        "council_priority": 1,
        "max_dph": 0.30,
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_latent_sidecar.sh \\\n"
            "  --label lane_pr106_latent_sidecar \\\n"
            "  --predicted-band 0.205 0.208 \\\n"
            "  --estimated-cost 0.60 --council-priority 1 --max-dph 0.30"
        ),
    },
]


# Phase-1 exact-eval packets: candidates that have already passed local static
# custody checks and are waiting on an exact CUDA submit environment. The packet
# JSON is the command authority so operator briefing cannot drift from the
# claim/submit/harvest commands generated by the packet builder.
PHASE_1_EXACT_EVAL_PACKETS = [
    {
        "lane_id": "wr01_apply_pr106x_half",
        "name": "WR01 half-strength HNeRV latent-sidecar transform on PR106x",
        "packet_path": (
            "experiments/results/hnerv_wavelet_apply_transform_pr106x_1_2_20260506_codex/"
            "wr01_exact_eval_packet.json"
        ),
    },
]


# Phase-4 gated lanes: pre-registered dispatches that REQUIRE a prior empirical
# result before launch. Per docs/INDEX_score_aware_sidechannel_thread_20260504.md
# decision pipeline, sequential validation prevents wasting GPU spend on
# stacking lanes that interact unexpectedly. Each entry adds a `gate_condition`
# string operator must satisfy before running the one-liner.
PHASE_4_GATED_LANES = [
    {
        "lane_id": "lane_pr106_yshift_sidechannel",
        "name": "PR106 + per-frame Y-shift sidechannel (codex_metric_yshift SC01 mode-7 pattern)",
        "predicted_band": (0.2065, 0.2080),
        "estimated_cost_usd": 0.40,
        "council_priority": 2,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_latent_sidecar lands < 0.20800 "
            "[contest-CUDA] (per docs/INDEX_score_aware_sidechannel_thread_20260504.md "
            "TICK 2). Verify via: `tools/score_dashboard.py --filter pr106_latent_sidecar`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_yshift_sidechannel.sh \\\n"
            "  --label lane_pr106_yshift_sidechannel \\\n"
            "  --predicted-band 0.2065 0.2080 \\\n"
            "  --estimated-cost 0.40 --council-priority 2 --max-dph 0.30 \\\n"
            "  --env PR106_YSHIFT_MODE=brute_force"
        ),
    },
    {
        "lane_id": "lane_pr106_lrl1_sidechannel",
        "name": "PR106 + per-frame LRL1 luma low-rank correction (codex_metric LRL1 mode-8 pattern, variant #6)",
        "predicted_band": (0.2050, 0.2065),
        "estimated_cost_usd": 0.50,
        "council_priority": 3,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_yshift_sidechannel lands < 0.20650 [contest-CUDA] "
            "(per docs/INDEX_score_aware_sidechannel_thread_20260504.md TICK 3 — 3rd "
            "stack-on after both variants #1 latent_sidecar AND #3 yshift land empirically). "
            "Verify via: `tools/score_dashboard.py --filter pr106_yshift_sidechannel`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_lrl1_sidechannel.sh \\\n"
            "  --label lane_pr106_lrl1_sidechannel \\\n"
            "  --predicted-band 0.2050 0.2065 \\\n"
            "  --estimated-cost 0.50 --council-priority 3 --max-dph 0.30 \\\n"
            "  --env PR106_LRL1_MODE=brute_force --env PR106_LRL1_K=4"
        ),
    },
]


# Phase-5 composition lanes: meta-composition lanes that compose multiple
# pre-built sister-lane archives into a single dispatch. Gated on ALL the
# sister single-sidechannel lanes landing empirically. Per the score-aware
# sidechannel paradigm decision pipeline, composition lanes are the
# single-dispatch payoff after the sister gates pass.
PHASE_5_COMPOSITION_LANES = [
    {
        "lane_id": "lane_pr106_stacked",
        "name": "PR106 + meta-composition of all 3 score-aware sidechannels (latent + yshift + lrl1)",
        "predicted_band": (0.16, 0.20),
        "estimated_cost_usd": 0.40,
        "council_priority": 4,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_lrl1_sidechannel + sisters all land < 0.20800 "
            "[contest-CUDA] empirically. Per tools/sidechannel_stack_predictor.py "
            "--bits 5 --all, the int4+full-stack predicted score is 0.163 "
            "(-0.046 vs PR106 0.20945). Composition lane is the single-dispatch "
            "payoff of all 3 sister lanes — verify via "
            "`tools/score_dashboard.py --filter pr106_lrl1_sidechannel`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_stacked.sh \\\n"
            "  --label lane_pr106_stacked \\\n"
            "  --predicted-band 0.16 0.20 \\\n"
            "  --estimated-cost 0.40 --council-priority 4 --max-dph 0.30 \\\n"
            "  --env STACKED_LATENT_ARCHIVE=<path/to/sister_latent_archive.zip> \\\n"
            "  --env STACKED_YSHIFT_ARCHIVE=<path/to/sister_yshift_archive.zip> \\\n"
            "  --env STACKED_LRL1_ARCHIVE=<path/to/sister_lrl1_archive.zip>"
        ),
    },
]


def _format_supplementary_lanes() -> str:
    lines = []
    for lane in PHASE_1_SUPPLEMENTARY_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    Operator one-liner:\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _load_exact_eval_packet(lane: dict) -> dict[str, object]:
    path = REPO_ROOT / str(lane["packet_path"])
    if not path.is_file():
        return {
            "lane_id": lane["lane_id"],
            "name": lane["name"],
            "packet_path": lane["packet_path"],
            "ready_for_submit": False,
            "blockers": ["missing_packet_json"],
            "missing_env": [],
            "archive_sha256": None,
            "archive_bytes": None,
            "commands": {},
        }
    try:
        packet = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {
            "lane_id": lane["lane_id"],
            "name": lane["name"],
            "packet_path": lane["packet_path"],
            "ready_for_submit": False,
            "blockers": [f"malformed_packet_json:{exc.msg}"],
            "missing_env": [],
            "archive_sha256": None,
            "archive_bytes": None,
            "commands": {},
        }
    return {
        "lane_id": lane["lane_id"],
        "name": lane["name"],
        "packet_path": lane["packet_path"],
        "ready_for_submit": bool(packet.get("ready_for_submit")),
        "blockers": list(packet.get("blockers") or []),
        "missing_env": list(packet.get("missing_env") or []),
        "archive_sha256": packet.get("archive_sha256"),
        "archive_bytes": packet.get("archive_bytes"),
        "preflight_ready": bool(packet.get("preflight_ready")),
        "compliance_ok": bool(packet.get("compliance_ok")),
        "payload_diff_ready": bool(packet.get("payload_diff_ready")),
        "dry_run_ready": bool(packet.get("dry_run_ready")),
        "commands": dict(packet.get("commands") or {}),
    }


def _exact_eval_packet_summaries() -> list[dict[str, object]]:
    return [_load_exact_eval_packet(lane) for lane in PHASE_1_EXACT_EVAL_PACKETS]


def _format_exact_eval_packets() -> str:
    lines = []
    for packet in _exact_eval_packet_summaries():
        commands = packet.get("commands") or {}
        blockers = packet.get("blockers") or []
        missing_env = packet.get("missing_env") or []
        state = "READY" if packet.get("ready_for_submit") else "BLOCKED"
        lines.append(
            f"  • {packet['lane_id']} — {packet['name']}\n"
            f"    state {state}   bytes {packet.get('archive_bytes')}   "
            f"sha256 {packet.get('archive_sha256')}\n"
            f"    static gates: preflight={packet.get('preflight_ready')} "
            f"compliance={packet.get('compliance_ok')} "
            f"payload_diff={packet.get('payload_diff_ready')} "
            f"dry_run={packet.get('dry_run_ready')}\n"
            f"    blockers: {', '.join(blockers) if blockers else '(none)'}\n"
            f"    missing env: {', '.join(missing_env) if missing_env else '(none)'}\n"
            f"    packet: {packet['packet_path']}\n"
            f"    Claim:\n"
            f"      {commands.get('claim', '(missing)')}\n"
            f"    Submit:\n"
            f"      {commands.get('submit', '(missing)')}\n"
            f"    Harvest:\n"
            f"      {commands.get('harvest', '(missing)')}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _format_gated_lanes() -> str:
    lines = []
    for lane in PHASE_4_GATED_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    GATE: {lane['gate_condition']}\n"
            f"    Operator one-liner (post-gate):\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _format_composition_lanes() -> str:
    lines = []
    for lane in PHASE_5_COMPOSITION_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    GATE: {lane['gate_condition']}\n"
            f"    Operator one-liner (post-gate):\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _run(script: Path, extra_args: list[str] | None = None) -> str:
    args = [sys.executable, str(script)]
    if extra_args:
        args.extend(extra_args)
    proc = subprocess.run(args, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        return (
            f"(tool exited with code {proc.returncode}; stderr: "
            f"{proc.stderr.strip()[:200]})"
        )
    return proc.stdout


def _run_json(script: Path, extra_args: list[str] | None = None) -> dict:
    text = _run(script, (extra_args or []) + ["--json"])
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {"_error": "non-JSON output", "_stdout": text[:500]}


def _section(title: str, body: str) -> str:
    bar = "═" * len(title)
    return f"\n{bar}\n{title}\n{bar}\n\n{body}"


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=20,
                        help="Cap dashboard rows (default: 20).")
    parser.add_argument("--skip-pareto", action="store_true",
                        help="Skip Phase 1 (Pareto pre-dispatch matrix).")
    parser.add_argument("--skip-dashboard", action="store_true",
                        help="Skip Phase 2 (general score dashboard).")
    parser.add_argument("--skip-reconciler", action="store_true",
                        help="Skip Phase 3 (apogee_intN predicted-vs-actual).")
    parser.add_argument("--skip-gated", action="store_true",
                        help="Skip Phase 4 (gated next-tick lanes).")
    parser.add_argument("--skip-composition", action="store_true",
                        help="Skip Phase 5 (meta-composition lanes).")
    parser.add_argument("--json", action="store_true",
                        help="Machine-readable composite JSON output.")
    args = parser.parse_args(argv)

    # Verify all 3 tools exist
    for tool in (PARETO, DASHBOARD, RECONCILER):
        if not tool.is_file():
            print(f"FATAL: missing dependency tool {tool.relative_to(REPO_ROOT)}",
                  file=sys.stderr)
            return 2

    if args.json:
        out = {}
        if not args.skip_pareto:
            out["pareto"] = _run_json(PARETO)
            out["supplementary_lanes"] = PHASE_1_SUPPLEMENTARY_LANES
            out["exact_eval_packets"] = _exact_eval_packet_summaries()
        if not args.skip_dashboard:
            out["dashboard"] = _run_json(DASHBOARD, ["--top", str(args.top)])
        if not args.skip_reconciler:
            out["reconciler"] = _run_json(RECONCILER)
        if not args.skip_gated:
            out["gated_lanes"] = PHASE_4_GATED_LANES
        if not args.skip_composition:
            out["composition_lanes"] = PHASE_5_COMPOSITION_LANES
        print(json.dumps(out, indent=2, default=str))
        return 0

    # Human-readable composite
    parts: list[str] = ["OPERATOR BRIEFING — dispatch trio"]
    if not args.skip_pareto:
        parts.append(_section(
            "Phase 1 — Pre-dispatch: apogee_intN Pareto frontier",
            _run(PARETO).strip(),
        ))
        parts.append(_section(
            "Phase 1 supplementary — pre-registered non-Pareto lanes",
            _format_supplementary_lanes(),
        ))
        parts.append(_section(
            "Phase 1 exact-eval packets — static-clean CUDA candidates",
            _format_exact_eval_packets(),
        ))
    if not args.skip_dashboard:
        parts.append(_section(
            f"Phase 2 — Post-dispatch (general): top {args.top} contest scores on disk",
            _run(DASHBOARD, ["--top", str(args.top)]).strip(),
        ))
    if not args.skip_reconciler:
        parts.append(_section(
            "Phase 3 — Post-dispatch (apogee_intN): predicted-vs-actual reconciliation",
            _run(RECONCILER).strip(),
        ))
    if not args.skip_gated:
        parts.append(_section(
            "Phase 4 — Gated next-tick lanes (sequential validation)",
            _format_gated_lanes(),
        ))
    if not args.skip_composition:
        parts.append(_section(
            "Phase 5 — Meta-composition lanes (single-dispatch payoff of multi-sister stacks)",
            _format_composition_lanes(),
        ))
    print("\n".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
