#!/usr/bin/env python3
"""Operator briefing: runs the dispatch trio in sequence — one command, full state.

Phases:
  1. Pre-dispatch (Pareto frontier + dispatch one-liners per non-dominated bits)
  2. Post-dispatch general (sorted view of every contest_auth_eval.json on disk)
  3. Post-dispatch apogee_intN (predicted-vs-actual reconciliation)

Use cases:
  - Start of session: see what's ready to dispatch + what's already landed
  - After a dispatch lands: see the new score in dashboard + reconciler verdict
  - Quick "where am I?" between deep work blocks

Usage:
  .venv/bin/python tools/operator_briefing.py                   # all 3 phases
  .venv/bin/python tools/operator_briefing.py --top 10           # cap dashboard rows
  .venv/bin/python tools/operator_briefing.py --skip-pareto      # only dashboard + reconciler
  .venv/bin/python tools/operator_briefing.py --json             # machine-readable composite
"""
from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SRC_ROOT = REPO_ROOT / "src"
if str(SRC_ROOT) not in sys.path:
    sys.path.insert(0, str(SRC_ROOT))
TOOLS = REPO_ROOT / "tools"

PARETO = TOOLS / "apogee_intN_pareto.py"
DASHBOARD = TOOLS / "score_dashboard.py"
RECONCILER = TOOLS / "predicted_vs_actual_reconciler.py"
CLAIM_DISPATCH = TOOLS / "claim_lane_dispatch.py"
CLOUD_PROVIDER_READINESS = TOOLS / "cloud_provider_readiness.py"
PROVIDER_READINESS_LATEST = REPO_ROOT / "experiments/results/cloud_provider_readiness_latest.json"
PR91_HPM1_READINESS = TOOLS / "audit_pr91_hpm1_readiness.py"
PR91_HPM1_RUNTIME_CONTRACT = TOOLS / "audit_pr91_hpm1_runtime_contract.py"
PR91_HPM1_READINESS_ARTIFACT = (
    REPO_ROOT / "experiments/results/pr91_hpm1_readiness_20260506_codex/readiness.json"
)
PR91_HPM1_RUNTIME_CONTRACT_ARTIFACT = (
    REPO_ROOT / "experiments/results/pr91_hpm1_runtime_contract_20260506_codex/runtime_contract.json"
)
DISPATCH_CLAIMS = REPO_ROOT / ".omx/state/active_lane_dispatch_claims.md"
EXACT_READY_SCAN_ROOT = REPO_ROOT / "experiments" / "results"

from tac.optimizer.exact_readiness import (  # noqa: E402
    ACTIVE_FLOOR_SCORE,
    as_bool,
    is_sha256,
    terminal_claim_result_conflicts,
)
from tac.optimizer.exact_ready_audit import (  # noqa: E402
    audit_exact_ready_queues,
    discover_exact_ready_queues,
)


# Phase-1 supplementary lanes: pre-registered dispatches that don't fit the
# apogee_intN Pareto matrix but are operator-launchable now. Each entry is
# (lane_id, predicted_band, estimated_cost, council_priority, one-liner).
PHASE_1_SUPPLEMENTARY_LANES = [
    {
        "lane_id": "lane_pr106_latent_sidecar",
        "name": "PR106 + per-pair latent-correction sidecar (PR100 hnerv_lc_v2 pattern)",
        "predicted_band": (0.205, 0.208),
        "estimated_cost_usd": 0.60,
        "council_priority": 1,
        "max_dph": 0.30,
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_latent_sidecar.sh \\\n"
            "  --label lane_pr106_latent_sidecar \\\n"
            "  --predicted-band 0.205 0.208 \\\n"
            "  --estimated-cost 0.60 --council-priority 1 --max-dph 0.30"
        ),
    },
]


# Phase-1 exact-eval packets: candidates that have already passed local static
# custody checks and are waiting on an exact CUDA submit environment. The packet
# JSON is the command authority so operator briefing cannot drift from the
# claim/submit/harvest commands generated by the packet builder.
PHASE_1_EXACT_EVAL_PACKETS = [
    {
        "lane_id": "wr01_apply_pr106x_half",
        "name": "WR01 half-strength HNeRV latent-sidecar transform on PR106x",
        "packet_path": (
            "experiments/results/hnerv_wavelet_apply_transform_pr106x_1_2_20260506_codex/"
            "wr01_exact_eval_packet.json"
        ),
    },
    {
        "lane_id": "pr106_q10_151byte_brotli",
        "name": "PR106 low-level Brotli q10 151-byte rate candidate",
        "packet_path": (
            "experiments/results/hnerv_lowlevel_repack_pr106_q10_packet_20260507_codex/"
            "hnerv_lowlevel_exact_eval_packet.json"
        ),
    },
    {
        "lane_id": "pr106x_lgblock16_1byte_brotli",
        "name": "PR106x low-level Brotli lgblock16 one-byte rate candidate",
        "packet_path": (
            "experiments/results/hnerv_lowlevel_repack_pr106x_lgblock16_20260507_codex/"
            "hnerv_lowlevel_exact_eval_packet.json"
        ),
    },
]


# Phase-4 gated lanes: pre-registered dispatches that REQUIRE a prior empirical
# result before launch. Per docs/INDEX_score_aware_sidechannel_thread_20260504.md
# decision pipeline, sequential validation prevents wasting GPU spend on
# stacking lanes that interact unexpectedly. Each entry adds a `gate_condition`
# string operator must satisfy before running the one-liner.
PHASE_4_GATED_LANES = [
    {
        "lane_id": "lane_pr106_yshift_sidechannel",
        "name": "PR106 + per-frame Y-shift sidechannel (codex_metric_yshift SC01 mode-7 pattern)",
        "predicted_band": (0.2065, 0.2080),
        "estimated_cost_usd": 0.40,
        "council_priority": 2,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_latent_sidecar lands < 0.20800 "
            "[contest-CUDA] (per docs/INDEX_score_aware_sidechannel_thread_20260504.md "
            "TICK 2). Verify via: `tools/score_dashboard.py --filter pr106_latent_sidecar`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_yshift_sidechannel.sh \\\n"
            "  --label lane_pr106_yshift_sidechannel \\\n"
            "  --predicted-band 0.2065 0.2080 \\\n"
            "  --estimated-cost 0.40 --council-priority 2 --max-dph 0.30 \\\n"
            "  --env PR106_YSHIFT_MODE=brute_force"
        ),
    },
    {
        "lane_id": "lane_pr106_lrl1_sidechannel",
        "name": "PR106 + per-frame LRL1 luma low-rank correction (codex_metric LRL1 mode-8 pattern, variant #6)",
        "predicted_band": (0.2050, 0.2065),
        "estimated_cost_usd": 0.50,
        "council_priority": 3,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_yshift_sidechannel lands < 0.20650 [contest-CUDA] "
            "(per docs/INDEX_score_aware_sidechannel_thread_20260504.md TICK 3 — 3rd "
            "stack-on after both variants #1 latent_sidecar AND #3 yshift land empirically). "
            "Verify via: `tools/score_dashboard.py --filter pr106_yshift_sidechannel`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_lrl1_sidechannel.sh \\\n"
            "  --label lane_pr106_lrl1_sidechannel \\\n"
            "  --predicted-band 0.2050 0.2065 \\\n"
            "  --estimated-cost 0.50 --council-priority 3 --max-dph 0.30 \\\n"
            "  --env PR106_LRL1_MODE=brute_force --env PR106_LRL1_K=4"
        ),
    },
]


# Phase-5 composition lanes: meta-composition lanes that compose multiple
# pre-built sister-lane archives into a single dispatch. Gated on ALL the
# sister single-sidechannel lanes landing empirically. Per the score-aware
# sidechannel paradigm decision pipeline, composition lanes are the
# single-dispatch payoff after the sister gates pass.
PHASE_5_COMPOSITION_LANES = [
    {
        "lane_id": "lane_pr106_stacked",
        "name": "PR106 + meta-composition of all 3 score-aware sidechannels (latent + yshift + lrl1)",
        "predicted_band": (0.16, 0.20),
        "estimated_cost_usd": 0.40,
        "council_priority": 4,
        "max_dph": 0.30,
        "gate_condition": (
            "DISPATCH ONLY IF lane_pr106_lrl1_sidechannel + sisters all land < 0.20800 "
            "[contest-CUDA] empirically. Per tools/sidechannel_stack_predictor.py "
            "--bits 5 --all, the int4+full-stack predicted score is 0.163 "
            "(-0.046 vs PR106 0.20945). Composition lane is the single-dispatch "
            "payoff of all 3 sister lanes — verify via "
            "`tools/score_dashboard.py --filter pr106_lrl1_sidechannel`."
        ),
        "one_liner": (
            ".venv/bin/python scripts/launch_lane_on_vastai.py full \\\n"
            "  --lane-script scripts/remote_lane_pr106_stacked.sh \\\n"
            "  --label lane_pr106_stacked \\\n"
            "  --predicted-band 0.16 0.20 \\\n"
            "  --estimated-cost 0.40 --council-priority 4 --max-dph 0.30 \\\n"
            "  --env STACKED_LATENT_ARCHIVE=<path/to/sister_latent_archive.zip> \\\n"
            "  --env STACKED_YSHIFT_ARCHIVE=<path/to/sister_yshift_archive.zip> \\\n"
            "  --env STACKED_LRL1_ARCHIVE=<path/to/sister_lrl1_archive.zip>"
        ),
    },
]


def _format_supplementary_lanes() -> str:
    lines = []
    for lane in PHASE_1_SUPPLEMENTARY_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    Operator one-liner:\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _packet_runtime_tree_sha256(packet: dict) -> str | None:
    for key in ("runtime_tree_sha256", "candidate_runtime_tree_sha256"):
        value = packet.get(key)
        if is_sha256(value):
            return str(value).lower()
    for key in ("runtime_manifest", "runtime_custody", "inflate_runtime_manifest"):
        nested = packet.get(key)
        if isinstance(nested, dict):
            value = nested.get("runtime_tree_sha256")
            if is_sha256(value):
                return str(value).lower()
    return None


def _load_exact_eval_packet(lane: dict) -> dict[str, object]:
    path = REPO_ROOT / str(lane["packet_path"])
    if not path.is_file():
        return {
            "lane_id": lane["lane_id"],
            "name": lane["name"],
            "packet_path": lane["packet_path"],
            "ready_for_submit": False,
            "blockers": ["missing_packet_json"],
            "missing_env": [],
            "archive_sha256": None,
            "archive_bytes": None,
            "commands": {},
        }
    try:
        packet = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError as exc:
        return {
            "lane_id": lane["lane_id"],
            "name": lane["name"],
            "packet_path": lane["packet_path"],
            "ready_for_submit": False,
            "blockers": [f"malformed_packet_json:{exc.msg}"],
            "missing_env": [],
            "archive_sha256": None,
            "archive_bytes": None,
            "commands": {},
        }
    blockers = list(packet.get("blockers") or packet.get("submit_blockers") or [])
    archive_sha256 = packet.get("archive_sha256")
    runtime_tree_sha256 = _packet_runtime_tree_sha256(packet)
    runtime_changed = as_bool(packet.get("score_affecting_runtime_changed"))
    terminal_blockers = []
    if isinstance(archive_sha256, str):
        terminal_blockers = terminal_claim_result_conflicts(
            str(lane["lane_id"]),
            archive_sha256,
            dispatch_claims_path=DISPATCH_CLAIMS,
            active_floor_score=ACTIVE_FLOOR_SCORE,
            runtime_tree_sha256=runtime_tree_sha256,
            score_affecting_runtime_changed=runtime_changed,
        )
        blockers.extend(
            blocker for blocker in terminal_blockers if blocker not in blockers
        )
    static_ready = bool(
        packet.get("preflight_ready")
        or packet.get("static_packet_ready")
        or packet.get("candidate_static_preflight_ready")
    )
    compliance_ok = bool(
        packet.get("compliance_ok")
        or packet.get("static_compliance_ok")
        or not packet.get("static_blockers")
    )
    artifacts = packet.get("artifacts")
    payload_diff_ready = bool(
        packet.get("payload_diff_ready")
        or packet.get("payload_section_diff_ready")
        or packet.get("linked_lowlevel_changes")
        or (
            isinstance(artifacts, dict)
            and bool(artifacts.get("payload_section_diff"))
        )
    )
    dry_run_ready = bool(
        packet.get("dry_run_ready")
        or packet.get("ready_for_exact_eval_dispatch_claim")
    )
    return {
        "lane_id": lane["lane_id"],
        "name": lane["name"],
        "packet_path": lane["packet_path"],
        "ready_for_submit": bool(packet.get("ready_for_submit")) and not terminal_blockers,
        "blockers": blockers,
        "terminal_exact_eval_evidence_blockers": terminal_blockers,
        "missing_env": list(packet.get("missing_env") or []),
        "archive_sha256": archive_sha256,
        "runtime_tree_sha256": runtime_tree_sha256,
        "score_affecting_runtime_changed": runtime_changed,
        "archive_bytes": packet.get("archive_bytes"),
        "preflight_ready": static_ready,
        "compliance_ok": compliance_ok,
        "payload_diff_ready": payload_diff_ready,
        "dry_run_ready": dry_run_ready,
        "commands": dict(packet.get("commands") or {}),
        "operator_next_steps": dict(packet.get("operator_next_steps") or {}),
    }


def _exact_eval_packet_summaries() -> list[dict[str, object]]:
    return [_load_exact_eval_packet(lane) for lane in PHASE_1_EXACT_EVAL_PACKETS]


def _format_exact_eval_packets() -> str:
    lines = []
    for packet in _exact_eval_packet_summaries():
        commands = packet.get("commands") or {}
        next_steps = packet.get("operator_next_steps") or {}
        step_rows = next_steps.get("steps") if isinstance(next_steps, dict) else []
        step_ids = (
            ", ".join(str(step.get("id")) for step in step_rows if isinstance(step, dict))
            if isinstance(step_rows, list)
            else ""
        )
        blockers = packet.get("blockers") or []
        missing_env = packet.get("missing_env") or []
        state = "READY" if packet.get("ready_for_submit") else "BLOCKED"
        lines.append(
            f"  • {packet['lane_id']} — {packet['name']}\n"
            f"    state {state}   bytes {packet.get('archive_bytes')}   "
            f"sha256 {packet.get('archive_sha256')}\n"
            f"    static gates: preflight={packet.get('preflight_ready')} "
            f"compliance={packet.get('compliance_ok')} "
            f"payload_diff={packet.get('payload_diff_ready')} "
            f"dry_run={packet.get('dry_run_ready')}\n"
            f"    blockers: {', '.join(blockers) if blockers else '(none)'}\n"
            f"    missing env: {', '.join(missing_env) if missing_env else '(none)'}\n"
            f"    packet: {packet['packet_path']}\n"
            f"    Claim:\n"
            f"      {commands.get('claim', '(missing)')}\n"
            f"    Submit:\n"
            f"      {commands.get('submit', '(missing)')}\n"
            f"    Harvest:\n"
            f"      {commands.get('harvest', '(missing)')}\n"
            f"    Copy-safe next steps:\n"
            f"      {step_ids if step_ids else '(missing)'}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _exact_ready_queue_audit() -> dict[str, object]:
    queues = discover_exact_ready_queues(
        repo_root=REPO_ROOT,
        scan_root=EXACT_READY_SCAN_ROOT,
    )
    return audit_exact_ready_queues(
        queues,
        repo_root=REPO_ROOT,
        dispatch_claims_path=DISPATCH_CLAIMS,
        active_floor_score=ACTIVE_FLOOR_SCORE,
    )


def _format_exact_ready_queue_audit() -> str:
    payload = _exact_ready_queue_audit()
    lines = [
        f"queues_scanned: {payload['queue_count']}",
        f"passed: {payload['passed']}",
        f"stale_ready_rows: {payload['stale_ready_row_count']}",
    ]
    if payload.get("stale_ready_row_count"):
        lines.append("blocked rows:")
        for queue in payload.get("queues", []):
            if not isinstance(queue, dict):
                continue
            for row in queue.get("stale_ready_rows", []):
                if not isinstance(row, dict):
                    continue
                blockers = ", ".join(str(b) for b in row.get("blockers", []))
                lines.append(
                    "  - "
                    f"{queue.get('queue_path')} :: {row.get('candidate_id')} "
                    f"lane={row.get('lane_id')} runtime={row.get('runtime_tree_sha256')} "
                    f"blockers={blockers}"
                )
    return "\n".join(lines)


def _load_pr91_hpm1_readiness_artifact() -> dict[str, object]:
    readiness = _run_json(PR91_HPM1_READINESS)
    runtime = _run_json(PR91_HPM1_RUNTIME_CONTRACT)
    readiness_artifact = _load_json_file(PR91_HPM1_READINESS_ARTIFACT)
    runtime_artifact = _load_json_file(PR91_HPM1_RUNTIME_CONTRACT_ARTIFACT)
    audit_errors = [
        str(payload["_error"])
        for payload in (readiness, runtime, readiness_artifact, runtime_artifact)
        if isinstance(payload.get("_error"), str)
    ]
    readiness_blockers = list(readiness.get("dispatch_blockers") or [])
    runtime_blockers = list(runtime.get("dispatch_blockers") or [])
    artifact_readiness_blockers = list(readiness_artifact.get("dispatch_blockers") or [])
    artifact_runtime_blockers = list(runtime_artifact.get("dispatch_blockers") or [])
    readiness_hash = _canonical_payload_hash(readiness)
    runtime_hash = _canonical_payload_hash(runtime)
    readiness_artifact_hash = _canonical_payload_hash(readiness_artifact)
    runtime_artifact_hash = _canonical_payload_hash(runtime_artifact)
    zip_report = {}
    if isinstance(readiness.get("member_x"), dict) and isinstance(readiness["member_x"].get("zip_report"), dict):
        zip_report = readiness["member_x"]["zip_report"]
    wire_contract = zip_report.get("wire_contract") if isinstance(zip_report, dict) else {}
    hpac_contract = runtime.get("hpac_device_contract")
    if not isinstance(hpac_contract, dict):
        hpac_contract = {}
    hpac_cpu_resolved = (
        hpac_contract.get("passed") is True
        and hpac_contract.get("status") == "resolved_cpu_only"
        and hpac_contract.get("resolved_device") == "cpu"
    )
    summary = (
        "PR91 static archive/member/HPM1 custody is visible, and HPAC device "
        "semantics are pinned CPU-only; HPM1 decode/reencode and sidecar-free "
        "runtime consumption remain blocked. This is not a score or dispatch artifact."
        if hpac_cpu_resolved
        else (
            "PR91 static archive/member/HPM1 custody is visible, but HPM1 decode/reencode "
            "and HPAC runtime device semantics remain blocked; this is not a score or "
            "dispatch artifact."
        )
    )
    next_patch = (
        "Recover full HPM1 decode/reencode parity, then prove sidecar-free runtime "
        "consumption before any dispatch."
        if hpac_cpu_resolved
        else (
            "Resolve HPAC CPU/CUDA device contract, recover full HPM1 decode/reencode "
            "parity, then prove sidecar-free runtime consumption before any dispatch."
        )
    )
    return {
        "kind": "pr91_hpm1_readiness_bundle",
        "name": "PR91 HPM1 categorical mask rate signal",
        "state": "AUDIT_ERROR_FAIL_CLOSED"
        if audit_errors
        else ("BLOCKED_CPU_CONTRACT_PINNED" if hpac_cpu_resolved else "BLOCKED_FAIL_CLOSED"),
        "evidence_grade": readiness.get("evidence_grade"),
        "ready_for_exact_eval_dispatch": False,
        "score_claim": False,
        "dispatch_attempted": False,
        "promotion_eligible": False,
        "audit_errors": audit_errors,
        "artifact_path": _repo_rel(PR91_HPM1_READINESS_ARTIFACT),
        "runtime_contract_artifact_path": _repo_rel(PR91_HPM1_RUNTIME_CONTRACT_ARTIFACT),
        "readiness_manifest_hash_self_consistent": _manifest_hash_self_consistent(readiness),
        "runtime_manifest_hash_self_consistent": _manifest_hash_self_consistent(runtime),
        "readiness_artifact_manifest_hash_self_consistent": _manifest_hash_self_consistent(
            readiness_artifact
        ),
        "runtime_artifact_manifest_hash_self_consistent": _manifest_hash_self_consistent(
            runtime_artifact
        ),
        "readiness_artifact_hash_matches_live": bool(readiness_hash)
        and readiness_hash == readiness_artifact_hash,
        "runtime_artifact_hash_matches_live": bool(runtime_hash)
        and runtime_hash == runtime_artifact_hash,
        "archive_custody_matches": (
            isinstance(readiness.get("source_archive"), dict)
            and readiness["source_archive"].get("matches_expected") is True
        ),
        "hpm1_mask_custody_matches": (
            isinstance(readiness.get("hpm1_mask_segment"), dict)
            and readiness["hpm1_mask_segment"].get("matches_expected") is True
        ),
        "zip_wire_contract_passed": isinstance(wire_contract, dict)
        and wire_contract.get("passed") is True,
        "ambient_device_call_count": runtime.get("ambient_device_call_count"),
        "contradiction_count": runtime.get("contradiction_count"),
        "dispatch_blockers": readiness_blockers + runtime_blockers,
        "artifact_dispatch_blockers": artifact_readiness_blockers + artifact_runtime_blockers,
        "summary": summary,
        "next_patch": next_patch,
    }


def _non_dispatchable_readiness_artifacts() -> list[dict[str, object]]:
    return [_load_pr91_hpm1_readiness_artifact()]


def _format_non_dispatchable_readiness_artifacts() -> str:
    lines = []
    for artifact in _non_dispatchable_readiness_artifacts():
        blockers = ", ".join(str(item) for item in artifact["dispatch_blockers"])
        lines.append(
            f"  • {artifact['kind']} — {artifact['name']}\n"
            f"    state {artifact['state']}   ready_for_exact_eval_dispatch=false\n"
            f"    readiness artifact: {artifact['artifact_path']}\n"
            f"    runtime artifact: {artifact['runtime_contract_artifact_path']}\n"
            f"    artifact/live hashes: readiness={artifact['readiness_artifact_hash_matches_live']} "
            f"runtime={artifact['runtime_artifact_hash_matches_live']}\n"
            f"    custody: archive={artifact['archive_custody_matches']} "
            f"hpm1_mask={artifact['hpm1_mask_custody_matches']} "
            f"zip_wire={artifact['zip_wire_contract_passed']}\n"
            f"    runtime: ambient_device_calls={artifact['ambient_device_call_count']} "
            f"contradictions={artifact['contradiction_count']}\n"
            f"    blockers: {blockers if blockers else '(none)'}\n"
            f"    audit errors: {', '.join(artifact['audit_errors']) if artifact['audit_errors'] else '(none)'}\n"
            f"    summary: {artifact['summary']}\n"
            f"    next patch: {artifact['next_patch']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _format_gated_lanes() -> str:
    lines = []
    for lane in PHASE_4_GATED_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    GATE: {lane['gate_condition']}\n"
            f"    Operator one-liner (post-gate):\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _format_composition_lanes() -> str:
    lines = []
    for lane in PHASE_5_COMPOSITION_LANES:
        lo, hi = lane["predicted_band"]
        lines.append(
            f"  • {lane['lane_id']} — {lane['name']}\n"
            f"    predicted [{lo:.4f}, {hi:.4f}]   est ${lane['estimated_cost_usd']:.2f}   "
            f"council priority {lane['council_priority']}\n"
            f"    GATE: {lane['gate_condition']}\n"
            f"    Operator one-liner (post-gate):\n"
            f"      {lane['one_liner']}"
        )
    return "\n\n".join(lines) if lines else "  (none)"


def _run(script: Path, extra_args: list[str] | None = None) -> str:
    args = [sys.executable, str(script)]
    if extra_args:
        args.extend(extra_args)
    proc = subprocess.run(args, capture_output=True, text=True, check=False)
    if proc.returncode != 0:
        return (
            f"(tool exited with code {proc.returncode}; stderr: "
            f"{proc.stderr.strip()[:200]})"
        )
    return proc.stdout


def _run_json(script: Path, extra_args: list[str] | None = None) -> dict:
    text = _run(script, extra_args or [])
    try:
        return json.loads(text)
    except json.JSONDecodeError:
        return {"_error": "non-JSON output", "_stdout": text[:500]}


def _dispatch_claim_summary() -> dict[str, object]:
    """Return the read-only dispatch-claim summary used to prevent duplicate evals."""
    return _run_json(CLAIM_DISPATCH, ["summary", "--format", "json"])


def _latest_provider_readiness_artifact() -> Path | None:
    if PROVIDER_READINESS_LATEST.is_file():
        return PROVIDER_READINESS_LATEST
    candidates = sorted(
        (REPO_ROOT / "experiments/results").glob("cloud_provider_readiness_*.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    return candidates[0] if candidates else None


def _provider_readiness(refresh: bool = False) -> dict[str, object]:
    """Return cloud-provider status without implicit network checks.

    Normal operator briefing loads the latest provider-readiness artifact from
    disk. Live cloud CLI checks are intentionally opt-in via
    ``--refresh-provider-readiness`` so a status briefing cannot hang or mutate
    provider state.
    """

    if refresh:
        return _run_json(
            CLOUD_PROVIDER_READINESS,
            [
                "--output",
                str(PROVIDER_READINESS_LATEST),
                "--timeout-s",
                "8",
            ],
        )
    latest = _latest_provider_readiness_artifact()
    if latest is None:
        return {
            "_error": "no provider readiness artifact found",
            "next_command": (
                ".venv/bin/python tools/cloud_provider_readiness.py "
                "--output experiments/results/cloud_provider_readiness_latest.json"
            ),
        }
    payload = _load_json_file(latest)
    payload["artifact_path"] = _repo_rel(latest)
    return payload


def _format_provider_readiness(refresh: bool = False) -> str:
    payload = _provider_readiness(refresh=refresh)
    if payload.get("_error"):
        return (
            "Provider readiness unavailable; no remote dispatch should be inferred.\n"
            f"  error: {payload.get('_error')}\n"
            f"  next:  {payload.get('next_command')}"
        )
    providers = payload.get("providers") if isinstance(payload.get("providers"), list) else []
    lines = [
        "Read-only provider readiness. This is not a dispatch or score claim.",
        f"  generated_at_utc: {payload.get('generated_at_utc', '<unknown>')}",
        f"  artifact:         {payload.get('artifact_path', _repo_rel(PROVIDER_READINESS_LATEST))}",
        f"  score_claim:      {payload.get('score_claim', False)}",
        f"  exact_dispatch:   {payload.get('ready_for_exact_eval_dispatch', False)}",
    ]
    for row in providers:
        if not isinstance(row, dict):
            continue
        blockers = ", ".join(str(x) for x in row.get("blockers", [])) or "-"
        lines.append(
            "  - "
            f"{row.get('provider', '<unknown>')}: "
            f"{row.get('status', '<unknown>')} "
            f"exact_cuda_now={bool(row.get('exact_cuda_evidence_allowed'))} "
            f"proxy_only={bool(row.get('proxy_only'))} "
            f"blockers={blockers}"
        )
    return "\n".join(lines)


def _format_dispatch_claim_summary() -> str:
    summary = _dispatch_claim_summary()
    if summary.get("_error"):
        return (
            "Dispatch claim helper failed; refuse remote/eval dispatch until "
            f"claim state is readable. error={summary.get('_error')}"
        )
    active = summary.get("active") if isinstance(summary.get("active"), list) else []
    stale = (
        summary.get("stale_nonterminal")
        if isinstance(summary.get("stale_nonterminal"), list)
        else []
    )
    lines = [
        "Read-only claim state from tools/claim_lane_dispatch.py summary.",
        f"  active: {summary.get('active_count', len(active))}",
        f"  stale_nonterminal: {summary.get('stale_nonterminal_count', len(stale))}",
        f"  terminal_latest: {summary.get('terminal_latest_count', '<unknown>')}",
    ]
    if active:
        lines.append("  ACTIVE CONFLICT GUARD: do not dispatch duplicate active lanes.")
        for row in active:
            lines.append(
                "    - "
                f"lane_id={row.get('lane_id', '<missing>')} "
                f"job={row.get('instance_job_id', '<missing>')} "
                f"platform={row.get('platform', '<missing>')} "
                f"status={row.get('status', '<missing>')} "
                f"agent={row.get('agent', '<missing>')}"
            )
    if stale:
        lines.append("  STALE NONTERMINAL: close/classify before relaunching these lanes.")
        for row in stale:
            lines.append(
                "    - "
                f"lane_id={row.get('lane_id', '<missing>')} "
                f"job={row.get('instance_job_id', '<missing>')} "
                f"status={row.get('status', '<missing>')}"
            )
    if not active and not stale:
        lines.append("  No active or stale nonterminal claims.")
    return "\n".join(lines)


def _load_json_file(path: Path) -> dict[str, object]:
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        return {"_error": f"{_repo_rel(path)} unreadable JSON: {exc}"}
    return payload if isinstance(payload, dict) else {"_error": f"{_repo_rel(path)} is not a JSON object"}


def _embedded_canonical_payload_hash(payload: dict[str, object]) -> str:
    manifest = payload.get("tool_run_manifest")
    if not isinstance(manifest, dict):
        return ""
    value = manifest.get("canonical_payload_without_tool_manifest_sha256")
    return value if isinstance(value, str) else ""


def _recomputed_canonical_payload_hash(payload: dict[str, object]) -> str:
    without_manifest = dict(payload)
    without_manifest.pop("tool_run_manifest", None)
    text = json.dumps(without_manifest, indent=2, sort_keys=True, allow_nan=False) + "\n"
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _manifest_hash_self_consistent(payload: dict[str, object]) -> bool:
    embedded = _embedded_canonical_payload_hash(payload)
    return bool(embedded) and embedded == _recomputed_canonical_payload_hash(payload)


def _canonical_payload_hash(payload: dict[str, object]) -> str:
    return _embedded_canonical_payload_hash(payload) if _manifest_hash_self_consistent(payload) else ""


def _repo_rel(path: Path) -> str:
    try:
        return str(path.relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def _section(title: str, body: str) -> str:
    bar = "═" * len(title)
    return f"\n{bar}\n{title}\n{bar}\n\n{body}"


# Phase-6 xray toolkit: surface the diagnostic tools landed 2026-05-09 so
# operators discover them without having to grep `tools/xray_*`. These are
# pure-CPU diagnostic tools — no GPU, no dispatch, no score claims.
XRAY_TOOLKIT = [
    {
        "tool": "tools/xray_archive_section_entropy_heatmap.py",
        "purpose": (
            "Per-section entropy density vs encoded-bytes — reveals which "
            "archive sections are saturated vs have recoverable headroom. "
            "Use BEFORE planning a new entropy-coder lane."
        ),
        "example": (
            ".venv/bin/python tools/xray_archive_section_entropy_heatmap.py \\\n"
            "  --archive experiments/results/public_pr101_hnerv_ft_microcodec_intake_20260504_codex/archive.zip \\\n"
            "  --label pr101_gold"
        ),
    },
    {
        "tool": "tools/xray_per_pr_archive_layout_compare.py",
        "purpose": (
            "Side-by-side byte-section layout for N archives — surfaces "
            "SHARED structure vs DIVERGED bytes. Use to understand 'what "
            "bytes did SajayR/PR101 change vs rem2/PR103?'"
        ),
        "example": (
            ".venv/bin/python tools/xray_per_pr_archive_layout_compare.py \\\n"
            "  --archive experiments/results/public_pr101_hnerv_ft_microcodec_intake_20260504_codex/archive.zip \\\n"
            "  --archive experiments/results/public_pr106_belt_and_suspenders_intake_20260504_codex/archive.zip \\\n"
            "  --label pr101 --label pr106"
        ),
    },
    {
        "tool": "tools/xray_per_tensor_saliency_heatmap.py",
        "purpose": (
            "Per-tensor saliency-vs-bytes — flags over-allocated tensors as "
            "next coarsening targets. Consumes a saliency dict from "
            "tac.score_gradient_param_saliency."
        ),
        "example": (
            ".venv/bin/python tools/xray_per_tensor_saliency_heatmap.py \\\n"
            "  --saliency-json reports/saliency_a1.json \\\n"
            "  --byte-map-json reports/per_tensor_bytes_a1.json \\\n"
            "  --bottom-n-percent 25"
        ),
    },
    {
        "tool": "tools/xray_inflate_op_cost_profiler.py",
        "purpose": (
            "Static AST-based op-cost catalog of inflate.py — finds "
            "per-channel mutation lines (the PR101→PR103 medal-delta "
            "pattern). Use BEFORE designing a new sidecar/inflate edit."
        ),
        "example": (
            ".venv/bin/python tools/xray_inflate_op_cost_profiler.py \\\n"
            "  --inflate-py experiments/results/public_pr101_hnerv_ft_microcodec_intake_20260504_codex/source/submissions/hnerv_ft_microcodec/inflate.py \\\n"
            "  --label pr101_canonical"
        ),
    },
    {
        "tool": "tools/xray_cpu_cuda_drift_per_arch_class.py",
        "purpose": (
            "Predict CPU score from CUDA score using per-architecture-class "
            "drift profile (HNeRV cluster R_pose=5.04). Use to decide "
            "WHETHER to spend on a [contest-CPU GHA] eval before paying."
        ),
        "example": (
            ".venv/bin/python tools/xray_cpu_cuda_drift_per_arch_class.py \\\n"
            "  --archive experiments/results/track4_sg_a1_t178000_20260509/archive.zip \\\n"
            "  --cuda-score 0.22933 --label pr107_apogee"
        ),
    },
]


def _format_xray_toolkit() -> str:
    lines = []
    for entry in XRAY_TOOLKIT:
        lines.append(f"• `{entry['tool']}`")
        lines.append(f"    {entry['purpose']}")
        lines.append("    Example:")
        for ln in entry["example"].splitlines():
            lines.append(f"      {ln}")
        lines.append("")
    return "\n".join(lines).rstrip()


# Phase-7: constrained-coord-search status (added 2026-05-09).
# Surfaces the lane_pr101_bias_constrained_coord_search (sister subagent
# a8522fca) rollup so operators can see the 64-variant grid status without
# having to grep experiments/results/.
def _format_constrained_coord_search_status() -> str:
    """Locate latest constrained_coord_search rollup; format key metadata."""
    import datetime as _dt
    import json as _json
    glob_root = REPO_ROOT / "experiments" / "results"
    candidates = sorted(
        glob_root.glob("constrained_coord_search_pr101_bias_*/rollup.json"),
        key=lambda p: p.stat().st_mtime,
        reverse=True,
    )
    if not candidates:
        return ("(no constrained_coord_search rollups found yet — "
                "sister subagent a8522fca has not landed grid)")
    latest = candidates[0]
    try:
        data = _json.loads(latest.read_text())
    except Exception as exc:
        return f"(rollup parse failed: {exc} at {latest.relative_to(REPO_ROOT)})"
    rel = latest.relative_to(REPO_ROOT)
    lines = [
        f"Rollup: {rel}",
        f"  lane_id:                {data.get('lane_id', '<unknown>')}",
        f"  n_variants:             {data.get('n_variants', 0)}",
        f"  n_unique_inflates:      {data.get('n_unique_inflates', 0)}",
        f"  evidence_grade:         {data.get('evidence_grade', '<unset>')}",
        f"  build_timestamp_utc:    {data.get('build_timestamp_utc', '<unset>')}",
    ]
    anchor = data.get("regression_anchor") or {}
    if anchor:
        lines.append(f"  regression_anchor:      {anchor.get('value', '<unset>')} "
                     f"({anchor.get('tag', '<no-tag>')})")
        lines.append(f"  regression_delta:       {anchor.get('delta_vs_baseline', '<unset>')}")
    blockers = data.get("dispatch_blockers") or []
    if blockers:
        lines.append(f"  dispatch_blockers ({len(blockers)}):")
        for b in blockers:
            lines.append(f"    - {b}")
    grid_keys = list((data.get("grid") or {}).keys())
    if grid_keys:
        lines.append(f"  grid_dims:              {', '.join(grid_keys)}")
    return "\n".join(lines)


# Phase-8: dispatch readiness per phase 1-5+ (added 2026-05-09).
# Compact roll-up of which phases have actionable next-step output, so the
# operator can navigate "what should I dispatch next" without re-reading the
# whole briefing.
def _format_dispatch_readiness() -> str:
    """Roll up actionable next-step status across phases."""
    lines = ["Per-phase dispatch readiness (current session):"]
    # Phase 1: pre-dispatch frontier — always actionable if PARETO emits rows
    lines.append("  Phase 1 (pre-dispatch Pareto):              "
                 "READY — see Phase 1 frontier table above")
    exact_ready_audit = _exact_ready_queue_audit()
    stale_rows = int(exact_ready_audit.get("stale_ready_row_count") or 0)
    if stale_rows:
        lines.append("  Phase 1 exact-ready queue hygiene:          "
                     f"BLOCKED — {stale_rows} stale row(s) carry terminal evidence")
    else:
        lines.append("  Phase 1 exact-ready queue hygiene:          "
                     "READY — no terminal-evidence conflicts")
    # Phase 4 / Phase 5: gated lanes — read PHASE_4_GATED_LANES count
    try:
        n_gated = len(PHASE_4_GATED_LANES)
    except NameError:
        n_gated = 0
    try:
        n_comp = len(PHASE_5_COMPOSITION_LANES)
    except NameError:
        n_comp = 0
    lines.append(f"  Phase 4 (gated next-tick):                  "
                 f"{n_gated} lane(s) gated; check entry conditions before dispatch")
    lines.append(f"  Phase 5 (meta-composition):                 "
                 f"{n_comp} compose-stack(s) tracked")
    # Phase 7: constrained-coord-search
    glob_root = REPO_ROOT / "experiments" / "results"
    cc_rollups = sorted(
        glob_root.glob("constrained_coord_search_pr101_bias_*/rollup.json"),
        reverse=True,
    )
    if cc_rollups:
        lines.append(f"  Phase 7 (constrained-coord-search):         "
                     f"READY — {len(cc_rollups)} rollup(s); top-5 to GHA next")
    else:
        lines.append("  Phase 7 (constrained-coord-search):         "
                     "PENDING — sister subagent a8522fca grid not landed")
    lines.append("")
    lines.append("Recommendation: prefer M5 Max parallel coarse-rank ($0) before "
                 "paid GHA promotion; reference Phase 6 xray toolkit for diagnosis.")
    return "\n".join(lines)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--top", type=int, default=20,
                        help="Cap dashboard rows (default: 20).")
    parser.add_argument("--skip-pareto", action="store_true",
                        help="Skip Phase 1 (Pareto pre-dispatch matrix).")
    parser.add_argument("--skip-dashboard", action="store_true",
                        help="Skip Phase 2 (general score dashboard).")
    parser.add_argument("--skip-reconciler", action="store_true",
                        help="Skip Phase 3 (apogee_intN predicted-vs-actual).")
    parser.add_argument("--skip-gated", action="store_true",
                        help="Skip Phase 4 (gated next-tick lanes).")
    parser.add_argument("--skip-composition", action="store_true",
                        help="Skip Phase 5 (meta-composition lanes).")
    parser.add_argument("--skip-provider-readiness", action="store_true",
                        help="Skip cached cloud-provider readiness section.")
    parser.add_argument("--refresh-provider-readiness", action="store_true",
                        help="Run read-only cloud provider checks before rendering the briefing.")
    parser.add_argument("--json", action="store_true",
                        help="Machine-readable composite JSON output.")
    args = parser.parse_args(argv)

    # Verify delegated tools exist before building either text or JSON output.
    for tool in (PARETO, DASHBOARD, RECONCILER, CLAIM_DISPATCH):
        if not tool.is_file():
            print(f"FATAL: missing dependency tool {tool.relative_to(REPO_ROOT)}",
                  file=sys.stderr)
            return 2
    if args.refresh_provider_readiness and not CLOUD_PROVIDER_READINESS.is_file():
        print(
            f"FATAL: missing dependency tool {CLOUD_PROVIDER_READINESS.relative_to(REPO_ROOT)}",
            file=sys.stderr,
        )
        return 2

    if args.json:
        out = {"dispatch_claim_summary": _dispatch_claim_summary()}
        if not args.skip_provider_readiness:
            out["provider_readiness"] = _provider_readiness(refresh=args.refresh_provider_readiness)
        if not args.skip_pareto:
            out["pareto"] = _run_json(PARETO, ["--json"])
            out["supplementary_lanes"] = PHASE_1_SUPPLEMENTARY_LANES
            out["exact_eval_packets"] = _exact_eval_packet_summaries()
            out["exact_ready_queue_audit"] = _exact_ready_queue_audit()
            out["non_dispatchable_readiness_artifacts"] = _non_dispatchable_readiness_artifacts()
        if not args.skip_dashboard:
            out["dashboard"] = _run_json(DASHBOARD, ["--top", str(args.top), "--json"])
        if not args.skip_reconciler:
            out["reconciler"] = _run_json(RECONCILER, ["--json"])
        if not args.skip_gated:
            out["gated_lanes"] = PHASE_4_GATED_LANES
        if not args.skip_composition:
            out["composition_lanes"] = PHASE_5_COMPOSITION_LANES
        print(json.dumps(out, indent=2, default=str))
        return 0

    # Human-readable composite
    parts: list[str] = ["OPERATOR BRIEFING — dispatch trio"]
    parts.append(_section(
        "Dispatch claim coordination — active lane guard",
        _format_dispatch_claim_summary(),
    ))
    if not args.skip_provider_readiness:
        parts.append(_section(
            "Cloud provider readiness — cached exact/proxy boundary",
            _format_provider_readiness(refresh=args.refresh_provider_readiness),
        ))
    if not args.skip_pareto:
        parts.append(_section(
            "Phase 1 — Pre-dispatch: apogee_intN Pareto frontier",
            _run(PARETO).strip(),
        ))
        parts.append(_section(
            "Phase 1 supplementary — pre-registered non-Pareto lanes",
            _format_supplementary_lanes(),
        ))
        parts.append(_section(
            "Phase 1 exact-eval packets — static-clean CUDA candidates",
            _format_exact_eval_packets(),
        ))
        parts.append(_section(
            "Phase 1 exact-ready queues — terminal-evidence audit",
            _format_exact_ready_queue_audit(),
        ))
        parts.append(_section(
            "Phase 1 blocked readiness artifacts — non-dispatchable public frontier work",
            _format_non_dispatchable_readiness_artifacts(),
        ))
    if not args.skip_dashboard:
        parts.append(_section(
            f"Phase 2 — Post-dispatch (general): top {args.top} contest scores on disk",
            _run(DASHBOARD, ["--top", str(args.top)]).strip(),
        ))
    if not args.skip_reconciler:
        parts.append(_section(
            "Phase 3 — Post-dispatch (apogee_intN): predicted-vs-actual reconciliation",
            _run(RECONCILER).strip(),
        ))
    if not args.skip_gated:
        parts.append(_section(
            "Phase 4 — Gated next-tick lanes (sequential validation)",
            _format_gated_lanes(),
        ))
    if not args.skip_composition:
        parts.append(_section(
            "Phase 5 — Meta-composition lanes (single-dispatch payoff of multi-sister stacks)",
            _format_composition_lanes(),
        ))
    parts.append(_section(
        "Phase 6 — XRAY toolkit (diagnostic tools landed 2026-05-09)",
        _format_xray_toolkit(),
    ))
    parts.append(_section(
        "Phase 7 — Constrained-coord-search status (sister subagent a8522fca)",
        _format_constrained_coord_search_status(),
    ))
    parts.append(_section(
        "Phase 8 — Per-phase dispatch readiness (next actionable step)",
        _format_dispatch_readiness(),
    ))
    print("\n".join(parts))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
