#!/usr/bin/env python3
"""Certify-or-block deletion of COMMAND-rebuildable payloads named by a producer manifest.

Sister of ``tools/sr5_certify_delete_derived.py``.  That tool handles payloads that
are a pure function of a sibling file, so every deletion can re-run the rebuild in
memory.  This tool handles the other shape: a closed arm whose payloads are
regenerated by re-running a recorded COMMAND against recorded, still-present inputs
(ddm_rbf1's ``render`` stage is the anchor).  Re-running that command per file is not
possible -- it regenerates a whole chunk -- so the certificate is built differently
and says so plainly:

  1. the chunk manifest names the artifact with a path, byte count and sha256;
  2. the artifact on disk hashes to that recorded sha256;
  3. every rebuild INPUT the manifest binds (archive, field, gt, raw, probe module,
     treatment module) exists and hashes to its recorded sha256 -- verified once per
     run and then required to be byte-identical in every chunk's binding block;
  4. the rebuild command was EXERCISED on a real slice of this class and reproduced
     the recorded sha256 byte-for-byte; the exercise receipt is hashed and named on
     every cert row, so no row rests on an unexercised claim.

Binding 4 is a class-level proof, not a per-file one.  That is weaker than the
sibling-derivation tool and the cert rows record it as ``class_level_exercise`` so a
reader is never misled about which kind of proof they are holding.
"""

from __future__ import annotations

import argparse
import fcntl
import glob
import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

SCHEMA = "ddm_sr5_certified_command_rebuildable_deletion.v1"
SIDECAR_NAME = "DERIVED_DELETED.json"

# Deliberately NOT the same list as the sibling tool: ddm_rbf1 is absent here
# because its claim closed (completed_n600_scorer, 2026-09-11T16:13:52Z) and it
# published its own retention certification.  Its rebuild INPUTS live under
# ddm_rlc5_cure_on_move43 and ddm_sj1_pass6, which stay protected -- deleting a
# payload is only safe while the bytes that regenerate it are untouchable.
PROTECTED_SUBSTRINGS = (
    "/ddm_pc3_",
    "/ddm_ntb2_",
    "/ddm_mxo2",
    "/ddm_mxo3",
    "/ddm_rlc5_cure_on_move43",
    "/ddm_sj1_pass6",
    "/ddm_rp1_round2",
    "/ddm_sr4_20260910/retained/ap_offload",
    "/public_datasets",
    "/cold_store",
    "/upstream/",
)


class CertifyError(RuntimeError):
    """Raised when the tool refuses to proceed."""


def utcnow() -> str:
    from datetime import datetime, timezone

    return datetime.now(timezone.utc).isoformat().replace("+00:00", "Z")


def sha256_file(path: Path, bufsize: int = 4 * 1024 * 1024) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        while True:
            chunk = handle.read(bufsize)
            if not chunk:
                break
            digest.update(chunk)
    return digest.hexdigest()


def df_free_bytes(mount: str) -> int:
    stat = os.statvfs(mount)
    return int(stat.f_bavail) * int(stat.f_frsize)


def df_snapshot(mount: str) -> dict[str, object]:
    out = subprocess.run(["df", "-k", mount], capture_output=True, text=True, check=True).stdout.strip()
    return {"mount": mount, "df_k": out, "free_bytes": df_free_bytes(mount)}


def assert_not_protected(path: Path) -> None:
    text = str(path.resolve())
    for needle in PROTECTED_SUBSTRINGS:
        if needle in text:
            raise CertifyError(f"protected path refused: {text} matches {needle!r}")


def append_ledger(ledger: Path, row: dict) -> None:
    """fcntl-locked, fsync'd append so a crash cannot lose a cert row."""
    ledger.parent.mkdir(parents=True, exist_ok=True)
    line = json.dumps(row, sort_keys=True) + "\n"
    with ledger.open("a", encoding="utf-8") as handle:
        fcntl.flock(handle.fileno(), fcntl.LOCK_EX)
        try:
            handle.write(line)
            handle.flush()
            os.fsync(handle.fileno())
        finally:
            fcntl.flock(handle.fileno(), fcntl.LOCK_UN)


def write_sidecar(directory: Path, rows: list[dict]) -> None:
    sidecar = directory / SIDECAR_NAME
    existing: list[dict] = []
    if sidecar.is_file():
        try:
            existing = list(json.loads(sidecar.read_text()).get("deleted", []))
        except (json.JSONDecodeError, OSError):
            existing = []
    payload = {
        "schema": SCHEMA,
        "written_at_utc": utcnow(),
        "note": (
            "Deleted as certified command-rebuildable payloads. Re-run the recorded "
            "rebuild_command against the recorded, still-present inputs to restore the "
            "exact sha256 named below."
        ),
        "deleted": existing + rows,
    }
    tmp = sidecar.with_suffix(".tmp")
    tmp.write_text(json.dumps(payload, indent=1, sort_keys=True))
    os.replace(tmp, sidecar)


def collect_binding_files(binding: dict) -> dict[str, dict]:
    """Flatten every {path, bytes, sha256} record the manifest's binding block names."""
    found: dict[str, dict] = {}

    def walk(node: object, label: str) -> None:
        if isinstance(node, dict):
            if "path" in node and "sha256" in node:
                found[str(node["path"])] = {"label": label, **node}
                return
            for key, value in node.items():
                walk(value, f"{label}.{key}")
        elif isinstance(node, list):
            for index, value in enumerate(node):
                walk(value, f"{label}[{index}]")

    walk(binding, "binding")
    return found


def verify_rebuild_inputs(binding: dict) -> list[dict]:
    """Binding 3: every recorded rebuild input is present and byte-identical."""
    verified: list[dict] = []
    for path_text, record in sorted(collect_binding_files(binding).items()):
        path = Path(path_text)
        if not path.is_file():
            raise CertifyError(f"rebuild input missing: {path_text} ({record['label']})")
        size = path.stat().st_size
        if "bytes" in record and int(record["bytes"]) != size:
            raise CertifyError(f"rebuild input size drift: {path_text}")
        digest = sha256_file(path)
        if digest != record["sha256"]:
            raise CertifyError(f"rebuild input sha drift: {path_text}")
        verified.append({"label": record["label"], "path": path_text, "bytes": size, "sha256": digest})
    return verified


def certify_artifact(
    manifest_path: Path,
    manifest: dict,
    key: str,
    context: dict,
    ledger: Path,
    apply: bool,
) -> dict:
    """Return the verdict row for one artifact key inside one chunk manifest."""
    directory = manifest_path.parent
    row: dict[str, object] = {
        "schema": SCHEMA,
        "written_at_utc": utcnow(),
        "payload_class": context["payload_class"],
        "artifact_key": key,
        "manifest_path": str(manifest_path),
        "closed_store_evidence": context["closed_store_evidence"],
        "rebuild_command": context["rebuild_command"],
        "rebuild_proof": "class_level_exercise",
        "exercise_receipt_path": context["exercise_receipt_path"],
        "exercise_receipt_sha256": context["exercise_receipt_sha256"],
        "rebuild_inputs_verified_sha256": context["inputs_digest"],
        "tool": "tools/sr5_certify_delete_command_rebuildable.py",
        "tool_sha256": context["tool_sha"],
        "score_claim": False,
        "promotable": False,
        "rank_or_kill_eligible": False,
        "verdict": "REFUSED",
    }
    try:
        record = manifest.get("artifacts", {}).get(key)
        if not isinstance(record, dict):
            raise CertifyError(f"manifest names no artifact {key!r}")
        for field in ("path", "bytes", "sha256"):
            if field not in record:
                raise CertifyError(f"artifact {key!r} record missing {field!r}")
        target = Path(str(record["path"]))
        row["original_path"] = str(target)
        row["manifest_sha256"] = str(record["sha256"])
        if target.parent != directory:
            raise CertifyError("artifact path points outside its own chunk directory")
        assert_not_protected(target)
        if not target.is_file() or target.is_symlink():
            raise CertifyError("artifact missing or not a regular file")

        link_count = os.lstat(target).st_nlink
        row["st_nlink"] = int(link_count)
        if link_count != 1:
            raise CertifyError(f"st_nlink={link_count}: deleting would not free the blocks")
        row["bytes"] = int(target.stat().st_size)
        if row["bytes"] != int(record["bytes"]):
            raise CertifyError("on-disk size differs from the manifest size")

        on_disk = sha256_file(target)
        row["on_disk_sha256"] = on_disk
        if on_disk != record["sha256"]:
            raise CertifyError("on-disk sha256 differs from the manifest sha256")

        if json.dumps(manifest.get("binding"), sort_keys=True) != context["binding_json"]:
            raise CertifyError("chunk binding differs from the verified rebuild-input binding")

        row["verdict"] = "CERTIFIED_REBUILDABLE"
    except (CertifyError, OSError, ValueError, json.JSONDecodeError) as exc:
        row["refusal_reason"] = f"{type(exc).__name__}: {exc}"
        return row

    if not apply:
        row["action"] = "PLAN_ONLY_NO_MUTATION"
        return row

    pending = dict(row)
    pending["action"] = "DELETE_PENDING"
    append_ledger(ledger, pending)
    target.unlink()
    row["action"] = "DELETED"
    row["deleted_at_utc"] = utcnow()
    append_ledger(ledger, row)
    write_sidecar(
        directory,
        [
            {
                "deleted_path": str(target),
                "bytes": row["bytes"],
                "sha256": on_disk,
                "rebuild_command": context["rebuild_command"],
                "exercise_receipt_path": context["exercise_receipt_path"],
                "deleted_at_utc": row["deleted_at_utc"],
            }
        ],
    )
    return row


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--manifest-glob", required=True, help="Glob of per-chunk manifests.")
    parser.add_argument("--artifact-keys", required=True, help="Comma-separated artifact keys.")
    parser.add_argument("--payload-class", required=True)
    parser.add_argument("--rebuild-command", required=True)
    parser.add_argument("--exercise-receipt", required=True, help="JSON receipt of the slice exercise.")
    parser.add_argument("--closed-store-evidence", required=True)
    parser.add_argument("--ledger", required=True)
    parser.add_argument("--target-free-gib", type=float, required=True)
    parser.add_argument("--mount", required=True)
    parser.add_argument("--apply", action="store_true")
    parser.add_argument("--progress-every", type=int, default=10)
    args = parser.parse_args()

    manifests = sorted(Path(p) for p in glob.glob(args.manifest_glob))
    if not manifests:
        print(f"REFUSE: no manifest matched {args.manifest_glob}", file=sys.stderr)
        return 2
    receipt_path = Path(args.exercise_receipt).resolve()
    if not receipt_path.is_file():
        print(f"REFUSE: exercise receipt missing: {receipt_path}", file=sys.stderr)
        return 3
    receipt = json.loads(receipt_path.read_text())
    if receipt.get("verdict") != "REBUILD_REPRODUCED_RECORDED_SHA256":
        print(f"REFUSE: exercise receipt verdict is {receipt.get('verdict')!r}", file=sys.stderr)
        return 4

    keys = [k.strip() for k in args.artifact_keys.split(",") if k.strip()]
    ledger = Path(args.ledger).resolve()
    tool_sha = sha256_file(Path(__file__).resolve())

    first = json.loads(manifests[0].read_text())
    binding = first.get("binding")
    if not isinstance(binding, dict):
        print("REFUSE: first manifest has no binding block", file=sys.stderr)
        return 5
    try:
        inputs = verify_rebuild_inputs(binding)
    except CertifyError as exc:
        print(f"REFUSE: {exc}", file=sys.stderr)
        return 6
    binding_json = json.dumps(binding, sort_keys=True)
    context = {
        "payload_class": args.payload_class,
        "closed_store_evidence": args.closed_store_evidence,
        "rebuild_command": args.rebuild_command,
        "exercise_receipt_path": str(receipt_path),
        "exercise_receipt_sha256": sha256_file(receipt_path),
        "inputs_digest": hashlib.sha256(json.dumps(inputs, sort_keys=True).encode()).hexdigest(),
        "binding_json": binding_json,
        "tool_sha": tool_sha,
    }
    print(
        f"[sr5] class={args.payload_class} manifests={len(manifests)} keys={keys} "
        f"rebuild inputs verified={len(inputs)} apply={args.apply}"
    )

    before = df_snapshot(args.mount)
    target_free = int(args.target_free_gib * (1024**3))
    certified = deleted = refused = 0
    freed = 0
    refusals: list[dict] = []
    stop = False
    for index, manifest_path in enumerate(manifests, start=1):
        if stop:
            break
        try:
            manifest = json.loads(manifest_path.read_text())
        except (OSError, json.JSONDecodeError) as exc:
            refused += 1
            refusals.append({"manifest_path": str(manifest_path), "refusal_reason": str(exc)})
            continue
        for key in keys:
            if args.apply and df_free_bytes(args.mount) >= target_free:
                print(f"[sr5] target reached after {deleted} deletions; stopping (no over-reclaim).")
                stop = True
                break
            row = certify_artifact(manifest_path, manifest, key, context, ledger, args.apply)
            if row["verdict"] != "CERTIFIED_REBUILDABLE":
                refused += 1
                refusals.append(row)
                append_ledger(ledger, row)
                print(f"[sr5] REFUSED {row.get('original_path')}: {row.get('refusal_reason')}", file=sys.stderr)
                continue
            certified += 1
            if row.get("action") == "DELETED":
                deleted += 1
                freed += int(row["bytes"])
        if index % args.progress_every == 0:
            print(
                f"[sr5] {index}/{len(manifests)} certified={certified} deleted={deleted} "
                f"refused={refused} freed={freed / 1024**3:.3f} GiB "
                f"free_now={df_free_bytes(args.mount) / 1024**3:.3f} GiB",
                flush=True,
            )

    after = df_snapshot(args.mount)
    summary = {
        "schema": SCHEMA + ".summary",
        "written_at_utc": utcnow(),
        "payload_class": args.payload_class,
        "manifest_glob": args.manifest_glob,
        "manifests": len(manifests),
        "artifact_keys": keys,
        "certified": certified,
        "deleted": deleted,
        "refused": refused,
        "freed_bytes_accounted": freed,
        "rebuild_command": args.rebuild_command,
        "rebuild_inputs_verified": inputs,
        "exercise_receipt_path": str(receipt_path),
        "exercise_receipt_sha256": context["exercise_receipt_sha256"],
        "closed_store_evidence": args.closed_store_evidence,
        "df_before": before,
        "df_after": after,
        "df_free_delta_bytes": int(after["free_bytes"]) - int(before["free_bytes"]),
        "apply": bool(args.apply),
        "tool_sha256": tool_sha,
        "refusal_reasons": sorted({str(r.get("refusal_reason")) for r in refusals}),
    }
    append_ledger(ledger, summary)
    print(json.dumps(summary, indent=1, sort_keys=True))
    return 0 if refused == 0 else 1


if __name__ == "__main__":
    raise SystemExit(main())
